### ISSUE TITLE
Rainshower

### ISSUE THREAD

**Issue by InvisibleGame6** [FlafyDev/auto-nong-indexes#10]
### Song Name

Rainshower

### Artist Name

Silentroom

### Source

Youtube

### Youtube Link

https://youtu.be/tLL8cqRmaNE?si=M6TB5-rq9ySq3nvA

### Song ID

100

**Comment by InvisibleGame6** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

already exists (the one with no name for some reason)
