### ISSUE TITLE
Add Nong Song: Wake up by Kayzo and Riot

### ISSUE THREAD

**Issue by Artl1us** [FlafyDev/auto-nong-indexes#1000]
### Song Name

Wake up

### Artist Name

Kayzo, Riot

### Source

Youtube

### Youtube Link

https://youtu.be/FwSpKQaksVw?si=mhiOSY2LLeQT19Dl

### Direct File Link

https://youtu.be/6aKMPLUMe80?si=tD6XMGuqO0fMBhhf

### Song ID

535970

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
accept
