### ISSUE TITLE
A

### ISSUE THREAD

**Issue by Ahmadreza-1265** [FlafyDev/auto-nong-indexes#1005]
### Song Name

Ride

### Artist Name

One pilot

### Source

Youtube

### Youtube Link

https://youtu.be/zJ6bBrB-OBA?si=X1kH6dOIshPvT0EO

### Song ID

682387

**Comment by Ahmadreza-1265** [comment]
Accept

**Comment by SpuckwasserDE** [comment]
reject

already in the mod
