### ISSUE TITLE
Add Acheron But Wulzy Sings It (AI COVER) by bobliver

### ISSUE THREAD

**Issue by HypnoTronicGD** [FlafyDev/auto-nong-indexes#1006]
### Song Name

Acheron But Wulzy Sings It (AI COVER)

### Artist Name

bobliver

### Source

Youtube

### Youtube Link

3W4hLPg8t2Q

### Song ID

770520

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 73667628

**Comment by SpuckwasserDE** [comment]
accept
