### ISSUE TITLE
Add Junko Ohashi - Telephone Number (Nightcore) by Junko Ohashi

### ISSUE THREAD

**Issue by elosoelosoculiqo** [FlafyDev/auto-nong-indexes#1007]
### Song Name

Junko Ohashi - Telephone Number (Nightcore)

### Artist Name

Junko Ohashi

### Source

Youtube

### Youtube Link

ib2ANS-hlsrHEU1l

### Song ID

56709

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 56924070

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
