### ISSUE TITLE
Add Rude Buster by Toby Fox

### ISSUE THREAD

**Issue by DemiSans** [FlafyDev/auto-nong-indexes#1008]
### Song Name

Rude Buster

### Artist Name

Toby Fox

### Source

Youtube

### Youtube Link

j3SIINmTmNlLrGCb

### Song ID

847197

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 98757638

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
