### ISSUE TITLE
Add at the speed of paul by kingsammelot

### ISSUE THREAD

**Issue by wrth875** [FlafyDev/auto-nong-indexes#1023]
### Song Name

at the speed of paul

### Artist Name

dimrain47

### Source

Direct file download

### Youtube Link

view

### Direct File Link

https://drive.google.com/file/d/1U5li6uw4CvZFd_aymqDcPy_kZ8NdhZEc/view

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 64763376

**Comment by FlafyDev** [comment]
reject

Must be a link to a proper CDN, Not Google Drive, Dropbox or MediaFile. Or a YT video
