### ISSUE TITLE
Add Nong Song: OTIS

### ISSUE THREAD

**Issue by TeahersAreStupid1234** [FlafyDev/auto-nong-indexes#1024]
### Song Name

My Ordinary Life

### Artist Name

The Living Tombstone

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=9Zj0JOHJR-s

### Song ID

815246

### Start Offset [ms]

13000

**Comment by TeahersAreStupid1234** [comment]
Quick update: The music viideo has some filler effects, ill use the actual music video, so heres an update
```
{
  "name": "My Ordinary Life",
  "artist": "The Living Tombstone",
  "source": "youtube",
  "startOffset": 0,
  "yt-id": "WuzIw73pmSc",
  "songs": [
    815246
  ]
}
```

**Comment by TeahersAreStupid1234** [comment]
on skub8d8

**Comment by SpuckwasserDE** [comment]
reject

already in the mod
