### ISSUE TITLE
Add DJ -Nate Clubstep | (Geeser Remix) by gyzer

### ISSUE THREAD

**Issue by Lim1t5d** [FlafyDev/auto-nong-indexes#1028]
### Song Name

DJ -Nate Clubstep | (Geeser Remix)

### Artist Name

gyzer

### Source

Youtube

### Youtube Link

ycJDIMnsBBI

### Song ID

13

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 67836390
Thank you for creating this mod!

**Comment by FlafyDev** [comment]
reject

a similar submission was accepted a few minutes ago
