### ISSUE TITLE
Add Pineapple Sunrise by beachweather

### ISSUE THREAD

**Issue by syn-atomic** [FlafyDev/auto-nong-indexes#1029]
### Song Name

Pineapple Sunrise

### Artist Name

beachweather

### Source

Youtube

### Youtube Link

qfRWlSiJUuRmYCQq

### Song ID

787153

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107461969

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
