### ISSUE TITLE
fairydust x camelot by rukkus, NLE choppa

### ISSUE THREAD

**Issue by olrarr** [FlafyDev/auto-nong-indexes#1039]
### Song Name

fairydust x camelot

### Artist Name

rukkus, NLE choppa

### Source

Youtube

### Youtube Link

2iJIrDO7Ams

### Song ID

541786

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 5310094

**Comment by olrarr** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

mashups should have some popularity to show that people want it.
Note that you can still use the nong yourself, but it wont be public
