### ISSUE TITLE
Add Time Leaper (Low Pitch) by LowPitchGod

### ISSUE THREAD

**Issue by sebashtioon** [FlafyDev/auto-nong-indexes#1043]
### Song Name

Time Leaper (Low Pitch)

### Artist Name

LowPitchGod

### Source

Youtube

### Youtube Link

3o7MWL6noapRr2U1

### Song ID

683996

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 24301797

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
