### ISSUE TITLE
OOOOOO

### ISSUE THREAD

**Issue by AdolphinHitlinear** [FlafyDev/auto-nong-indexes#1048]
### Song Name

1234294

### Artist Name

ESTRELAR

### Source

Youtube

### Youtube Link

https://youtu.be/ozykI6kMs2c?si=NosgLUsLpQ-1tofh

### Song ID

157672

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 64937094

**Comment by comicsteel** [comment]
reject
