### ISSUE TITLE
Add Brain Wash by SEVENTHLINKS

### ISSUE THREAD

**Issue by Saltrain13** [FlafyDev/auto-nong-indexes#1053]
### Song Name

Brain Wash

### Artist Name

SEVENTHLINKS

### Source

Direct file download

### Youtube Link

9tlx1xQNvTs

### Direct File Link

https://drive.google.com/file/d/1fneI6xf9aAxf7tb8TPSfpelKSepUMVRn/view?usp=sharing

### Song ID

905108

### Start Offset [ms]

0

### Extra

Cool anime type song

**Comment by LousyBook-01** [comment]
reject

bruh the bot picked up the wrong url, google drive is not supported
