### ISSUE TITLE
Add FLAWLESS WINGS OF Yatagarasu X BIG DICK RANDY by karalislol

### ISSUE THREAD

**Issue by gugus358** [FlafyDev/auto-nong-indexes#1055]
### Song Name

FLAWLESS WINGS OF Yatagarasu X BIG DICK RANDY

### Artist Name

karalislol

### Source

Youtube

### Youtube Link

UpYOv-LZDkSRaSH-

### Song ID

490479

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 41782371

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
