### ISSUE TITLE
Add Nova by Ahrix

### ISSUE THREAD

**Issue by CyZcodes** [FlafyDev/auto-nong-indexes#1058]
### Song Name

Nova

### Artist Name

Ahrix

### Source

Youtube

### Youtube Link

0lif67PwB9U7xpPN

### Song ID

592052

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 9948921

**Comment by CyZcodes** [comment]
> Thanks for contributing! Someone will soon review your request.
> 
> Here is the JSON result for the reviewer:
> 
> ```json
> {
>   "name": "Nova",
>   "artist": "Ahrix",
>   "source": "youtube",
>   "startOffset": 0,
>   "yt-id": "0lif67PwB9U7xpPN",
>   "songs": [
>     592052
>   ]
> }
> ```
> 
> To accept the request, a reviewer needs to write "accept".

accept

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
