### ISSUE TITLE
Add Crazy x Fenda da Sunga by Mc VV

### ISSUE THREAD

**Issue by Trozu** [FlafyDev/auto-nong-indexes#1064]
### Song Name

Crazy x Fenda da Sunga

### Artist Name

Mc VV

### Source

Direct file download

### Direct File Link

https://drive.google.com/file/d/1c_Rz9LcIO3pAwR8kPHnzqyp96zT-hr8m/view

### Song ID

905108

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86018142

**Comment by FlafyDev** [comment]
reject

Must be a link to a proper CDN, Not Google Drive, Dropbox or MediaFile. Or a YT video
