### ISSUE TITLE
rapture by interworld

### ISSUE THREAD

**Issue by Sonicblast4** [FlafyDev/auto-nong-indexes#1069]
### Song Name

rapture

### Artist Name

interworld

### Source

Youtube

### Youtube Link

g-yYDwGghMVzR-K6

### Direct File Link

https://youtube.com/watch?v=QJufE7T0tGo&si=RN2Q5V5oL6Jy1FVm

### Song ID

1230880

### Start Offset [ms]

2

### Extra

Created from Auto Nong.
Created for level: 97377502

**Comment by Sonicblast4** [comment]
For geometry dash

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
