### ISSUE TITLE
Add Creo - Sphere x kiss me more by Shlant

### ISSUE THREAD

**Issue by DXC3Y** [FlafyDev/auto-nong-indexes#1070]
### Song Name

Creo - Sphere x kiss me more

### Artist Name

Shlant

### Source

Youtube

### Youtube Link

wysOhAxIRBy-rJ3P

### Song ID

739991

### Start Offset [ms]

23

### Extra

Created from Auto Nong.
Created for level: 52374843

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
