### ISSUE TITLE
Add Raining Sunshine by Miranda Cosgrove

### ISSUE THREAD

**Issue by scaryb6** [FlafyDev/auto-nong-indexes#1083]
### Song Name

Raining Sunshine

### Artist Name

Miranda Cosgrove

### Source

Youtube

### Youtube Link

lVkWnbORe6AKPI-4

### Song ID

619258

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 45818039

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
