### ISSUE TITLE
Add Mtg Girl A (Young Girl Funk Remix X Sonic Exe) by MBF and more

### ISSUE THREAD

**Issue by Imshinora** [FlafyDev/auto-nong-indexes#1084]
### Song Name

Mtg Girl A (Young Girl Funk Remix X Sonic Exe)

### Artist Name

MBF and more

### Source

Youtube

### Youtube Link

xi0Shzk1wsanfujz

### Song ID

1284048

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 99497425

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
