### ISSUE TITLE
Add Sonic Blaster (3in1) by f777, decody and hjfod

### ISSUE THREAD

**Issue by DEBILlord** [FlafyDev/auto-nong-indexes#1094]
### Song Name

Sonic Blaster (3in1)

### Artist Name

f777, decody and hjfod

### Source

Youtube

### Youtube Link

6gR3aoiQWLgfmwj_

### Song ID

574484

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 102265892
maybe it good?

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
