### ISSUE TITLE
FETCH

### ISSUE THREAD

**Issue by zenvo-white** [FlafyDev/auto-nong-indexes#1098]
### Song Name

the fetch song

### Artist Name

Dawko & DHeusta

### Source

Youtube

### Youtube Link

https://youtu.be/lUFQrPixgfk?si=mxDkyzMf4_Jjlcvq

### Song ID

689654

### Start Offset [ms]

0

**Comment by notmika126** [comment]
good song zen.

**Comment by notmika126** [comment]
accept

**Comment by zenvo-white** [comment]
> good song zen, i wanna make a level with it

thanks mika

**Comment by zenvo-white** [comment]
i wanna make a level with it too

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Hop" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
