### ISSUE TITLE
Add blunder for the level "blunder"

### ISSUE THREAD

**Issue by HamzaAbudaqa** [FlafyDev/auto-nong-indexes#1101]
### Song Name

blunder

### Artist Name

idk

### Source

Youtube

### Youtube Link

YB5p0k8-DQo

### Song ID

346

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 89384184

**Comment by SpuckwasserDE** [comment]
reject

artist name must be descriptive
