### ISSUE TITLE
Add PIKITO by RUSOWSKY

### ISSUE THREAD

**Issue by ZcoofGF** [FlafyDev/auto-nong-indexes#1112]
### Song Name

PIKITO

### Artist Name

RUSOWSKY

### Source

Youtube

### Youtube Link

https://youtu.be/DPqULcZXuGE?si=TvON6j5ehxMZ7P8Q

### Song ID

8

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107571033

**Comment by SpuckwasserDE** [comment]
reject

duplicate request, see issue 1111
