### ISSUE TITLE
Add Nong Song: Get Out

### ISSUE THREAD

**Issue by CoderMonkey1956** [FlafyDev/auto-nong-indexes#1118]
### Song Name

GET OUT

### Artist Name

DAGames

### Source

Youtube

### Youtube Link

https://youtu.be/ziaf3RrG80U?si=P4fFDQc3iD_GYkyM

### Song ID

475234

### Start Offset [ms]

0

### Extra

Used in the level "Get Out"

Id: 107010635

**Comment by SpuckwasserDE** [comment]
reject

kinda confused here, does this replace run or stereo madness? either way
popular songs are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
