### ISSUE TITLE
Add fixer by idk 

### ISSUE THREAD

**Issue by TriaosloverOo** [FlafyDev/auto-nong-indexes#1123]
### Song Name

fixer

### Artist Name

idk 

### Source

Youtube

### Youtube Link

xxV9fXcXQe3hg0qb

### Song ID

458479

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 77255632

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
