### ISSUE TITLE
Mans Not Time Machine

### ISSUE THREAD

**Issue by ZeroAero** [FlafyDev/auto-nong-indexes#1132]
### Song Name

Time Machine Mashup

### Artist Name

Big Shaq

### Source

Youtube

### Youtube Link

https://youtu.be/J60GlzoU6vo?si=OtDRN3xodvNI5enQ

### Song ID

7

### Start Offset [ms]

0

### Extra

Used in the Level "Time Machine v2" or anything else with Time Machine as the song.

**Comment by ZeroAero** [comment]
I specially requested this for Time Machine v2 btw

**Comment by ZeroAero** [comment]
its still open

**Comment by SpuckwasserDE** [comment]
reject

needs an offset (out of sync)
