### ISSUE TITLE
Add Grissinbon by Grissinbon

### ISSUE THREAD

**Issue by cessobarese** [FlafyDev/auto-nong-indexes#1137]
### Song Name

Grissinbon

### Artist Name

Grissinbon

### Source

Youtube

### Youtube Link

sLQ98JkbIEPqhEFO

### Song ID

1309683

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 103365876

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
