### ISSUE TITLE
Add Zodiac x happier mashup by AidanTR

### ISSUE THREAD

**Issue by Hugtaper** [FlafyDev/auto-nong-indexes#1138]
### Song Name

Zodiac x happier mashup

### Artist Name

AidanTR

### Source

Youtube

### Youtube Link

3ARqE-cxgjk

### Song ID

739991

### Start Offset [ms]

-22000

### Extra

Created from Auto Nong.
Created for level: 106424300

**Comment by Hugtaper** [comment]
probably one of the best mashup i can find

**Comment by FlafyDev** [comment]
accept

nice
