### ISSUE TITLE
Add Time Leaper x Etzer by Hinkik

### ISSUE THREAD

**Issue by Q9769611** [FlafyDev/auto-nong-indexes#1140]
### Song Name

Time Leaper x Etzer

### Artist Name

Hinkik

### Source

Youtube

### Youtube Link

https://youtu.be/giNn4BdCPw0?si=V1G1EkHkopcEWdtD

### Song ID

683996

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 24301797

**Comment by Q9769611** [comment]
Yes, I accept.

**Comment by SpuckwasserDE** [comment]
reject

already in the mod
