### ISSUE TITLE
Add Kyouki if it had good music by enculoj16

### ISSUE THREAD

**Issue by egorzo** [FlafyDev/auto-nong-indexes#1144]
### Song Name

Kyouki if it had good music

### Artist Name

enculoj16

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=JJMNYeq75uo

### Direct File Link

https://www.youtube.com/watch?v=JJMNYeq75uo

### Song ID

905108

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86018142

**Comment by FlafyDev** [comment]
reject
