### ISSUE TITLE
Add At The speed of light by Dmrain47

### ISSUE THREAD

**Issue by Asmatheo** [FlafyDev/auto-nong-indexes#1155]
### Song Name

At The speed of light

### Artist Name

Dmrain47

### Source

Youtube

### Youtube Link

https://youtu.be/rlWtSEFfIu0?si=lD9nThwy6DAapuLM

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 3979721

**Comment by AJXPRO** [comment]
reject
