### ISSUE TITLE
Add Nova by Ahrix

### ISSUE THREAD

**Issue by CyZcodes** [FlafyDev/auto-nong-indexes#1163]
### Song Name

Nova

### Artist Name

Ahrix

### Source

Youtube

### Youtube Link

X5mcY8ecs8I

### Song ID

592052

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 4981164

**Comment by CyZcodes** [comment]
Accept

**Comment by CyZcodes** [comment]
> Thanks for contributing! Someone will soon review your request.
> 
> Here is the JSON result for the reviewer:
> 
> ```json
> {
>   "name": "Nova",
>   "artist": "Ahrix",
>   "source": "youtube",
>   "startOffset": 0,
>   "yt-id": "X5mcY8ecs8I",
>   "songs": [
>     592052
>   ]
> }
> ```
> 
> To accept the request, a reviewer needs to write "accept".

this is current request

**Comment by CyZcodes** [comment]
> auto

accept

**Comment by CyZcodes** [comment]
> Thanks for contributing! Someone will soon review your request.
> 
> Here is the JSON result for the reviewer:
> 
> ```json
> {
>   "name": "Nova",
>   "artist": "Ahrix",
>   "source": "youtube",
>   "startOffset": 0,
>   "yt-id": "X5mcY8ecs8I",
>   "songs": [
>     592052
>   ]
> }
> ```
> 
> To accept the request, a reviewer needs to write "accept".

accept

**Comment by SpuckwasserDE** [comment]
accept
