### ISSUE TITLE
Add Storyteller by Daisuke Ishiwatari

### ISSUE THREAD

**Issue by amogusfr** [FlafyDev/auto-nong-indexes#1169]
### Song Name

Storyteller

### Artist Name

Daisuke Ishiwatari

### Source

Youtube

### Youtube Link

mg8_7SfwdfY

### Song ID

769216

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107629990

**Comment by SpuckwasserDE** [comment]
accept
