### ISSUE TITLE
Add Infectious ( Original Mix ) by Tobu, 7obu

### ISSUE THREAD

**Issue by CyZcodes** [FlafyDev/auto-nong-indexes#1171]
### Song Name

Infectious ( Original Mix )

### Artist Name

Tobu, 7obu

### Source

Youtube

### Youtube Link

qlinKNqHCyg

### Song ID

593702

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 4363865

**Comment by neprao** [comment]
accept
