### ISSUE TITLE
Add Infectious ( Piano Version ) by Tobu, 7obu, AsdKeys

### ISSUE THREAD

**Issue by CyZcodes** [FlafyDev/auto-nong-indexes#1172]
### Song Name

Infectious ( Piano Version )

### Artist Name

Tobu, 7obu, AsdKeys

### Source

Youtube

### Youtube Link

g_jEGcjpiyk

### Song ID

593702

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 4363865

**Comment by FlafyDev** [comment]
reject

doesn't sync with the level
