### ISSUE TITLE
Thanks for contributing!

### ISSUE THREAD

**Issue by CyZcodes** [FlafyDev/auto-nong-indexes#1173]
Thanks for contributing!
Someone will soon review your request.

Here is the JSON result for the reviewer:
```json
{
  "name": "Infectious ( NoCopyrightSounds Mix )",
  "artist": "Tobu, 7obu, NoCopyrightSounds",
  "source": "youtube",
  "startOffset": 0,
  "yt-id": "MCxjJV9nQjw",
  "songs": [
    593702
  ]
}
```
To accept the request, a reviewer needs to write "accept".

_Originally posted by @auto-nong[bot] in https://github.com/FlafyDev/auto-nong-indexes/issues/1170#issuecomment-2219708617_

**Comment by Daepicgdplayer** [comment]
reject
This can not be accepted because it's missing everything.  Please make an new post with the right info.
