### ISSUE TITLE
Add Dark Dragon Fire x The Spectre (Mashup) by F-777

### ISSUE THREAD

**Issue by ductmuddy** [FlafyDev/auto-nong-indexes#1176]
### Song Name

Dark Dragon Fire x The Spectre (Mashup)

### Artist Name

F-777

### Source

Youtube

### Youtube Link

https://youtu.be/FpiDtFA_XtU?si=kk3snusXQtQoT1Xl

### Song ID

91656

### Start Offset [ms]

75

### Extra

Created from Auto Nong.
Created for level: 89496627

**Comment by FlafyDev** [comment]
reject

doesn't sync!
