### ISSUE TITLE
Add CG5 - GRIMACE (Official Song) by CG5

### ISSUE THREAD

**Issue by salmangufari** [FlafyDev/auto-nong-indexes#1179]
### Song Name

CG5 - GRIMACE (Official Song)

### Artist Name

CG5

### Source

Youtube

### Youtube Link

4cg1TXO4KO19SC0X

### Song ID

54795

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 93688232

**Comment by salmangufari** [comment]
I'm sorry if the Nong is early, I don't know where to cut the song from

**Comment by neprao** [comment]
reject

invalid youtube link
