### ISSUE TITLE
Add Explorers  by Hinkik

### ISSUE THREAD

**Issue by Therealcapybara1641** [FlafyDev/auto-nong-indexes#1182]
### Song Name

Explorers 

### Artist Name

Hinkik

### Source

Youtube

### Youtube Link

eVKdgbudIHeFhUbx

### Song ID

22

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 98450100

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
