### ISSUE TITLE
Add ahegao by maxime link 

### ISSUE THREAD

**Issue by kazudrig0** [FlafyDev/auto-nong-indexes#1186]
### Song Name

ahegao

### Artist Name

maxime link 

### Source

Youtube

### Youtube Link

ir5M_x4dxbo

### Direct File Link

https://www.youtube.com/watch?v=ir5M_x4dxbo

### Song ID

76743

### Start Offset [ms]

200

### Extra

Created from Auto Nong.
Created for level: 86084399

**Comment by SpuckwasserDE** [comment]
reject

popular songs like isolation are too inconvenient to be replaced by smth unrelated.
