### ISSUE TITLE
Add zayavka na evrovidinie by nikver

### ISSUE THREAD

**Issue by gmdotchim** [FlafyDev/auto-nong-indexes#1188]
### Song Name

zayavka na evrovidinie

### Artist Name

nikver

### Source

Youtube

### Youtube Link

TGlcVzGWovB89hd4

### Song ID

1024087

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 71216292

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
