### ISSUE TITLE
Sonic Wave

### ISSUE THREAD

**Issue by XUnfair** [FlafyDev/auto-nong-indexes#1189]
### Song Name

Sonic Blaster x Katy Perry Last Friday Night

### Artist Name

YoFridayGamer

### Source

Youtube

### Youtube Link

https://youtu.be/lyZ66nL006s?si=_5hGHO9A5hwzD3CG

### Song ID

574484

**Comment by SpuckwasserDE** [comment]
reject

already in the mod - "sonic blaster x katy perry"
