### ISSUE TITLE
Sonic boss

### ISSUE THREAD

**Issue by Sergio94-dev** [FlafyDev/auto-nong-indexes#1190]
### Song Name

sonic boss saundtrack

### Artist Name

sega

### Source

Youtube

### Youtube Link

ZHG-vSAyGnrX_TRX

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 1244147

**Comment by SpuckwasserDE** [comment]
@Sergio94-dev accept needs to be lower case

**Comment by FlafyDev** [comment]
reject

invalid yt ID.

> accept needs to be lower case

they don't even have perms lol

**Comment by Sergio94-dev** [comment]
Accept
