### ISSUE TITLE
Add Ijime, Dame, Zettai by BABYMETAL

### ISSUE THREAD

**Issue by marlonus** [FlafyDev/auto-nong-indexes#1196]
### Song Name

Ijime, Dame, Zettai

### Artist Name

BABYMETAL

### Source

Youtube

### Youtube Link

nDqaTXqCN-Q

### Song ID

1237542

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107655274

**Comment by neprao** [comment]
accept
