### ISSUE TITLE
Add XO (Npesta cover) by Eden

### ISSUE THREAD

**Issue by MarkimedesisHere** [FlafyDev/auto-nong-indexes#1198]
### Song Name

XO (Npesta cover)

### Artist Name

Eden

### Source

Youtube

### Youtube Link

8JH314TVnaY

### Song ID

766165

### Start Offset [ms]

8000

### Extra

Created from Auto Nong.
Created for level: 58825144

**Comment by neprao** [comment]
reject

**Comment by neprao** [comment]
reject

doesnt sync
