### ISSUE TITLE
Add At Speed Of Light (lightcube remix) by Dimrain47

### ISSUE THREAD

**Issue by EmanetGamer** [FlafyDev/auto-nong-indexes#1202]
### Song Name

At Speed Of Light (lightcube remix)

### Artist Name

Dimrain47

### Source

Youtube

### Youtube Link

_nHWc096QDU

### Song ID

467339

### Start Offset [ms]

945

### Extra

Created from Auto Nong.
Created for level: 77428474

**Comment by GDFainter** [comment]
accept

**Comment by neprao** [comment]
accept
