### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by UniF1shl** [FlafyDev/auto-nong-indexes#1203]
### Song Name

After Dark x Sweater Weather

### Artist Name

Gerson

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=KPq5DGaSQ9I

### Song ID

10

### Extra

"Kerosene house" - 96733442

**Comment by UniF1shl** [comment]
accept

**Comment by neprao** [comment]
accept

im the one who accepts buddy 💀

**Comment by UniF1shl** [comment]
@neprao tysm!
