### ISSUE TITLE
Add WOULD YOU RUN by TRI.BE

### ISSUE THREAD

**Issue by Rdrgz0712** [FlafyDev/auto-nong-indexes#1204]
### Song Name

WOULD YOU RUN

### Artist Name

TRI.BE

### Source

Youtube

### Youtube Link

nfQHnabtJfM

### Song ID

100724

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107666493

**Comment by neprao** [comment]
accept

**Comment by Rdrgz0712** [comment]
Tysm!
