### ISSUE TITLE
Add RINGO by ITZY

### ISSUE THREAD

**Issue by Rdrgz0712** [FlafyDev/auto-nong-indexes#1205]
### Song Name

RINGO

### Artist Name

ITZY

### Source

Youtube

### Youtube Link

https://music.youtube.com/watch?v=57M-OOclIjU&si=B0pYgFwNMkFi0A4J

### Song ID

100324

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 102255630

**Comment by GDFainter** [comment]
accept
