### ISSUE TITLE
Add Candyland by Tobu, 7obu

### ISSUE THREAD

**Issue by CyZcodes** [FlafyDev/auto-nong-indexes#1206]
### Song Name

Candyland

### Artist Name

Tobu, 7obu

### Source

Youtube

### Youtube Link

lhchfhxvPKI

### Song ID

620710

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 9833189

**Comment by CyZcodes** [comment]
This is wrong

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
