### ISSUE TITLE
Add Candyland by Tobu, 7obu

### ISSUE THREAD

**Issue by CyZcodes** [FlafyDev/auto-nong-indexes#1207]
### Song Name

Candyland

### Artist Name

Tobu, 7obu

### Source

Youtube

### Youtube Link

IhchfhxvPKI

### Song ID

620710

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 9833189

**Comment by CyZcodes** [comment]
Current issue

**Comment by GDFainter** [comment]
accept

**Comment by SpuckwasserDE** [comment]
accept
