### ISSUE TITLE
Add Life ( NoCopyrightSounds Mix ) by Tobu, 7obu, NoCopyrightSounds

### ISSUE THREAD

**Issue by CyZcodes** [FlafyDev/auto-nong-indexes#1209]
### Song Name

Life ( NoCopyrightSounds Mix )

### Artist Name

Tobu, 7obu, NoCopyrightSounds

### Source

Youtube

### Youtube Link

wxPplfyl1_M

### Song ID

604075

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 9934280

**Comment by GDFainter** [comment]
accept
