### ISSUE TITLE
Add Hope ( NoCopyrightSounds Version ) by Tobu, 7obu, NoCopyrightSounds

### ISSUE THREAD

**Issue by CyZcodes** [FlafyDev/auto-nong-indexes#1210]
### Song Name

Hope ( NoCopyrightSounds Version )

### Artist Name

Tobu, 7obu, NoCopyrightSounds

### Source

Youtube

### Youtube Link

aSi7mt3Z_ys

### Song ID

595696

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 23288969

**Comment by GDFainter** [comment]
accept
