### ISSUE TITLE
Add Hope ( Tobu Version ) by Tobu, 7obu

### ISSUE THREAD

**Issue by CyZcodes** [FlafyDev/auto-nong-indexes#1211]
### Song Name

Hope ( Tobu Version )

### Artist Name

Tobu, 7obu

### Source

Youtube

### Youtube Link

Y1Z3Q3O7IRE

### Song ID

595696

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 23288969

**Comment by GDFainter** [comment]
accept
