### ISSUE TITLE
Add Cloud 9 by Tobu, 7obu

### ISSUE THREAD

**Issue by CyZcodes** [FlafyDev/auto-nong-indexes#1213]
### Song Name

Cloud 9

### Artist Name

Tobu, 7obu

### Source

Youtube

### Youtube Link

1KqQQHpQc8w

### Song ID

604269

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 20680616

**Comment by GDFainter** [comment]
accept
