### ISSUE TITLE
Add Cloud 9 ( NoCopyrightSounds Mix ) by Tobu, 7obu, NoCopyrightSounds

### ISSUE THREAD

**Issue by CyZcodes** [FlafyDev/auto-nong-indexes#1214]
### Song Name

Cloud 9 ( NoCopyrightSounds Mix )

### Artist Name

Tobu, 7obu, NoCopyrightSounds

### Source

Youtube

### Youtube Link

FZa2yA7r-T0

### Song ID

604269

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 20680616

**Comment by GDFainter** [comment]
Acccept (cause original copyrighted)

**Comment by GDFainter** [comment]
accept
