### ISSUE TITLE
Add star u by star u

### ISSUE THREAD

**Issue by atrexxgd** [FlafyDev/auto-nong-indexes#1219]
### Song Name

star u

### Artist Name

star u

### Source

Youtube

### Youtube Link

Cj-KpO6Q1lOHymPO

### Song ID

99999999999

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 13519

**Comment by SpuckwasserDE** [comment]
reject

wrong song id and invalid YouTube link
