### ISSUE TITLE
Add Nong Song: VIII

### ISSUE THREAD

**Issue by SeraphinePlus** [FlafyDev/auto-nong-indexes#1227]
### Song Name

VIII

### Artist Name

Cight

### Source

Youtube

### Youtube Link

https://youtu.be/jMp0n1CJ1k4?si=hkImSd_riq-HocgT

### Song ID

176929

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

the delay is off by a lot. Please test the nongs you are submitting before you submit them
