### ISSUE TITLE
Add Freedom Dive by XI

### ISSUE THREAD

**Issue by Vlentcalderon** [FlafyDev/auto-nong-indexes#1228]
### Song Name

Freedom Dive

### Artist Name

XI

### Source

Youtube

### Youtube Link

ozhgVit7Uld3Ejrl

### Song ID

712779

### Start Offset [ms]

1.5

### Extra

Created from Auto Nong.
Created for level: 57225251

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
