### ISSUE TITLE
sonic boss saundtrack by sega

### ISSUE THREAD

**Issue by Sergio94-dev** [FlafyDev/auto-nong-indexes#1229]
### Song Name

sonic boss saundtrack

### Artist Name

sega

### Source

Youtube

### Youtube Link

ZHG-vSAyGnrX_TRX

### Song ID

1908

### Start Offset [ms]

3

### Extra

Created from Auto Nong.
Created for level: 1244147

**Comment by Sergio94-dev** [comment]
Accept

**Comment by neprao** [comment]
reject

youtube link doesnt work
