### ISSUE TITLE
Add Nong Song: DANCE TILL YOU'RE DEAD

### ISSUE THREAD

**Issue by FrozenPaperclip** [FlafyDev/auto-nong-indexes#1231]
### Song Name

DANCE TILL YOU'RE DEAD

### Artist Name

RagenYT

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=r5_NvFTfAWc

### Song ID

1

### Start Offset [ms]

0

**Comment by neprao** [comment]
accept
