### ISSUE TITLE
Add FIREWORK MASHUP | Classical Idol - Classical VIP x IDOL | Geometry Dash by Deji [GMD]

### ISSUE THREAD

**Issue by mintydoesthings** [FlafyDev/auto-nong-indexes#1232]
### Song Name

FIREWORK MASHUP | Classical Idol - Classical VIP x IDOL | Geometry Dash

### Artist Name

Deji [GMD]

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=_PyRO7XXxq4

### Song ID

502268

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 75206202

**Comment by neprao** [comment]
accept
