### ISSUE TITLE
Add CaseOh Wave by CaseOh

### ISSUE THREAD

**Issue by ThePeanutBrain** [FlafyDev/auto-nong-indexes#1235]
### Song Name

CaseOh Wave

### Artist Name

CaseOh

### Source

Youtube

### Youtube Link

hdkcIdq-lHM

### Song ID

1266014

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86407629

**Comment by Cosmo304** [comment]
Reject

**Comment by Cosmo304** [comment]
reject
