### ISSUE TITLE
Add Rush ABCDEFG Tuned by Dominatrus, Kellon, and SMB

### ISSUE THREAD

**Issue by Dominatrus** [FlafyDev/auto-nong-indexes#1236]
### Song Name

Rush ABCDEFG Tuned

### Artist Name

Dominatrus, Kellon, and SMB

### Source

Youtube

### Youtube Link

pz48zgLGKUo

### Song ID

845288

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 64026102

**Comment by vsaucing** [comment]
accept

**Comment by FlafyDev** [comment]
.reject

doesn't sync
