### ISSUE TITLE
Add Times Up by TheFatRatxHinkik

### ISSUE THREAD

**Issue by Chrisfrm54** [FlafyDev/auto-nong-indexes#1237]
### Song Name

Times Up

### Artist Name

TheFatRatxHinkik

### Source

Youtube

### Youtube Link

https://m.youtube.com/watch?time_continue=2&v=EbqT9oaLQ-o&embeds_referring_euri=https%3A%2F%2Fwww.google.com%2Fsearch%3Fq%3Drise%2Bup%2Bx%2Btime%2Bleapwe%26oq%3Drise%2Bup%2Bx%2Btime%2Bleapwe%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOTIHCAEQABiABDIHCAIQA&source_ve_path=Mjg2NjY&feature=emb_logo

### Song ID

683996

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 27581663

**Comment by vsaucing** [comment]
accept

**Comment by vsaucing** [comment]
u cooked with dat level
