### ISSUE TITLE
Add Terbang Bersamaku by DJ Asahan

### ISSUE THREAD

**Issue by GDplayer1234** [FlafyDev/auto-nong-indexes#1238]
### Song Name

Terbang Bersamaku

### Artist Name

DJ Asahan

### Source

Youtube

### Youtube Link

https://youtu.be/E6Jxo_VBj3U?feature=shared

### Song ID

755488

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107673613

**Comment by vsaucing** [comment]
accept
