### ISSUE TITLE
Add Up! by Connor Price

### ISSUE THREAD

**Issue by JosueSerrato** [FlafyDev/auto-nong-indexes#1240]
### Song Name

Up by Connor Price & Forrest Frank

### Artist Name

Connor Price & Forrest Frank

### Source

Direct file download

### Youtube Link

https://youtu.be/wCw-W-2Rs0k?si=uZ3H1Q9WZDLyWcOo

### Direct File Link

https://www.mediafire.com/file/hi09rltk40ya6nx/Connor_Price_%2526_Forrest_Frank_-_UP%2521_%2528Official_Video%2529.mp3/file

### Song ID

702947

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 60871123

**Comment by vsaucing** [comment]
accept

**Comment by FlafyDev** [comment]
.reject

mediafire not supported

**Comment by vsaucing** [comment]
> .reject
> 
> mediafire not supported

It has a YouTube link also?
