### ISSUE TITLE
Add Tu falta de querer by Mon Laferte

### ISSUE THREAD

**Issue by Alepei9774** [FlafyDev/auto-nong-indexes#1242]
### Song Name

Tu falta de querer

### Artist Name

Mon Laferte

### Source

Youtube

### Youtube Link

https://youtu.be/WT-VE9OyAJk?si=p0uNlJuk-JOUOURs

### Song ID

701013

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 44062068

**Comment by Alepei9774** [comment]
Accept

**Comment by neprao** [comment]
reject


wants to replace a famous song
