### ISSUE TITLE
Add Tu falta de querer by Mon Laferte

### ISSUE THREAD

**Issue by Alepei9774** [FlafyDev/auto-nong-indexes#1243]
### Song Name

Tu falta de querer

### Artist Name

Mon Laferte

### Source

Youtube

### Youtube Link

https://youtu.be/WT-VE9OyAJk?si=p0uNlJuk-JOUOURs

### Direct File Link

Mon Laferte - Tu Falta De Querer (En Vivo)_1720736942390.mp3

### Song ID

701013

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 44062068

**Comment by neprao** [comment]
reject

wants to replace a famous song
