### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by Kway345** [FlafyDev/auto-nong-indexes#1245]
### Song Name

Kyouki right version

### Artist Name

idk

### Source

Youtube

### Youtube Link

https://youtu.be/vQrgg1Lw5y8?si=6R6Y-yKKFDSfWOYG

### Song ID

905108

### Start Offset [ms]

9

### Extra

use in kyouki elpepe wazaaa

**Comment by vsaucing** [comment]
no level named  kyouki elpepe wazaaa so denied
