### ISSUE TITLE
Add Dio Helix by Desolo Zantos

### ISSUE THREAD

**Issue by blooket-guy** [FlafyDev/auto-nong-indexes#1247]
### Song Name

Dio Helix

### Artist Name

Desolo Zantos

### Source

Youtube

### Youtube Link

EGks5AQbTyM

### Song ID

631160

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107705782

**Comment by vsaucing** [comment]
blank level denied
