### ISSUE TITLE
Add Candyland [NCS Release] by Tobu

### ISSUE THREAD

**Issue by Bravlov** [FlafyDev/auto-nong-indexes#1251]
### Song Name

Candyland [NCS Release]

### Artist Name

Tobu

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=bJ-ldzTkJEA

### Song ID

620710

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level:

**Comment by vsaucing** [comment]
for level what? denied.

**Comment by LousyBook-01** [comment]
accept

@vsaucing it is a not allowed song on newgrounds, so this can be used, this is correct
