### ISSUE TITLE
Add Nong Song: The Amazing Limbo x Insolation (KingSammelot cover)

### ISSUE THREAD

**Issue by AnAcaRaAlt** [FlafyDev/auto-nong-indexes#1252]
### Song Name

The Amazing Limbo x Insolation (KingSammelot cover)

### Artist Name

Bigthunder556

### Source

Youtube

### Youtube Link

https://youtu.be/eoj5VxiDF3U

### Song ID

76743

### Extra

User in the level "Limbo": 86084399

**Comment by vsaucing** [comment]
i deny this

**Comment by LousyBook-01** [comment]
accept

this sounds like my school classroom
