### ISSUE TITLE
MURDER IN MY MIND 

### ISSUE THREAD

**Issue by gab-sketch** [FlafyDev/auto-nong-indexes#1255]
### Song Name

Murder In My Mind 

### Artist Name

KORDHELL

### Source

Youtube

### Youtube Link

https://youtu.be/w-sQRS-Lc9k?si=uLiUiokzLtwIM2mQ

### Song ID

33333

### Start Offset [ms]

0

### Extra

Used in Level: Murder In My Mind - 87265181

**Comment by SpuckwasserDE** [comment]
reject

already in the mod
