### ISSUE TITLE
Add Gangsta's Paradise x Sakupen Hell Yes Remix by YaBoiMega

### ISSUE THREAD

**Issue by Jalovec7997** [FlafyDev/auto-nong-indexes#1256]
### Song Name

Gangsta's Paradise x Sakupen Hell Yes Remix

### Artist Name

YaBoiMega

### Source

Youtube

### Youtube Link

WhPq7dzyMDUPMMmw

### Song ID

360804

### Start Offset [ms]

0

### Extra

Created from Auto Nong.

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
