### ISSUE TITLE
Add Suffer (Ft. Skoot) by Petit Biscuit

### ISSUE THREAD

**Issue by Chel2212** [FlafyDev/auto-nong-indexes#1258]
### Song Name

Suffer (Ft. Scoot)

### Artist Name

Petit Biscuit

### Source

Youtube

### Youtube Link

FoHr23PYwaZm-5ni

### Song ID

985524

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 71195247

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
