### ISSUE TITLE
Add ferocious by sky

### ISSUE THREAD

**Issue by ZorxFait** [FlafyDev/auto-nong-indexes#1259]
### Song Name

ferocious

### Artist Name

sky

### Source

Youtube

### Youtube Link

https://youtu.be/eLmDZQ7KgVw?si=DOz02wDMflra3dwV

### Song ID

10003069

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 97571110

**Comment by SpuckwasserDE** [comment]
reject

the name should be more descriptive, stating for example that this is instrumental
