### ISSUE TITLE
Add KOCMOC killoway cover by killoway

### ISSUE THREAD

**Issue by CrazyGrach** [FlafyDev/auto-nong-indexes#1260]
### Song Name

KOCMOC killoway cover

### Artist Name

killoway

### Source

Youtube

### Youtube Link

ioXKzmMcyao

### Song ID

1163222

### Start Offset [ms]

81000

### Extra

Created from Auto Nong.
Created for level: 87665224

**Comment by LousyBook-01** [comment]
accept
