### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by CLXUDMANE** [FlafyDev/auto-nong-indexes#1261]
### Song Name

The attack of the dead men

### Artist Name

Sabaton

### Source

Youtube

### Youtube Link

https://youtu.be/-AFdwoyNT24?si=7foOGphrCScGPmuJ

### Song ID

830628

### Extra

used in Osowiec

**Comment by CLXUDMANE** [comment]
accept

**Comment by vsaucing** [comment]
reject
level does not exist
