### ISSUE TITLE
Add Sonic Blaster x Bad Apple by F777

### ISSUE THREAD

**Issue by TheSpheric** [FlafyDev/auto-nong-indexes#1262]
### Song Name

Sonic Blaster x Bad Apple

### Artist Name

F777

### Source

Youtube

### Youtube Link

Tm7cQqVaafY

### Song ID

574484

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 26681070

**Comment by AJXPRO** [comment]
accept

**Comment by SpuckwasserDE** [comment]
accept
