### ISSUE TITLE
Add ABYSS OF DARKNESS BADMAN MASHUP by CafneZ

### ISSUE THREAD

**Issue by MalteKH** [FlafyDev/auto-nong-indexes#1263]
### Song Name

ABYSS OF DARKNESS BADMAN MASHUP

### Artist Name

CafneZ

### Source

Youtube

### Youtube Link

NNnnrjs5qng

### Song ID

513539

### Start Offset [ms]

4150

### Extra

Created from Auto Nong.
Created for level: 49896559

**Comment by AJXPRO** [comment]
accept
