### ISSUE TITLE
Add Stereo Madness (Rock Cover) by Creepy Team

### ISSUE THREAD

**Issue by Gd64bit** [FlafyDev/auto-nong-indexes#1265]
### Song Name

Stereo Madness (Rock Cover)

### Artist Name

Creepy Team

### Source

Youtube

### Youtube Link

2ope1-3fvSg

### Song ID

0

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107510523

**Comment by LousyBook-01** [comment]
accept

epic stereo madness cover
