### ISSUE TITLE
Add Sendan Life (Katagiri Bootleg) by Shoue, Katagiri

### ISSUE THREAD

**Issue by Arturviper0** [FlafyDev/auto-nong-indexes#1268]
### Song Name

Sendan Life (Katagiri Bootleg)

### Artist Name

Shoue, Katagiri

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=ZgjrL8XDNEQ

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 106590574

**Comment by Arturviper0** [comment]
accept

**Comment by LousyBook-01** [comment]
accept

i guess? also @Arturviper0  bro you are not a mod, anyways thanks for adding a song
