### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by Alanazo** [FlafyDev/auto-nong-indexes#127]
### Song Name

Nene malo

### Artist Name

Naim_

### Source

Youtube

### Youtube Link

https://youtu.be/r7qr20wa3Aw?si=P8aBJDLMJIGgvbIG

### Direct File Link

https://drive.google.com/file/d/1mquWAtOGDQslwoMFQ8OFf0VGXcSNGLwc/view?usp=drivesdk

### Song ID

56

### Extra

Nene malo

**Comment by Alanazo** [comment]
Aceptar

**Comment by Alanazo** [comment]
> ¡Gracias por contribuir! Alguien pronto revisará su solicitud.
> 
> Aquí está el resultado JSON para el revisor:
> 
> ```json
> {
>   "name": "Nene malo",
>   "artist": "Naim_",
>   "source": "youtube",
>   "yt-id": "r7qr20wa3Aw",
>   "songs": [
>     56
>   ]
> }
> ```
> 
> Para aceptar la solicitud, el revisor debe escribir "aceptar".

aceptar

**Comment by James45MC** [comment]
OOPS! Real song ID is 1106112! Sorry!
