### ISSUE TITLE
INFINITY BLASTER (Sonic Blaster MASSIVE ULTIMATE MIX) by Mecha-Ruben

### ISSUE THREAD

**Issue by Nachoosan** [FlafyDev/auto-nong-indexes#1270]
### Song Name

INFINITY BLASTER (Sonic Blaster MASSIVE ULTIMATE MIX)

### Artist Name

Mecha-Ruben

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=NEZzfLfhnqs&list=PLzJTm1rlevc5ZQXOty5OfquAbGwFr31qp&index=5

### Song ID

574484

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 574484

**Comment by OM3GA6400** [comment]
accept
