### ISSUE TITLE
Add Nong Song: It's Been So Long (FNAF Remix/Cover)

### ISSUE THREAD

**Issue by Meatballmoose** [FlafyDev/auto-nong-indexes#1272]
### Song Name

It's Been So Long (FNAF Remix/Cover)

### Artist Name

APAngryPiggy

### Source

Youtube

### Youtube Link

https://youtu.be/P4zBEiMTnAo?si=J4g9plb5a90ZfagG

### Song ID

600915

### Extra

For the level 65332406
and Im also making a level with this song

**Comment by SpuckwasserDE** [comment]
accept
