### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by St0rme450** [FlafyDev/auto-nong-indexes#1273]
### Song Name

Bloodbath x Tidal Wave

### Artist Name

CokeOnYT

### Source

Youtube

### Direct File Link

https://drive.google.com/file/d/1VLZQ4Ht6Ox9TRuHIvhNCcLN_u_oMJxkz/view?usp=sharing

### Song ID

1266014

**Comment by LousyBook-01** [comment]
reject

google drive not accepted
