### ISSUE TITLE
Add Ludicrous Speed x After Party by GeoBlitzy

### ISSUE THREAD

**Issue by chwdunder** [FlafyDev/auto-nong-indexes#1275]
### Song Name

Ludicrous Speed x After Party

### Artist Name

GeoBlitzy

### Source

Youtube

### Youtube Link

https://youtu.be/civN_LZuWDc?si=wwHZZflE1eolVrpW

### Song ID

467267

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 4706930

**Comment by OM3GA6400** [comment]
accept
