### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by s0r3nnn** [FlafyDev/auto-nong-indexes#1279]
### Song Name

To Slay The Undead

### Artist Name

Gregor F. Narholz

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=Zah2VLgVc9c

### Song ID

1233480

**Comment by AJXPRO** [comment]
The music doesn't match.

**Comment by LousyBook-01** [comment]
reject

Worst sync i've ever seen
