### ISSUE TITLE
Add Trap Anthem by Mc Virgins 

### ISSUE THREAD

**Issue by Agent-Smiff** [FlafyDev/auto-nong-indexes#1282]
### Song Name

Trap Anthem

### Artist Name

Mc Virgins 

### Source

Youtube

### Youtube Link

8X4bSHz9Aou

### Song ID

1163930

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107479532

**Comment by LousyBook-01** [comment]
reject

wrong link
