### ISSUE TITLE
the 7 seas (gd cut) by F777

### ISSUE THREAD

**Issue by MuscleCarsRuleYT** [FlafyDev/auto-nong-indexes#1283]
### Song Name

The Seven Seas (Geometry Dash cut)

### Artist Name

F777

### Source

Youtube

### Youtube Link

JVw4g1hfx8BHPMBw

### Song ID

23

### Start Offset [ms]

0

**Comment by MuscleCarsRuleYT** [comment]
> Thanks for contributing! Someone will soon review your request.
> 
> Here is the JSON result for the reviewer:
> 
> ```json
> {
>   "name": "The Seven Seas (Geometry Dash cut)",
>   "artist": "F777",
>   "source": "youtube",
>   "startOffset": 0,
>   "yt-id": "JVw4g1hfx8BHPMBw",
>   "songs": [
>     23
>   ]
> }
> ```
> 
> To accept the request, a reviewer needs to write "accept".

accept

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
