### ISSUE TITLE
Blank by Disfigure

### ISSUE THREAD

**Issue by TGOHhakerbrine** [FlafyDev/auto-nong-indexes#1284]
### Song Name

Blank

### Artist Name

Disfigure

### Source

Youtube

### Youtube Link

JtuAa6FzfPvgVm7E

### Song ID

251266

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107712023

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
