### ISSUE TITLE
Add Waterflame-glorious morning (Piano cover) by guwunfish

### ISSUE THREAD

**Issue by actualsparky** [FlafyDev/auto-nong-indexes#1286]
### Song Name

Waterflame-glorious morning (Piano cover)

### Artist Name

guwunfish

### Source

Youtube

### Youtube Link

guwunfishyt

### Song ID

91476

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86761609

**Comment by LousyBook-01** [comment]
reject

@actualsparky that is not a actual youtube link
