### ISSUE TITLE
Add OOPARTS by Camellia

### ISSUE THREAD

**Issue by Supergglol** [FlafyDev/auto-nong-indexes#1287]
### Song Name

OOPARTS

### Artist Name

Camellia

### Source

Youtube

### Youtube Link

lc4nTM6M9KY

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107755269

**Comment by LousyBook-01** [comment]
accept

@Supergglol i don't know your level bcuz you probably made it friends only or deleted it, anyways yeah ok
