### ISSUE TITLE
Add Crunchy night by Gab1239Muzic

### ISSUE THREAD

**Issue by Gabriel-Cre** [FlafyDev/auto-nong-indexes#1288]
### Song Name

Crunchy night

### Artist Name

Gab1239Muzic

### Source

Youtube

### Youtube Link

wPKaEpw8qugVHvaI

### Song ID

13389

### Extra

Created from Auto Nong.
Created for level: 450920

**Comment by FlafyDev** [comment]
reject

invalid yt id
