### ISSUE TITLE
Add Rebirth Blaster (2024) by Plexity

### ISSUE THREAD

**Issue by comicsteel** [FlafyDev/auto-nong-indexes#1292]
### Song Name

Rebirth Blaster (2024)

### Artist Name

Plexity

### Source

Youtube

### Youtube Link

6GotIsZi4xc

### Song ID

574484

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 26681070

**Comment by LousyBook-01** [comment]
accept

nice
