### ISSUE TITLE
Add BIKE (Piano Cover) by tangermusic

### ISSUE THREAD

**Issue by comicsteel** [FlafyDev/auto-nong-indexes#1294]
### Song Name

BIKE (Piano Cover)

### Artist Name

tangermusic

### Source

Youtube

### Youtube Link

csy6Mh6OZC4

### Song ID

1191782

### Start Offset [ms]

950

### Extra

Created from Auto Nong.
Created for level: 89886591

**Comment by neprao** [comment]
reject

tanger created the song, not the cover.
