### ISSUE TITLE
Add Nong Song: Cityfade

### ISSUE THREAD

**Issue by Romancom1794** [FlafyDev/auto-nong-indexes#1295]
### Song Name

Cityfade

### Artist Name

Against all logic

### Source

Youtube

### Youtube Link

https://youtu.be/Ov5e0SLGEgg?si=xR7CjzSQ2Gfj1Scm

### Song ID

1307480

### Start Offset [ms]

0

### Extra

The legendary level "Cityfade" uses the song.

**Comment by neprao** [comment]
accept
