### ISSUE TITLE
Add Killing Me Slow by Player1, Sarah de Warren

### ISSUE THREAD

**Issue by Arturviper0** [FlafyDev/auto-nong-indexes#1296]
### Song Name

Killing Me Slow

### Artist Name

Player1, Sarah de Warren

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=FBlTMrwGvN0

### Song ID

595361

### Start Offset [ms]

0

### Extra

Created from Auto Nong.

**Comment by LousyBook-01** [comment]
accept

I mean it is good, but it syncs a bit, but not too much but the sync is still good

**Comment by FlafyDev** [comment]
.reject

has nothing to do with the song it replaces. and the original song is used a lot
