### ISSUE TITLE
Add Thermodynamix x Party Rock Anthem by Xcemines

### ISSUE THREAD

**Issue by M0hFR** [FlafyDev/auto-nong-indexes#1297]
### Song Name

Thermodynamix x Party Rock Anthem 

### Artist Name

Xcemines

### Source

Youtube

### Youtube Link

XoY1sQMFoguP1L5r

### Song ID

770520

### Start Offset [ms]

93

### Extra

Created from Auto Nong.
Created for level: 73667628

**Comment by neprao** [comment]
reject

incorrect youtube link
