### ISSUE TITLE
Add Freedom Dive (Suzu Remix) by Suzu

### ISSUE THREAD

**Issue by AJXPRO** [FlafyDev/auto-nong-indexes#1299]
### Song Name

Freedom Dive (Suzu Remix)

### Artist Name

Suzu

### Source

Youtube

### Youtube Link

https://youtu.be/pvV3ClwkzKY?si=SIKhVbuAY15zAPav

### Song ID

735623

### Start Offset [ms]

5

### Extra

Created from Auto Nong.
Created for level: 55274070

**Comment by LousyBook-01** [comment]
accept
