### ISSUE TITLE
Add Polargeist (AD Remix) by Eleme NTRIX

### ISSUE THREAD

**Issue by AJXPRO** [FlafyDev/auto-nong-indexes#1301]
### Song Name

Polargeist (AD Remix)

### Artist Name

Eleme NTRIX

### Source

Youtube

### Youtube Link

https://youtu.be/OD24JxwJZ-4?si=5lnUOjnWEdXVWHmE

### Song ID

2

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 65106

**Comment by LousyBook-01** [comment]
accept
