### ISSUE TITLE
Add Sakupen Hell x All of the Lights by Razaplays

### ISSUE THREAD

**Issue by M336G** [FlafyDev/auto-nong-indexes#1302]
### Song Name

Sakupen Hell x All of the Lights

### Artist Name

mr-jazzman

### Source

Youtube

### Youtube Link

https://youtu.be/jzf0a9HWrBU

### Song ID

360804

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 23262780

**Comment by elnexreal** [comment]
accept
