### ISSUE TITLE
Add Blast Processing (Zedrick Remix) by Zedrick

### ISSUE THREAD

**Issue by Cosmo304** [FlafyDev/auto-nong-indexes#1303]
### Song Name

Blast Processing (Zedrick Remix)

### Artist Name

Zedrick

### Source

Youtube

### Youtube Link

pxdapEl0vQU

### Song ID

16

### Start Offset [ms]

0

### Extra

Created from Auto Nong.

**Comment by LousyBook-01** [comment]
accept

good music
