### ISSUE TITLE
Add Isolation x 2.2 Predictions by NightHawk22

### ISSUE THREAD

**Issue by M336G** [FlafyDev/auto-nong-indexes#1304]
### Song Name

Isolation x 2.2 Predictions

### Artist Name

NightHawk22

### Source

Youtube

### Youtube Link

KmCOLqXlQL0

### Song ID

76743

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86084399

**Comment by elnexreal** [comment]
accept
