### ISSUE TITLE
Add GIRL A villager mc (IA COVER) by sinammota

### ISSUE THREAD

**Issue by Ma7ex** [FlafyDev/auto-nong-indexes#1305]
### Song Name

GIRL A villager mc (IA COVER)

### Artist Name

sinammota

### Source

Youtube

### Youtube Link

9p2W8M2Y0X4

### Song ID

1284048

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 97809134

**Comment by Ma7ex** [comment]
accept

**Comment by vsaucing** [comment]
accept
