### ISSUE TITLE
Add What's a future funk?|geometry dash by Alisniz

### ISSUE THREAD

**Issue by Ma7ex** [FlafyDev/auto-nong-indexes#1306]
### Song Name

What's a future funk?|geometry dash

### Artist Name

Alisniz

### Source

Youtube

### Youtube Link

MkGzqAim4Tw

### Song ID

701013

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 44062068

**Comment by LousyBook-01** [comment]
reject

very bad song
