### ISSUE TITLE
Add SHMW Yeat by Yeat

### ISSUE THREAD

**Issue by Komqetenter** [FlafyDev/auto-nong-indexes#1307]
### Song Name

SHMW Yeat

### Artist Name

Yeat

### Source

Youtube

### Youtube Link

JYYwYFUQIkWBLkag

### Song ID

1135860

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 85844400

**Comment by vsaucing** [comment]
.reject
link is broken

**Comment by LousyBook-01** [comment]
reject

yeah link not working
