### ISSUE TITLE
Add fingerbang real by mdk

### ISSUE THREAD

**Issue by MenugGD** [FlafyDev/auto-nong-indexes#1308]
### Song Name

fingerbang real

### Artist Name

mdk

### Source

Youtube

### Youtube Link

https://youtu.be/BuPmq7yjDnI?si=_veqivNEiwmL1NO-

### Song ID

757266

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 46122741

**Comment by LousyBook-01** [comment]
accept
