### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by BINGOLDDT4852** [FlafyDev/auto-nong-indexes#1310]
### Song Name

@SrGuillester canta ErebuS (song remix) by Manuelito juega | Geometry Dash

### Artist Name

Manuelito Juega

### Source

Youtube

### Youtube Link

https://youtu.be/t4NX9G1XqSA?si=a-jBTarY4J20vcyF

### Song ID

462681

### Start Offset [ms]

0

### Extra

Use in the level "Erebus"

**Comment by BINGOLDDT4852** [comment]
yes

**Comment by BINGOLDDT4852** [comment]
accept

**Comment by LousyBook-01** [comment]
accept
