### ISSUE TITLE
Murder in my Mind by Kordhell

### ISSUE THREAD

**Issue by ElDexrolsUwU** [FlafyDev/auto-nong-indexes#1311]
### Song Name

Murder in my Mind

### Artist Name

Kordhell

### Source

Youtube

### Youtube Link

https://youtu.be/w-sQRS-Lc9k?si=EHR6gkBQAESDzw7h

### Song ID

701013

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 83177725

**Comment by vsaucing** [comment]
accept

**Comment by vsaucing** [comment]
btw if you made this level there is a secret way on %0 if u spam

**Comment by ElDexrolsUwU** [comment]
thank you
