### ISSUE TITLE
Add rincon by milo

### ISSUE THREAD

**Issue by BPER224** [FlafyDev/auto-nong-indexes#1312]
### Song Name

rincon

### Artist Name

milo

### Source

Youtube

### Youtube Link

https://youtu.be/Kw2nmnhMMwU?si=B4EY-fT_AHsbWiy4

### Song ID

810618

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 82192449

**Comment by vsaucing** [comment]
Someone do this I cant play the level so hard

**Comment by LousyBook-01** [comment]
reject

No sync
