### ISSUE TITLE
Chicken nugget - The calling

### ISSUE THREAD

**Issue by mr-boias** [FlafyDev/auto-nong-indexes#1313]
### Song Name

CHICKEN NUGGET SINGING VERITY

### Artist Name

CHICKEN NUGGET

### Source

Direct file download

### Youtube Link

https://www.youtube.com/watch?v=2JRfK3Ty6MY

### Song ID

677785

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 18834999

**Comment by vsaucing** [comment]
.reject
Not popular, just earrape.

**Comment by LousyBook-01** [comment]
reject

Bad
