### ISSUE TITLE
CHICKEN NUGGET SINGING VERITY

### ISSUE THREAD

**Issue by mr-boias** [FlafyDev/auto-nong-indexes#1314]
### Song Name

CHICKEN NUGGET MASHUP

### Artist Name

 RAZELICIOUS ON TIKTOK

### Source

Youtube

### Direct File Link

"C:\Users\Carov\Downloads\677785.mp3"

### Song ID

677785

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 18834999

**Comment by vsaucing** [comment]
.reject

**Comment by LousyBook-01** [comment]
reject

bruh
