### ISSUE TITLE
CHICKEN NUGGET MASHUP

### ISSUE THREAD

**Issue by mr-boias** [FlafyDev/auto-nong-indexes#1316]
### Song Name

CHICKEN NUGGET SINGING VERITY

### Artist Name

razelicous on tiktok

### Source

Direct file download

### Direct File Link

"C:\Users\Carov\Downloads\677785.mp3"

### Song ID

677785

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 18834999

**Comment by vsaucing** [comment]
.reject 
only youtube

**Comment by LousyBook-01** [comment]
reject

BRO WHY DID YOU COPY YOUR LOCAL FILE LINK, UPLOAD IT TO YOUTUBE OR SOMETHING
