### ISSUE TITLE
Add Unwelcome School by Mitsukiyo

### ISSUE THREAD

**Issue by Xis95k** [FlafyDev/auto-nong-indexes#1317]
### Song Name

Unwelcome School

### Artist Name

Mitsukiyo

### Source

Youtube

### Youtube Link

8pBh7k-ZZXOnnHNu

### Song ID

1322579

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107716639

**Comment by vsaucing** [comment]
.reject
I can't open the youtube page?

**Comment by LousyBook-01** [comment]
reject

invalid link
