### ISSUE TITLE
Add Cradles x Melanie Martinez by Sur Urban

### ISSUE THREAD

**Issue by comicsteel** [FlafyDev/auto-nong-indexes#1318]
### Song Name

Cradles x Melanie Martinez

### Artist Name

Sur Urban

### Source

Youtube

### Youtube Link

nYAooU_CnOg

### Song ID

10011223

### Start Offset [ms]

1000

### Extra

Created from Auto Nong.
Created for level: 107084500

**Comment by vsaucing** [comment]
accept
