### ISSUE TITLE
Add Cradles x Rabbit Hole x Cirque x Uh Oh x Freak  by Sur Urban

### ISSUE THREAD

**Issue by comicsteel** [FlafyDev/auto-nong-indexes#1320]
### Song Name

Cradles x Rabbit Hole x Cirque x Uh Oh x Freak 

### Artist Name

Sur Urban

### Source

Youtube

### Youtube Link

i3LhhIU8WD0

### Song ID

10011223

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107084500

**Comment by vsaucing** [comment]
.reject
lyrics dont match

**Comment by comicsteel** [comment]
is a mashup ofc the lyrics aint gonna match lmao

**Comment by vsaucing** [comment]
accept
