### ISSUE TITLE
Add Stereo Madness (Mellon Remix) by DJ-Mellon

### ISSUE THREAD

**Issue by comicsteel** [FlafyDev/auto-nong-indexes#1321]
### Song Name

Stereo Madness (Mellon Remix)

### Artist Name

DJ-Mellon

### Source

Youtube

### Youtube Link

IXpLdfwm228

### Song ID

0

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 506009

**Comment by vsaucing** [comment]
.reject
popular song

**Comment by comicsteel** [comment]
> .reject popular song

tfym LMAO

**Comment by comicsteel** [comment]
did this jit even read the index???

**Comment by vsaucing** [comment]
accept
