### ISSUE TITLE
Add Stereo Madness (2015) by ForeverBound

### ISSUE THREAD

**Issue by comicsteel** [FlafyDev/auto-nong-indexes#1322]
### Song Name

Stereo Madness (2015)

### Artist Name

ForeverBound

### Source

Youtube

### Youtube Link

JtwYgQ0B198

### Song ID

0

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 506009

**Comment by vsaucing** [comment]
.reject
popular song

**Comment by comicsteel** [comment]
> .reject popular song

??????

**Comment by LousyBook-01** [comment]
accept

@vsaucing well yeah, but it is still stereo madness, so it syncs, only if it sync for that specific level and not others then probably don't accept it
