### ISSUE TITLE
Add Stereo Madness (Piano Cover) by PNG

### ISSUE THREAD

**Issue by comicsteel** [FlafyDev/auto-nong-indexes#1323]
### Song Name

Stereo Madness (Piano Cover)

### Artist Name

PNG

### Source

Youtube

### Youtube Link

TBHL-xX1ZLg

### Song ID

0

### Start Offset [ms]

2650

### Extra

Created from Auto Nong.
Created for level: 506009

**Comment by LousyBook-01** [comment]
accept

it is good
