### ISSUE TITLE
Add Nong Song: cybermiso - corps-sans-organes (Extended ver.)

### ISSUE THREAD

**Issue by frski07** [FlafyDev/auto-nong-indexes#1325]
### Song Name

corps-sans-organes (Extended ver.)

### Artist Name

cybermiso

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=oau2Pb0oRTM

### Direct File Link

https://cdn.discordapp.com/attachments/1034605734798835785/1261934605733335121/corps-sans-organes_Extended_ver._oau2Pb0oRTM.mp3?ex=6694c3af&is=6693722f&hm=92abdadb51c433b705077a7b80da6b00cccdb96606481a03b3337601c2d5c099&

### Song ID

1239973

### Start Offset [ms]

13030

### Extra

Used in the level achromatic made by theREALfirky (me) ID: 107792546 (start offset in seconds is 130.3 incase i got ms wrong)

**Comment by vsaucing** [comment]
.reject
direct file links are not supported now

**Comment by LousyBook-01** [comment]
accept

@vsaucing he provided the youtube link too

**Comment by frski07** [comment]
mightve fucked up woops :p (no offset was needed bruh)
