### ISSUE TITLE
Add Mii Channel Music by Nintendo

### ISSUE THREAD

**Issue by comicsteel** [FlafyDev/auto-nong-indexes#1327]
### Song Name

Mii Channel Music

### Artist Name

Nintendo

### Source

Youtube

### Youtube Link

E9s1ltPGQOo

### Song ID

754325

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 97571110

**Comment by comicsteel** [comment]
close this bc is not the right yt link

**Comment by comicsteel** [comment]
nvm keep this on is the correct link

**Comment by vsaucing** [comment]
i am scared if i accept this we may get sued nvm lemme check

**Comment by vsaucing** [comment]
accept
