### ISSUE TITLE
Add ToE 2 x Final Theory (full) by DJ-Nate

### ISSUE THREAD

**Issue by wrth875** [FlafyDev/auto-nong-indexes#1335]
### Song Name

ToE 2 x Final Theory (full)

### Artist Name

DJ-Nate

### Source

Youtube

### Youtube Link

6P9OTt1cguA

### Song ID

790340

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 46604847

**Comment by LousyBook-01** [comment]
accept
