### ISSUE TITLE
Add tidal wave x et (gd mashup) by wackylol

### ISSUE THREAD

**Issue by Pikachu71462** [FlafyDev/auto-nong-indexes#1337]
### Song Name

tidal wave x et (gd mashup)

### Artist Name

wackylol

### Source

Youtube

### Youtube Link

6En_ZkmbrwQbeXFu

### Song ID

1266014

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86407629

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
