### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by RTCreatoR** [FlafyDev/auto-nong-indexes#1338]
### Song Name

Broke

### Artist Name

Skyfall beats

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=PzxNFUCLRPg

### Song ID

272626

### Start Offset [ms]

0

**Comment by RTCreatoR** [comment]
accept

  
>Воскресенье, 14 июля 2024, 17:39 +03:00 от auto-nong[bot] ***@***.***>:
> 
> 
>Thanks for contributing!
>Someone will soon review your request.
>Here is the JSON result for the reviewer:
>{
>  "name": "Broke",
>  "artist": "Skyfall beats",
>  "source": "youtube",
>  "startOffset": 0,
>  "yt-id": "PzxNFUCLRPg",
>  "songs": [
>    272626
>  ]
>}
>To accept the request, a reviewer needs to write "accept".
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <FlafyDev/auto-nong-indexes/issues/1338/2227372216 @ github . com> 
 
 
--
Игорь Дёмин
Отправлено из Почты  Mail.ru

**Comment by AJXPRO** [comment]
accept
