### ISSUE TITLE
Add E.T x death note by GD Mashup

### ISSUE THREAD

**Issue by Pikachu71462** [FlafyDev/auto-nong-indexes#1339]
### Song Name

E.T x death note

### Artist Name

GD Mashup

### Source

Youtube

### Youtube Link

AST6rZn0uIbpoD0M

### Song ID

513539

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 49896559

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
