### ISSUE TITLE
Add 100 Bills by Camellia

### ISSUE THREAD

**Issue by Phellie** [FlafyDev/auto-nong-indexes#1342]
### Song Name

100 Bills

### Artist Name

Camellia

### Source

Youtube

### Youtube Link

2hHHrMIR6D-Zbtvh

### Song ID

10101

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 59489931

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
