### ISSUE TITLE
Add sonic blaster x ganman style by HardCops2588

### ISSUE THREAD

**Issue by Jmendin** [FlafyDev/auto-nong-indexes#1345]
### Song Name

sonic blaster x ganman style

### Artist Name

HardCops2588

### Source

Youtube

### Youtube Link

OnOETLbuCneqcFzg

### Song ID

574484

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 12341888

**Comment by AJXPRO** [comment]
Reject
Youtube link is incorrect

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
