### ISSUE TITLE
Add Nong Song: OOO

### ISSUE THREAD

**Issue by Tihxuwu** [FlafyDev/auto-nong-indexes#1346]
### Song Name

OOO

### Artist Name

Dakku

### Source

Direct file download

### Direct File Link

https://drive.google.com/file/d/12NShoLy3cOIy2xru7DO8ii_cNAXSxVMO/view?usp=drivesdk

### Song ID

1

### Start Offset [ms]

0

### Extra

A simple layout (The song has no name because it is not finished)

**Comment by IMGer4** [comment]
reject
