### ISSUE TITLE
CHICKEN NUGGET SINGING VERITY

### ISSUE THREAD

**Issue by mr-boias** [FlafyDev/auto-nong-indexes#1347]
### Song Name

CHICKEN NUGGET

### Artist Name

Chicken nugget

### Source

Youtube

### Youtube Link

cWJpJqYmctM

### Song ID

677785

### Start Offset [ms]

2

### Extra

Created from Auto Nong.
Created for level: 18834999

**Comment by SpuckwasserDE** [comment]
reject

shit mashups have to be popular to be considered a meme and therefore addworthy
