### ISSUE TITLE
Add so far so good by Rex Orange County

### ISSUE THREAD

**Issue by IKNOWMYMOMISCOOL** [FlafyDev/auto-nong-indexes#1348]
### Song Name

so far so good

### Artist Name

Rex Orange County

### Source

Youtube

### Youtube Link

MEUJGR7H_f7ErKxn

### Song ID

10009925

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107791316

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
