### ISSUE TITLE
Add in heat x bloodpop by non7mer

### ISSUE THREAD

**Issue by yippeezz** [FlafyDev/auto-nong-indexes#1349]
### Song Name

in heat x bloodpop

### Artist Name

non7mer

### Source

Youtube

### Youtube Link

bCl-w_ndoOovHtZY

### Song ID

35491

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 94646409

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
