### ISSUE TITLE
Add the weekend 12 remix by i forgor

### ISSUE THREAD

**Issue by epikducker** [FlafyDev/auto-nong-indexes#1351]
### Song Name

the weekend 12 remix

### Artist Name

i forgor

### Source

Youtube

### Youtube Link

LCUHKCtNAUg

### Song ID

1001

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 106530747

**Comment by SpuckwasserDE** [comment]
reject

artist name must be descriptive
