### ISSUE TITLE
Add Sonic Blaster x Eden XO by Annoying Guy

### ISSUE THREAD

**Issue by januha** [FlafyDev/auto-nong-indexes#1355]
### Song Name

Sonic Blaster x Eden XO

### Artist Name

Annoying Guy

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=q1i5PmG_X00

### Song ID

574484

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 26681070

**Comment by Cosmo304** [comment]
Reject. Good mix but horrible audio quality.

**Comment by IMGer4** [comment]
reject
