### ISSUE TITLE
Add Sonic Blaster x The Next Episode by F-777

### ISSUE THREAD

**Issue by Sanguisugaboggg** [FlafyDev/auto-nong-indexes#1360]
### Song Name

Sonic Blaster x The Next Episode

### Artist Name

F-777

### Source

Youtube

### Youtube Link

Yi5ZTa39qBk

### Song ID

574484

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 26681070

**Comment by SpuckwasserDE** [comment]
reject

mashups should have some popularity to show that people want it.
Note that you can still use the nong yourself, it just won't be public
