### ISSUE TITLE
Add Close to you by Jason paris

### ISSUE THREAD

**Issue by SXNDMANE** [FlafyDev/auto-nong-indexes#1363]
### Song Name

Close to you

### Artist Name

Jason paris

### Source

Youtube

### Youtube Link

SMbX_pCYOqy94sc-

### Song ID

66666

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107830268

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
