### ISSUE TITLE
Zedd (ft. Matthew Koma) - Spectrum (Rukkus Remix)

### ISSUE THREAD

**Issue by KenOliver117** [FlafyDev/auto-nong-indexes#1364]
### Song Name

Zedd (ft. Matthew Koma) - Spectrum (Rukkus Remix)

### Artist Name

Rukkus

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=ld_d6Kc45OM

### Song ID

586990

### Start Offset [ms]

109664

### Extra

To be used in any future level (probably an upcoming 1.9 NC Extreme Demon level)

**Comment by KenOliver117** [comment]
accept

**Comment by KenOliver117** [comment]
> Thanks for contributing! Someone will soon review your request.
> 
> Here is the JSON result for the reviewer:
> 
> ```json
> {
>   "name": "Zedd (ft. Matthew Koma) - Spectrum (Rukkus Remix)",
>   "artist": "Rukkus",
>   "source": "youtube",
>   "startOffset": 109664,
>   "yt-id": "ld_d6Kc45OM",
>   "songs": [
>     586990
>   ]
> }
> ```
> 
> To accept the request, a reviewer needs to write "accept".



> Thanks for contributing! Someone will soon review your request.
> 
> Here is the JSON result for the reviewer:
> 
> ```json
> {
>   "name": "Zedd (ft. Matthew Koma) - Spectrum (Rukkus Remix)",
>   "artist": "Rukkus",
>   "source": "youtube",
>   "startOffset": 109664,
>   "yt-id": "ld_d6Kc45OM",
>   "songs": [
>     586990
>   ]
> }
> ```
> 
> To accept the request, a reviewer needs to write "accept".

accept

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Soulwind" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
