### ISSUE TITLE
Add The experiment (english vocaloid) by CalypSonata

### ISSUE THREAD

**Issue by Akoris1** [FlafyDev/auto-nong-indexes#1365]
### Song Name

The experiment (english vocaloid)

### Artist Name

CalypSonata

### Source

Youtube

### Youtube Link

shared

### Song ID

690156

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 71514967

**Comment by Akoris1** [comment]
Accept

**Comment by SpuckwasserDE** [comment]
reject

link missing
