### ISSUE TITLE
Add Nong Song: Euphoria (in the style of Undertale)

### ISSUE THREAD

**Issue by wi000000** [FlafyDev/auto-nong-indexes#1366]
### Song Name

Euphoria (In the style of Undertale)

### Artist Name

Queerified, Kendrick Lamar Duckworth

### Source

Youtube

### Youtube Link

https://youtu.be/2VEtjNGJIb8

### Song ID

1339052

### Extra

from Newgrounds (1339052 was the ID),  got taken down but I could still download it on GD lol
if you are from Russia or Belarus you cant access the video sorryyy

**Comment by wi000000** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

made sure to ask bc of this, but this doesnt have the quality to be added
