### ISSUE TITLE
Add Let Go by bislink

### ISSUE THREAD

**Issue by Vmontiel0304** [FlafyDev/auto-nong-indexes#1367]
### Song Name

Let Go

### Artist Name

bislink

### Source

Youtube

### Youtube Link

https://youtu.be/gWHxi7Du28Q?si=zGSS43G9KJx2C9-f

### Song ID

9

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 82664569

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "xStep" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
