### ISSUE TITLE
Add Jumper by JF-Voice

### ISSUE THREAD

**Issue by Radmir388** [FlafyDev/auto-nong-indexes#1368]
### Song Name

Jumper

### Artist Name

JF-Voice

### Source

Youtube

### Youtube Link

tXehL9GHa2ZzRlHU

### Song ID

6

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 1988404

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
