### ISSUE TITLE
Add ATM III by FirstFeel

### ISSUE THREAD

**Issue by JustAp1ayer228** [FlafyDev/auto-nong-indexes#1369]
### Song Name

ATM III

### Artist Name

FirstFeel, MZLFF and more

### Source

Youtube

### Youtube Link

YYYn1_Vto78

### Song ID

12345

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 91328835

**Comment by JustAp1ayer228** [comment]
song for gp collab "ATM 3" id 91328835

**Comment by SpuckwasserDE** [comment]
accept
