### ISSUE TITLE
Add At The Speed of Light x Face Off by Dimrain47

### ISSUE THREAD

**Issue by M336G** [FlafyDev/auto-nong-indexes#1370]
### Song Name

At The Speed of Light x Face Off

### Artist Name

Dimrain47

### Source

Youtube

### Youtube Link

Rs6WXfzbgAI

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 3979721

**Comment by OM3GA6400** [comment]
accept

**Comment by FlafyDev** [comment]
accept
