### ISSUE TITLE
Add At The Speed of Light (Orchestral Cover) by Dimrain47

### ISSUE THREAD

**Issue by M336G** [FlafyDev/auto-nong-indexes#1372]
### Song Name

At The Speed of Light (Orchestral Cover)

### Artist Name

Dimrain47

### Source

Youtube

### Youtube Link

igFwe4Oal2Q

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 3979721

**Comment by OM3GA6400** [comment]
accept
