### ISSUE TITLE
Add One More Hour by Tame Impala

### ISSUE THREAD

**Issue by egorics** [FlafyDev/auto-nong-indexes#1373]
### Song Name

One More Hour

### Artist Name

Tame Impala

### Source

Youtube

### Youtube Link

I8cOWc-PgtVIGRlZ

### Song ID

672264

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 72282102

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
