### ISSUE TITLE
Add At The Speed of Light (Soullspa Cover) by Dimrain47

### ISSUE THREAD

**Issue by M336G** [FlafyDev/auto-nong-indexes#1376]
### Song Name

At The Speed of Light (Soullspa Cover)

### Artist Name

Dimrain47

### Source

Youtube

### Youtube Link

rqfTO2vaKaM

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 3979721

**Comment by OM3GA6400** [comment]
reject
