### ISSUE TITLE
Add   serega pirat - Where Is My Mind? by serega pirat

### ISSUE THREAD

**Issue by egor-crypto** [FlafyDev/auto-nong-indexes#1378]
### Song Name

  serega pirat - Where Is My Mind?

### Artist Name

serega pirat

### Source

Youtube

### Youtube Link

hB15FaAulF4

### Song ID

563184

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 97847737

**Comment by egor-crypto** [comment]
accept

пн, 15 июл. 2024 г., 17:39 auto-nong[bot] ***@***.***>:

**Comment by SpuckwasserDE** [comment]
reject

if the song is not the original that has to be clear from the name
