### ISSUE TITLE
add Sonic Blaster - F777 (DOKI DOKI WAKU WAKU Remix) FULL by EpikDARK

### ISSUE THREAD

**Issue by SkepGitHub** [FlafyDev/auto-nong-indexes#1379]
### Song Name

Sonic Blaster - F777 (DOKI DOKI WAKU WAKU Remix) FULL

### Artist Name

EpikDARK

### Source

Youtube

### Youtube Link

https://youtu.be/g7tKsJiCNcI?feature=shared

### Song ID

574484

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 20705695

**Comment by SpuckwasserDE** [comment]
acceept

**Comment by SpuckwasserDE** [comment]
accept

**Comment by SpuckwasserDE** [comment]
sorry bout that
