### ISSUE TITLE
Add this one is for u <3 by KENTENSHI

### ISSUE THREAD

**Issue by testACCCOUNT1** [FlafyDev/auto-nong-indexes#1381]
### Song Name

this one is for u <3

### Artist Name

KENTENSHI

### Source

Youtube

### Youtube Link

1_6hvoZdiEQ

### Song ID

766165

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 58825144

**Comment by SpuckwasserDE** [comment]
reject

popular songs like the xo song are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
