### ISSUE TITLE
Add Sakupen Circles X Gangsta Paradise X Super idol by Unknown

### ISSUE THREAD

**Issue by FyckyCZ** [FlafyDev/auto-nong-indexes#1382]
### Song Name

Sakupen Circles X Gangsta Paradise X Super idol

### Artist Name

Unknown

### Source

Youtube

### Youtube Link

6QVc17M7feI

### Song ID

360804

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 77183024

**Comment by SpuckwasserDE** [comment]
reject

artist must be descriptive
