### ISSUE TITLE
Add The Crazy by Gab1239Muzic

### ISSUE THREAD

**Issue by Gabriel-Cre** [FlafyDev/auto-nong-indexes#1384]
### Song Name

The Crazy

### Artist Name

Gab1239Muzic

### Source

Youtube

### Youtube Link

d8llHHs3kE930HlD

### Direct File Link

https://youtu.be/-N4jf6rtyuw?si=rUWUQoZ_R18LMv8M

### Song ID

648034

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 36357089

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
