### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by Twitchgd2024** [FlafyDev/auto-nong-indexes#1387]
### Song Name

Bling-bang-bang-born

### Artist Name

Creepy Nuts

### Source

Youtube

### Youtube Link

https://m.youtube.com/watch?v=mLW35YMzELE

### Song ID

102030

**Comment by Twitchgd2024** [comment]
hello guys i made this song for the creator of geode auto nong to make me put on the auto nong

**Comment by Twitchgd2024** [comment]
and Flafy, what do you think?

**Comment by SpuckwasserDE** [comment]
accept
