### ISSUE TITLE
Add Bozodiac by GDBozo

### ISSUE THREAD

**Issue by ItaliaGD** [FlafyDev/auto-nong-indexes#1389]
### Song Name

Bozodiac

### Artist Name

GDBozo

### Source

Youtube

### Youtube Link

https://youtu.be/ga0ynboTfAs?si=-tqPrNoY3FmH7GF5

### Direct File Link

https://www.mediafire.com/file/ratsikbtavosbhp/Zodiac_Beat.mp3/file

### Song ID

739991

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 82375724

**Comment by IMGer4** [comment]
reject. its so bad + the mashup its not finished

**Comment by IMGer4** [comment]
reject
