### ISSUE TITLE
Add atsol guitar cover by esteban artizaba

### ISSUE THREAD

**Issue by TRGgd1** [FlafyDev/auto-nong-indexes#1397]
### Song Name

atsol guitar cover

### Artist Name

esteban artizabal

### Source

Youtube

### Youtube Link

Y48mpycTGdE

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 3979721

**Comment by IMGer4** [comment]
reject. stupid cover + its a guitarherostyles cover.
