### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by FerkiDark** [FlafyDev/auto-nong-indexes#1398]
### Song Name

Fanta$y L0v3

### Artist Name

riiece

### Source

Youtube

### Youtube Link

https://www.youtube.com/results?search_query=fanta%24y+l0v3

### Song ID

686782

**Comment by Cosmo304** [comment]
Reject. First of all, the YouTube link is a search, not an actual video. Second, the song does not relate to the song it's replacing one bit.
