### ISSUE TITLE
Add Take A Slice by Animal glasses

### ISSUE THREAD

**Issue by Secabef** [FlafyDev/auto-nong-indexes#1400]
### Song Name

Take A Slice

### Artist Name

Animal glasses

### Source

Direct file download

### Youtube Link

NLAd5ZpPT3V0OqqH

### Song ID

679002

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 20511156

**Comment by SpuckwasserDE** [comment]
reject

source and link dont match
