### ISSUE TITLE
Add Take A Slice by glass animal

### ISSUE THREAD

**Issue by Secabef** [FlafyDev/auto-nong-indexes#1402]
### Song Name

Take A Slice

### Artist Name

glass animal

### Source

Youtube

### Youtube Link

https://youtu.be/wEtypAUozk0?si=NLAd5ZpPT3V0OqqH

### Song ID

679002

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 20511156

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "jet set" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
