### ISSUE TITLE
Add Five Nights At Freedy's 3 "Die In A Fire" by The Living Tombstone, EileMonty, Orko

### ISSUE THREAD

**Issue by CyZcodes** [FlafyDev/auto-nong-indexes#1407]
### Song Name

Five Nights At Freedy's 3 "Die In A Fire"

### Artist Name

The Living Tombstone, EileMonty, Orko

### Source

Youtube

### Youtube Link

AibtyCAhyQE

### Song ID

697828

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 23325320

**Comment by SpuckwasserDE** [comment]
accept
