### ISSUE TITLE
Add Shiawase VIP X Shawn Mendes by Shawn Mendes

### ISSUE THREAD

**Issue by secondpolishrepublic** [FlafyDev/auto-nong-indexes#1409]
### Song Name

Shiawase VIP X Shawn Mendes

### Artist Name

Shawn Mendes

### Source

Youtube

### Youtube Link

2--k2pQBtOJnB9xr

### Song ID

1266014

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107679656

**Comment by Cosmo304** [comment]
Reject. There is an issue with Auto Nong where it doesn't convert some YouTube links to YouTube ids correctly. I recommend testing the songs in-game before you try to add them. It will hopefully get fixed soon.
