### ISSUE TITLE
Add 2 Phut Hon by Phao x Masew

### ISSUE THREAD

**Issue by HKJ79-GDVN** [FlafyDev/auto-nong-indexes#1410]
### Song Name

2 Phut Hon

### Artist Name

Phao x Masew

### Source

Youtube

### Youtube Link

MxXKfq86E0I

### Song ID

123231

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 88526921

**Comment by SpuckwasserDE** [comment]
accept
