### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by Ronnorika** [FlafyDev/auto-nong-indexes#1424]
### Song Name

Lost x Becane

### Artist Name

CRIM3S

### Source

Direct file download

### Youtube Link

https://www.youtube.com/watch?v=KL-W4VE5oYI

### Song ID

945695

### Start Offset [ms]

0

### Extra

Used in Slaughterhouse 27690100. my first remix and hella proud of it. HIIIII

**Comment by Cosmo304** [comment]
Reject. This is a good song, but I can't add it because it isn't synced. Slaughterhouse has an offset of 35 seconds, meaning that when this is used for Slaughterhouse, the level starts while being 35 seconds into the song. Sorry :/

**Comment by IMGer4** [comment]
reject
