### ISSUE TITLE
Add Pedro by Raffaella Carra, Jaxomy, Agatino Romero

### ISSUE THREAD

**Issue by DarkPhantom030100** [FlafyDev/auto-nong-indexes#1428]
### Song Name

Pedro

### Artist Name

Raffaella Carra, Jaxomy, Agatino Romero

### Source

Youtube

### Youtube Link

https://youtu.be/OCZIzzQpJUw?si=VEjIoFsDcLGQkJo7

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 105201767

**Comment by IMGer4** [comment]
reject
