### ISSUE TITLE
Add glass by Poshlaya molli

### ISSUE THREAD

**Issue by Kolljeip** [FlafyDev/auto-nong-indexes#1445]
### Song Name

glass

### Artist Name

Poshlaya molli

### Source

Youtube

### Youtube Link

kQQYY_WpalE3Ovpe

### Song ID

574484

### Start Offset [ms]

28.3

### Extra

Created from Auto Nong.
Created for level: 26681070

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
