### ISSUE TITLE
Add acheron x gimn russia by dj-nate

### ISSUE THREAD

**Issue by pufish** [FlafyDev/auto-nong-indexes#1452]
### Song Name

acheron x gimn russia

### Artist Name

dj-nate

### Source

Youtube

### Youtube Link

JT0wXhYM66U

### Song ID

770520

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 73667628

**Comment by Cosmo304** [comment]
Reject. Acheron has a song offset of 92.3 seconds, meaning this is not synced
