### ISSUE TITLE
Add Nong Song: Eternal Silence

### ISSUE THREAD

**Issue by Kawoshin1995** [FlafyDev/auto-nong-indexes#1460]
### Song Name

Eternal Silence

### Artist Name

dj-nate

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=JWUg2ZILWbM&t=1s

### Song ID

13

### Start Offset [ms]

0

### Extra

Used in the level "Eternal Silence" - 83476262

**Comment by Cosmo304** [comment]
Accept
