### ISSUE TITLE
Add Shiawase (VIP) Low Quality  by Dion Timmer

### ISSUE THREAD

**Issue by Ravz-oss** [FlafyDev/auto-nong-indexes#1467]
### Song Name

Shiawase (VIP) Low Quality 

### Artist Name

Dion Timmer

### Source

Youtube

### Youtube Link

0zmE65ptla4

### Song ID

1266014

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 104356905

**Comment by IMGer4** [comment]
reject

**Comment by IMGer4** [comment]
bad remix
