### ISSUE TITLE
Add planes by rucka rucka ali

### ISSUE THREAD

**Issue by CodeVdog** [FlafyDev/auto-nong-indexes#1469]
### Song Name

planes

### Artist Name

rucka rucka ali

### Source

Youtube

### Youtube Link

Xd3FCvEr9x7kk7gc

### Song ID

791974

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 104889491

**Comment by comicsteel** [comment]
reject

invalid yt link
