### ISSUE TITLE
The Promised Consort by Elden Ring (DLC) OST

### ISSUE THREAD

**Issue by gabeygoobers** [FlafyDev/auto-nong-indexes#1488]
### Song Name

The Promised Consort

### Artist Name

Elden Ring (DLC) OST

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=1D4e-ru6U00

### Song ID

1788

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107951046
For homie jittlygang MegaFarto on his Elden Ring level

**Comment by comicsteel** [comment]
reject

invalid level id so idk if it fits with the level or not
