### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by gabeygoobers** [FlafyDev/auto-nong-indexes#1489]
### Song Name

Broken Games

### Artist Name

Shangri-la Frontier

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=GasIaj6iNOU

### Song ID

1124343

### Extra

It was made for me and my friend's "level draft yes". You won't be able to find the level, hence it being unlisted. We plan to make it a huge project, so please accept this nong song.

**Comment by SpuckwasserDE** [comment]
accept
