### ISSUE TITLE
Broken Games by Shangri-la Frontier

### ISSUE THREAD

**Issue by gabeygoobers** [FlafyDev/auto-nong-indexes#1490]
### Song Name

Broken Games

### Artist Name

Shangri-la Frontier

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=GasIaj6iNOU

### Song ID

1124343

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 100836920

**Comment by SpuckwasserDE** [comment]
reject

duplicate request, no worries, the song has already been accepted
