### ISSUE TITLE
Add Nong Song: Flashback by Frizk

### ISSUE THREAD

**Issue by 8rbit** [FlafyDev/auto-nong-indexes#1496]
### Song Name

Flashback

### Artist Name

Frizk

### Source

Youtube

### Youtube Link

https://youtu.be/yfSIWCjIayc?si=BWfrrCx_RZzze1m8

### Song ID

1262691

### Start Offset [ms]

0

### Extra

No comment

**Comment by SpuckwasserDE** [comment]
accept
