### ISSUE TITLE
Add Jumper by Waterflame

### ISSUE THREAD

**Issue by GMDZerox** [FlafyDev/auto-nong-indexes#1498]
### Song Name

Jumper

### Artist Name

Waterflame

### Source

Youtube

### Youtube Link

https://youtu.be/Vl3tadg6G1Q?si=L7OiEBTz8TH8k6HX

### Song ID

6

### Start Offset [ms]

0

### Extra

Created from Auto Nong.

**Comment by SpuckwasserDE** [comment]
reject

artist and song name must be descriptive (indicate what is different)
