### ISSUE TITLE
Add NONG song

### ISSUE THREAD

**Issue by DragosDobrican** [FlafyDev/auto-nong-indexes#15]
### Song Name

Beatbox

### Artist Name

Dragosdobrican

### Source

Direct file download

### Direct File Link

https://drive.google.com/drive/folders/15qNh2gIxKbny2c9iCJ8YvKdFLhb3tWAl

### Song ID

1

### Extra

Used in my level **Joke Demon** ID: 103829263

**Comment by DragosDobrican** [comment]
accept

**Comment by FlafyDev** [comment]
Auto nong doesn't work with google drive. can you upload it to youtube?

**Comment by DragosDobrican** [comment]
i'm not sure, i cant upload mp3 files directly to youtube, and i don't have access to a editing software other than CapCut and alight motion.

**Comment by DragosDobrican** [comment]
but what links (other than youtube) work with it?

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported
