### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by duck1ee** [FlafyDev/auto-nong-indexes#1506]
### Song Name

Your best nightmare

### Artist Name

Toby fox

### Source

Youtube

### Youtube Link

https://youtu.be/SObWQRaltug?si=wdhGrwytNOeY_vNk

### Song ID

653251

### Extra

used in level "omega flowey", ID — 83723689

**Comment by Cosmo304** [comment]
reject. does not sync with the remix
