### ISSUE TITLE
tell me by james blake

### ISSUE THREAD

**Issue by catotrox** [FlafyDev/auto-nong-indexes#1513]
### Song Name

tell me

### Artist Name

james blake

### Source

Youtube

### Youtube Link

C2fLkcpbdAIgwqyK

### Song ID

557117

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level:6508283

**Comment by catotrox** [comment]
accept

**Comment by catotrox** [comment]
> Thanks for contributing! Someone will soon review your request.
> 
> Here is the JSON result for the reviewer:
> 
> ```json
> {
>   "name": "tell me",
>   "artist": "james blake",
>   "source": "youtube",
>   "startOffset": 0,
>   "yt-id": "C2fLkcpbdAIgwqyK",
>   "songs": [
>     557117
>   ]
> }
> ```
> 
> To accept the request, a reviewer needs to write "accept".

accept

**Comment by Cosmo304** [comment]
reject
