### ISSUE TITLE
mid.

### ISSUE THREAD

**Issue by Smuppy-the-cat** [FlafyDev/auto-nong-indexes#1520]
### Song Name

mid.

### Artist Name

Blabbit09

### Source

Youtube

### Youtube Link

hZcibrxf7lw

### Song ID

575768

### Start Offset [ms]

0

### Extra

Created from Auto Nong.

**Comment by Cosmo304** [comment]
reject. has nothing to do with the original song

**Comment by Y4hy4-M4x-G4m3r** [comment]
> reject. has nothing to do with the original song

dude dry out has a nong by silvagunner that isn't related to dry out and it's allowed and not implementing sevcon to replace the gd menu song? what the fuck?
