### ISSUE TITLE
reject. has absolutely nothing to do with the GD menu song.

### ISSUE THREAD

**Issue by Y4hy4-M4x-G4m3r** [FlafyDev/auto-nong-indexes#1521]
this was meant to be a FUCKING NONG FOR A LAYOUT HOW ARE PEOPLE SO GODDAMN DUMB

**Comment by FlafyDev** [comment]
you were trying to replace 584131 with an unrelated song. 584131 is used in many rated levels so we can't afford to replace it with a random song

**Comment by Y4hy4-M4x-G4m3r** [comment]
is there random song that is barely used that i can replace?

**Comment by Y4hy4-M4x-G4m3r** [comment]
> you were trying to replace 584131 with an unrelated song. 584131 is used in many rated levels so we can't afford to replace it with a random song

is there a random unused song that i can replace?

**Comment by FlafyDev** [comment]
> > you were trying to replace 584131 with an unrelated song. 584131 is used in many rated levels so we can't afford to replace it with a random song
> 
> is there a random unused song that i can replace?

I don't know if there is currently an easy way to find one. maybe i should think of something...
anyway, you can go to https://www.newgrounds.com/audio and look for songs no level uses and probably never use.
