### ISSUE TITLE
e

### ISSUE THREAD

**Issue by comicsteel** [FlafyDev/auto-nong-indexes#1522]
### Song Name

Clubstep (Geeser Remix) RobTop Cut Ver.

### Artist Name

GeezerOkee

### Source

Youtube

### Youtube Link

JWUg2ZILWbM

### Song ID

13

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 450920

**Comment by FlafyDev** [comment]
accepted the previous submission

**Comment by FlafyDev** [comment]
im dumb. my message started with "accept"...
