### ISSUE TITLE
Add Dejame Tranki by LIT Killah

### ISSUE THREAD

**Issue by Loxtrans** [FlafyDev/auto-nong-indexes#1527]
### Song Name

Dejame Tranki

### Artist Name

LIT Killah

### Source

Youtube

### Youtube Link

gk4udFVq3mXUb9La

### Song ID

1234397

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107970905

**Comment by IMGer4** [comment]
nong is not related with the original song + any famous lvl with that nong, srr but reject

**Comment by IMGer4** [comment]
reject
