### ISSUE TITLE
Add Practice: Stay Inside Me by OcularNebula (not gonna work but itll be funny)

### ISSUE THREAD

**Issue by comicsteel** [FlafyDev/auto-nong-indexes#1528]
### Song Name

Practice: Stay Inside Me

### Artist Name

OcularNebula

### Source

Youtube

### Youtube Link

ix6e9h40qMg

### Song ID

-1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 77713693

**Comment by IMGer4** [comment]
reject

**Comment by comicsteel** [comment]
bruh

**Comment by comicsteel** [comment]
u reject this and not accepting my other submissions bruh
