### ISSUE TITLE
Add Singularity by Camellia

### ISSUE THREAD

**Issue by Phellie** [FlafyDev/auto-nong-indexes#1531]
### Song Name

Singularity

### Artist Name

Camellia

### Source

Youtube

### Youtube Link

mDtm4DdwPuslshSt

### Song ID

614535

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 79598199

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
