### ISSUE TITLE
Add Brain Power by NOMA.

### ISSUE THREAD

**Issue by Zz-Zirael** [FlafyDev/auto-nong-indexes#1542]
### Song Name

Brain Power

### Artist Name

NOMA

### Source

Youtube

### Youtube Link

https://youtu.be/YMy5uugeEis

### Song ID

1299591

### Start Offset [ms]

0

### Extra

The existing version of the song in the mod is a remix.  This is the original. You can see it in NexusGD's video https://youtu.be/ThroGkahQFw

Created from Auto Nong.
Created for level: 104444534

**Comment by Zz-Zirael** [comment]
UPD: edited song link

**Comment by SpuckwasserDE** [comment]
reject

already in the mod
