### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by annery827** [FlafyDev/auto-nong-indexes#1543]
### Song Name

racing into the night (vietnamese ver)

### Artist Name

Lacie⭐DesuKa?

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=9Q5DKUYNewo&ab_channel=Lacie%E2%AD%90DesuKa%3F

### Song ID

1024087

**Comment by annery827** [comment]
accept

**Comment by Ann559** [comment]
accept
