### ISSUE TITLE
Add pumped of sing by me

### ISSUE THREAD

**Issue by itsayuwoki** [FlafyDev/auto-nong-indexes#1555]
### Song Name

pumped of sing

### Artist Name

me

### Source

Youtube

### Youtube Link

Hz9Bx2dVxlcG4TkF

### Song ID

627121

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 48353992

**Comment by comicsteel** [comment]
reject

invalid yt link
