### ISSUE TITLE
XO (only if u say yes) By Enhypen kpop

### ISSUE THREAD

**Issue by HyperSonar324** [FlafyDev/auto-nong-indexes#1559]
### Song Name

XO (only if u say yes)

### Artist Name

Enhypen

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=4-GEf5dQqkc

### Song ID

675154

### Start Offset [ms]

0

### Extra

Nothing yet

**Comment by HyperSonar324** [comment]
Accept

**Comment by comicsteel** [comment]
reject

invalid song id
