### ISSUE TITLE
Add At The Speed of Light x Squid Game vs. MrBeast by nadire

### ISSUE THREAD

**Issue by piggypleb** [FlafyDev/auto-nong-indexes#1561]
### Song Name

At The Speed of Light x Squid Game vs. MrBeast

### Artist Name

nadire

### Source

Youtube

### Youtube Link

ZEomMdwe77w

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 57215346

**Comment by comicsteel** [comment]
accept
