### ISSUE TITLE
Add purgatori x crank that by koraii x soulja boy

### ISSUE THREAD

**Issue by TOXISS-gd** [FlafyDev/auto-nong-indexes#1568]
### Song Name

purgatori x crank that

### Artist Name

koraii x soulja boy

### Source

Youtube

### Youtube Link

W58tXdhBboc

### Song ID

895761

### Start Offset [ms]

165

### Extra

Created from Auto Nong.
Created for level: 68668045

**Comment by SpuckwasserDE** [comment]
reject

mashups should have some popularity to show that people want it.
Note that you can still use the nong yourself, but it wont be public
