### ISSUE TITLE
Add neon blade by Moondeity

### ISSUE THREAD

**Issue by Valtinos** [FlafyDev/auto-nong-indexes#1569]
### Song Name

neon blade

### Artist Name

Moondeity

### Source

Youtube

### Youtube Link

fMlkZv9pVcAXaFSC

### Song ID

895130

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 89007603

**Comment by comicsteel** [comment]
reject

invalid yt link
