### ISSUE TITLE
Stalemate The Remake

### ISSUE THREAD

**Issue by Eldemoniodelaradio666** [FlafyDev/auto-nong-indexes#1570]
### Song Name

KZX STALEMATE THE REMAKE

### Artist Name

MIL009

### Source

Direct file download

### Direct File Link

storage/emulated/0/Music/KZX STALEMATE THE NIGHMARE_24-06-24_17-47-21-880_99_10.230390

### Song ID

230390

**Comment by comicsteel** [comment]
reject

only accept yt link
