### ISSUE TITLE
Add Stereo Madness (Lyrics VERSION) by 64Beastyman

### ISSUE THREAD

**Issue by Therealcapybara1641** [FlafyDev/auto-nong-indexes#1575]
### Song Name

Stereo Madness (Lyrics Version)

### Artist Name

64Beastyman

### Source

Youtube

### Youtube Link

https://youtu.be/NA_CG-_mCIQ?si=EdLh0COrsVRHwtWL

### Song ID

500476

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 105130586

**Comment by comicsteel** [comment]
accept

**Comment by Therealcapybara1641** [comment]
Hurray!!!
