### ISSUE TITLE
Add KOCMOC by SLEEPING HUMMINGBIRD

### ISSUE THREAD

**Issue by ezpz256** [FlafyDev/auto-nong-indexes#1576]
### Song Name

KOCMOC

### Artist Name

SLEEPING HUMMINGBIRD

### Source

Youtube

### Youtube Link

youtube.com/watch?v=zlea-ttxdgc

### Song ID

1163222

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 101882354

**Comment by comicsteel** [comment]
reject

invalid yt link
