### ISSUE TITLE
Life goes on by Oliver Tree

### ISSUE THREAD

**Issue by Reflyway** [FlafyDev/auto-nong-indexes#1578]
### Song Name

Life goes on

### Artist Name

Oliver Tree

### Source

Youtube

### Youtube Link

https://youtu.be/8F2s8ivKXNY?si=QskLerdnrgBBT2on

### Song ID

101010

### Extra

Created from Auto Nong.
Created for level: 75549568

**Comment by comicsteel** [comment]
accept
