### ISSUE TITLE
Add Dry out x Mr.Beast by Lopzinc

### ISSUE THREAD

**Issue by OzniumGit** [FlafyDev/auto-nong-indexes#1579]
### Song Name

Dry out x Mr.Beast

### Artist Name

Lopzinc

### Source

Youtube

### Youtube Link

yvq7CMAGQWDwswY0

### Song ID

3

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 4

**Comment by comicsteel** [comment]
reject

invalid yt link
