### ISSUE TITLE
Add Bad Apple!! x Electroman Adventures by Hema [GD]

### ISSUE THREAD

**Issue by DerpOKat21** [FlafyDev/auto-nong-indexes#1583]
### Song Name

Bad Apple!! x Electroman Adventures

### Artist Name

Hema [GD]

### Source

Youtube

### Youtube Link

0jW0p8gjExm2NzMT

### Song ID

12

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 428765

**Comment by LousyBook-01** [comment]
reject

@DerpOKat21 invalid link
