### ISSUE TITLE
nekoglaya ebali by sbomba3131

### ISSUE THREAD

**Issue by bekasikhuesosov69** [FlafyDev/auto-nong-indexes#1586]
### Song Name

nekoglaya ebali

### Artist Name

sbomba3131

### Source

Youtube

### Youtube Link

https://youtu.be/uwswpXMzcLM?si=2OZGbZ_n6RdxmnbI

### Song ID

9

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 4299772

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "xStep" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
