### ISSUE TITLE
Add At the Speed of Light (Garageband Remake) by UI_Bourne

### ISSUE THREAD

**Issue by comicsteel** [FlafyDev/auto-nong-indexes#1587]
### Song Name

At the Speed of Light (Garageband Remake)

### Artist Name

UI_Bourne

### Source

Youtube

### Youtube Link

WtYPOwB_RW8

### Song ID

467339

### Start Offset [ms]

270

### Extra

Created from Auto Nong.
Created for level: 7485599

**Comment by LousyBook-01** [comment]
accept
