### ISSUE TITLE
Add BURN by Kanye West & Ty Dolla $ign

### ISSUE THREAD

**Issue by availax** [FlafyDev/auto-nong-indexes#159]
### Song Name

BURN

### Artist Name

Kanye West & Ty Dolla $ign

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=DnEOoCWqY9M

### Song ID

1328792

### Extra

Created from Auto Nong.
Created for level: 106207569

**Comment by FlafyDev** [comment]
accept
