### ISSUE TITLE
Add At The Speed Of Light (2023 Phonk Remix) by sxdboy 

### ISSUE THREAD

**Issue by CaptainJokes** [FlafyDev/auto-nong-indexes#1591]
### Song Name

At The Speed Of Light (2023 Phonk Remix)

### Artist Name

sxdboy 

### Source

Youtube

### Youtube Link

qL6eG4OCPOs

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 38601659

**Comment by LousyBook-01** [comment]
accept
