### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by skywildonbudget** [FlafyDev/auto-nong-indexes#1603]
### Song Name

Space Invaders (SkyWildOnBudget Remix)

### Artist Name

Skywild3789

### Source

Youtube

### Youtube Link

https://youtu.be/9jr6hZlLV0s?si=y-hPYHjeA2mXNzJ8

### Song ID

865364

### Start Offset [ms]

175

### Extra

used in level "Space Invaders"

**Comment by comicsteel** [comment]
reject

no, its bad + u just make a cover over the original space invader song
