### ISSUE TITLE
Add Kyouki x Nirvana by AidanTR

### ISSUE THREAD

**Issue by mintydoesthings** [FlafyDev/auto-nong-indexes#1604]
### Song Name

Kyouki x Nirvana

### Artist Name

AidanTR

### Source

Youtube

### Youtube Link

g2xjFJ7m9xk

### Song ID

905108

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86018142

**Comment by comicsteel** [comment]
reject

song is not called kyouki
