### ISSUE TITLE
Add heatens by twenty one pilots

### ISSUE THREAD

**Issue by Alexelpro24TK** [FlafyDev/auto-nong-indexes#1607]
### Song Name

heatens

### Artist Name

twenty one pilots

### Source

Youtube

### Youtube Link

https://youtu.be/UprcpdwuwCg?si=z_ePXlU1YySWo2nX

### Song ID

703291

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 34799345

**Comment by comicsteel** [comment]
reject
song is not called heatens
