### ISSUE TITLE
Add heatens by twenty one pilots

### ISSUE THREAD

**Issue by Alexelpro24TK** [FlafyDev/auto-nong-indexes#1608]
### Song Name

heatens

### Artist Name

twenty one pilots

### Source

Youtube

### Youtube Link

z_ePXlU1YySWo2nX

### Song ID

703291

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 34799345

**Comment by comicsteel** [comment]
reject

invalid yt link
