### ISSUE TITLE
Add do not drugs orginal by stasqqq

### ISSUE THREAD

**Issue by stasqq422** [FlafyDev/auto-nong-indexes#1614]
### Song Name

do not drugs orginal

### Artist Name

stasqqq

### Source

Youtube

### Youtube Link

https://youtu.be/TTX0ddlOWd4

### Song ID

1257815

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 104079162

**Comment by comicsteel** [comment]
reject

spams from other same submissions and its the same link to "i seel crack original"
