### ISSUE TITLE
Add sonic blaster remix by F-777

### ISSUE THREAD

**Issue by diego417xd** [FlafyDev/auto-nong-indexes#1623]
### Song Name

sonic blaster remix

### Artist Name

F-777

### Source

Youtube

### Youtube Link

Wb61pz4EA8Y3x3wQ

### Song ID

574484

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 20705695

**Comment by Cosmo304** [comment]
reject. The link does not work correctly due to an Auto Nong bug. To prevent this, I suggest testing the song in-game before sending it here.
