### ISSUE TITLE
Gamblecore

### ISSUE THREAD

**Issue by NotTwikker** [FlafyDev/auto-nong-indexes#1624]
### Song Name

Gamblecore

### Artist Name

raxdflipnote

### Source

Youtube

### Youtube Link

https://youtu.be/IPFiKEm-oNI?si=-DxA3w6rs5-PLdZa

### Direct File Link

https://www.mediafire.com/file/fckanz7q6fqz7uz/gamblecore.mp3/file

### Song ID

10007189

### Start Offset [ms]

0

### Extra

Used in the level "Lets go gambling" by Nfanboi with the id of 108052183

**Comment by FlafyDev** [comment]
reject

levels use this song
