### ISSUE TITLE
Add PP3 - HOMER SIMPSON VS PETER GRIFFIN

### ISSUE THREAD

**Issue by Multex** [FlafyDev/auto-nong-indexes#1625]
### Song Name

-API- Paradise on E [REMIX]

### Artist Name

apimusic

### Source

Direct file download

### Direct File Link

https://i.supa.codes/BzlSS

### Song ID

32772

### Start Offset [ms]

0

### Extra

Used in the level Plasma Pulse III - 20159880

**Comment by FlafyDev** [comment]
```
https://i.supa.codes/BzlSS
```
1. Is this your cdn? We need permissions to put this in auto nong from the owner of the url
2. Link isn't working
