### ISSUE TITLE
Add flowers are blomming in antartica by vyrval

### ISSUE THREAD

**Issue by NECRODASHING767** [FlafyDev/auto-nong-indexes#1627]
### Song Name

flowers are blomming in antartica

### Artist Name

vyrval

### Source

Youtube

### Youtube Link

COGBAZCJ3A7TfVLQ

### Direct File Link

https://youtu.be/3u-O9UOs6EI?si=COGBAZCJ3A7TfVLQ

### Song ID

3425

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108044117

**Comment by comicsteel** [comment]
reject

invalid yt link
