### ISSUE TITLE
Tidal Wave (Cycki Wave) by Nettil

### ISSUE THREAD

**Issue by Baaddd7000** [FlafyDev/auto-nong-indexes#1630]
### Song Name

Tidal Wave (Cycki Wave)

### Artist Name

Nettil

### Source

Direct file download

### Youtube Link

669d570a

### Song ID

1266014

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86407629

**Comment by Baaddd7000** [comment]
accept

**Comment by comicsteel** [comment]
reject

invalid yt link
