### ISSUE TITLE
Add Change To Win - Just A Game by Christof Bachmeier

### ISSUE THREAD

**Issue by XxChapKoxX** [FlafyDev/auto-nong-indexes#1633]
### Song Name

Change To Win - Just A Game

### Artist Name

Christof Bachmeier

### Source

Youtube

### Youtube Link

h2xgG9bPHhcj3cPW

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108045875

**Comment by comicsteel** [comment]
reject

invalid yt link
