### ISSUE TITLE
THE MONKEY

### ISSUE THREAD

**Issue by JAKDYTY** [FlafyDev/auto-nong-indexes#1636]
### Song Name

THE MONKEY

### Artist Name

haezer

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=nvKGbcX2fyI

### Song ID

679002

**Comment by JAKDYTY** [comment]
btw i forgot to say in extra im trying to make a level with this song so i just picked a random id i wont use

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Jet set" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
