### ISSUE TITLE
Add Clubstep (Vision's pitch) by Vision

### ISSUE THREAD

**Issue by Freedomdiver1** [FlafyDev/auto-nong-indexes#1638]
### Song Name

Clubstep (Vision's pitch)

### Artist Name

Vision

### Source

Youtube

### Youtube Link

v7VqZ-kpq-I

### Song ID

13

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 1347537

**Comment by comicsteel** [comment]
i dont think the artist is called vision
