### ISSUE TITLE
Add Vu dieu 5K by Bo Y Te

### ISSUE THREAD

**Issue by PhonpNB11GH** [FlafyDev/auto-nong-indexes#1639]
### Song Name

Vu dieu 5K

### Artist Name

Bo Y Te

### Source

Youtube

### Youtube Link

f68ORJkjqtEDbYFn

### Song ID

2

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 72352333

**Comment by comicsteel** [comment]
reject

invalid yt link
