### ISSUE TITLE
Add VZLOM by GLYCKOZA

### ISSUE THREAD

**Issue by THALODYGGGG** [FlafyDev/auto-nong-indexes#1646]
### Song Name

VZLOM

### Artist Name

GLYCKOZA

### Source

Direct file download

### Direct File Link

https://open.spotify.com/track/75feEPMGpyT5CzdmUP5sbL?si=2ea84601b7c04d21

### Song ID

659212

### Start Offset [ms]

1

### Extra

Created from Auto Nong.

**Comment by comicsteel** [comment]
reject

spams from same submission
