### ISSUE TITLE
Add VZLOM by GLYCKOZA

### ISSUE THREAD

**Issue by THALODYGGGG** [FlafyDev/auto-nong-indexes#1647]
### Song Name

VZLOM

### Artist Name

GLUKOZA

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=PxrT4MfDdEE

### Song ID

659212

### Start Offset [ms]

1

### Extra

Created from Auto Nong.

**Comment by comicsteel** [comment]
reject

unrelated
