### ISSUE TITLE
ALL CAPS by MF Doom

### ISSUE THREAD

**Issue by D0kida** [FlafyDev/auto-nong-indexes#1650]
### Song Name

ALL CAPS

### Artist Name

Dokida

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=w2sSx6FNz80

### Song ID

4356

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: ALL CAPS - Dokida

**Comment by comicsteel** [comment]
reject

ure not the artist
