### ISSUE TITLE
Add shitty stalemate mashup by julio torria 

### ISSUE THREAD

**Issue by Storm1233211** [FlafyDev/auto-nong-indexes#1651]
### Song Name

shitty stalemate mashup

### Artist Name

kayoszx 

### Source

Youtube

### Youtube Link

m90qIs0J2uA

### Song ID

482872

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 81527152

**Comment by comicsteel** [comment]
reject

its bad...
