### ISSUE TITLE
Side by Side by Felguk

### ISSUE THREAD

**Issue by IgnoreMePls1230** [FlafyDev/auto-nong-indexes#1658]
### Song Name

Side by Side

### Artist Name

Felguk

### Source

Direct file download

### Youtube Link

https://youtu.be/QyuQj8LeqOg?si=tKdN_-xZTgtSaWgU

### Direct File Link

file:///C:/Users/User/OneDrive/%C3%81rea%20de%20Trabalho/Felguk%20-%20Side%20By%20Side%20(Official%20Audio).mp3

### Song ID

1233219

### Start Offset [ms]

0

### Extra

rhmhgh n

**Comment by comicsteel** [comment]
reject

only use yt links
