### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by taki1024** [FlafyDev/auto-nong-indexes#1660]
### Song Name

Lost (XVA Remix)

### Artist Name

CRIM3S

### Source

Youtube

### Youtube Link

https://m.youtube.com/watch?v=I-Brjao7tR8&pp=ygUObG9zdCB4dmEgcmVtaXg%3D

### Song ID

945695

### Start Offset [ms]

0.1 ms

### Extra

anywhere level use the song

**Comment by comicsteel** [comment]
reject

alerady exists
