### ISSUE TITLE
Add Jojo Pose by Apollo Fresh

### ISSUE THREAD

**Issue by m4cHinee** [FlafyDev/auto-nong-indexes#1661]
### Song Name

Jojo Pose

### Artist Name

Apollo Fresh

### Source

Youtube

### Youtube Link

w_Q235AogOp3KcxY

### Song ID

1

### Start Offset [ms]

100

### Extra

Created from Auto Nong.
Created for level: 2119963

**Comment by comicsteel** [comment]
reject

invalid yt link
