### ISSUE TITLE
Add This Was My Life by Megadeth

### ISSUE THREAD

**Issue by yosher2** [FlafyDev/auto-nong-indexes#1664]
### Song Name

This Was My Life

### Artist Name

Megadeth

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=muoHUavIyMU

### Song ID

467339

### Start Offset [ms]

11000

### Extra

Created from Auto Nong.
Created for level: 10565740

**Comment by comicsteel** [comment]
reject

apparently the song and level id linked to bloodbath so is unrelated
