### ISSUE TITLE
Add Nevada by Vicetone, Cozi Zuehlsdorff

### ISSUE THREAD

**Issue by CyZcodes** [FlafyDev/auto-nong-indexes#1681]
### Song Name

Nevada

### Artist Name

Vicetone, Cozi Zuehlsdorff

### Source

Youtube

### Youtube Link

AnMhdn0wJ4I

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 88541450

**Comment by comicsteel** [comment]
reject

level id links to walk thru fire, means the nong is unrelated
