### ISSUE TITLE
Add Walk Thru Fire by Vicetone, Meron Ryan

### ISSUE THREAD

**Issue by CyZcodes** [FlafyDev/auto-nong-indexes#1682]
### Song Name

Walk Thru Fire

### Artist Name

Vicetone, Meron Ryan

### Source

Youtube

### Youtube Link

kRauptdx_Is

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 88541450

**Comment by SpuckwasserDE** [comment]
accept
