### ISSUE TITLE
Add Godzilla by Slim Sh4dy (eminem)

### ISSUE THREAD

**Issue by EternalZer0** [FlafyDev/auto-nong-indexes#1683]
### Song Name

Godzilla

### Artist Name

Slim Sh4dy (Eminem)

### Source

Youtube

### Youtube Link

ol-6J3AmrB2X2w6S

### Song ID

4

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 59847342

**Comment by comicsteel** [comment]
reject

invalid yt link
