### ISSUE TITLE
Add Skibidi Adventures by WaterFlame

### ISSUE THREAD

**Issue by 3dollarsx** [FlafyDev/auto-nong-indexes#1684]
### Song Name

Skibidi Adventures

### Artist Name

WaterFlame

### Source

Youtube

### Youtube Link

U2sHYblWwGs

### Song ID

12

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 428765

**Comment by comicsteel** [comment]
reject

doesnt sync properly
