### ISSUE TITLE
Walk Thru Fire

### ISSUE THREAD

**Issue by Ahysipo** [FlafyDev/auto-nong-indexes#1685]
### Song Name

Walk Thru Fire

### Artist Name

Vicetone

### Source

Youtube

### Youtube Link

https://youtu.be/kRauptdx_Is?si=t47MQAvEHiMdbhmr

### Song ID

1

### Start Offset [ms]

0

### Extra

Used in the level 'Walk Thru Fire' by Skylar

**Comment by comicsteel** [comment]
reject

already existed
