### ISSUE TITLE
Add BLaze Or Iris by Phyrnna

### ISSUE THREAD

**Issue by Soviet-XD** [FlafyDev/auto-nong-indexes#1691]
### Song Name

BLaze Or Iris

### Artist Name

Phyrnna

### Source

Youtube

### Youtube Link

TOdjK4pYCUg

### Song ID

359229

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107456182

**Comment by Soviet-XD** [comment]
Accept

**Comment by Soviet-XD** [comment]
accept

**Comment by SpuckwasserDE** [comment]
accept
