### ISSUE TITLE
Add Lovely Bastards by  ZWE1HVNDXR and yatashigang

### ISSUE THREAD

**Issue by Wompwomp63** [FlafyDev/auto-nong-indexes#1692]
### Song Name

Lovely Bastards

### Artist Name

 ZWE1HVNDXR and yatashigang

### Source

Youtube

### Youtube Link

L5zE7EthV1o

### Song ID

22222

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 95267864

**Comment by SpuckwasserDE** [comment]
accept
