### ISSUE TITLE
Add C18H27NO3 by no

### ISSUE THREAD

**Issue by Demrichok** [FlafyDev/auto-nong-indexes#1693]
### Song Name

C18H27NO3

### Artist Name

no

### Source

Youtube

### Youtube Link

ZEPz2RBW_b5W_n5K

### Song ID

945695

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 27690100

**Comment by comicsteel** [comment]
reject

invalid yt link
