### ISSUE TITLE
Add Gas Gas Gas by Manuel

### ISSUE THREAD

**Issue by ezpz256** [FlafyDev/auto-nong-indexes#1694]
### Song Name

Gas Gas Gas

### Artist Name

Manuel

### Source

Youtube

### Youtube Link

youtube.com/watch?v=atufSv2bLa8

### Song ID

794665

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: Any level

**Comment by ezpz256** [comment]
Also I can't download any songs that i've requested anymore. I've tried to disable and re-enable the mod but it doesn't work.

**Comment by comicsteel** [comment]
accept
