### ISSUE TITLE
Add Pedro by Raffaella Carra

### ISSUE THREAD

**Issue by SoyJ3SU5** [FlafyDev/auto-nong-indexes#1696]
### Song Name

Pedro

### Artist Name

Raffaella Carra

### Source

Youtube

### Youtube Link

https://youtu.be/OCZIzzQpJUw?si=SSzsSsSugSxivspv

### Direct File Link

https://youtu.be/OCZIzzQpJUw?si=SSzsSsSugSxivspv

### Song ID

1987

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 105201767

**Comment by comicsteel** [comment]
accept

**Comment by comicsteel** [comment]
reject
