### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by Aural0** [FlafyDev/auto-nong-indexes#17]
### Song Name

Clubstep x Angry Birds

### Artist Name

DJ-Nate

### Source

Direct file download

### Direct File Link

https://drive.google.com/file/d/1EYZFk_YbDACPz3g2TkkEqB_xOfzoq1A7/view?usp=drive_link

### Song ID

13

**Comment by FlafyDev** [comment]
Auto nong doesn't work with google drive. can you upload it to youtube?

**Comment by Aural0** [comment]
Does it work for direct discord dl links?

**Comment by FlafyDev** [comment]
nope

**Comment by FlafyDev** [comment]
need a proper CDN or upload to youtube

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported
