### ISSUE TITLE
Zodiac

### ISSUE THREAD

**Issue by Yunnblu** [FlafyDev/auto-nong-indexes#1701]
### Song Name

Zodiac Mega Mashup - Sphere x Dame tu cosita, El Pepe, Eso Tilín, Potaxio, Ete Sech

### Artist Name

Yafet

### Source

Youtube

### Youtube Link

https://youtu.be/IPNA-gQhb_s?si=__PDn33PNn44Zjic

### Direct File Link

https://drive.google.com/file/d/1UIzR...

### Song ID

739991

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 52374843``

**Comment by comicsteel** [comment]
accept
