### ISSUE TITLE
Add Nong Song: Sairk - Dreams

### ISSUE THREAD

**Issue by Cybricall** [FlafyDev/auto-nong-indexes#1703]
### Song Name

Sairk - Dreams

### Artist Name

Sairk

### Source

Direct file download

### Direct File Link

https://www.newgrounds.com/audio/listen/860917

### Song ID

860917

### Start Offset [ms]

0

### Extra

Used in the level "Six Hours", sourced from Newgrounds. (I couldn't turn this song into a pc file from Newgrounds so instead I gave you a website link to the song so that you can download and port the song to GD yourself if that's possible).

**Comment by comicsteel** [comment]
reject

we only accept yt links for now
