### ISSUE TITLE
Add enchanted love by linear ring for the level name is enchanted love

### ISSUE THREAD

**Issue by Nigelduky** [FlafyDev/auto-nong-indexes#1706]
### Song Name

enchanted love

### Artist Name

linear ring

### Source

Youtube

### Youtube Link

https://youtu.be/qE6mruRB1PA?si=esXV71oTTtxS7ctd

### Song ID

949936

### Extra

Used in the level "enchanted love" (id: 80398571), and.. may be used in a level I will make for it!

**Comment by Nigelduky** [comment]
Accpet plsss

**Comment by SpuckwasserDE** [comment]
accept
