### ISSUE TITLE
Rebirth Blaster x Queencard by Plexity, (G)I-DLE

### ISSUE THREAD

**Issue by ghost** [FlafyDev/auto-nong-indexes#1707]
### Song Name

Rebirth Blaster x Queencard

### Artist Name

Plexity, (G)I-DLE

### Source

Youtube

### Youtube Link

wYnfJX3FtDY_Qi

### Song ID

574484

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 26681070

**Comment by comicsteel** [comment]
reject

invalid yt link
