### ISSUE TITLE
Add Yamada Perfect by jon-Yakitory

### ISSUE THREAD

**Issue by velocityrifat** [FlafyDev/auto-nong-indexes#1721]
### Song Name

Yamada Perfect

### Artist Name

jon-Yakitory

### Source

Youtube

### Youtube Link

https://youtu.be/zGMftuCqLhk?si=EBVucXSease8HXVu

### Song ID

18

### Start Offset [ms]

0

### Extra

Created from Auto Nong.

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Geometrical Dominator" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
