### ISSUE TITLE
Add Yamada Perfect by jon-YAKITORY

### ISSUE THREAD

**Issue by velocityrifat** [FlafyDev/auto-nong-indexes#1723]
### Song Name

Yamada Perfect

### Artist Name

jon-YAKITORY

### Source

Youtube

### Youtube Link

https://youtu.be/zGMftuCqLhk?si=W-UqCdW9mIyVoiNw

### Song ID

1001

### Start Offset [ms]

0

### Extra

Created from Auto Nong.

**Comment by SpuckwasserDE** [comment]
accept
