### ISSUE TITLE
Take The Slice Song

### ISSUE THREAD

**Issue by Gabriel-Cre** [FlafyDev/auto-nong-indexes#1725]
### Song Name

Take The Slice

### Artist Name

Gab1239Muzic

### Source

Youtube

### Youtube Link

https://youtu.be/WS0ZqIWSy84?si=llTUR4ESDM3JejhK

### Direct File Link

Ex . www.takeaslice.com.Mc3

### Song ID

945367

### Start Offset [ms]

0

### Extra

Used the Level Take A Slice

**Comment by SpuckwasserDE** [comment]
reject

the artist is glass animals
