### ISSUE TITLE
Add Repair Me (Indigo Park Song Animation) by CG5

### ISSUE THREAD

**Issue by DilhnElSalvaNalgones** [FlafyDev/auto-nong-indexes#1727]
### Song Name

Repair Me (Indigo Park Song Animation)

### Artist Name

CG5

### Source

Youtube

### Youtube Link

oG_uqqqoWSw

### Song ID

964033

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108166030
Created from My NEW Level REPAIR ME by me

**Comment by comicsteel** [comment]
reject

ur level is just a 7 second platformer so adding a nong song for it is not worth it sorry
