### ISSUE TITLE
Twisted Garden By ENNWAY

### ISSUE THREAD

**Issue by vittorioms2** [FlafyDev/auto-nong-indexes#1731]
### Song Name

Twisted Garden

### Artist Name

ENNWAY

### Source

Youtube

### Youtube Link

https://youtu.be/3bIy-eaLmKc?si=hvQkDuXkWlYCsKQK

### Direct File Link

https://youtu.be/3bIy-eaLmKc?si=hvQkDuXkWlYCsKQK

### Song ID

1266014

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 99474443

**Comment by comicsteel** [comment]
reject

unrelated nong
