### ISSUE TITLE
Add Twisted Garden by ENNWAY

### ISSUE THREAD

**Issue by vittorioms2** [FlafyDev/auto-nong-indexes#1732]
### Song Name

Twisted Garden

### Artist Name

ENNWAY

### Source

Youtube

### Youtube Link

hvQkDuXkWlYCsKQK

### Song ID

76743

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108166311

**Comment by comicsteel** [comment]
reject

invalid yt link

**Comment by comicsteel** [comment]
reject

unrelated nong
