### ISSUE TITLE
Add pumped up kicks by dytamipro

### ISSUE THREAD

**Issue by Dytamipro** [FlafyDev/auto-nong-indexes#1736]
### Song Name

pumped up kicks

### Artist Name

dytamipro

### Source

Youtube

### Youtube Link

https://youtu.be/eKi9fED6sfM?si=MkOGT32_PaNc3jVk

### Song ID

492978

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 4836730

**Comment by comicsteel** [comment]
reject

ure not the artist and the artist should be foster the people
