### ISSUE TITLE
Add Plague Inc OST - Plague Blossom by Plasstyre

### ISSUE THREAD

**Issue by 2016Hayden** [FlafyDev/auto-nong-indexes#1737]
### Song Name

Plague Inc OST - Plague Blossom

### Artist Name

Plasstyre

### Source

Youtube

### Youtube Link

-Rr1Vrw60WidYcuG

### Song ID

396093

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 65050608

**Comment by comicsteel** [comment]
reject

invalid yt link
