### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by fmgore** [FlafyDev/auto-nong-indexes#1742]
### Song Name

Plug in Baby

### Artist Name

Muse

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=Kler5kYbRqM&t=0s&ab_channel=Muse-Topic

### Song ID

306640

### Extra

nothing, it's just a song that I would like them to add to the level

**Comment by comicsteel** [comment]
accept
