### ISSUE TITLE
Add Dnyami Nochami by Pyrokinesis, MYKKA

### ISSUE THREAD

**Issue by Arturviper0** [FlafyDev/auto-nong-indexes#1768]
### Song Name

Dnyami Nochami

### Artist Name

Pyrokinesis, MYKKA

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=zY7yvZcZIoE

### Song ID

928876

### Start Offset [ms]

0

### Extra

Created from Auto Nong.

**Comment by SpuckwasserDE** [comment]
accept
