### ISSUE TITLE
Add I Got No Time (High Pitch) by The Living Tombstone

### ISSUE THREAD

**Issue by BridylYT** [FlafyDev/auto-nong-indexes#1774]
### Song Name

I Got No Time (High Pitch)

### Artist Name

The Living Tombstone

### Source

Youtube

### Youtube Link

bxpPgiE2nkw

### Song ID

672264

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 59219724

**Comment by comicsteel** [comment]
accept
