### ISSUE TITLE
Add Kocmoc  by Sleeping Hummingbird

### ISSUE THREAD

**Issue by NoxarusGD** [FlafyDev/auto-nong-indexes#1776]
### Song Name

Kocmoc 

### Artist Name

Sleeping Hummingbird

### Source

Youtube

### Youtube Link

frbY511wT4o

### Song ID

1163222

### Start Offset [ms]

0

**Comment by comicsteel** [comment]
reject

doesnt sync and doesnt fit with kocmoc or any other level that uses the remixes
