### ISSUE TITLE
Isolation - Nighthawk22 (E minor)

### ISSUE THREAD

**Issue by GamerAmirTVGD** [FlafyDev/auto-nong-indexes#1778]
### Song Name

Isolation

### Artist Name

Wswaggers

### Source

Direct file download

### Direct File Link

https://jmp.sh/s/M9DUnSDaGzS70xwVFP7a

### Song ID

76743

### Extra

Used In level "Limbo' by Mindcap 86084399

**Comment by comicsteel** [comment]
reject

currently we only accept youtube links

**Comment by GamerAmirTVGD** [comment]
aw ok
