### ISSUE TITLE
Add Crystalia by DJ Totto

### ISSUE THREAD

**Issue by Imanuel307** [FlafyDev/auto-nong-indexes#1780]
### Song Name

Crystalia

### Artist Name

DJ Totto

### Source

Youtube

### Youtube Link

https://youtu.be/LtE7SUCl4Yo?si=Lcys7IPVjF3NmfhQ

### Direct File Link

https://youtu.be/LtE7SUCl4Yo?si=Lcys7IPVjF3NmfhQ

### Song ID

3412

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107434381

**Comment by Imanuel307** [comment]
agree pls :)

**Comment by comicsteel** [comment]
accept
