### ISSUE TITLE
Add Stereo Madness No Copyright by Mx5Knight

### ISSUE THREAD

**Issue by 84018-4397893572222875** [FlafyDev/auto-nong-indexes#1781]
### Song Name

Stereo Madness No Copyright

### Artist Name

Mx5Knight

### Source

Youtube

### Youtube Link

shared

### Song ID

89244

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 77236587

**Comment by comicsteel** [comment]
reject

invalid yt link
