### ISSUE TITLE
Add Ashley Wave Trials x Shake by zZoink

### ISSUE THREAD

**Issue by XandgoGD** [FlafyDev/auto-nong-indexes#1783]
### Song Name

Ashley Wave Trials x Shake

### Artist Name

zZoink

### Source

Youtube

### Youtube Link

VxmxftfBCSA

### Song ID

383158

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 62912799

**Comment by SpuckwasserDE** [comment]
reject

already in the mod - dr. finkelfrackens cure x ishowspeed by bossfight
