### ISSUE TITLE
Add Did I Stutter (speed up) by beamglow

### ISSUE THREAD

**Issue by Droolthing** [FlafyDev/auto-nong-indexes#1787]
### Song Name

Did I Stutter (speed up)

### Artist Name

beamglow

### Source

Youtube

### Youtube Link

T2XpdvsFFqcu0K8o

### Song ID

559803

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 85086987

**Comment by GDFainter** [comment]
Youtube video doesn't exist anymore : Youtube error
![image_2024-07-25_105836035](https://github.com/user-attachments/assets/0ccd3786-d91e-4176-826b-1b3463843c88)

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
