### ISSUE TITLE
Limbo (Vepium Remix High Pitch)

### ISSUE THREAD

**Issue by GamerAmirTVGD** [FlafyDev/auto-nong-indexes#1791]
### Song Name

Limbo (VepiumOfficial & Nighthawk22 - Isolation (Official LIMBO Remix) High Pitch

### Artist Name

NightVail Team [GD]

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=4DtvqLE-Gpo

### Song ID

86084399

### Extra

used in limbo 86084399

**Comment by comicsteel** [comment]
reject

song id is not the level id

**Comment by GamerAmirTVGD** [comment]
whoops just now realized
