### ISSUE TITLE
Golie blyadi 3

### ISSUE THREAD

**Issue by Rollton103** [FlafyDev/auto-nong-indexes#1792]
### Song Name

Golie blyadi 3 

### Artist Name

Detishlux

### Source

Youtube

### Youtube Link

https://youtu.be/rI7L7jXc6Dk?si=bNruk1x06s2sGuA8

### Song ID

433947

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "NK fracture" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
