### ISSUE TITLE
Add Cycles [Piano Cover] by DJVI

### ISSUE THREAD

**Issue by Tv-Github1** [FlafyDev/auto-nong-indexes#1798]
### Song Name

Cycles [Piano Cover]

### Artist Name

DJVI

### Source

Youtube

### Youtube Link

fc4pzhjY20MKJxKm

### Song ID

8

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 379772

**Comment by comicsteel** [comment]
reject

invalid yt link and djvi is not the creator for cycles piano cover
