### ISSUE TITLE
Add Blast Procesing [cover piano] by Waterfame

### ISSUE THREAD

**Issue by Tv-Github1** [FlafyDev/auto-nong-indexes#1801]
### Song Name

Blast Procesing [cover piano]

### Artist Name

Waterfame

### Source

Youtube

### Youtube Link

ZGXcaQQDE01t7ktp

### Song ID

16

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 77239595

**Comment by comicsteel** [comment]
reject
invalid yt link
