### ISSUE TITLE
Phobos x Big Shaq

### ISSUE THREAD

**Issue by GamerAmirTVGD** [FlafyDev/auto-nong-indexes#1803]
### Song Name

Phobos x Big Shaq

### Artist Name

Solkrieg

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=voyk7fXRceY&list=PL6KWVSr0fgt6AvfOV3unGBimg9w1xS0is&index=5

### Song ID

436814

### Extra

used in phobos id: 19759411

**Comment by GamerAmirTVGD** [comment]
accept

**Comment by SpuckwasserDE** [comment]
accept

**Comment by GamerAmirTVGD** [comment]
YEEEEEEEEEEEESSS
