### ISSUE TITLE
Add Lost by CRIM3S

### ISSUE THREAD

**Issue by HereToPlay99** [FlafyDev/auto-nong-indexes#1807]
### Song Name

Lost

### Artist Name

CRIM3S

### Source

Youtube

### Youtube Link

hU06a_VVgL91qEIP

### Song ID

7

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 10109

**Comment by comicsteel** [comment]
reject

unrelated and invalid yt link
