### ISSUE TITLE
Add Skrillex - First of the years  ( experiment GD) by Nakanochan GD

### ISSUE THREAD

**Issue by NakanochanGd** [FlafyDev/auto-nong-indexes#1808]
### Song Name

Skrillex - First of the years  ( experiment GD)

### Artist Name

Nakanochan GD

### Source

Youtube

### Youtube Link

UCKnmJpEdDGMUFuJRv0Qw3ow

### Direct File Link

https://m.youtube.com/channel/UCKnmJpEdDGMUFuJRv0Qw3ow

### Song ID

72371244

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 3264805

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
