### ISSUE TITLE
Add Worst Geometry dash beat Ever Created by Geoblitzy

### ISSUE THREAD

**Issue by MrEpokCoderIdk** [FlafyDev/auto-nong-indexes#1809]
### Song Name

Worst Geometry dash beat Ever Created

### Artist Name

Geoblitzy

### Source

Youtube

### Youtube Link

watch?vWimk6Y15kE8

### Song ID

12

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 428765

**Comment by MrEpokCoderIdk** [comment]
why did I do this shit

**Comment by SpuckwasserDE** [comment]
reject

you need to remove the watch?v from your link

**Comment by MrEpokCoderIdk** [comment]
Sorry I was late to responding but I fixed it dw
