### ISSUE TITLE
Add SHINIGAMI X oxxxmyron by GMD RYTP

### ISSUE THREAD

**Issue by okiau229** [FlafyDev/auto-nong-indexes#1827]
### Song Name

SHINIGAMI X oxxxmyron

### Artist Name

GMD RYTP

### Source

Youtube

### Youtube Link

OiDQf-ccdsQ

### Direct File Link

https://www.youtube.com/watch?v=OiDQf-ccdsQ

### Song ID

714112

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 93262795

**Comment by SpuckwasserDE** [comment]
reject

needs a slight offset
