### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by Roario0602** [FlafyDev/auto-nong-indexes#184]
### Song Name

Epilogue (mashup)

### Artist Name

Xer07 x Creo

### Source

Youtube

### Direct File Link

https://www.dropbox.com/scl/fi/5vwkvlex43906fh9my3hr/Xer07-x-Creo-Epilogue-mashup-_-Mp3-Bullet.ru.mp3?rlkey=5tv7iyxwhwe4q6nfu1exo5hn8&st=s2budocq&dl=0

### Song ID

723714

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported
