### ISSUE TITLE
Add The Golden X Avernus by tgeccov

### ISSUE THREAD

**Issue by GamerAmirTVGD** [FlafyDev/auto-nong-indexes#1841]
### Song Name

The Golden X Avernus

### Artist Name

tgeccov

### Source

Youtube

### Youtube Link

s7Op0L7qHBk

### Song ID

638150

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 60978746

**Comment by Cosmo304** [comment]
reject. test the song in-game before sending it here. The Golden has the song on an offset, meaning it does not sync
