### ISSUE TITLE
Add Kitty City by cyriak

### ISSUE THREAD

**Issue by crimsonwxnter** [FlafyDev/auto-nong-indexes#1842]
### Song Name

Kitty City

### Artist Name

cyriak

### Source

Youtube

### Youtube Link

jX3iLfcMDCw

### Song ID

959666

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 95435650

**Comment by Cosmo304** [comment]
reject. Has nothing to do with the original song
