### ISSUE TITLE
Add Rebel Love Song by Black Veil Brides

### ISSUE THREAD

**Issue by crimsonwxnter** [FlafyDev/auto-nong-indexes#1843]
### Song Name

Rebel Love Song

### Artist Name

Black Veil Brides

### Source

Youtube

### Youtube Link

Rl-_ZmNCOvo

### Song ID

671322

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 74713232

**Comment by Cosmo304** [comment]
reject. The original Newgrounds song was removed
