### ISSUE TITLE
Add Clubstep - Mashup Rihanna Diamonds

### ISSUE THREAD

**Issue by rKapeh** [FlafyDev/auto-nong-indexes#1846]
### Song Name

Clubstep x Rihanna

### Artist Name

miky

### Source

Youtube

### Youtube Link

https://youtu.be/5CatgOY5jbU?si=d3dZQ_3fJHnkVzpO

### Song ID

396093

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: All level with the song Clubstep

**Comment by rKapeh** [comment]
It's a mashup that I love, I would be very grateful if you put it inside.

**Comment by SpuckwasserDE** [comment]
accept

**Comment by SpuckwasserDE** [comment]
i hope it was intentional that this only works for 396093, not 13
