### ISSUE TITLE
Add Kocmoc Evacore Remix V2 by Evacore

### ISSUE THREAD

**Issue by NhuCaiLon1** [FlafyDev/auto-nong-indexes#1850]
### Song Name

Kocmoc Evacore Remix V2

### Artist Name

Evacore

### Source

Youtube

### Youtube Link

tHnbChc_5UU

### Direct File Link

https://www.y2mate.com/vi/youtube-mp3/tHnbChc_5UU

### Song ID

6666

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 89531570

**Comment by comicsteel** [comment]
accept
