### ISSUE TITLE
Add Caliente by rickyedit

### ISSUE THREAD

**Issue by ignaciogfx** [FlafyDev/auto-nong-indexes#1852]
### Song Name

Caliente

### Artist Name

rickyedit

### Source

Youtube

### Youtube Link

xXMLQyZsWVf9xgxv

### Song ID

15108

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 98417984

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
