### ISSUE TITLE
Add Caliente by rickyedit

### ISSUE THREAD

**Issue by ignaciogfx** [FlafyDev/auto-nong-indexes#1853]
### Song Name

Caliente

### Artist Name

rickyedit

### Source

Youtube

### Youtube Link

xXMLQyZsWVf9xgxv

### Direct File Link

https://drive.google.com/file/d/1WkZVDyzsLJC4xnas_IOylmTinUif9W-h/view

### Song ID

15108

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 98417984

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
