### ISSUE TITLE
FUWA FUWA SPRING STORM - 02 Illusionary Night by ELECTR

### ISSUE THREAD

**Issue by Coldmein** [FlafyDev/auto-nong-indexes#1856]
### Song Name

FUWA FUWA SPRING STORM - 02 Illusionary Night

### Artist Name

ELECTR

### Source

Youtube

### Youtube Link

L-ZWcbm4OinAFwir

### Song ID

13

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 102135018
Angelicide - lexycat

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
