### ISSUE TITLE
Add Sound Chimera by Laur

### ISSUE THREAD

**Issue by PyxleIsHere** [FlafyDev/auto-nong-indexes#1858]
### Song Name

Sound Chimera

### Artist Name

Laur

### Source

Youtube

### Youtube Link

2-C9l2-qjAwqvQCf

### Song ID

127473

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 59453742

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
