### ISSUE TITLE
Add Nong Song: mp3

### ISSUE THREAD

**Issue by MiixLyrics** [FlafyDev/auto-nong-indexes#1862]
### Song Name

EL RAP DE PERÚ🗣🇵🇪

### Artist Name

Danm. Xhett

### Source

Youtube

### Youtube Link

https://www.youtube.com/elrapdeperu🗣🇵🇪

### Direct File Link

www.github.com/elrapdeperu

### Song ID

peru

### Extra

El Rap de Peru

**Comment by SpuckwasserDE** [comment]
reject

you cant put text as the song id
