### ISSUE TITLE
Add El Rap de Peru by Danm. Xhett

### ISSUE THREAD

**Issue by MiixLyrics** [FlafyDev/auto-nong-indexes#1863]
### Song Name

El Rap de Peru

### Artist Name

Danm. Xhett

### Source

Youtube

### Youtube Link

elrapdeperu

### Direct File Link

https://www.github.com/elrapdeperu

### Song ID

El Rap de Peru

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 105190671

**Comment by SpuckwasserDE** [comment]
reject

you cant put text as the song id
