### ISSUE TITLE
El Rap De Peru

### ISSUE THREAD

**Issue by MiixLyrics** [FlafyDev/auto-nong-indexes#1864]
### Song Name

El Rap De Peru

### Artist Name

Danm. Xhett

### Source

Youtube

### Youtube Link

https://www.youtube.com/elrapdeperu/@danm.xhett

### Direct File Link

https://www.github.com/elrapdeperu

### Song ID

1234567899

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 100882023

**Comment by MiixLyrics** [comment]
El rap de peru mrd

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
