### ISSUE TITLE
Add CRIM3S - Lost (XVA Remix) / Low pitch by XVA

### ISSUE THREAD

**Issue by Woahmehe** [FlafyDev/auto-nong-indexes#1866]
### Song Name

CRIM3S - Lost (XVA Remix) / Low pitch

### Artist Name

XVA

### Source

Youtube

### Youtube Link

T52Nd5p73ym-3eZR

### Song ID

945695

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108057153

**Comment by SpuckwasserDE** [comment]
@AJXPRO your not a mod lol

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link

**Comment by AJXPRO** [comment]
> @AJXPRO your not a mod lol
How can I be mod?
