### ISSUE TITLE
Add Inferno by Mrs. Green Apple

### ISSUE THREAD

**Issue by Bostacu** [FlafyDev/auto-nong-indexes#1868]
### Song Name

Inferno

### Artist Name

Mrs. Green Apple

### Source

Youtube

### Youtube Link

qGhs4Q2knuzIJcbU

### Song ID

945695

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 27690100

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
