### ISSUE TITLE
Add Sonic Blaster x Big Chungus by F-777

### ISSUE THREAD

**Issue by armali-poop** [FlafyDev/auto-nong-indexes#1869]
### Song Name

Sonic Blaster x Big Chungus

### Artist Name

F-777

### Source

Youtube

### Youtube Link

g08V6IlOzCg

### Song ID

574484

### Start Offset [ms]

5000

### Extra

Created from Auto Nong.
Created for level: 26681070

**Comment by armali-poop** [comment]
it is relevant

**Comment by SpuckwasserDE** [comment]
reject

wrong offset

**Comment by armali-poop** [comment]
its fine for me??
