### ISSUE TITLE
Add lost by crim3s

### ISSUE THREAD

**Issue by IkuMSC** [FlafyDev/auto-nong-indexes#1871]
### Song Name

lost

### Artist Name

crim3s

### Source

Youtube

### Youtube Link

zH0gcBmVcXrNXSkB

### Song ID

945695

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 68794509

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
