### ISSUE TITLE
Add At The Speed Of Light (CR7 Cover) by SuperKek

### ISSUE THREAD

**Issue by ElRandomXX** [FlafyDev/auto-nong-indexes#1883]
### Song Name

At The Speed Of Light (CR7 Cover)

### Artist Name

SuperKek

### Source

Youtube

### Youtube Link

ZBg5TvfsUldQJOR2

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 10565740

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
