### ISSUE TITLE
Add stereo madness PHONK REMIX by vokla

### ISSUE THREAD

**Issue by Cream76284** [FlafyDev/auto-nong-indexes#1887]
### Song Name

stereo madness PHONK REMIX

### Artist Name

vokla

### Source

Youtube

### Youtube Link

KkRybNvGi91CK8PN

### Song ID

461836

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 1556066

**Comment by Cream76284** [comment]
Accept

сб, 27 июл. 2024 г., 18:03 auto-nong[bot] ***@***.***>:

**Comment by Cream76284** [comment]
accept

сб, 27 июл. 2024 г., 21:21 Михаил Кузнецов ***@***.***>:

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link

**Comment by Cream76284** [comment]
Ok, thanks for the update.

вс, 28 июл. 2024 г., 15:45 auto-nong[bot] ***@***.***>:
