### ISSUE TITLE
Add Apparitions Stalk The Night (Remix) by ZUN (Original) Pheonix Project (Remix)

### ISSUE THREAD

**Issue by GaspherVOI** [FlafyDev/auto-nong-indexes#1892]
### Song Name

Apparitions Stalk The Night (Remix)

### Artist Name

ZUN (Original) Pheonix Project (Remix)

### Source

Youtube

### Youtube Link

aB9NGX0VMmQ

### Song ID

20

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108244545

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Fingerdash" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
