### ISSUE TITLE
Add Nong Song: A Nebula Inside 

### ISSUE THREAD

**Issue by Advy44** [FlafyDev/auto-nong-indexes#1896]
### Song Name

A Nebula Inside 

### Artist Name

ELFL

### Source

Direct file download

### Youtube Link

https://youtu.be/lMLyqDpSgGM?si=h9SyMoQEXIj3l0kf

### Direct File Link

/storage/emulated/0/Download/Y2meta.app - ELFL - A Nebula Inside (320 kbps).mp3

### Song ID

156693

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported

**Comment by Advy44** [comment]
> rechazar
> 
> No se admiten fuentes que no sean de YouTube 

> reject
> 
> non-YouTube sources are not supported

Aaa ok, I'm new here haha
