### ISSUE TITLE
Add A Nebula Inside by nlfl

### ISSUE THREAD

**Issue by Advy44** [FlafyDev/auto-nong-indexes#1897]
### Song Name

A Nebula Inside

### Artist Name

nlfl

### Source

Youtube

### Youtube Link

https://youtu.be/lMLyqDpSgGM?si=DPqJC0oERwuV005y

### Song ID

156693

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 95453908

**Comment by SpuckwasserDE** [comment]
reject

duplicate request, see issue 1894
