### ISSUE TITLE
Add Nightcore - Thunder (Gabry Ponte, LUM!X, Prezioso) - (Lyrics) by Syrex

### ISSUE THREAD

**Issue by RaksoGD** [FlafyDev/auto-nong-indexes#1898]
### Song Name

Nightcore - Thunder (Gabry Ponte, LUM!X, Prezioso) - (Lyrics)

### Artist Name

Syrex

### Source

Youtube

### Youtube Link

7QEG3w5EyX86Aiy0

### Song ID

505816

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108325652

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
