### ISSUE TITLE
Add Lost by crim3s

### ISSUE THREAD

**Issue by Lotbit** [FlafyDev/auto-nong-indexes#1901]
### Song Name

Lost

### Artist Name

crim3s

### Source

Youtube

### Youtube Link

watch?vIDzpocvPq4

### Song ID

945695

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 27690100

**Comment by SpuckwasserDE** [comment]
reject

you need to remove the watch?v from your link
