### ISSUE TITLE
Add Shooting Stars by Paul Pollux

### ISSUE THREAD

**Issue by DerEpik** [FlafyDev/auto-nong-indexes#1904]
### Song Name

Shooting Stars

### Artist Name

Paul Pollux

### Source

Youtube

### Youtube Link

vtXhlUMYVTDUJOyw

### Song ID

730373

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 32292932

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
