### ISSUE TITLE
Add Crystallize - [All My Life] by Crystallize

### ISSUE THREAD

**Issue by destrxxy** [FlafyDev/auto-nong-indexes#1913]
### Song Name

Crystallize - [All My Life]

### Artist Name

Crystallize

### Source

Youtube

### Youtube Link

vmDqX3X-cEE

### Song ID

302522

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 19453401

**Comment by destrxxy** [comment]
Yes, I accept.

**Comment by SpuckwasserDE** [comment]
accept
