### ISSUE TITLE
Add Crystallize - [All My Life] (Sync ver.) by Crystallize

### ISSUE THREAD

**Issue by destrxxy** [FlafyDev/auto-nong-indexes#1915]
### Song Name

Crystallize - [All My Life] (Sync ver.)

### Artist Name

Crystallize

### Source

Youtube

### Youtube Link

jZ-vsS5ZU90

### Song ID

302522

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 19453401

**Comment by destrxxy** [comment]
Yes, I accept.

**Comment by SpuckwasserDE** [comment]
accept
