### ISSUE TITLE
Add Symbolic by Death

### ISSUE THREAD

**Issue by DrFunk21** [FlafyDev/auto-nong-indexes#1917]
### Song Name

Symbolic

### Artist Name

Death

### Source

Youtube

### Youtube Link

eaL7zGvJtpFHSx

### Song ID

726252

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 38306937

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
