### ISSUE TITLE
Add Crystal Mountains by Death

### ISSUE THREAD

**Issue by DrFunk21** [FlafyDev/auto-nong-indexes#1919]
### Song Name

Crystal Mountains

### Artist Name

Death

### Source

Youtube

### Youtube Link

dRx2qP8yXuY

### Song ID

726252

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 38306937

**Comment by SpuckwasserDE** [comment]
reject

popular songs are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
