### ISSUE TITLE
Add Octavarium by Dream Theater

### ISSUE THREAD

**Issue by DrFunk21** [FlafyDev/auto-nong-indexes#1920]
### Song Name

Octavarium

### Artist Name

Dream Theater

### Source

Youtube

### Youtube Link

XYV8Zt2k0RQ

### Song ID

726252

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 38306937

**Comment by SpuckwasserDE** [comment]
reject

popular songs are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
