### ISSUE TITLE
Add Astronaut by juliette Reilly

### ISSUE THREAD

**Issue by GGGames2010** [FlafyDev/auto-nong-indexes#1925]
### Song Name

Astronaut

### Artist Name

juliette Reilly

### Source

Youtube

### Youtube Link

DVEtG6hAVN6NHwKX

### Song ID

787153

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 59626284

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
