### ISSUE TITLE
Add red theme batlet by pokeli

### ISSUE THREAD

**Issue by GuineaL018** [FlafyDev/auto-nong-indexes#1926]
### Song Name

red theme batlet

### Artist Name

pokeli

### Source

Youtube

### Youtube Link

6imZ_1MYiguqmpR2

### Song ID

360804

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 79920768

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
