### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by Z-Coder2100** [FlafyDev/auto-nong-indexes#1927]
### Song Name

Speed of Paul

### Artist Name

KingSammelot

### Source

Direct file download

### Direct File Link

https://drive.google.com/uc?export=download&id=1U5li6uw4CvZFd_aymqDcPy_kZ8NdhZEc

### Song ID

467339

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported
