### ISSUE TITLE
Paranoia ost fnf mario madness

### ISSUE THREAD

**Issue by Nightmareglioficial** [FlafyDev/auto-nong-indexes#1930]
### Song Name

Paranoia ost fnf mario madness

### Artist Name

Marco Antonio

### Source

Youtube

### Youtube Link

https://youtu.be/Q5UMKP2K5to?si=wDZcuevcuN1O0iD9

### Song ID

28549

### Start Offset [ms]

0

### Extra

Paranoia 100813464

**Comment by neprao** [comment]
reject

link doesnt work
