### ISSUE TITLE
Add Crossing Field by LiSA

### ISSUE THREAD

**Issue by KinjiGMD** [FlafyDev/auto-nong-indexes#1932]
### Song Name

Crossing Field

### Artist Name

LiSA

### Source

Youtube

### Youtube Link

https://youtu.be/KId6eunoiWk?si=F9mif7pSy8vl6K9m

### Song ID

574678

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 10096589

**Comment by SpuckwasserDE** [comment]
accept
