### ISSUE TITLE
Add Anónimo by Cuarteto de Nos 

### ISSUE THREAD

**Issue by Salchipapasz** [FlafyDev/auto-nong-indexes#1934]
### Song Name

Anónimo

### Artist Name

Cuarteto de Nos

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=KH8PIsSUd9E

### Song ID

1275022

### Extra

I am going to use this nong for my level I would be grateful if it could be done

**Comment by Salchipapasz** [comment]
Hello

**Comment by SpuckwasserDE** [comment]
accept
