### ISSUE TITLE
Add Xo (diaz800 cover) by Noski

### ISSUE THREAD

**Issue by Diesmil** [FlafyDev/auto-nong-indexes#1943]
### Song Name

Xo (diaz800 cover)

### Artist Name

Diaz800

### Source

Youtube

### Youtube Link

https://youtu.be/PA-JgeKuV4k?si=y18b_YDeAQKNZsTd

### Direct File Link

https://www.mediafire.com/file/ke7rtnpd8w8cq2g/EL_MEJOR_COVER_DE_GEOMETRY_DASH_XO_PAN__.mp3/file

### Song ID

766165

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 58825144

**Comment by SpuckwasserDE** [comment]
reject

mashups/covers should have some popularity to show that people want it.
Note that you can still use the nong yourself, but it wont be public
