### ISSUE TITLE
Add Nong Song: Fukkireta

### ISSUE THREAD

**Issue by GreenEnvy10** [FlafyDev/auto-nong-indexes#1990]
### Song Name

Fukkireta

### Artist Name

Kasane Teto

### Source

Youtube

### Youtube Link

https://youtu.be/6gg1ehnDoY8

### Song ID

808406

### Start Offset [ms]

0

**Comment by GreenEnvy10** [comment]
accept

**Comment by GreenEnvy10** [comment]
Reopen

**Comment by SpuckwasserDE** [comment]
reject

popular songs (if used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
