### ISSUE TITLE
Beyond the fire by Don Diablo

### ISSUE THREAD

**Issue by Bilzjuasjuas** [FlafyDev/auto-nong-indexes#1994]
### Song Name

Beyond the fire

### Artist Name

Don Diablo

### Source

Direct file download

### Youtube Link

vztXfR2oBg3t7F2F

### Direct File Link

https://youtu.be/wyQQzaMzo_8?si=vztXfR2oBg3t7F2F

### Song ID

889238

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 57974846

**Comment by SpuckwasserDE** [comment]
reject

change source to youtube, as other sources are not supported
