### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by luminescentgem** [FlafyDev/auto-nong-indexes#20]
### Song Name

Heya

### Artist Name

Ive

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=9ecyOa8DH1k

### Song ID

742681

### Extra

Used in the level "**Heya**" by _Issanagay_

**Comment by SpuckwasserDE** [comment]
reject

ahead of the curve by creo is too popular to serve as the replaced song for smth unrelated
