### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by reddonline** [FlafyDev/auto-nong-indexes#2002]
### Song Name

Stalemate x Big D Randy

### Artist Name

ReddGMD

### Source

Direct file download

### Direct File Link

https://cdn.discordapp.com/attachments/1007926300117311559/1046746878554939502/482872.mp3?ex=66a8233f&is=66a6d1bf&hm=7e6344f46e7eb47b3824f1819369edaa0ad12d8b16477b33f23a8778eccbe166&

### Song ID

482872

### Start Offset [ms]

0

### Extra

Specifically made to work with Stalemate Redux

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported
