### ISSUE TITLE
Add She Wants Me Death by CAZZETTE

### ISSUE THREAD

**Issue by Juanmht** [FlafyDev/auto-nong-indexes#2004]
### Song Name

She Wants Me Death

### Artist Name

CAZZETTE

### Source

Youtube

### Youtube Link

htM6xuCwoXD032_s

### Song ID

11006

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108393623

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
