### ISSUE TITLE
Add Em Khong Hieu High Pitch by CHANGG

### ISSUE THREAD

**Issue by TheBINisgood** [FlafyDev/auto-nong-indexes#2005]
### Song Name

Em Khong Hieu High Pitch

### Artist Name

CHANGG

### Source

Youtube

### Youtube Link

2uQ3EK_MqLM

### Direct File Link

https://cdn.discordapp.com/attachments/952474570093387806/1267382026449977404/em_ko_hieu.mp3?ex=66a894fd&is=66a7437d&hm=172b1da50e0fde61625f8fc62a21133956a1de2f5561594b9e4084ec8fcbe8f8&

### Song ID

18

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 74054225

**Comment by TheBINisgood** [comment]
accept

**Comment by TheBINisgood** [comment]
> Thanks for contributing! Someone will soon review your request.
> 
> Here is the JSON result for the reviewer:
> 
> ```json
> {
>   "name": "Em Khong Hieu High Pitch",
>   "artist": "CHANGG",
>   "source": "youtube",
>   "startOffset": 0,
>   "yt-id": "2uQ3EK_MqLM",
>   "songs": [
>     18
>   ]
> }
> ```
> 
> To accept the request, a reviewer needs to write "accept".

accept

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Geometrical Dominator" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
