### ISSUE TITLE
Add Brain Power by Noma

### ISSUE THREAD

**Issue by GDsk3leton** [FlafyDev/auto-nong-indexes#2008]
### Song Name

Brain Power

### Artist Name

Noma

### Source

Youtube

### Direct File Link

https://youtu.be/cVP8D_FwPU8?si=fvdFUrQUWMk6CWQb

### Song ID

1299591

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 104444534

**Comment by SpuckwasserDE** [comment]
reject

no youtube link given
