### ISSUE TITLE
Add I love Hardcore by Xdree

### ISSUE THREAD

**Issue by FurNice360** [FlafyDev/auto-nong-indexes#2009]
### Song Name

I love Hardcore

### Artist Name

Xdree

### Source

Youtube

### Youtube Link

rvdHxHij1c5tNbZo

### Song ID

123123

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 98154993

**Comment by FurNice360** [comment]
accept

пн, 29 июл. 2024 г., 14:01 auto-nong[bot] ***@***.***>:

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
