### ISSUE TITLE
Add MrLololoshka - The Anthem of Radiance by Quineros AE BOCXOD

### ISSUE THREAD

**Issue by FurNice360** [FlafyDev/auto-nong-indexes#2010]
### Song Name

MrLololoshka - The Anthem of Radiance

### Artist Name

Quineros AE BOCXOD

### Source

Youtube

### Youtube Link

CYqnmwDF6pTzMaku

### Song ID

993

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108395799

**Comment by FurNice360** [comment]
accept

пн, 29 июл. 2024 г., 14:08 auto-nong[bot] ***@***.***>:

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
