### ISSUE TITLE
Add MrLololoshka - The Anthem of Radiance by Quineros AE BOCXOD

### ISSUE THREAD

**Issue by FurNice360** [FlafyDev/auto-nong-indexes#2011]
### Song Name

MrLololoshka - The Anthem of Radiance

### Artist Name

Quineros AE BOCXOD

### Source

Direct file download

### Youtube Link

CYqnmwDF6pTzMaku

### Direct File Link

quineros-ae-voshod-gimn-siyaniya-mp3.mp3

### Song ID

993

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108395799

**Comment by SpuckwasserDE** [comment]
reject

use youtube as source, other sources are not supported
