### ISSUE TITLE
Add dry out rmx by djvi (rmx by robotic wisp)

### ISSUE THREAD

**Issue by Khonlanggg** [FlafyDev/auto-nong-indexes#2019]
### Song Name

dry out rmx

### Artist Name

djvi (rmx by robotic wisp)

### Source

Youtube

### Youtube Link

https://youtu.be/Qpa-ETxt5Vg?si=nwpl1-rB6o0F62Hx

### Song ID

3

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 1314024

**Comment by SpuckwasserDE** [comment]
accept
