### ISSUE TITLE
Add She Wants Me Death by CAZZETTE

### ISSUE THREAD

**Issue by Juanmht** [FlafyDev/auto-nong-indexes#2021]
### Song Name

She Wants Me Death

### Artist Name

CAZZETTE

### Source

Youtube

### Youtube Link

https://youtu.be/FHccClTAdzc?si=OaVKoZ54_ui_RPax

### Song ID

11006

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108393623

**Comment by Juanmht** [comment]
ye

**Comment by SpuckwasserDE** [comment]
accept
