### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by wbiyx** [FlafyDev/auto-nong-indexes#2026]
### Song Name

moment

### Artist Name

vierre cloud

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=1QMG2QjsjdA

### Song ID

1488911

**Comment by wbiyx** [comment]
accept

**Comment by wbiyx** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

song id doesnt exist
