### ISSUE TITLE
Add Shawiase x Skibidi Sigma x Hide Away by DuolingoGD

### ISSUE THREAD

**Issue by DuolingoGD** [FlafyDev/auto-nong-indexes#2029]
### Song Name

Shawiase x Skibidi Sigma x Hide Away

### Artist Name

DuolingoGD

### Source

Youtube

### Youtube Link

VWVBhOZwKAs

### Direct File Link

https://www.mediafire.com/file/w7i3ssquv2xohwn/1266014.mp3/file

### Song ID

1266014

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86407629

**Comment by SpuckwasserDE** [comment]
reject

mashups should have some popularity to show that people want it.
Note that you can still use the nong yourself, but it wont be public
