### ISSUE TITLE
Add Shawiase x Skibidi Sigma x Hide Away by DuolingoGD

### ISSUE THREAD

**Issue by DuolingoGD** [FlafyDev/auto-nong-indexes#2030]
### Song Name

Shawiase x Skibidi Sigma x Hide Away

### Artist Name

DuolingoGD

### Source

Youtube

### Youtube Link

VWVBhOZwKAs

### Song ID

1266014

### Extra

Created from Auto Nong.
Created for level: 94498010

**Comment by SpuckwasserDE** [comment]
reject

mashups should have some popularity to show that people want it.
Note that you can still use the nong yourself, but it wont be public
