### ISSUE TITLE
Add Purge ~K~ by Kubatko

### ISSUE THREAD

**Issue by Soviet-XD** [FlafyDev/auto-nong-indexes#2035]
### Song Name

Purge ~K~

### Artist Name

Kubatko

### Source

Youtube

### Youtube Link

ffLs4E6FD4w

### Song ID

354826

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 3072765

**Comment by Soviet-XD** [comment]
accept

**Comment by Soviet-XD** [comment]
accept

**Comment by Soviet-XD** [comment]
accept

**Comment by Soviet-XD** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

popular songs like toe xl are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
