### ISSUE TITLE
Add flor de la sandia(frutas en el aire) by Riki Musso

### ISSUE THREAD

**Issue by Andiuuhx** [FlafyDev/auto-nong-indexes#2039]
### Song Name

flor de la sandia(frutas en el aire)

### Artist Name

Riki Musso

### Source

Youtube

### Youtube Link

GhevHXnAAwGAe1jQ

### Song ID

640986

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 73356823

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
