### ISSUE TITLE
Add Endgame X Eminem by Waterflame

### ISSUE THREAD

**Issue by pipe1155** [FlafyDev/auto-nong-indexes#2045]
### Song Name

Endgame X Eminem

### Artist Name

Waterflame

### Source

Youtube

### Youtube Link

https://youtu.be/AbhMgRP5IcU?si=S2R0BBH96OsFX5xI

### Song ID

587069

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 2997354

**Comment by pipe1155** [comment]
yes

**Comment by SpuckwasserDE** [comment]
accept
