### ISSUE TITLE
Add Tidal Wave by OniLink

### ISSUE THREAD

**Issue by Kostya2412** [FlafyDev/auto-nong-indexes#2048]
### Song Name

Tidal Wave

### Artist Name

OniLink

### Source

Youtube

### Youtube Link

mgQL2xeviN8

### Song ID

1266014

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86407629

**Comment by SpuckwasserDE** [comment]
reject

the song name and artist name are incorrect, also pretty sure the song is already added
