### ISSUE TITLE
Add cycles rmx by ...

### ISSUE THREAD

**Issue by Khonlanggg** [FlafyDev/auto-nong-indexes#2050]
### Song Name

cycles rmx

### Artist Name

...

### Source

Youtube

### Youtube Link
https://youtu.be/AQXJSVWmTSo?si=Of-3ON-OICyNzNKS

### Song ID

8

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 161116

**Comment by SpuckwasserDE** [comment]
reject

try only using the youtube id for link
