### ISSUE TITLE
Add Sonic Blaster X Don Pollo by F-777

### ISSUE THREAD

**Issue by JustToilet** [FlafyDev/auto-nong-indexes#2054]
### Song Name

Sonic Blaster X Don Pollo

### Artist Name

F-777

### Source

Youtube

### Youtube Link

07DzXHPHXnUV0QBw

### Song ID

574484

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 102265892

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
