### ISSUE TITLE
Add cycles rmx by ...

### ISSUE THREAD

**Issue by Khonlanggg** [FlafyDev/auto-nong-indexes#2063]
### Song Name

cycles rmx

### Artist Name

...

### Source

Youtube

### Youtube Link

nJWfDas5kg6PFRLr

### Song ID

8

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 161116

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
