### ISSUE TITLE
Add tek it by cafun

### ISSUE THREAD

**Issue by KorraGd** [FlafyDev/auto-nong-indexes#2069]
### Song Name

Tek it (I watch the moon)

### Artist Name

cafun

### Source

Youtube

### Youtube Link

srnEjfykY8lECfyG

### Song ID

100

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86871436

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
