### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by Enderb0t75** [FlafyDev/auto-nong-indexes#2071]
### Song Name

FFM (I don't know which way to turn)

### Artist Name

Cacola

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=th8xY21wTPs

### Song ID

1298493

### Start Offset [ms]

0

### Extra

Going to be used in FFM by Enderb0t75

**Comment by Enderb0t75** [comment]
It will take a while for it to be closed

**Comment by SpuckwasserDE** [comment]
accept
