### ISSUE TITLE
Add Lonely - Yoe Mase (Geometry dash) by Yoe Mase

### ISSUE THREAD

**Issue by YandelXD** [FlafyDev/auto-nong-indexes#2072]
### Song Name

Lonely - Yoe Mase (Geometry dash)

### Artist Name

Yoe Mase

### Source

Youtube

### Youtube Link

https://youtu.be/VFErR0FdB0Q?si=cF8Qgx_bcARbu05W

### Song ID

1254555

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 102033033

**Comment by YandelXD** [comment]
Accept

**Comment by YandelXD** [comment]
Accept

**Comment by SpuckwasserDE** [comment]
accept
