### ISSUE TITLE
Add Nong Song: STAYSOLD - TEMPLAR

### ISSUE THREAD

**Issue by DarkShark558** [FlafyDev/auto-nong-indexes#2077]
### Song Name

STAYSOLD - TEMPLAR

### Artist Name

STAYSOLD

### Source

Youtube

### Youtube Link

https://youtu.be/qQqQvJTYdfg?si=ECInTwctGmjySRCg

### Song ID

102995

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
accept
