### ISSUE TITLE
Flawless Wings Of Yatagarasu x Bonfire

### ISSUE THREAD

**Issue by Empyrious** [FlafyDev/auto-nong-indexes#208]
### Song Name

Flawless Wings Of Yatagarasu x Bonfire

### Artist Name

EmpyriousGD

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=6th7J6ejl5w

### Direct File Link

https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqblgzTnk1ZDQwa3pTYzhUaW00d0FxTlNodno4d3xBQ3Jtc0tsZVFVanNoQW0zRzVGSW41TXM5bDd6SDRVTktUQVlMVDRvS1RMem00SlhWVk54OHVHWEd1RURNSzlmQ082N2FXMjdtU0paZzFUNDdrbkFYaFF6a3E3aXlkRGR2eHJmeENaeTBqbWNlYWF4QkhfaXNCdw&q=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1juJWkkEWwdqZET3B1CUL8WCH0kVJKdZl%2Fview%3Fusp%3Dsharing&v=6th7J6ejl5w

### Song ID

490479

**Comment by SpuckwasserDE** [comment]
accept

**Comment by Empyrious** [comment]
forgot to not make "of" capitalize you don't need to update it if you want i thought it wasnt gonna send a request
