### ISSUE TITLE
Add Beliver by Imagine Dragons 

### ISSUE THREAD

**Issue by AskMarti** [FlafyDev/auto-nong-indexes#2081]
### Song Name

Beliver

### Artist Name

Imagine Dragons

### Source

Youtube

### Youtube Link

7wtfhZwyrcc

### Song ID

299992

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 84066035

**Comment by CyanYTplays** [comment]
You bring me up you bring me up believer believer
