### ISSUE TITLE
Add SS EN TERRITORIO ENEMIGO by wolfnacht

### ISSUE THREAD

**Issue by Maxuwu7w7** [FlafyDev/auto-nong-indexes#2086]
### Song Name

SS EN TERRITORIO ENEMIGO

### Artist Name

wolfnacht

### Source

Youtube

### Youtube Link

ivCo_42vSlHR25XA

### Song ID

945695

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 27690100

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
