### ISSUE TITLE
Add CLXBBIN (Clubstep Phonk Remix) by MXGY

### ISSUE THREAD

**Issue by Greenevsky** [FlafyDev/auto-nong-indexes#2092]
### Song Name

CLXBBIN (Clubstep Phonk Remix)

### Artist Name

MXGY

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=-rK-5wrmRiM

### Song ID

13

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108477196

**Comment by Greenevsky** [comment]
its not stale you dumb bot

**Comment by SpuckwasserDE** [comment]
accept
