### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by i7lex** [FlafyDev/auto-nong-indexes#210]
### Song Name

Virtual Idols

### Artist Name

remix

### Source

Direct file download

### Direct File Link

https://www.mediafire.com/file/uzg1dwybhe12c1w/794165.mp3?dkey=nmg8mhn20nr&r=780

### Song ID

794165

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported
