### ISSUE TITLE
Add Thermodynamix X Bolgy Wolgy by DJ Nate

### ISSUE THREAD

**Issue by Moonwolf14** [FlafyDev/auto-nong-indexes#2101]
### Song Name

Thermodynamix X Bolgy Wolgy

### Artist Name

DJ Nate

### Source

Youtube

### Youtube Link

2oN7K1uhkgE

### Song ID

770520

### Start Offset [ms]

0

### Extra

X-3
Nuzzles, pounces on you
UwU, you're so warm
Couldn't help but notice your bulge from across the floor
Nuzzles your necky wecky; murr; (he-he)
Unzips your baggy ass pants, oh, baby, you' so musky
Take me home, pet me and make me yours
And don't forget to stuff me
See me wag my wittle baby tail, all for your bulgy-wulgy
Kissies and lickies you' neck, I hope daddy likies
Nuzzle and wuzzles your chest (yeah), I be (yeah) getting thirsty
Hey, I got a little itch, you think you can help me?
Only seven inches long, UwU
Please adopt me!
Paws on your bulge as I lick my lips
(OwO, punish me please)
Gotta hit 'em with this furry shit (he don't see it coming)

**Comment by CyanYTplays** [comment]
If someone uses this ima draw furry art in gd 💀

**Comment by Moonwolf14** [comment]
I thinked some of my mashups by ear and it's quite off, I'm syncing them with Audacity now
