### ISSUE TITLE
Add Danger by Rareblin

### ISSUE THREAD

**Issue by CyanYTplays** [FlafyDev/auto-nong-indexes#2128]
### Song Name

Danger

### Artist Name

Rareblin

### Source

Youtube

### Youtube Link

kSvy4wbGv62sgsCc

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for a layout.

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
