### ISSUE TITLE
Add Renai Circulation「恋愛サーキュレーション」歌ってみた【＊なみりん】*namirin

### ISSUE THREAD

**Issue by mintydoesthings** [FlafyDev/auto-nong-indexes#2137]
### Song Name

Renai Circulation???????????????????*????

### Artist Name

*namirin

### Source

Youtube

### Youtube Link

qVXHo-bRNIpSSlL4

### Song ID

3

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 12663648

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
