### ISSUE TITLE
Add Renai Circulation???????????????????*???? by *namirin

### ISSUE THREAD

**Issue by mintydoesthings** [FlafyDev/auto-nong-indexes#2138]
### Song Name

Renai Circulation???????????????????*????

### Artist Name

*namirin

### Source

Youtube

### Youtube Link

https://youtu.be/uKxyLmbOc0Q?si=SQkt9wVHWozHZ0wt

### Song ID

3

### Start Offset [ms]

0

### Extra

please add

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Dry Out" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
