### ISSUE TITLE
at the speed of light guitar cover

### ISSUE THREAD

**Issue by GermanyURU** [FlafyDev/auto-nong-indexes#214]
### Song Name

At The Speed Of Light (Guitar Cover)

### Artist Name

Zimnior12

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=S9h5MyltJqE

### Song ID

467339

### Extra

"aftercatabath" - 57215346
"cataclysm" - 3979721
"bloodbath" - 467339
"aftermath" - 25610878

**Comment by SpuckwasserDE** [comment]
explain to me why it is called guitar cover and ill Accept it

**Comment by comicsteel** [comment]
reject

already existed and why is it called guitar cover anyway
