### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by fiban123** [FlafyDev/auto-nong-indexes#2145]
### Song Name

Loreen - Tattoo (Trusta Hardstyle Bootleg)

### Artist Name

Loreen, Trusta

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=39qqvAXdMPg

### Song ID

815245

### Start Offset [ms]

0

### Extra

Will be used in a level of mine

**Comment by fiban123** [comment]
...

**Comment by SpuckwasserDE** [comment]
reject

popular songs (used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
I suggest using a different song as a replaced song, maybe theres a remix on newgrounds?

**Comment by fiban123** [comment]
ok i willl
