### ISSUE TITLE
Add ? x TETVOVEN

### ISSUE THREAD

**Issue by Garzon16** [FlafyDev/auto-nong-indexes#2149]
### Song Name

? x TETVOVEN

### Artist Name

GDVL MASHUP 2024

### Source

Youtube

### Youtube Link

19Ob5-cQnFD-6fqZ

### Song ID

727020

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 62556400

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
