### ISSUE TITLE
Add ? x Rap Cham Thoi (Offest Fix) by GDVL MASHUP 2024

### ISSUE THREAD

**Issue by Garzon16** [FlafyDev/auto-nong-indexes#2150]
### Song Name

? x Rap Cham Thoi (Offest Fix)

### Artist Name

GDVL MASHUP 2024

### Source

Youtube

### Youtube Link

YjQXddtIjlJli-md

### Song ID

727020

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 62556400

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
