### ISSUE TITLE
Sphere Ultimate mashup 9 artists

### ISSUE THREAD

**Issue by FinSoulGD** [FlafyDev/auto-nong-indexes#2172]
### Song Name

Sphere ultimate mashup

### Artist Name

Creo, Miranda Cosgrove, eminem, El chombo, Dj jazzy jeff, will smith, doja cat, backstreet boys, kanye west, childish gambino, the living tombstone

### Source

Youtube

### Youtube Link

https://youtu.be/vtaUc-9_554?si=hdYHvT10VnLsCvf9

### Song ID

739991

### Start Offset [ms]

23

**Comment by SpuckwasserDE** [comment]
I love it, if I ever play Zodiac I will use this

**Comment by SpuckwasserDE** [comment]
accept

**Comment by FinSoulGD** [comment]
Thanks for adding this to gd i really mean it
