### ISSUE TITLE
Airborne Robots (Zoftle remix)

### ISSUE THREAD

**Issue by SnS4k42** [FlafyDev/auto-nong-indexes#2174]
### Song Name

Airborne Robots (Zoftle remix)

### Artist Name

Zoftle

### Source

Youtube

### Youtube Link

7maFrftQKXQfq33I

### Direct File Link

https://youtu.be/ECPl3MB9RL0?si=7maFrftQKXQfq33I

### Song ID

25

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 77240642

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
