### ISSUE TITLE
Add Sonic Blaster X Big Chungus by F-777 vs Endigo

### ISSUE THREAD

**Issue by Al3xGD18** [FlafyDev/auto-nong-indexes#2179]
### Song Name

Sonic Blaster X Big Chungus

### Artist Name

F-777 vs Endigo

### Source

Youtube

### Youtube Link

TRv0zZNpmNa5P2sz

### Direct File Link

https://youtu.be/-TQS5aj7uBg?si=TRv0zZNpmNa5P2sz

### Song ID

574484

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 4015623

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
