### ISSUE TITLE
Add Finall x Isolation by Toby fox 

### ISSUE THREAD

**Issue by MrDupe** [FlafyDev/auto-nong-indexes#2182]
### Song Name

Finall x Isolation

### Artist Name

Toby fox 

### Source

Youtube

### Youtube Link

https://youtu.be/5PTIhCCA8WM?si=B3va4qdAgPbwHJcJ

### Song ID

76743

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 104722306

**Comment by SpuckwasserDE** [comment]
reject

song is too short and can therefore not serve as a replacement for isolation
