### ISSUE TITLE
Add TURU R9 by DJJUNE01

### ISSUE THREAD

**Issue by whatsaname771** [FlafyDev/auto-nong-indexes#2189]
### Song Name

TURU R9

### Artist Name

DJJUNE01

### Source

Youtube

### Youtube Link

ZesHz8mNIMBiMTsQ

### Song ID

10011223

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108534751

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
