### ISSUE TITLE
Add Give Me Back The Night (Schtiffles Remix) by Schtiffles

### ISSUE THREAD

**Issue by Juanmht** [FlafyDev/auto-nong-indexes#2190]
### Song Name

Give Me Back The Night (Schtiffles Remix)

### Artist Name

Schtiffles

### Source

Youtube

### Youtube Link

https://youtu.be/thzVnOiLViY?si=0lQbcUJu7N7FCJew

### Song ID

762712

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 87232063

**Comment by Juanmht** [comment]
Ye

**Comment by SpuckwasserDE** [comment]
accept
