### ISSUE TITLE
 I want to add a cool russian minecraft youtuber's song to geode.

### ISSUE THREAD

**Issue by Nappix871** [FlafyDev/auto-nong-indexes#2198]
### Song Name

I Can Buy You (RMTK)

### Artist Name

Wiscur

### Source

Youtube

### Youtube Link

https://youtu.be/KAYAyAPhX_0?si=K8nAURBEFcCpjXgz

### Song ID

533927

### Start Offset [ms]

0

### Extra

My favorite song ever❤️❤️

**Comment by SpuckwasserDE** [comment]
reject

popular songs like the nine Nine Circles song are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
