### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by AlwaysJolly** [FlafyDev/auto-nong-indexes#22]
### Song Name

PUNK TACTICS

### Artist Name

Joey Valence & Brae

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=OklSZmIx9-o

### Song ID

151235

**Comment by AlwaysJolly** [comment]
Same thing with this, no rated levels use the song and it's the song ID of the replacement the level uses.

**Comment by FlafyDev** [comment]
accept
