### ISSUE TITLE
Add crazy x flow by creo

### ISSUE THREAD

**Issue by Lxrdkanxko** [FlafyDev/auto-nong-indexes#2201]
### Song Name

crazy x flow

### Artist Name

creo

### Source

Youtube

### Youtube Link

L2CPyuxm3PRNI1C9

### Song ID

905108

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 87901006

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
