### ISSUE TITLE
Add Shiawase (VIP) x Stitches by Dion Timmer x Shawn Mendes

### ISSUE THREAD

**Issue by MisTTisM** [FlafyDev/auto-nong-indexes#2205]
### Song Name

Shiawase (VIP) x Stitches

### Artist Name

Dion Timmer x Shawn Mendes

### Source

Youtube

### Youtube Link

jCW45aOYj5Td0c_E

### Song ID

1266014

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 100575641

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
