### ISSUE TITLE
Add crazy x flow by creo

### ISSUE THREAD

**Issue by Lxrdkanxko** [FlafyDev/auto-nong-indexes#2209]
### Song Name

crazy x flow

### Artist Name

creo

### Source

Youtube

### Youtube Link

L2CPyuxm3PRNI1C9

### Direct File Link

https://ytmp3s.nu/l1U3/

### Song ID

905108

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86018142

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
