### ISSUE TITLE
Add Flew Far Faster (FFF) by Doin

### ISSUE THREAD

**Issue by deandre32** [FlafyDev/auto-nong-indexes#2212]
### Song Name

Flew Far Faster (FFF)

### Artist Name

Doin

### Source

Youtube

### Youtube Link

_tyo3TfDSTx2oNcS

### Song ID

905110

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 77461295

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
