### ISSUE TITLE
Electrodynamix

### ISSUE THREAD

**Issue by Yarub123456** [FlafyDev/auto-nong-indexes#2213]
### Song Name

Electrodynamix Dako remix

### Artist Name

DakoMusic

### Source

Direct file download

### Direct File Link

947500_Electrodynamix-Dako-Remix.mp3

### Song ID

947500

### Start Offset [ms]

0

**Comment by Yarub123456** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported
