### ISSUE TITLE
Add Carousel by Amidst x Sacry

### ISSUE THREAD

**Issue by DiegoG1608** [FlafyDev/auto-nong-indexes#2216]
### Song Name

Carousel

### Artist Name

Amidst x Sacry

### Source

Youtube

### Youtube Link

e6st_84nQvQAs5BK

### Song ID

818917

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 56898043

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
