### ISSUE TITLE
Add Nong Song: STAY x Epilogue

### ISSUE THREAD

**Issue by will13131313** [FlafyDev/auto-nong-indexes#2218]
### Song Name

Stay

### Artist Name

The Kid LAROI, Creo

### Source

Youtube

### Youtube Link

https://youtu.be/WRqfT-8X4Nk

### Song ID

732714

### Start Offset [ms]

3800

### Extra

used in acu

**Comment by will13131313** [comment]
pls dont forget abt this one i reuploaded it 1 month ago and got left

**Comment by SpuckwasserDE** [comment]
i remember this one

**Comment by SpuckwasserDE** [comment]
accept
