### ISSUE TITLE
Add Nong Song: Viking Arena by F-777

### ISSUE THREAD

**Issue by dariochicomalo** [FlafyDev/auto-nong-indexes#2228]
### Song Name

Viking Arena

### Artist Name

F-777

### Source

Youtube

### Youtube Link

https://youtu.be/oawvTsTInBU?list=PLzco4N2wXWKGTHnI4XvwUdAbm2mLytREL

### Song ID

24

**Comment by NDKcute** [comment]
accept?

**Comment by SpuckwasserDE** [comment]
accept
