### ISSUE TITLE
Add Tidal Wave by Dion Timmer

### ISSUE THREAD

**Issue by Tinalt** [FlafyDev/auto-nong-indexes#2230]
### Song Name

Tidal Wave

### Artist Name

Dion Timmer

### Source

Youtube

### Youtube Link

6RyfmO3c4v34Jz2j

### Song ID

1266014

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86407629

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
