### ISSUE TITLE
Add Payload by Dex Arson

### ISSUE THREAD

**Issue by dariochicomalo** [FlafyDev/auto-nong-indexes#2231]
### Song Name

Payload

### Artist Name

Dex Arson

### Source

Youtube

### Youtube Link

https://youtu.be/P2xYukG4F3c?list=PLzco4N2wXWKG5RPdMTfm8kNlOpVouPogL

### Song ID

27

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 77241646

**Comment by SpuckwasserDE** [comment]
accept
