### ISSUE TITLE
Son mis amigos

### ISSUE THREAD

**Issue by Oliverkahn07** [FlafyDev/auto-nong-indexes#2233]
### Song Name

Marta, Sebas, Guile y los demás

### Artist Name

Amaral

### Source

Youtube

### Youtube Link

https://youtu.be/HPX-b6ZQD0s?si=RvMDz_8TKqOUETPb

### Direct File Link

O

### Song ID

17

### Start Offset [ms]

0

### Extra

No

**Comment by SpuckwasserDE** [comment]
reject

popular songs like ToE 2 are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
