### ISSUE TITLE
Add we are the pro stargrinders by Jumpyball x Billy Joel

### ISSUE THREAD

**Issue by lTorenn** [FlafyDev/auto-nong-indexes#2235]
### Song Name

we are the pro stargrinders

### Artist Name

Jumpyball x Billy Joel

### Source

Youtube

### Youtube Link

Ln0FuNcOhLiU_o0a

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 4456683

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
