### ISSUE TITLE
Add TheFatRat - Windfall x Close To The Sun Mashup by TheFatRat

### ISSUE THREAD

**Issue by Amazing1509** [FlafyDev/auto-nong-indexes#2236]
### Song Name

TheFatRat - Windfall x Close To The Sun Mashup

### Artist Name

TheFatRat

### Source

Youtube

### Youtube Link

https://youtu.be/-QK6lnbNsOA?si=HsSCBqxvuBffj_U4

### Song ID

621135

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 4957691

**Comment by SpuckwasserDE** [comment]
accept

**Comment by SpuckwasserDE** [comment]
im using that
