### ISSUE TITLE
 Clubstep{piano cover} by OfficialGoorgo

### ISSUE THREAD

**Issue by Ghbhh33** [FlafyDev/auto-nong-indexes#2243]
### Song Name

Clubstep{piano cover}

### Artist Name

OfficialGoorgo

### Source

Youtube

### Youtube Link

jxJZzf_Tb2Xr8qxO

### Song ID

13

### Start Offset [ms]

1134457

### Extra

Created from Auto Nong.
Created for level: 90876934

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
