### ISSUE TITLE
Add CYBERNETIC HEART by Ivycomb Music

### ISSUE THREAD

**Issue by Deitz578** [FlafyDev/auto-nong-indexes#2251]
### Song Name

CYBERNETIC HEART

### Artist Name

Ivycomb Music

### Source

Youtube

### Youtube Link

hnJr0Fdm0bU

### Song ID

1016476

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108578139

**Comment by Deitz578** [comment]
So i just put a random comment to reopen or?

**Comment by SpuckwasserDE** [comment]
reject

popular songs (used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
