### ISSUE TITLE
Add Godzilla (Feat. Juice WRLD) by Eminem

### ISSUE THREAD

**Issue by SZGCrow** [FlafyDev/auto-nong-indexes#2252]
### Song Name

Godzilla

### Artist Name

Eminem, Juice WRLD

### Source

Youtube

### Youtube Link

T5J_F7MBnZhseU7S

### Song ID

4

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 59847342

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
