### ISSUE TITLE
Add Nong Aria Math - C418

### ISSUE THREAD

**Issue by fiban123** [FlafyDev/auto-nong-indexes#2253]
### Song Name

Aria Math

### Artist Name

C418

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=6YFJk326vHY

### Song ID

815245

### Extra

will be used in an upcoming level

**Comment by SpuckwasserDE** [comment]
reject

same here, use a not as popular song as a replaced song, or find a remix on newgrounds
