### ISSUE TITLE
Lost

### ISSUE THREAD

**Issue by ZeanRavendt** [FlafyDev/auto-nong-indexes#2255]
### Song Name

Lost (XVA Remix)

### Artist Name

CRIM3S

### Source

Youtube

### Youtube Link

https://m.youtube.com/watch?v=ua75lp0Q-Mo&pp=ygUQbG9zdCAoeHZhIHJlbWl4KQ%3D%3D

### Direct File Link

https://on.soundcloud.com/H3KmzT7fNdiRmRW2A

### Song ID

945695

### Start Offset [ms]

0

### Extra

Slaughterhouse-27690100

**Comment by SpuckwasserDE** [comment]
reject

this ones already in the mod
