### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by SoleTrash329656** [FlafyDev/auto-nong-indexes#2261]
### Song Name

Sphere x Leviating

### Artist Name

Nightvail Team

### Source

Youtube

### Youtube Link

https://youtu.be/6qr6GFEvn8Y?si=BDl9EnVXiX4Wtxuc

### Direct File Link

https://www.mediafire.com/file/5211wfpng0b4vh8/Zodiac_x_Levitating_My_Ver_Sync.mp3/file

### Song ID

739991

### Start Offset [ms]

23.0

### Extra

Used zodiac

**Comment by SpuckwasserDE** [comment]
accept
