### ISSUE TITLE
Add Sphere by CreoMusic

### ISSUE THREAD

**Issue by SoleTrash329656** [FlafyDev/auto-nong-indexes#2262]
### Song Name

Sphere

### Artist Name

CreoMusic

### Source

Youtube

### Youtube Link

BDl9EnVXiX4Wtxuc

### Song ID

739991

### Start Offset [ms]

30

### Extra

Created from Auto Nong.
Created for level: 53858796

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
