### ISSUE TITLE
Add Core by Zed

### ISSUE THREAD

**Issue by GDBenybeni** [FlafyDev/auto-nong-indexes#2265]
### Song Name

Core

### Artist Name

Zef

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=Z8D9PfRzeJg

### Song ID

4

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 56028719

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Base after Base" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
