### ISSUE TITLE
Add Second Warning by Dr.ReB

### ISSUE THREAD

**Issue by Poisongaurdian1** [FlafyDev/auto-nong-indexes#2273]
### Song Name

Second Warning

### Artist Name

Dr.ReB

### Source

Youtube

### Youtube Link

pe3h62MrlPE

### Song ID

122

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108498477

**Comment by SpuckwasserDE** [comment]
accept
