### ISSUE TITLE
Add Cradles x Blast!

### ISSUE THREAD

**Issue by IXxXLbunbune** [FlafyDev/auto-nong-indexes#2274]
### Song Name

Cradles x Blast!

### Artist Name

Sub Urban x Big Baby Tape

### Source

Youtube

### Youtube Link

64ihJjHemn1mJ8mS

### Song ID

10011223

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 106987309

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
