### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by ReTenDer** [FlafyDev/auto-nong-indexes#2275]
### Song Name

Kawaii Dancing Girl (Yandere Remix)

### Artist Name

Mistry, yandere

### Source

Direct file download

### Direct File Link

https://web.ligaudio.ru/mp3/kawaii%20dancing%20girl%20yandere?ysclid=lze9tlroo7824839783

### Song ID

13798561

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from
