### ISSUE TITLE
Add lost x el rap del pepe ete sech by crim3s

### ISSUE THREAD

**Issue by angelconatun41** [FlafyDev/auto-nong-indexes#2281]
### Song Name

lost x el rap del pepe ete sech

### Artist Name

crim3s

### Source

Direct File download

### Youtube Link

qFHRLsoTVRA

### Direct File Link

https://www.mediafire.com/file/laatifg6brd24a7/945695.mp3/file

### Song ID

945695

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 105623347

**Comment by SpuckwasserDE** [comment]
reject

wrong offset
