### ISSUE TITLE
Add Jawbreaker (High Pitch) by Rukkus

### ISSUE THREAD

**Issue by Logboi731** [FlafyDev/auto-nong-indexes#2286]
### Song Name

Jawbreaker (High Pitch)

### Artist Name

Rukkus

### Source

Youtube

### Youtube Link

TQ1b0HCw9gA

### Song ID

546561

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 6939821

**Comment by NDKcute** [comment]
accept
