### ISSUE TITLE
Add Betrayal of Fear low piched by goukisan

### ISSUE THREAD

**Issue by ItzEmmanuelG** [FlafyDev/auto-nong-indexes#2291]
### Song Name

Betrayal of Fear low piched

### Artist Name

goukisan

### Source

Youtube

### Youtube Link

gsp6OL7yq4STaF4i

### Song ID

167229

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 89220865

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
