### ISSUE TITLE
Add 4etire tridcat by Violetta Sokolova

### ISSUE THREAD

**Issue by ProviaZoV** [FlafyDev/auto-nong-indexes#2297]
### Song Name

Четыре Тридцать

### Artist Name

Violetta Sokolova

### Source

Youtube

### Youtube Link

KdZzWEfrHIBf4JzM

### Direct File Link

https://youtu.be/ixjDLdvoC5Q?si=KdZzWEfrHIBf4JzM

### Song ID

54558

### Start Offset [ms]

0

### Extra

Created from Auto Nong.

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
