### ISSUE TITLE
Add tidal wave by g2961

### ISSUE THREAD

**Issue by Sol1Mihaly** [FlafyDev/auto-nong-indexes#2299]
### Song Name

tidal wave

### Artist Name

g2961

### Source

Youtube

### Youtube Link

pkzaOPblt68

### Song ID

1298724

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 98209637

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
