### ISSUE TITLE
Lost (XVA Remix) x World Cup Mashup

### ISSUE THREAD

**Issue by Firzo** [FlafyDev/auto-nong-indexes#23]
### Song Name

Lost (XVA Remix) x World Cup Mashup

### Artist Name

AidanTR

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=FsiXaDwrTWg

### Song ID

945695

### Extra

27690100

**Comment by Firzo** [comment]
accept

**Comment by elnexreal** [comment]
I'll reject this because the song has a very bad offset
