### ISSUE TITLE
Add Peanut Butter Jelly Time by Buckwheat Boyz

### ISSUE THREAD

**Issue by daniel12123** [FlafyDev/auto-nong-indexes#2301]
### Song Name

Peanut Butter Jelly Time

### Artist Name

Buckwheat Boyz

### Source

Youtube

### Youtube Link

fFDlnEdRwWHbpiLZ

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 90047160

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
