### ISSUE TITLE
CUANDO SE TE MOJA LA TAREA

### ISSUE THREAD

**Issue by exquisitley** [FlafyDev/auto-nong-indexes#2308]
### Song Name

CUANDO SE TE MOJA LA TAREA

### Artist Name

LDDR

### Source

Youtube

### Youtube Link

xSGAIYM4h7o

### Direct File Link

https://www.youtube.com/watch?v=xSGAIYM4h7o

### Song ID

20

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 28672992

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Fingerdash" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
