### ISSUE TITLE
 Montagem Bionca Espectral 2

### ISSUE THREAD

**Issue by exquisitley** [FlafyDev/auto-nong-indexes#2309]
### Song Name

Montagem Bionca Espectral 2

### Artist Name

DJ OLIVEIRA

### Source

Youtube

### Youtube Link

5pAcQLoqqwQ

### Song ID

8

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 278956

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Cycles" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
