### ISSUE TITLE
Add SICKO MODE RESONANCE by jonsch

### ISSUE THREAD

**Issue by Shadowizawesome** [FlafyDev/auto-nong-indexes#2310]
### Song Name

SICKO MODE RESONANCE

### Artist Name

jonsch

### Source

Youtube

### Youtube Link

bEgae6xbZDeVL7DH

### Song ID

12345

### Start Offset [ms]

0

### Extra

Made specifically bc I like this song :3c I hope there can be some cool levels with it!

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
