### ISSUE TITLE
Add Cute depressed by dyan dxddy

### ISSUE THREAD

**Issue by PlayZinFR** [FlafyDev/auto-nong-indexes#2312]
### Song Name

Cute depressed (Perfection)

### Artist Name

dyan dxddy

### Source

Youtube

### Youtube Link

cYqstnwZ2LU

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108565155

**Comment by MyDadWentWihatj** [comment]
> Thanks for contributing! Someone will soon review your request.
> 
> Here is the JSON result for the reviewer:
> 
> ```json
> {
>   "name": "Cute depressed (Perfection)",
>   "artist": "dyan dxddy",
>   "source": "youtube",
>   "startOffset": 0,
>   "yt-id": "cYqstnwZ2LU",
>   "songs": [
>     1
>   ]
> }
> ```
> 
> To accept the request, a reviewer needs to write "accept".

Accept
