### ISSUE TITLE
Make you mine by Madison Beer

### ISSUE THREAD

**Issue by Kerfydude** [FlafyDev/auto-nong-indexes#2316]
### Song Name

Make you mine

### Artist Name

Madison Beer

### Source

Youtube

### Youtube Link

IcMdxFUU5ZjOwKrK

### Song ID

726062

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 726062

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
