### ISSUE TITLE
Baby Hotline

### ISSUE THREAD

**Issue by MyDadWentWihatj** [FlafyDev/auto-nong-indexes#2317]
### Song Name

Baby Hotline

### Artist Name

Jack Stauber

### Source

Youtube

### Youtube Link

https://youtu.be/jbTj2M3vmts?si=DxHAqzHeyq1z-dUr

### Song ID

1

**Comment by MyDadWentWihatj** [comment]
Please

**Comment by MyDadWentWihatj** [comment]
accept

**Comment by SpuckwasserDE** [comment]
is this still relevant? already accepted your other request for song id 1000

**Comment by MyDadWentWihatj** [comment]
You didn't respond!

**Comment by MyDadWentWihatj** [comment]
> is this still relevant? already accepted your other request for song id 1000

It dosent show up in geode (auto nong)

**Comment by MyDadWentWihatj** [comment]
> is this still relevant? already accepted your other request for song id 1000

Yo please fix I dosent show in game
