### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by MyDadWentWihatj** [FlafyDev/auto-nong-indexes#2319]
### Song Name

Baby Hotline

### Artist Name

Jack Stauber

### Source

Youtube

### Youtube Link

https://youtu.be/jbTj2M3vmts?si=DxHAqzHeyq1z-dUr

### Song ID

1000

### Extra

Please respond

**Comment by MyDadWentWihatj** [comment]
{
  "name": "Baby Hotline",
  "artist": "Jack Stauber",
  "source": "youtube",
  "startOffset": 0,
  "yt-id": "jbTj2M3vmts",
  "songs": [
    1000
  ]
}

**Comment by MyDadWentWihatj** [comment]
accept

**Comment by MyDadWentWihatj** [comment]
https://cdn.jsdelivr.net/gh/FlafyDev/auto-nong-indexes@dist/official.json.gz

**Comment by SpuckwasserDE** [comment]
accept
