### ISSUE TITLE
Dr. Frinkelfrackens X IShowSpeed (Correct version)

### ISSUE THREAD

**Issue by Bodysz** [FlafyDev/auto-nong-indexes#2334]
### Song Name

Dr. Frinkelfrackens X IShowSpeed (Correct Version)

### Artist Name

Bossfight

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=1D-GSvW2d5k

### Song ID

383158

### Start Offset [ms]

0

### Extra

This is the correct version of Zoink's mashup 
(Watch here : https://www.youtube.com/watch?v=pzFduXI6sJM )

**Comment by Bodysz** [comment]
I failed the link sorry : https://www.youtube.com/watch?v=q5mj0XMppFk

**Comment by SpuckwasserDE** [comment]
reject

the song is already in the mod
