### ISSUE TITLE
Add Barracuda by NoiseStorm

### ISSUE THREAD

**Issue by Markiz283Attacks** [FlafyDev/auto-nong-indexes#2336]
### Song Name

Barracuda

### Artist Name

NoiseStorm

### Source

Youtube

### Youtube Link

LGamaKv0zNg

### Song ID

1260456

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 99461054

**Comment by FlafyDev** [comment]
accept

**Comment by FlafyDev** [comment]
accept
