### ISSUE TITLE
Add lost x el rap del pepe by crim3s

### ISSUE THREAD

**Issue by angelconatun41** [FlafyDev/auto-nong-indexes#2339]
### Song Name

lost x el rap del pepe

### Artist Name

crim3s

### Source

Direct file download

### Youtube Link

qFHRLsoTVRA

### Direct File Link

https://cdn.discordapp.com/attachments/1220122981435576543/1224227135628116030/945695.mp3?ex=66b10a1e&is=66afb89e&hm=c83ba1008275de31e9454412e39a8e2f10ad6f9e5c837edb4a60080765fbf170&

### Song ID

945695

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 105623347

**Comment by FlafyDev** [comment]
reject

-wrong song offset
-discord links are not allowed
