### ISSUE TITLE
Add crimewave by crystallcastles

### ISSUE THREAD

**Issue by legendaponosa2289** [FlafyDev/auto-nong-indexes#2343]
### Song Name

crimewave

### Artist Name

crystallcastles

### Source

Direct file download

### Song ID

520618

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 100183881

**Comment by legendaponosa2289** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

no link provided
