### ISSUE TITLE
Creo - Spere X Rhett & Link: Nerd vs Geek rap battle. Mashup

### ISSUE THREAD

**Issue by continuummm1** [FlafyDev/auto-nong-indexes#235]
### Song Name

Creo - Spere X Rhett & Link: Nerd vs Geek rap battle. Mashup

### Artist Name

Creo, Rhett, Link, RaQwA, Dorito0910

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=HkHrc7S9-xk

### Song ID

739991

### Extra

used in the level: zodiac

**Comment by beetle15** [comment]
PLS ACEP

**Comment by continuummm1** [comment]
Pls do

**Comment by SpuckwasserDE** [comment]
accept
