### ISSUE TITLE
Add Nong Song: Base After Base x Lady Gaga

### ISSUE THREAD

**Issue by bigmanvidi** [FlafyDev/auto-nong-indexes#2356]
### Song Name

Base After Base x Lady Gaga

### Artist Name

DJVI

### Source

Direct file download

### Direct File Link

https://cdn.discordapp.com/attachments/666654256908206101/1269784774893895682/BaseAfterBase.mp3?ex=66b152b9&is=66b00139&hm=efa2ec66b7e5def8b6b446765e6f4c29a8fe7ebef3a178644d10b455a5d51fbd&

### Song ID

4

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from

(yours is not permanent)
