### ISSUE TITLE
Add Nong Song: Blast Processing x Avicii

### ISSUE THREAD

**Issue by bigmanvidi** [FlafyDev/auto-nong-indexes#2357]
### Song Name

Blast Processing x Avicii

### Artist Name

Waterflame

### Source

Direct file download

### Direct File Link

https://cdn.discordapp.com/attachments/666654256908206101/1269784775573504040/BlastProcessing.mp3?ex=66b152b9&is=66b00139&hm=6fadae42c3dc71f2151dc70b89ccbab0944f417699dbda6ae62eaf5b1e8af51f&

### Song ID

16

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from

(yours is not permanent)
