### ISSUE TITLE
Add Nong Song: Cycles x Coldplay

### ISSUE THREAD

**Issue by bigmanvidi** [FlafyDev/auto-nong-indexes#2361]
### Song Name

Cycles x Coldplay

### Artist Name

DJVI

### Source

Direct file download

### Direct File Link

https://cdn.discordapp.com/attachments/666654256908206101/1269784776919748608/Cycles.mp3?ex=66b152ba&is=66b0013a&hm=6d1b6f85ad002d4bc8e531e5d52cd81b41bb797a2a7793fa635b2d8ee45adf03&

### Song ID

8

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from

(yours is not permanent)
