### ISSUE TITLE
Add Nong Song: Deadlocked x Imagine Dragons

### ISSUE THREAD

**Issue by bigmanvidi** [FlafyDev/auto-nong-indexes#2362]
### Song Name

Deadlocked x Imagine Dragons

### Artist Name

F-777

### Source

Direct file download

### Direct File Link

https://cdn.discordapp.com/attachments/666654256908206101/1269784777180057611/Deadlocked.mp3?ex=66b152ba&is=66b0013a&hm=f6ba41e13375f62f8904059fc710b2c1bc3541439120440c3f924016ee9e9ac9&

### Song ID

19

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from

(yours is not permanent)
