### ISSUE TITLE
Add Nong Song: Electrodynamix x Safe & Sound

### ISSUE THREAD

**Issue by bigmanvidi** [FlafyDev/auto-nong-indexes#2364]
### Song Name

Electrodynamix x Safe & Sound

### Artist Name

dj-Nate, Capital Cities

### Source

Direct file download

### Direct File Link

https://cdn.discordapp.com/attachments/666654256908206101/1269784777842495538/Electrodynamix.mp3?ex=66b152ba&is=66b0013a&hm=9e39f8700aa29439b147ebb26820ce6240340a9561cd05baea8f504863a8a7f3&

### Song ID

14

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from

(yours is not permanent)
