### ISSUE TITLE
Add Nong Song: Electroman Adventures x Shooting Stars

### ISSUE THREAD

**Issue by bigmanvidi** [FlafyDev/auto-nong-indexes#2365]
### Song Name

Electroman Adventures x Shooting Stars

### Artist Name

Waterflame, Bag Raiders

### Source

Direct file download

### Direct File Link

https://cdn.discordapp.com/attachments/666654256908206101/1269788884859097119/Electroman.mp3?ex=66b1568d&is=66b0050d&hm=4d3934889264921b02255638e60f66f9784d5044a4a5c2d3f5ca0d8226168934&

### Song ID

12

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from

(yours is not permanent)
