### ISSUE TITLE
Add Nong Song: Jumper x I'm Yours

### ISSUE THREAD

**Issue by bigmanvidi** [FlafyDev/auto-nong-indexes#2368]
### Song Name

Jumper x I'm Yours

### Artist Name

Waterflame, Jason Mraz

### Source

Direct file download

### Direct File Link

https://cdn.discordapp.com/attachments/666654256908206101/1269788885848948736/Jumper.mp3?ex=66b1568d&is=66b0050d&hm=6c191db29c33d6f721aa47bb2173c02730a47cdd0e47be6afd8fde11bacf2a0f&

### Song ID

6

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from

(yours is not permanent)
