### ISSUE TITLE
Add Nong Song: Polargeist x Black and Yellow

### ISSUE THREAD

**Issue by bigmanvidi** [FlafyDev/auto-nong-indexes#2369]
### Song Name

Polargeist x Black and Yellow

### Artist Name

Step, Wiz Khalifa

### Source

Direct file download

### Direct File Link

https://cdn.discordapp.com/attachments/666654256908206101/1269788886201008178/Polargeist.mp3?ex=66b1568e&is=66b0050e&hm=64c900e27773200a0560aa2a84233bd9afcc91e481e5f1b5d035257d76f1e401&

### Song ID

2

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from

(yours is not permanent)
