### ISSUE TITLE
Add Nong Song: Theory Of Everything x Carly Rae Jepsen

### ISSUE THREAD

**Issue by bigmanvidi** [FlafyDev/auto-nong-indexes#2370]
### Song Name

Theory Of Everything x Carly Rae Jepsen

### Artist Name

dj-Nate

### Source

Direct file download

### Direct File Link

https://cdn.discordapp.com/attachments/666654256908206101/1269788886754660425/TheoryOfEverything.mp3?ex=66b1568e&is=66b0050e&hm=4087ce79cc913296957bc53e8fa35b3bc650603546bdb315431a814170a72804&

### Song ID

11

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from

(yours is not permanent)
