### ISSUE TITLE
Add Nong Song: Theory Of Everything 2 x Pink

### ISSUE THREAD

**Issue by bigmanvidi** [FlafyDev/auto-nong-indexes#2371]
### Song Name

Theory Of Everything 2 x Pink

### Artist Name

dj-Nate

### Source

Direct file download

### Direct File Link

https://cdn.discordapp.com/attachments/666654256908206101/1269788887123890327/TheoryOfEverything2.mp3?ex=66b1568e&is=66b0050e&hm=fdeefb370d58eff37168dd3e69b6a9fa5e7a5b3d1cfce237ca6829d949e115ff&

### Song ID

17

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from

(yours is not permanent)
