### ISSUE TITLE
Add Nong Song: Time Machine x Revenge

### ISSUE THREAD

**Issue by bigmanvidi** [FlafyDev/auto-nong-indexes#2372]
### Song Name

Time Machine x Revenge

### Artist Name

Waterflame, CaptainSparklez, TryHardNinja

### Source

Direct file download

### Direct File Link

https://cdn.discordapp.com/attachments/666654256908206101/1269788887342125087/TimeMachine.mp3?ex=66b1568e&is=66b0050e&hm=393b9e396a5afc1e5ee573d7a992150b6aecf2220eb0d9d0db63d8dbf3c752d3&

### Song ID

7

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from

(yours is not permanent)
