### ISSUE TITLE
Add Nong Song: xStep x Maroon 5

### ISSUE THREAD

**Issue by bigmanvidi** [FlafyDev/auto-nong-indexes#2373]
### Song Name

xStep x Maroon 5

### Artist Name

DJVI

### Source

Direct file download

### Direct File Link

https://cdn.discordapp.com/attachments/666654256908206101/1269788887719350322/xStep.mp3?ex=66b1568e&is=66b0050e&hm=5b9174f5693d4abe20f5a6cfaff2c9da3dc144c18ff1b185212f2999c7f5efff&

### Song ID

9

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from

(yours is not permanent)
