### ISSUE TITLE
"Địt nhau trên cây cau" for level "Dit nhau tren cay cau"

### ISSUE THREAD

**Issue by NDKcute** [FlafyDev/auto-nong-indexes#2381]
### Song Name

Địt nhau trên cây cau

### Artist Name

kanicchi

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=V-nXRo7drzY&t=0s

### Song ID

Nong

### Start Offset [ms]

0

### Extra

Used in the lv "Dit nhau tren cay cau" - id: 83933638

**Comment by DuyKhia** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

song id needs to be a number
