### ISSUE TITLE
At the Speed of Light x Rap God by Dimrain47

### ISSUE THREAD

**Issue by LevGasht** [FlafyDev/auto-nong-indexes#2382]
### Song Name

At the Speed of Light x Rap God

### Artist Name

Dimrain47

### Source

Youtube

### Youtube Link

qMw1TjgDnj33hAFs

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.

**Comment by LevGasht** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
