### ISSUE TITLE
Add At the Speed of Light x Rap God by Dimrain47

### ISSUE THREAD

**Issue by LevGasht** [FlafyDev/auto-nong-indexes#2383]
### Song Name

At the Speed of Light x Rap God

### Artist Name

Dimrain47

### Source

Youtube

### Youtube Link

qMw1TjgDnj33hAFs

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 7573669

**Comment by LevGasht** [comment]
Accept

**Comment by LevGasht** [comment]
accept

пн, 5 авг. 2024 г., 08:06 auto-nong[bot] ***@***.***>:

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
