### ISSUE TITLE
Add At the Speed of Light x Rap God by Dimrain47

### ISSUE THREAD

**Issue by LevGasht** [FlafyDev/auto-nong-indexes#2393]
### Song Name

At the Speed of Light x Rap God

### Artist Name

Dimrain47

### Source

Youtube

### Youtube Link

https://youtu.be/Wv2NLzBeX5Q?si=qMw1TjgDnj33hAFs

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 7573669

**Comment by LevGasht** [comment]
accept

пн, 5 авг. 2024 г., 12:50 auto-nong[bot] ***@***.***>:

**Comment by SpuckwasserDE** [comment]
accept
