### ISSUE TITLE
Core

### ISSUE THREAD

**Issue by InvisibleGame6** [FlafyDev/auto-nong-indexes#2394]
### Song Name

Core

### Artist Name

Zef

### Source

Youtube

### Youtube Link

https://youtu.be/vw557zol5Cw?si=DmWvo9YGCamPOtfN

### Song ID

4

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 56028719

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Base after Base" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
