### ISSUE TITLE
One love

### ISSUE THREAD

**Issue by TTarol** [FlafyDev/auto-nong-indexes#2399]
### Song Name

One love 

### Artist Name

C.Z kind 

### Source

Youtube

### Youtube Link

https://youtu.be/dZkOOi-L0aM?si=y7De2vAOyAXemVWv

### Song ID

7864

### Start Offset [ms]

1

### Extra

Used in the level your mom - 96234709

**Comment by SpuckwasserDE** [comment]
accept
