### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by fucksd** [FlafyDev/auto-nong-indexes#24]
### Song Name

tidal wave

### Artist Name

idk

### Source

Youtube

### Youtube Link

https://youtu.be/hxSWtELthRo?si=PnlvVjl1cH_Jdrhz

### Direct File Link

https://youtu.be/hxSWtELthRo?si=PnlvVjl1cH_Jdrhz

### Song ID

1266014

### Extra

tidal wave

**Comment by SpuckwasserDE** [comment]
reject

artist and song name must be descriptive
