### ISSUE TITLE
Add One love by c.z kind

### ISSUE THREAD

**Issue by TTarol** [FlafyDev/auto-nong-indexes#2400]
### Song Name

One love

### Artist Name

c.z kind

### Source

Youtube

### Youtube Link

wK_LaGDKL0E9N76b

### Song ID

7864

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 96234709

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
