### ISSUE TITLE
Sonic blaster mega-mashup

### ISSUE THREAD

**Issue by FinSoulGD** [FlafyDev/auto-nong-indexes#2401]
### Song Name

Sonic blaster Mega-Mashup

### Artist Name

F-777

### Source

Youtube

### Youtube Link

https://youtu.be/ZXq_7BkTZ5c?si=6H9laP8p-WqGSTDf

### Song ID

574484

### Start Offset [ms]

0

**Comment by FinSoulGD** [comment]
Accept this

**Comment by SpuckwasserDE** [comment]
reject

mashups/covers should have some popularity to show that people want it (especially if the song doesnt sound great).
Note that you can still use the nong yourself, but it wont be public
