### ISSUE TITLE
Sonic blaster X 2 Phut Hon

### ISSUE THREAD

**Issue by FinSoulGD** [FlafyDev/auto-nong-indexes#2402]
### Song Name

Sonic blaster X 2 Phut Hon

### Artist Name

Light night music

### Source

Youtube

### Youtube Link

https://youtu.be/hlG9meH2lhQ?si=QQGglLHH6ZKPoqOM

### Song ID

574484

### Start Offset [ms]

0

**Comment by FinSoulGD** [comment]
Accept this

**Comment by SpuckwasserDE** [comment]
accept
