### ISSUE TITLE
Add 505 by arctic monkeys

### ISSUE THREAD

**Issue by Muslim-cool** [FlafyDev/auto-nong-indexes#2405]
### Song Name

505

### Artist Name

arctic monkeys

### Source

Youtube

### Youtube Link

https://youtu.be/qU9mHegkTc4?si=-FM0WqxPzXRiObZo

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 68322322

**Comment by SpuckwasserDE** [comment]
reject

duplicate request, no worries the song has been accepted
