### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by GreenEnvy10** [FlafyDev/auto-nong-indexes#2406]
### Song Name

Electric Angel

### Artist Name

Yasuo

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=sSYoz0JmnZo

### Song ID

593489

### Start Offset [ms]

0

**Comment by GreenEnvy10** [comment]
reopen

**Comment by SpuckwasserDE** [comment]
accept
