### ISSUE TITLE
Add nightmare by boy with uke

### ISSUE THREAD

**Issue by IBGoatman** [FlafyDev/auto-nong-indexes#2416]
### Song Name

nightmare

### Artist Name

boy with uke

### Source

Youtube

### Youtube Link

fyqd606URzzgZSEF

### Song ID

10101

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 59489931

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
