### ISSUE TITLE
Add Sendan Life (Katagiri Bootleg) by Shoue, Katagiri

### ISSUE THREAD

**Issue by Arturviper0** [FlafyDev/auto-nong-indexes#242]
### Song Name

Sendan Life (Katagiri Bootleg)

### Artist Name

Shoue, Katagiri

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=qy4oe4rEGsw

### Song ID

18856464

### Extra

Created from Auto Nong.
Created for level: 106590574

**Comment by FlafyDev** [comment]
accept
