### ISSUE TITLE
vsdox

### ISSUE THREAD

**Issue by Bilembo174** [FlafyDev/auto-nong-indexes#2421]
### Song Name

vsdox

### Artist Name

undertale

### Source

Youtube

### Youtube Link

PTXm9zJMf7AkJsNh

### Direct File Link

https://youtu.be/mTcUEboHq8Q?si=PTXm9zJMf7AkJsNh

### Song ID

587069

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 5904109

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
