### ISSUE TITLE
Add D.A.A.N.A.C.C.E by NegaRen

### ISSUE THREAD

**Issue by Leonardo2212** [FlafyDev/auto-nong-indexes#2424]
### Song Name

D.A.A.N.A.C.C.E

### Artist Name

NegaRen

### Source

Youtube

### Youtube Link

b-14xMtAZ8bhdmM1

### Song ID

1

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 106801438

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
