### ISSUE TITLE
Add i wanna be here by Deathbrain

### ISSUE THREAD

**Issue by zspringkyl-b4** [FlafyDev/auto-nong-indexes#2428]
### Song Name

i wanna be here

### Artist Name

Deathbrain

### Source

Youtube

### Youtube Link

3KAYr3qepGqw1JGn

### Song ID

827

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 97428235

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
