### ISSUE TITLE
Add Base After Base by DJVI (FULL VERSIONS)

### ISSUE THREAD

**Issue by Tv-Github1** [FlafyDev/auto-nong-indexes#2431]
### Song Name

Base After Base

### Artist Name

DJVI 

### Source

Youtube

### Youtube Link

https://youtu.be/TZULkgQPHt0?si=Ctcl_VsWTVnZv0-9

### Song ID

4

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 3294

**Comment by SpuckwasserDE** [comment]
reject

that's litterally already the song in game

**Comment by Tv-Github1** [comment]
But is it the full version you have?
