### ISSUE TITLE
Add dance till your dead by what the beep just happened

### ISSUE THREAD

**Issue by BeigeArtist1951** [FlafyDev/auto-nong-indexes#2433]
### Song Name

Dance till your dead

### Artist Name

A person

### Source

Youtube

### Youtube Link

_zV0WiekcPU

### Song ID

2

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 13519

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Polargeist" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
