### ISSUE TITLE
Add (ORIGINAL)Drink my piss you nasty slut yeah yeah by Lil darkie

### ISSUE THREAD

**Issue by BieluchGD** [FlafyDev/auto-nong-indexes#2434]
### Song Name

(ORIGINAL)Drink my piss you nasty slut yeah yeah

### Artist Name

Lil darkie

### Source

Youtube

### Youtube Link

kOlY_b9YxCTJ8QR6

### Song ID

1257815

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
IT IS FOR CRACKHEAD CIRCLES OR CREATIONS THAT U MAKE

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
