### ISSUE TITLE
No sabía que canción poner xd

### ISSUE THREAD

**Issue by Username3344** [FlafyDev/auto-nong-indexes#2437]
### Song Name

Bartolito el gallo

### Artist Name

nose

### Source

Youtube

### Youtube Link

1DoBoCEHbwb2KH8o

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 1244147

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link

**Comment by Username3344** [comment]
Accept
