### ISSUE TITLE
Add Eternal Silence by DJ-Nate

### ISSUE THREAD

**Issue by Kawoshin1995** [FlafyDev/auto-nong-indexes#244]
### Song Name

Eternal Silence

### Artist Name

DJ-Nate

### Source

Direct file download

### Youtube Link

JWUg2ZILWbM

### Direct File Link

https://ve32.aadika.xyz/download/JWUg2ZILWbM/mp3/320/1718534567/a24f379462d65e099ffeeef1be635b3de57fe350c5e2beba473fec34dd599988/1?f=Y2mate.mx

### Song ID

13

### Extra

Created from Auto Nong.
Created for level: 59075347

**Comment by Kawoshin1995** [comment]
accept

**Comment by FlafyDev** [comment]
link isn't working
