### ISSUE TITLE
"Thằng Điên" for level "Thang Dien"

### ISSUE THREAD

**Issue by NDKcute** [FlafyDev/auto-nong-indexes#2440]
### Song Name

Thằng Điên

### Artist Name

JUSTATEE x PHƯƠNG LY

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=HXkh7EOqcQ4

### Song ID

2378

### Start Offset [ms]

0

### Extra

Used in the level "Thang dien" - id: 60846065

**Comment by DuyKhia** [comment]
accept
