### ISSUE TITLE
Add Surface (Low Pitch) by Dimrain47

### ISSUE THREAD

**Issue by Amazing1509** [FlafyDev/auto-nong-indexes#2444]
### Song Name

Surface (Low Pitch)

### Artist Name

Dimrain47

### Source

Youtube

### Youtube Link

https://youtu.be/T8kjvZUXwm8?si=QU3XOFW4xnyy65ap

### Song ID

63082

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 27122654

**Comment by Amazing1509** [comment]
comment

**Comment by SpuckwasserDE** [comment]
accept
