### ISSUE TITLE
Add avalon kars epic theme by sameul kim

### ISSUE THREAD

**Issue by Thewrld-prog** [FlafyDev/auto-nong-indexes#2445]
### Song Name

avalon kars epic theme

### Artist Name

sameul kim

### Source

Direct file download

### Direct File Link

https://app.mediafire.com/hda26486j4kx1

### Song ID

63082

### Start Offset [ms]

5

### Extra

Created from Auto Nong.
Created for level: 108712788

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from
