### ISSUE TITLE
 Codependence X Mr beast by Darmageon 

### ISSUE THREAD

**Issue by Pengel996** [FlafyDev/auto-nong-indexes#2453]
### Song Name

Codependence X Mr beast

### Artist Name

Darmageon 

### Source

Youtube

### Youtube Link

1Ctd4...

### Song ID

727020

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 94258024

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
