### ISSUE TITLE
Add Crazy x DB RAP by None

### ISSUE THREAD

**Issue by Citydivers** [FlafyDev/auto-nong-indexes#246]
### Song Name

Crazy x DB RAP

### Artist Name

None

### Source

Direct file download

### Direct File Link

https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqbkZOR0Y3TjQxRmZld3M1QlFoTlF3OVh4ZXJBd3xBQ3Jtc0ttcWFPdlFMVC1mNXk0RjU5M1JEd01wY1FrQ3J4Y1lMZ3hNR1p2bGE1ZVpvRGNHbF9haTRVMktmdUNoeWVxV0N2NWNsM1owYy1od0NSQTNrM0lpam9OUTdKYmpEYmlYeEZGa3ZfSHVrWEhpVVNHaTFrMA&q=https%3A%2F%2Fwww.mediafire.com%2Ffile%2F41jfv8na4mz837v%2Fkyouki_mashup.mp3%2Ffile

### Song ID

905108

### Extra

Created from Auto Nong.
Created for level: 60060213

**Comment by FlafyDev** [comment]
reject

mediafile links are not supported. I suggest uploading the audio to YouTube or using an existing YouTube video.
