### ISSUE TITLE
Add Viking Arena (Piano Cover) by F-777

### ISSUE THREAD

**Issue by comicsteel** [FlafyDev/auto-nong-indexes#2461]
### Song Name

Viking Arena (Piano Cover)

### Artist Name

PNG

### Source

Youtube

### Youtube Link

5hkuUMuF-bs

### Song ID

24

### Start Offset [ms]

2450

### Extra

Created from Auto Nong.
Created for level: 77240637

**Comment by comicsteel** [comment]
accept

**Comment by DuyKhia** [comment]
accept
