### ISSUE TITLE
Add Deadlocked (phonk) by Cerulity

### ISSUE THREAD

**Issue by fa2233** [FlafyDev/auto-nong-indexes#2463]
### Song Name

Deadlocked (phonk)

### Artist Name

Cerulity

### Source

Youtube

### Youtube Link

QsoL69j5pzCR62mx

### Song ID

19

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 11549880

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
