### ISSUE TITLE
Add Idols (Piano Cover) by PokeyYapper1991

### ISSUE THREAD

**Issue by PokeyYapper1991** [FlafyDev/auto-nong-indexes#2483]
### Song Name

Idols (Piano Cover)

### Artist Name

PokeyYapper1991

### Source

Direct file download

### Youtube Link

Lr-eE4skqdA

### Direct File Link

https://api.songfilehub.com/song/66b2ade50675b3295f1abf34?download=true&name=1088817

### Song ID

1088817

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 48175126

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from
