### ISSUE TITLE
Add Krazyman50real's 8o Mashup

### ISSUE THREAD

**Issue by Hypervisor-Stealer** [FlafyDev/auto-nong-indexes#2493]
### Song Name

Eighto X Mario & Peach Have a Baby

### Artist Name

Krazyman50real

### Source

Direct file download

### Direct File Link

https://files.catbox.moe/votudg.MP3

### Song ID

624882

### Start Offset [ms]

0

### Extra

im sorry but it sounds good ok

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from
