### ISSUE TITLE
Add Shiawase VIP x E.T by Dion Timmer

### ISSUE THREAD

**Issue by Pikachu71462** [FlafyDev/auto-nong-indexes#2496]
### Song Name

Shiawase VIP x E.T

### Artist Name

Dion Timmer

### Source

Youtube

### Youtube Link

gn38IODa1_ewaE8g

### Song ID

1266014

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86407629

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
