### ISSUE TITLE
Add Fresh New Kicks by Dimitri K

### ISSUE THREAD

**Issue by matvey-byte46** [FlafyDev/auto-nong-indexes#2506]
### Song Name

Fresh New Kicks

### Artist Name

Dimitri K

### Source

Youtube

### Youtube Link

https://youtu.be/Z3Eq7uja8AQ?si=mDAeJiDtAGgUC-qD

### Song ID

621136

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108759077

**Comment by matvey-byte46** [comment]
accept

**Comment by matvey-byte46** [comment]
`open`

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Xenogenesis" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
