### ISSUE TITLE
The Lamp Is Low by Laurindo Almeida

### ISSUE THREAD

**Issue by vladushark** [FlafyDev/auto-nong-indexes#2507]
### Song Name

The Lamp Is Low

### Artist Name

Laurindo Almeida

### Source

Youtube

### Youtube Link

https://youtu.be/lkk6m14htzw?si=jVnT5fK5r3_ICJKl

### Song ID

1210043

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for song ":3"

**Comment by vladushark** [comment]
it is relevant

**Comment by SpuckwasserDE** [comment]
reject

popular songs (if used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
