### ISSUE TITLE
Add Shiawase VIP x Kanye and Katie Perry by Catarani

### ISSUE THREAD

**Issue by cataranii** [FlafyDev/auto-nong-indexes#2509]
### Song Name

Shiawase VIP x Kanye and Katie Perry

### Artist Name

Catarani

### Source

Youtube

### Youtube Link

LztTBMFSZJB505ZS

### Song ID

1266014

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86407629

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
