### ISSUE TITLE
Add youre cute by youre cute

### ISSUE THREAD

**Issue by Linhcute9022** [FlafyDev/auto-nong-indexes#2510]
### Song Name

youre cute

### Artist Name

youre cute

### Source

Youtube

### Youtube Link

K4xLi8IF1FM

### Direct File Link

https://m.youtube.com/watch?v=K4xLi8IF1FM&pp=ygUPa2F3YWlrdXRlIGdvbWVu

### Song ID

405060

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 87075478

**Comment by Linhcute9022** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

artist and song name must be descriptive
