### ISSUE TITLE
Add Cafune-tek it (sped up) by cafune

### ISSUE THREAD

**Issue by Milangd1711** [FlafyDev/auto-nong-indexes#2512]
### Song Name

Cafune-tek it (sped up)

### Artist Name

cafune

### Source

Youtube

### Youtube Link

1UQJqp2gVT3q7qvQ

### Song ID

100

### Start Offset [ms]

167

### Extra

Created from Auto Nong.
Created for level: 86871436

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
