### ISSUE TITLE
Add Free bird by Lynyrd Skynyrd

### ISSUE THREAD

**Issue by NightmareLeonGg** [FlafyDev/auto-nong-indexes#2513]
### Song Name

Free bird

### Artist Name

Lynyrd Skynyrd

### Source

Youtube

### Youtube Link

7otbYVU1J9rEd_Mi

### Song ID

85354

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 100523751

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
