### ISSUE TITLE
Add Nong Song: Europapa

### ISSUE THREAD

**Issue by bubzilla** [FlafyDev/auto-nong-indexes#2519]
### Song Name

Europapa

### Artist Name

Joost Klein

### Source

Youtube

### Youtube Link

https://youtu.be/gInOau6EFdI

### Song ID

1326193

### Start Offset [ms]

0

### Extra

nuh uh

**Comment by bubzilla** [comment]
Shikanoko Nokonoko Koshitantan

**Comment by SpuckwasserDE** [comment]
accept
