### ISSUE TITLE
Lost (XVA REMIX) x Pink Fluffy Unicorns

### ISSUE THREAD

**Issue by BUBBABUBZXVA** [FlafyDev/auto-nong-indexes#2536]
### Song Name

Lost (XVA REMIX) x Pink Fluffy Unicorns

### Artist Name

Krobin.Kerosine

### Source

Youtube

### Youtube Link

https://youtu.be/gJqb0zWJ2cY?feature=shared

### Song ID

945695

### Extra

Used in level slaughterhouse

**Comment by SpuckwasserDE** [comment]
reject

mashups/covers should have some popularity to show that people want it.
Note that you can still use the nong yourself, but it wont be public
