### ISSUE TITLE
Add ANGUISH, EXILED, elfevass - Gulyau

### ISSUE THREAD

**Issue by LevGasht** [FlafyDev/auto-nong-indexes#2537]
### Song Name

Gulyau

### Artist Name

ANGUISH, EXILED, elfevass

### Source

Youtube

### Youtube Link

https://youtube.com/watch?v=3PP1p7ex3Vc

### Song ID

475234

### Extra

I like this song :)

**Comment by LevGasht** [comment]
:(

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Run!" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
