### ISSUE TITLE
Add Nong Song: Epilogue x indxgo

### ISSUE THREAD

**Issue by Crooozy** [FlafyDev/auto-nong-indexes#2542]
### Song Name

Epilogue x Femboy Friday

### Artist Name

Creo

### Source

Direct file download

### Direct File Link

https://plwcse.top/f/711164345cf2fb9c6f4185d2b6c405ee

### Song ID

723714

### Extra

First mashup :) these lined up so ridiculously easily

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from
