### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by XPAPlTA** [FlafyDev/auto-nong-indexes#2543]
### Song Name

ta1lsd0ll

### Artist Name

 g2961

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=CljzyH_c3Uo&t=0s

### Direct File Link

https://www.kapwing.com/videos/66b42a8ad38f92fb9508c2a2

### Song ID

1326366

### Start Offset [ms]

0

**Comment by XPapita** [comment]
accept

**Comment by XPapita** [comment]
"accept"

**Comment by IMGer4** [comment]
accept
