### ISSUE TITLE
Tokyo

### ISSUE THREAD

**Issue by Danzeon** [FlafyDev/auto-nong-indexes#2545]
### Song Name

Tokyo Nya (Speed Up)

### Artist Name

Zendoy

### Source

Youtube

### Youtube Link

https://youtu.be/MbZnec2uH1o?si=qEDz_9GmYtT_r6wB

### Song ID

54535657

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 59223777

**Comment by SpuckwasserDE** [comment]
reject

song id doesnt exist
