### ISSUE TITLE
Add Privet by mzlff

### ISSUE THREAD

**Issue by LukSey4ka** [FlafyDev/auto-nong-indexes#2549]
### Song Name

Privet

### Artist Name

mzlff

### Source

Youtube

### Youtube Link

https://youtu.be/ZcSWyHxVlRQ?si=E_GKMpjoX_lgciU0

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108795037

**Comment by SpuckwasserDE** [comment]
reject

duplicate request, no worries, the song has been accepted
