### ISSUE TITLE
mzlff - privet by mazellovvv

### ISSUE THREAD

**Issue by LukSey4ka** [FlafyDev/auto-nong-indexes#2550]
### Song Name

mzlff - privet

### Artist Name

mazellovvv

### Source

Youtube

### Youtube Link

E_GKMpjoX_lgciU0

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108795037

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
