### ISSUE TITLE
Add mzlff - privet by mazellovvv

### ISSUE THREAD

**Issue by LukSey4ka** [FlafyDev/auto-nong-indexes#2551]
### Song Name

mzlff - privet

### Artist Name

mazellovvv

### Source

Youtube

### Youtube Link

https://youtu.be/ZcSWyHxVlRQ?si=E_GKMpjoX_lgciU0

### Direct File Link

https://drive.google.com/file/d/1CICyxIZFHGwU25XXdPAfQRzWQPjnyfmC/view?usp=drivesdk

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108795037

**Comment by SpuckwasserDE** [comment]
accept
