### ISSUE TITLE
Add Paqoe slh  by Yea

### ISSUE THREAD

**Issue by Blyxx2** [FlafyDev/auto-nong-indexes#2553]
### Song Name

Paqoe slh 

### Artist Name

Yea

### Source

Youtube

### Youtube Link

https://youtu.be/XSFkJpK-_nU?si=iUNUGmHtkwjfDKBx

### Song ID

945695

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 105575796

**Comment by SpuckwasserDE** [comment]
reject

that is not the artists name
