### ISSUE TITLE
Lost

### ISSUE THREAD

**Issue by Zerys44** [FlafyDev/auto-nong-indexes#2577]
### Song Name

Lost

### Artist Name

Zerys44

### Source

Youtube

### Youtube Link

https://youtube.com/@icedcave?si=me2UM2y7TwsrMg7T

### Direct File Link

https://youtube.com/@icedcave?si=me2UM2y7TwsrMg7T

### Song ID

937373

### Extra

83838383838892938

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
