### ISSUE TITLE
Lost

### ISSUE THREAD

**Issue by Zerys44** [FlafyDev/auto-nong-indexes#2578]
### Song Name

Lost

### Artist Name

Zerys44

### Source

Youtube

### Youtube Link

https://youtube.com/@icedcave?si=me2UM2y7TwsrMg7T

### Direct File Link

https://youtube.com/@icedcave?si=me2UM2y7TwsrMg7T

### Song ID

937373

### Start Offset [ms]

0

### Extra

3939939393939

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link (the mod needs the youtube id)
