### ISSUE TITLE
Add XO (but sung by a child) by Eden & Potatogame1

### ISSUE THREAD

**Issue by Fizzyhappiboi** [FlafyDev/auto-nong-indexes#2579]
### Song Name

XO (but sung by a child)

### Artist Name

Eden 

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=Vvcf1KiBzhc

### Song ID

766165

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108633743

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
