### ISSUE TITLE
Add XO (but sung by a child) 

### ISSUE THREAD

**Issue by Fizzyhappiboi** [FlafyDev/auto-nong-indexes#2580]
### Song Name

XO (but sung by a child)

### Artist Name

Eden 

### Source

Direct file download

### Youtube Link

erm no link

### Direct File Link

C:\Users\milan\Desktop\yt videos\0809(1)

### Song ID

766165

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108633743

**Comment by SpuckwasserDE** [comment]
reject

thats a folder location not a link
