### ISSUE TITLE
Add kuzureta by borame

### ISSUE THREAD

**Issue by Gangsug** [FlafyDev/auto-nong-indexes#2590]
### Song Name

kuzureta

### Artist Name

borame

### Source

Youtube

### Youtube Link

1qNnL6Gp4wkF0Hny

### Song ID

1024087

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 65692344

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
