### ISSUE TITLE
Add notion by The rare occations

### ISSUE THREAD

**Issue by HoliapGD** [FlafyDev/auto-nong-indexes#2593]
### Song Name

notion

### Artist Name

The rare occations

### Source

Youtube

### Youtube Link

erE9Nt_QcLNOEpT-

### Song ID

939780

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: Notion

**Comment by HoliapGD** [comment]
I'm tired of un-usealbe songs 😡

**Comment by HoliapGD** [comment]
Accept

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link

**Comment by SpuckwasserDE** [comment]
sorry about your concerns about unusable songs... Flafy is actively working on the mod and im sure he will be able to fix that issue one day as well
