### ISSUE TITLE
Add Take A Slice by Glass Animals

### ISSUE THREAD

**Issue by Muslim-cool** [FlafyDev/auto-nong-indexes#2595]
### Song Name

Take A Slice

### Artist Name

Glass Animals

### Source

Youtube

### Youtube Link

https://youtu.be/WS0ZqIWSy84?si=hanloxaaj-_YvFGi

### Song ID

48

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107553957 
Please add this song, i love it!

**Comment by SpuckwasserDE** [comment]
accept
