### ISSUE TITLE
Add Take A Slice by Glass Animals

### ISSUE THREAD

**Issue by Muslim-cool** [FlafyDev/auto-nong-indexes#2596]
### Song Name

Take A Slice

### Artist Name

Glass Animals

### Source

Youtube

### Youtube Link

https://youtu.be/KqwqyywjDH4?si=vHA2yqlomkRUTlId

### Song ID

48

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107553957

**Comment by SpuckwasserDE** [comment]
reject

duplicate request, no worries, the song has been accepted
