### ISSUE TITLE
Add 505 by Arctic Monkeys

### ISSUE THREAD

**Issue by Muslim-cool** [FlafyDev/auto-nong-indexes#2597]
### Song Name

505

### Artist Name

Arctic Monkeys

### Source

Youtube

### Youtube Link

https://youtu.be/1Jd2DysfCW8?si=p7XSWwiiFQNTmvEr

### Song ID

48

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107553957
plz

**Comment by SpuckwasserDE** [comment]
accept
