### ISSUE TITLE
Add Say it ain't so by weezer

### ISSUE THREAD

**Issue by SargeDargeq11** [FlafyDev/auto-nong-indexes#2599]
### Song Name

Say it ain't so

### Artist Name

weezer

### Source

Youtube

### Youtube Link

hi5Z_omLSiku604P

### Song ID

244771

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 88946494

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
