### ISSUE TITLE
Add lay your all love on me by abba

### ISSUE THREAD

**Issue by konsta-rally** [FlafyDev/auto-nong-indexes#2603]
### Song Name

lay your all love on me

### Artist Name

abba

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=5mHzaIehRTE

### Song ID

677785

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 18834999

**Comment by SpuckwasserDE** [comment]
reject

popular songs like songs by thefatrat are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
