### ISSUE TITLE
Add lay your all love on me by abba

### ISSUE THREAD

**Issue by konsta-rally** [FlafyDev/auto-nong-indexes#2604]
### Song Name

lay your all love on me

### Artist Name

abba

### Source

Youtube

### Youtube Link

5mHzalehRTE

### Song ID

677785

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 18834999

**Comment by konsta-rally** [comment]
accept

pe 9. elok. 2024 klo 21.38 auto-nong[bot] ***@***.***>
kirjoitti:

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
