### ISSUE TITLE
add KOCMOC [korathink remix]

### ISSUE THREAD

**Issue by MooD-UnDone** [FlafyDev/auto-nong-indexes#2605]
### Song Name

KOCMOC (korathink remix)

### Artist Name

Korathink

### Source

Direct file download

### Direct File Link

https://drive.google.com/file/d/1dt4Ccamv87_glWvBjkma_jSG5jA2wpFU/view?usp=sharing

### Song ID

1348719

### Start Offset [ms]

0

### Extra

to be used in KOCMOC remake made by mood

**Comment by korathink** [comment]
accept

**Comment by MooD-UnDone** [comment]
> Thanks for contributing! Someone will soon review your request.
> 
> Here is the JSON result for the reviewer:
> 
> ```json
> {
>   "name": "KOCMOC (korathink remix)",
>   "artist": "Korathink",
>   "source": "host",
>   "startOffset": 0,
>   "url": "https://drive.google.com/file/d/1dt4Ccamv87_glWvBjkma_jSG5jA2wpFU/view?usp=sharing",
>   "songs": [
>     1348719
>   ]
> }
> ```
> 
> To accept the request, a reviewer needs to write "accept".

accept

**Comment by korathink** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported, unless it is a permanent direct download link from a CDN that has given permission for Auto Nong to download from
