### ISSUE TITLE
Add Nevada by Vicetone

### ISSUE THREAD

**Issue by CoolerdudeYT** [FlafyDev/auto-nong-indexes#2606]
### Song Name

Nevada

### Artist Name

Vicetone

### Source

Youtube

### Youtube Link

L1lOfaeOfhzUsc22

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 89115769

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
