### ISSUE TITLE
Add Smile Hall by agent26105

### ISSUE THREAD

**Issue by agent26105** [FlafyDev/auto-nong-indexes#2607]
### Song Name

Smile Hall

### Artist Name

agent26105

### Source

Youtube

### Youtube Link

aGTxyxnUeSJytXBb

### Song ID

1266014

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108780575

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
