### ISSUE TITLE
Add why'd you only call me when you're high by Arctic Monkeys

### ISSUE THREAD

**Issue by NexukBlade** [FlafyDev/auto-nong-indexes#2622]
### Song Name

why'd you only call me when you're high

### Artist Name

Arctic Monkeys

### Source

Youtube

### Youtube Link

XUQuNxMFr_5eWUZ6

### Song ID

709578

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108623520

**Comment by NexukBlade** [comment]
Good

**Comment by NexukBlade** [comment]
> ¡Gracias por tu colaboración! Pronto alguien revisará tu solicitud.
> 
> Aquí está el resultado JSON para el revisor:
> 
> ```json
> {
>   "name": "why'd you only call me when you're high",
>   "artist": "Arctic Monkeys",
>   "source": "youtube",
>   "startOffset": 0,
>   "yt-id": "XUQuNxMFr_5eWUZ6",
>   "songs": [
>     709578
>   ]
> }
> ```
> 
> Para aceptar la solicitud, un revisor debe escribir "aceptar".

accept

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
