### ISSUE TITLE
Niwa

### ISSUE THREAD

**Issue by Kyuosy** [FlafyDev/auto-nong-indexes#2626]
### Song Name

monster

### Artist Name

yoasabi

### Source

Youtube

### Youtube Link

FBm8mZIfkVdqTD71

### Direct File Link

https://youtu.be/WmFMEQcgbiE?si=omGEgGYwijiXmwc5

### Song ID

233860

### Start Offset [ms]

10

### Extra

Created from Auto Nong.
Created for level: 88863390

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
