### ISSUE TITLE
Add Shiawase (vip) by Dion Timmer

### ISSUE THREAD

**Issue by JarieParie** [FlafyDev/auto-nong-indexes#2633]
### Song Name

Shiawase (vip)

### Artist Name

Dion Timmer

### Source

Youtube

### Youtube Link

sfh-rooot.json.gz

### Song ID

1255249

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 99564598

**Comment by SpuckwasserDE** [comment]
reject

thats not a youtube link
