### ISSUE TITLE
Add August by Intilligency

### ISSUE THREAD

**Issue by Muslim-cool** [FlafyDev/auto-nong-indexes#2636]
### Song Name

August

### Artist Name

Intilligency

### Source

Youtube

### Youtube Link

https://youtu.be/ZPeJyu6n9iU?si=N6HrjG4MDdpPfsXt

### Song ID

48

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107553957

**Comment by AlwaysJolly** [comment]
The artist name is wrong.

**Comment by SpuckwasserDE** [comment]
accept
