### ISSUE TITLE
Add Heavenly wings by TEENWXVE, 2nigxt

### ISSUE THREAD

**Issue by DolorosEyes** [FlafyDev/auto-nong-indexes#2637]
### Song Name

Heavenly wings

### Artist Name

TEENWXVE, 2nigxt

### Source

Youtube

### Youtube Link

3zqBOxSDj0071ZRP

### Song ID

701013

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 44062068

**Comment by DolorosEyes** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
