### ISSUE TITLE
Add Heavenly wings by TEENWXVE, 2nigxt

### ISSUE THREAD

**Issue by DolorosEyes** [FlafyDev/auto-nong-indexes#2638]
### Song Name

Heavenly wings

### Artist Name

TEENWXVE, 2nigxt

### Source

Youtube

### Youtube Link

https://youtu.be/PfTmAAhvC3Y?si=mmNL2fTe1gCnhxi_

### Song ID

701013

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 44062068

**Comment by DolorosEyes** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "whats a future funk" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
