### ISSUE TITLE
Add Nong Song: Stickerbrush Symphony by David Wise

### ISSUE THREAD

**Issue by AlanoDV** [FlafyDev/auto-nong-indexes#2641]
### Song Name

Stickerbrush Symphony

### Artist Name

David Wise

### Source

Youtube

### Youtube Link

https://youtu.be/lndBgOrTWxo?si=WTHuO87vWAMJVjsl

### Song ID

452513

**Comment by AlanoDV** [comment]
Thank you!

Op za 10 aug 2024 15:31 schreef auto-nong[bot] ***@***.***>:

**Comment by SpuckwasserDE** [comment]
accept

**Comment by AlanoDV** [comment]
LETS GOOOO

Op di 27 aug 2024 21:21 schreef auto-nong[bot] ***@***.***>:
