### ISSUE TITLE
Add Kyouki x Metamorphosis 3 by Arshadow

### ISSUE THREAD

**Issue by raidexgmd** [FlafyDev/auto-nong-indexes#2649]
### Song Name

Kyouki x Metamorphosis 3

### Artist Name

Arshadow

### Source

Youtube

### Youtube Link

KWkEIIGYYHaC4BAW

### Song ID

905108

### Start Offset [ms]

119

### Extra

Created from Auto Nong.
Created for level: 87901006

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
