### ISSUE TITLE
Add happyland by happiness1

### ISSUE THREAD

**Issue by Happiness100** [FlafyDev/auto-nong-indexes#2651]
### Song Name

happyland

### Artist Name

happiness1

### Source

Youtube

### Youtube Link

nOeVNsHeidOp0rcO

### Song ID

4235

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107173199

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
