### ISSUE TITLE
Add jump in the caac edit by epochgd 

### ISSUE THREAD

**Issue by KillerMeganet** [FlafyDev/auto-nong-indexes#2652]
### Song Name

jump in the caac edit

### Artist Name

epochgd 

### Source

Youtube

### Youtube Link

wLQR3qkvk8cQsKkG

### Song ID

1001

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 103460234

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
