### ISSUE TITLE
Add Guns and ships by Hamilton

### ISSUE THREAD

**Issue by Foxiseminger** [FlafyDev/auto-nong-indexes#2653]
### Song Name

Guns and ships

### Artist Name

Hamilton

### Source

Youtube

### Youtube Link

0D3zz6byFT4

### Song ID

944913

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108331825

**Comment by Foxiseminger** [comment]
accept

**Comment by FoxyWorld1** [comment]
ah man 😭😭

**Comment by Foxiseminger** [comment]
why 😭😭😭

**Comment by SpuckwasserDE** [comment]
reject

popular songs (if used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public

**Comment by FoxyWorld1** [comment]
what about instrumental ver? (No lyrics)

**Comment by SpuckwasserDE** [comment]
general rule of thumb is that if a song that is used in rated levels is going to be replaced, it should be some form of remix or mashup of the song, since unrelated songs would flood the mod
