### ISSUE TITLE
Add Rose At Nightfall High Pitch by NemesisTheory

### ISSUE THREAD

**Issue by GYTOGD** [FlafyDev/auto-nong-indexes#2655]
### Song Name

Rose At Nightfall High Pitch

### Artist Name

NemesisTheory

### Source

Youtube

### Youtube Link

Im2LMh2hDeOuP8ZY

### Direct File Link

https://www.mediafire.com/file/0h27bki2c04j91o/193466_Rose_At_Twilight.mp3/file

### Song ID

153668

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 69119062

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
