### ISSUE TITLE
Add jealous by eyedress

### ISSUE THREAD

**Issue by Iontey** [FlafyDev/auto-nong-indexes#2658]
### Song Name

jealous

### Artist Name

eyedress

### Source

Youtube

### Youtube Link

Y_WqmAmT1rpCnOGp

### Song ID

1818291

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 91948655

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
