### ISSUE TITLE
Add Hydra - F-777 (HJfod Remix) by F-777

### ISSUE THREAD

**Issue by rehehehehee** [FlafyDev/auto-nong-indexes#267]
### Song Name

Hydra - F-777 (HJfod Remix)

### Artist Name

F-777

### Source

Youtube

### Youtube Link

MfC1vNErRXo

### Direct File Link

https://api.songfilehub.com/song/65ffe89105ef6c2254f092a2?download=true&name=724517

### Song ID

725417

### Extra

Created from Auto Nong.
Created for level: 39832512

**Comment by FlafyDev** [comment]
reject

don't use sfh's cdn

**Comment by SpuckwasserDE** [comment]
reject

already in the mod ("Hydra x HJFod Remix")
