### ISSUE TITLE
 Acheron x Showdown

### ISSUE THREAD

**Issue by savylui** [FlafyDev/auto-nong-indexes#2670]
### Song Name

Acheron x Showdown

### Artist Name

savylui

### Source

Youtube

### Youtube Link

fcae91CaPe7zF4Jq

### Song ID

770520

### Start Offset [ms]

10000

### Extra

Created from Auto Nong.
Created for level: 73667628

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
