### ISSUE TITLE
Add Moonlight Sonata 3rd Movement by Beethoven

### ISSUE THREAD

**Issue by gold198** [FlafyDev/auto-nong-indexes#268]
### Song Name

Moonlight Sonata 3rd Movement

### Artist Name

Beethoven

### Source

Youtube

### Youtube Link

6unwFFeNTjQ

### Direct File Link

https://www.youtube.com/watch?v=6unwFFeNTjQ

### Song ID

1167964

### Extra

Created from Auto Nong.
Created for level: 90475473

**Comment by FlafyDev** [comment]
doesn't sync
