### ISSUE TITLE
Add Nong Song: linenine

### ISSUE THREAD

**Issue by Iinenine** [FlafyDev/auto-nong-indexes#2680]
### Song Name

Cannibal

### Artist Name

Tally Hall

### Source

Direct file download

### Direct File Link

https://drive.google.com/file/d/17fH2rwnTF4QgY8t3F1d5uEaCrviEYW9L/view?usp=sharing

### Song ID

66901

### Extra

Used in my level under the same name. ID: 108902530

**Comment by SpuckwasserDE** [comment]
reject

already in the mod
