### ISSUE TITLE
Add Nong Song: linenine (resubmit)

### ISSUE THREAD

**Issue by Iinenine** [FlafyDev/auto-nong-indexes#2681]
### Song Name

Cannibal

### Artist Name

Tally Hall

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=SRyoPJeOuR4

### Song ID

66901

### Extra

Used in my level under the same name. ID: 108902530

**Comment by SpuckwasserDE** [comment]
reject

already in the mod
