### ISSUE TITLE
Add Nong Song: linenine (resubmit 2, sorry to do it so many times, ive just been told i did it wrong)

### ISSUE THREAD

**Issue by Iinenine** [FlafyDev/auto-nong-indexes#2682]
### Song Name

Cannibal

### Artist Name

Tally Hall

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=5_QwMRE-BKc

### Song ID

66901

### Extra

Used in my level under the same name. ID: 108902530

**Comment by AlwaysJolly** [comment]
accept
