### ISSUE TITLE
Very cool uwu sigma

### ISSUE THREAD

**Issue by IPummmpXD** [FlafyDev/auto-nong-indexes#27]
### Song Name

Rip and Tear

### Artist Name

Mick Gordon

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=5Nz3HXwEG4M&t=0s

### Direct File Link

https://www.mediafire.com/file/dq4ribzcq4bory0/1253069.mp3/file

### Song ID

1253069

### Extra

Used in level Aeternus by Riot and more

**Comment by IPummmpXD** [comment]
Accept

**Comment by FlafyDev** [comment]
it's by Mick Gordon. edited

**Comment by FlafyDev** [comment]
accept
