### ISSUE TITLE
Doradura by Dora

### ISSUE THREAD

**Issue by savylui** [FlafyDev/auto-nong-indexes#2700]
### Song Name

Doradura

### Artist Name

Dora

### Source

Youtube

### Youtube Link

jxvZgJp0HsIfg6Jd

### Direct File Link

https://youtu.be/GE0y_Yv-fTU?si=jxvZgJp0HsIfg6Jd

### Song ID

905921

### Start Offset [ms]

10000

### Extra

Created from Auto Nong.
Created for level: 77258026

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
