### ISSUE TITLE
Add geometrical dominator piano cover by lsksgd

### ISSUE THREAD

**Issue by Lsksgd** [FlafyDev/auto-nong-indexes#2710]
### Song Name

geometrical dominator piano cover

### Artist Name

lsksgd

### Source

Youtube

### Youtube Link

aeir143bUqGTJRju

### Direct File Link

Https//www.aeir143bUqGTJRju.com/gdpianocover.mp3

### Song ID

18

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 13166058

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
