### ISSUE TITLE
Add Namae No Nai Kaibutsu by EGOIST

### ISSUE THREAD

**Issue by Shuiniem** [FlafyDev/auto-nong-indexes#2719]
### Song Name

Namae No Nai Kaibutsu

### Artist Name

EGOIST

### Source

Youtube

### Youtube Link

https://youtu.be/pS_OEmjIRxo?si=4p9YZZcLEYaLOCqD

### Song ID

2

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Polargeist" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
