### ISSUE TITLE
Add crim3S lost by crim3S

### ISSUE THREAD

**Issue by Qwsdi** [FlafyDev/auto-nong-indexes#2730]
### Song Name

crim3S lost

### Artist Name

crim3S

### Source

Youtube

### Youtube Link

Y7p9wClWy-6f1SzJ

### Song ID

945695

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 27690100

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
