### ISSUE TITLE
Add Jschlatt Aria Math by Levi Rochell or kaylistired

### ISSUE THREAD

**Issue by velocityrifat** [FlafyDev/auto-nong-indexes#2735]
### Song Name

Jschlatt Aria Math

### Artist Name

Levi Rochell or kaylistired

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=HXSLtSQTVTM

### Song ID

889642

### Start Offset [ms]

0

### Extra

Created from Auto Nong.

**Comment by SpuckwasserDE** [comment]
accept
