### ISSUE TITLE
Big Dawgs (Big Stepper)

### ISSUE THREAD

**Issue by M4deFromScr4tch** [FlafyDev/auto-nong-indexes#2739]
### Song Name

Big Dawgs

### Artist Name

Hanumankind, Kalmi

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=hOHKltAiKXQ

### Song ID

14

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "electrodynamix" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
