### ISSUE TITLE
Zodiac (Cursed Pitch) by Creo

### ISSUE THREAD

**Issue by ItzHudson** [FlafyDev/auto-nong-indexes#2745]
### Song Name

Zodiac (Cursed Pitch)

### Artist Name

Creo

### Source

Youtube

### Youtube Link

uD3nIUwFkuo

### Song ID

739991

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 52374843

**Comment by Tv-Github1** [comment]
I think it will be accepted

**Comment by SpuckwasserDE** [comment]
accept
