### ISSUE TITLE
Add KOCMOC [korathink remix]

### ISSUE THREAD

**Issue by MooD-UnDone** [FlafyDev/auto-nong-indexes#2747]
### Song Name

KOCMOC (korathink remix)

### Artist Name

Korathink

### Source

Youtube

### Youtube Link

https://youtu.be/Yy9AEsP2PXo

### Song ID

1348719

### Start Offset [ms]

0

### Extra

To be used in a kocmoc remake called "KOCMOC undone" made by mood.

**Comment by MooD-UnDone** [comment]
is this good now?

**Comment by korathink** [comment]
accept

**Comment by SpuckwasserDE** [comment]
I assume this is the right song id and you dont want to use the kocmoc song id? then yes, everything is good now

**Comment by SpuckwasserDE** [comment]
accept
