### ISSUE TITLE
Lost-crim3s

### ISSUE THREAD

**Issue by Cryogenic-chamber** [FlafyDev/auto-nong-indexes#275]
### Song Name

Lost

### Artist Name

CRIM3S

### Source

Youtube

### Youtube Link

https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.youtube.com/watch%3Fv%3DoBsp2WjRQfk&ved=2ahUKEwijvcvwg-SGAxUqzjgGHd9eDREQypYNegQIHRAB&usg=AOvVaw3VLRiWbCOn4kOSS_Hvg09V

### Song ID

945695

### Extra

Used in the level Slaughterhouse

**Comment by Cryogenic-chamber** [comment]
Accept

**Comment by IMGer4** [comment]
reject
