### ISSUE TITLE
Add i wanna be here by Deathbrain

### ISSUE THREAD

**Issue by zspringkyl-b4** [FlafyDev/auto-nong-indexes#2768]
### Song Name

i wanna be here

### Artist Name

Deathbrain

### Source

Youtube

### Youtube Link

sqKmB684jTU

### Song ID

827

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 97428235
i realized i put the link wrong so i fixed it

**Comment by zspringkyl-b4** [comment]
a

**Comment by SpuckwasserDE** [comment]
accept
