### ISSUE TITLE
Add Citrus Rap by AeAone

### ISSUE THREAD

**Issue by ElFrozt** [FlafyDev/auto-nong-indexes#2776]
### Song Name

Citrus Rap

### Artist Name

AeAone

### Source

Youtube

### Youtube Link

f-pzlCsyEyc

### Song ID

8

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: Level in creation

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "cycles" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
