### ISSUE TITLE
Add Poslednee Leto by POSLEDEELETOGD

### ISSUE THREAD

**Issue by PR024344W** [FlafyDev/auto-nong-indexes#2777]
### Song Name

Poslednee Leto

### Artist Name

Oose

### Source

Youtube

### Youtube Link

NhWaOpRV0RcAtIix

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108176162

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
