### ISSUE TITLE
Add At the speed of light (electroman adventures remix) by Josradu

### ISSUE THREAD

**Issue by Dream2407** [FlafyDev/auto-nong-indexes#2778]
### Song Name

At the speed of light (electroman adventures remix)

### Artist Name

Josradu

### Source

Youtube

### Youtube Link

RUSQIWN-HQ8

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108976361

**Comment by Dream2407** [comment]
accept

**Comment by Avokerhesoki** [comment]
Accept
