### ISSUE TITLE
Add Nong Song: KLYDIX - Night Flight

### ISSUE THREAD

**Issue by Spyritzzz** [FlafyDev/auto-nong-indexes#2779]
### Song Name

Night Flight

### Artist Name

KLYDIX

### Source

Youtube

### Youtube Link

https://youtube.com/watch?v=ddszgJcQvIU&si=5_CvNgDnEvTN7hKP

### Song ID

1000

### Start Offset [ms]

0

### Extra

Used in my own level "Night Flight" -108598295

**Comment by SpuckwasserDE** [comment]
accept
