### ISSUE TITLE
Add jump in the caac edit by epochgd 

### ISSUE THREAD

**Issue by KillerMeganet** [FlafyDev/auto-nong-indexes#2781]
### Song Name

jump in the caac edit

### Artist Name

epochgd 

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=lVOrE3OsFSo

### Song ID

1001

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 103460234

**Comment by SpuckwasserDE** [comment]
accept
