### ISSUE TITLE
Add Jschlatt Aria Math by Levi Rochell

### ISSUE THREAD

**Issue by velocityrifat** [FlafyDev/auto-nong-indexes#2785]
### Song Name

Jschlatt Aria Math

### Artist Name

Levi Rochell

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=ozOjWSe0kaA&t=0s

### Song ID

889642

### Start Offset [ms]

0

### Extra

Created from Auto Nong.

**Comment by SpuckwasserDE** [comment]
accept
