### ISSUE TITLE
lost by crim3s

### ISSUE THREAD

**Issue by Avokerhesoki** [FlafyDev/auto-nong-indexes#2786]
### Song Name

Lost

### Artist Name

Crim3s

### Source

Youtube

### Youtube Link

https://youtu.be/7W5bZJY2IPI?si=K5fVy7XDEPKbwMak

### Song ID

945695

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 27690100

**Comment by SpuckwasserDE** [comment]
reject

same here, already in the mod
