### ISSUE TITLE
Add KOCMOC [korathink remix(kocmoc replacement)]

### ISSUE THREAD

**Issue by MooD-UnDone** [FlafyDev/auto-nong-indexes#2787]
### Song Name

KOCMOC (korathink remix)

### Artist Name

Korathink

### Source

Youtube

### Youtube Link

https://youtu.be/Yy9AEsP2PXo

### Song ID

1163222

### Start Offset [ms]

80800

### Extra

This time the remix is used to replace the kocmoc song for whoever prefers this remix :).

**Comment by MooD-UnDone** [comment]
i know i asked many times but my friends wanna replace the song so thank you all for helping me out :).

**Comment by SpuckwasserDE** [comment]
accept
