### ISSUE TITLE
Add lost by crim3s

### ISSUE THREAD

**Issue by Avokerhesoki** [FlafyDev/auto-nong-indexes#2788]
### Song Name

lost

### Artist Name

crim3s

### Source

Youtube

### Youtube Link

https://youtu.be/7W5bZJY2IPI?si=K5fVy7XDEPKbwMak

### Direct File Link

https://www.mediafire.com/Lost.mp3

### Song ID

945695

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 27690100

**Comment by SpuckwasserDE** [comment]
reject

same here, already in the mod
