### ISSUE TITLE
Add lost by crim3s

### ISSUE THREAD

**Issue by Avokerhesoki** [FlafyDev/auto-nong-indexes#2789]
### Song Name

Lost

### Artist Name

Crim3s

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch/7W5bZJY2IPI?si=K5fVy7XDEPKbwMak

### Song ID

945695

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 27690100

**Comment by Avokerhesoki** [comment]
Best

**Comment by Avokerhesoki** [comment]
Accept

**Comment by SpuckwasserDE** [comment]
reject

already in the mod (both the original and the remix have been added already)
