### ISSUE TITLE
Euphoria

### ISSUE THREAD

**Issue by MrEpokCoderIdk** [FlafyDev/auto-nong-indexes#2797]
### Song Name

Euphoria

### Artist Name

Kendrick Lamar

### Source

Youtube

### Youtube Link

=NPqDIwWMtxg

### Song ID

810618

**Comment by MrEpokCoderIdk** [comment]
I'm practicing a level called "Euphoria" and since it uses a Creo song I thought it'll be funny to include Euphoria by K.Dot. Also I'm not sure if this is copyrighted or not

**Comment by SpuckwasserDE** [comment]
reject

copyright doesnt matter, but the link is wrong, the problem is probably the = sign
