### ISSUE TITLE
Add Seirogan 2000 by Taiko web

### ISSUE THREAD

**Issue by Careamel** [FlafyDev/auto-nong-indexes#2798]
### Song Name

Seirogan 2000

### Artist Name

Taiko web

### Source

Youtube

### Youtube Link

i5ZG-MRCE0WLi6aq

### Song ID

573278

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 20635816
Funny minus world "sequel"

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
