### ISSUE TITLE
Add time machine x burger by face

### ISSUE THREAD

**Issue by barabudai1** [FlafyDev/auto-nong-indexes#2799]
### Song Name

time machine x burger

### Artist Name

face

### Source

Youtube

### Youtube Link

WbVMFdCSqOZTXIgc

### Song ID

Time Machine

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 72744364

**Comment by SpuckwasserDE** [comment]
reject

song id has to be a number
