### ISSUE TITLE
Add The Beginning by Modestep

### ISSUE THREAD

**Issue by Cyannohex** [FlafyDev/auto-nong-indexes#2801]
### Song Name

The Beginning

### Artist Name

Modestep

### Source

Youtube

### Youtube Link

I-fr9z8PrFo

### Song ID

781102

### Start Offset [ms]

0

**Comment by Cyannohex** [comment]
Accept

**Comment by SpuckwasserDE** [comment]
reject

popular songs (if used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
