### ISSUE TITLE
Add Beamer Boy by Lil Peep

### ISSUE THREAD

**Issue by ace693** [FlafyDev/auto-nong-indexes#2811]
### Song Name

Beamer Boy

### Artist Name

Lil Peep

### Source

Youtube

### Youtube Link

youtube.com/watch?v=fePnUenEZPk

### Song ID

502268

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 109016323

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "NK - Classical VIP" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
