### ISSUE TITLE
Add Apocalyse 1992 by Goldhammer

### ISSUE THREAD

**Issue by DangerX99** [FlafyDev/auto-nong-indexes#2820]
### Song Name

Apocalyse 1992

### Artist Name

Goldhammer

### Source

Youtube

### Youtube Link

https://m.youtube.com/watch?v=rGu710WkVqQ

### Song ID

727020

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107018100

**Comment by SpuckwasserDE** [comment]
reject

popular songs (if used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
