### ISSUE TITLE
Add LOST [Sidewalks and Skeletons REMIX] by CRIM3S

### ISSUE THREAD

**Issue by Vechea** [FlafyDev/auto-nong-indexes#2822]
### Song Name

LOST [Sidewalks and Skeletons REMIX]

### Artist Name

CRIM3S

### Source

Youtube

### Youtube Link

EpoF_AOPaW

### Song ID

666666

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 74851324

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
