### ISSUE TITLE
Add Crunched Up by HammSlamm

### ISSUE THREAD

**Issue by Alexc42305** [FlafyDev/auto-nong-indexes#2823]
### Song Name

Crunched Up

### Artist Name

HammSlamm

### Source

Youtube

### Youtube Link

UXZFpNgWu8U

### Song ID

1126904

### Start Offset [ms]

750

### Extra

Created from Auto Nong.
Created for level: 80223427

**Comment by SpuckwasserDE** [comment]
accept
