### ISSUE TITLE
Add Spooky Scary Skeleton rmx by The Living Tombstones

### ISSUE THREAD

**Issue by Usermanndamlie** [FlafyDev/auto-nong-indexes#2824]
### Song Name

Spooky Scary Skeleton rmx

### Artist Name

The Living Tombstones

### Source

Youtube

### Youtube Link

q6-ZGAGcJrk

### Song ID

589755

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 103564242

**Comment by SpuckwasserDE** [comment]
accept
