### ISSUE TITLE
Add Dream On by Pegboard Nerds 

### ISSUE THREAD

**Issue by Deitz578** [FlafyDev/auto-nong-indexes#2831]
### Song Name

Dream On

### Artist Name

Pegboard Nerds 

### Source

Youtube

### Youtube Link

pMx36VC8R-Q

### Song ID

10006751

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 109017533

**Comment by SpuckwasserDE** [comment]
accept
