### ISSUE TITLE
Add Fratricide by Ivycomb Music

### ISSUE THREAD

**Issue by Deitz578** [FlafyDev/auto-nong-indexes#2832]
### Song Name

Fratricide

### Artist Name

Ivycomb Music

### Source

Youtube

### Youtube Link

Tu0ZSTkF6qA

### Song ID

639410

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 109017541

**Comment by SpuckwasserDE** [comment]
reject

popular songs (used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
