### ISSUE TITLE
My ordinary life

### ISSUE THREAD

**Issue by Aaronbhernandez** [FlafyDev/auto-nong-indexes#2851]
### Song Name

My ordinary life

### Artist Name

The living tombstone

### Source

Youtube

### Youtube Link

https://youtu.be/9Zj0JOHJR-s?si=lzT3nABtQuoZrF8p

### Song ID

Nong

### Start Offset [ms]

14

### Extra

Todos los que lleven de nombre my ordinary life

**Comment by SpuckwasserDE** [comment]
reject

song id cant contain text
