### ISSUE TITLE
Add Duchess of the Zoo (still jumper) by Krayon Koz

### ISSUE THREAD

**Issue by Leatsyke** [FlafyDev/auto-nong-indexes#2854]
### Song Name

Duchess of the Zoo (still jumper)

### Artist Name

Krayon Koz

### Source

Youtube

### Youtube Link

gU4DIN-NrOWL8P92

### Song ID

6

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
As the name suggests, jumper is literally the beat koz uses with no changes or remixes

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
