### ISSUE TITLE
Add the world revolving by toby fox

### ISSUE THREAD

**Issue by TGP9063** [FlafyDev/auto-nong-indexes#2875]
### Song Name

the world revolving

### Artist Name

toby fox

### Source

Youtube

### Youtube Link

8gkTtNefxws

### Song ID

623104

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 7599504

**Comment by SpuckwasserDE** [comment]
reject

popular songs (if used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
