### ISSUE TITLE
centipede

### ISSUE THREAD

**Issue by nugget2937232** [FlafyDev/auto-nong-indexes#29]
### Song Name

Centipede

### Artist Name

Knife Party

### Source

Direct file download

### Direct File Link

https://cdn.discordapp.com/attachments/1150072034630574090/1246138687893274784/599637.mp3?ex=665b4c97&is=6659fb17&hm=28273475848820e36e9086767afafbc01d35f1294020749011a3e7f29f2fa2c0&

### Song ID

599637

### Extra

Centipede

**Comment by SpuckwasserDE** [comment]
reject

non-YouTube sources are not supported
