### ISSUE TITLE
Add Nong Song: 7 Skies H3

### ISSUE THREAD

**Issue by Omicron23real** [FlafyDev/auto-nong-indexes#2919]
### Song Name

7 Skies H3

### Artist Name

The Flaming Lips

### Source

Direct file download

### Direct File Link

https://sylvia-storm.filemail.com/d/itxzaonowavzwwy

### Song ID

724831

### Start Offset [ms]

0

**Comment by Omicron23real** [comment]
I'll have to find a new link, no longer relevant sorry

**Comment by SpuckwasserDE** [comment]
reject

@Omicron23real if you make a new issue, send me the link via discord, my usernam is spuckwasser.de
I will immediatly look at the new one, so that you dont have to wait again
