### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by Marcotrix** [FlafyDev/auto-nong-indexes#2928]
### Song Name

Space Abyss (Lunar & Solar Mashup)

### Artist Name

Originally Lchavasse, but the mashup is by HyperRemix

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=WjAWl5wQGLo

### Song ID

737166

### Extra

Originally used in master duel, need it on solar abyss to sync on mobile or other places where NONGs are not avaliable

**Comment by SpuckwasserDE** [comment]
accept
