### ISSUE TITLE
Add Nong Song: Proud Heroes A

### ISSUE THREAD

**Issue by Indo00** [FlafyDev/auto-nong-indexes#2942]
### Song Name

Proud Heroes

### Artist Name

Citokid

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=UPvMYXrp6Gc

### Song ID

631299

### Start Offset [ms]

0

**Comment by Indo00** [comment]
I will like it to be re-opened

**Comment by SpuckwasserDE** [comment]
accept

**Comment by SpuckwasserDE** [comment]
accept
