### ISSUE TITLE
Add Such a Whore (Stellular Remix) by JVLA

### ISSUE THREAD

**Issue by Craanky** [FlafyDev/auto-nong-indexes#2946]
### Song Name

Such a Whore (Stellular Remix)

### Artist Name

JVLA

### Source

Youtube

### Youtube Link

8fFOtGETlrU

### Song ID

969494

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 99317345
Downloaded: Yes

**Comment by Craanky** [comment]
ok

**Comment by SpuckwasserDE** [comment]
accept
