### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by MonkeYT2332** [FlafyDev/auto-nong-indexes#2948]
### Song Name

Creo Sphere X Dont Threaten Me With A Good Time

### Artist Name

Creo x P!ATD

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=9eqJ4hsLBnA

### Song ID

739991

### Start Offset [ms]

0

**Comment by Cosmo304** [comment]
accept
