### ISSUE TITLE
Add Can You Feel My Heart - Remix (Gigachad) by G6400

### ISSUE THREAD

**Issue by AskMarti** [FlafyDev/auto-nong-indexes#2949]
### Song Name

Can You Feel My Heart - Remix (Gigachad)

### Artist Name

G6400

### Source

Youtube

### Youtube Link

m81NQ8tFR7s

### Song ID

1110953

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 84282539
Downloaded: Yes

**Comment by AskMarti** [comment]
A

**Comment by SpuckwasserDE** [comment]
accept
