### ISSUE TITLE
Add Yomi yori Kikoyu, Koukoku No Hi To Honoo No Syoujo. (Orchestral Ver.) by Imperial Circus Dead Decadence

### ISSUE THREAD

**Issue by V4-Vashek** [FlafyDev/auto-nong-indexes#2952]
### Song Name

Yomi yori Kikoyu, Koukoku No Hi To Honoo No Syoujo. (Orchestral Ver.)

### Artist Name

Imperial Circus Dead Decadence

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=4x3QyjCnHLc

### Song ID

847746

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 49907278

**Comment by bBr3ad** [comment]
accept
