### ISSUE TITLE
Add Nong Song: DNA. X Classic Pursuit (OlivRulz Remix)

### ISSUE THREAD

**Issue by OlivRulzGD** [FlafyDev/auto-nong-indexes#2954]
### Song Name

DNA. X Classic Pursuit

### Artist Name

Kendrick Lamar x cYsmix

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=PN3f9lYAWxM

### Song ID

718171

### Extra

Can be used in all levels w song

**Comment by Daepicgdplayer** [comment]
accept

**Comment by Daepicgdplayer** [comment]
accept

**Comment by Daepicgdplayer** [comment]
Accept

**Comment by SpuckwasserDE** [comment]
accept
