### ISSUE TITLE
Add Nong Song: Zodiac X J. Cole

### ISSUE THREAD

**Issue by OlivRulzGD** [FlafyDev/auto-nong-indexes#2956]
### Song Name

Zodiac X J. Cole

### Artist Name

J. Cole

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=Lt8X_8W_AIw

### Song ID

739991

**Comment by Daepicgdplayer** [comment]
Accept

**Comment by SpuckwasserDE** [comment]
reject

mashups/covers should have some popularity to show that people want it (especially if the song doesnt sound great).
Note that you can still use the nong yourself, but it wont be public
