### ISSUE TITLE
Add Night Flight by KLYDIX

### ISSUE THREAD

**Issue by Spyritzzz** [FlafyDev/auto-nong-indexes#2964]
### Song Name

Night Flight

### Artist Name

KLYDIX

### Source

Youtube

### Youtube Link

https://youtu.be/ddszgJcQvIU

### Song ID

1000

### Start Offset [ms]

0

### Extra

Used in my own level "Night Flight" - 108598295

**Comment by SpuckwasserDE** [comment]
reject

duplicate request, no worries the song has been accepted
