### ISSUE TITLE
Add At The Speed Of Light X Face Of by saiveeon

### ISSUE THREAD

**Issue by Dimasik745** [FlafyDev/auto-nong-indexes#2969]
### Song Name

At The Speed Of Light X Face Of

### Artist Name

saiveeon

### Source

Youtube

### Youtube Link

Rs6WXfzbgAI

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 51631216
Downloaded: No

**Comment by IMGer4** [comment]
accept
