### ISSUE TITLE
Add ? x MrBeast Rizz by Darmageon

### ISSUE THREAD

**Issue by GDisCool** [FlafyDev/auto-nong-indexes#2998]
### Song Name

? x MrBeast Rizz

### Artist Name

Darmageon

### Source

Youtube

### Youtube Link

5AQszffkuzE

### Song ID

727020

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 62556400

**Comment by SpuckwasserDE** [comment]
reject

artist name must be descriptive and correct
