### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by RASINAHSAN** [FlafyDev/auto-nong-indexes#30]
### Song Name

Bling-Bang-Bang-Born

### Artist Name

Creepy Nuts

### Source

Youtube

### Youtube Link

https://youtu.be/5NzfqW_Yt6Y?si=CqYe2EgdYY3Y2ccd

### Song ID

1311743

**Comment by RASINAHSAN** [comment]
Gg

**Comment by FlafyDev** [comment]
the artist should be Creepy Nuts not the uploader xD

**Comment by FlafyDev** [comment]
accept
