### ISSUE TITLE
Add ? x MrBeast Rizz by Darmageon

### ISSUE THREAD

**Issue by GDisCool** [FlafyDev/auto-nong-indexes#3000]
### Song Name

? x MrBeast Rizz

### Artist Name

Darmageon

### Source

Youtube

### Youtube Link

5AQszffkuzE

### Direct File Link

https://www.cjoint.com/doc/24_08/NHrtLycyiDH_-MASHUP-Codependence-X-Mr-beast-Rizz.mp3

### Song ID

727020

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 94258024

**Comment by SpuckwasserDE** [comment]
reject

song name must be descriptive and correct
