### ISSUE TITLE
Add idc by idk

### ISSUE THREAD

**Issue by beggogd** [FlafyDev/auto-nong-indexes#3010]
### Song Name

moves like jagger

### Artist Name

maroon 5

### Source

Youtube

### Direct File Link

file:///C:/Users/beggo/Music/acheron%20moves%20like%20jagger.mp3

### Song ID

770520

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 109169184

**Comment by SpuckwasserDE** [comment]
reject

no youtube link given
