### ISSUE TITLE
Add Nong Song: From The Start

### ISSUE THREAD

**Issue by Toe-Enjoyer42** [FlafyDev/auto-nong-indexes#3020]
### Song Name

From The Start

### Artist Name

Laufey

### Source

Direct file download

### Direct File Link

https://uploadnow.io/s/e3b8758c-9382-4780-8f91-0025a67526d3?o=t

### Song ID

1281828

### Extra

100827191

**Comment by Mogulazo** [comment]
There is a similar one by goodkidband, i dont know the song id but if I get it I give it to you
