### ISSUE TITLE
Add Gangstas Paradise by Coolio

### ISSUE THREAD

**Issue by Hallo15486** [FlafyDev/auto-nong-indexes#3022]
### Song Name

Gangstas Paradise

### Artist Name

Coolio

### Source

Youtube

### Youtube Link

Tw0_qHNRAEA

### Song ID

0

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 100499696
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Stereo Madness" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
