### ISSUE TITLE
Add Until The Sun Comes up by Drew Seeley

### ISSUE THREAD

**Issue by Hallo15486** [FlafyDev/auto-nong-indexes#3023]
### Song Name

Until The Sun Comes up

### Artist Name

Drew Seeley

### Source

Youtube

### Youtube Link

FfcSAfsjCeI

### Song ID

1266014

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 109123394
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
reject

popular songs like the tidal wave song are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
