### ISSUE TITLE
Add Snow Goose by Mutsuhiko Itzumi

### ISSUE THREAD

**Issue by top28-alt** [FlafyDev/auto-nong-indexes#3025]
### Song Name

Snow Goose

### Artist Name

Mutsuhiko Itzumi

### Source

Youtube

### Youtube Link

6IH0GOCgv4ZuACrR

### Song ID

10004431

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108025798
Downloaded: No

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
