### ISSUE TITLE
Add Flashback by Miyavi

### ISSUE THREAD

**Issue by Usdf123** [FlafyDev/auto-nong-indexes#3029]
### Song Name

Flashback

### Artist Name

Miyavi

### Source

Youtube

### Youtube Link

fhBA6ynorvc

### Song ID

0 [Stereo Madness]

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 87544150
Downloaded: No

**Comment by SpuckwasserDE** [comment]
reject

song id cant contain text
