### ISSUE TITLE
Add Nong Song: Sonic blaster X last friday night

### ISSUE THREAD

**Issue by NaliX3308** [FlafyDev/auto-nong-indexes#3030]
### Song Name

Sonic blaster X Last friday night

### Artist Name

F-777

### Source

Youtube

### Youtube Link

https://youtu.be/lyZ66nL006s?si=HgcrEtNxKn4jC54O

### Song ID

574484

**Comment by NaliX3308** [comment]
Lol thanks

**Comment by SpuckwasserDE** [comment]
accept
