### ISSUE TITLE
Add Night Flight by KLYDIX

### ISSUE THREAD

**Issue by Spyritzzz** [FlafyDev/auto-nong-indexes#3031]
### Song Name

Night Flight

### Artist Name

KLYDIX

### Source

Youtube

### Youtube Link

ddszgJcQvIU

### Song ID

1000

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108598295
Downloaded: No

**Comment by SpuckwasserDE** [comment]
reject

duplicate request, no worries the song has been accepted
