### ISSUE TITLE
Add I Got No Time (Guitar Cover)  by The Living Tombstone / Alex Heacock

### ISSUE THREAD

**Issue by YRalvarez** [FlafyDev/auto-nong-indexes#3054]
### Song Name

I Got No Time (Guitar Cover) 

### Artist Name

The Living Tombstone / Alex Heacock

### Source

Youtube

### Youtube Link

1BeUAg1cWiqz6WEj

### Song ID

672264

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 17128328
Downloaded: No

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
