### ISSUE TITLE
Add Take A Slice by Glass Animal

### ISSUE THREAD

**Issue by Tv-Github1** [FlafyDev/auto-nong-indexes#3056]
### Song Name

Take A Slice

### Artist Name

Glass Animal

### Source

Youtube

### Youtube Link

https://youtu.be/WS0ZqIWSy84?si=IfvkhXwRURRCgnaU

### Song ID

1269411

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 109205018
Downloaded: No

**Comment by Tv-Github1** [comment]
UnDelete this

**Comment by Cosmo304** [comment]
reject. This has nothing to do with the original song.
