### ISSUE TITLE
Add hagansolaton by haganhawk22

### ISSUE THREAD

**Issue by Hagan8ar** [FlafyDev/auto-nong-indexes#3071]
### Song Name

hagansolaton

### Artist Name

haganhawk22

### Source

Youtube

### Youtube Link

H7YVLfVoV6U-VG7O

### Song ID

76743

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 92107229
Downloaded: No

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
