### ISSUE TITLE
Add InSaniTy by Pony GMD

### ISSUE THREAD

**Issue by domesticundead** [FlafyDev/auto-nong-indexes#3082]
### Song Name

InSaniTy

### Artist Name

Pony GMD

### Source

Youtube

### Youtube Link

tI4-jExIxTbLiffM

### Song ID

507971

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 55979949

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
