### ISSUE TITLE
Sakupen Circles x Gangsta paradise piano (Diamond ver)

### ISSUE THREAD

**Issue by Bodysz** [FlafyDev/auto-nong-indexes#3083]
### Song Name

Sakupen Circles x Gangsta paradise piano (Diamond ver)

### Artist Name

mr-jazzman

### Source

Youtube

### Youtube Link

sWE_YX-SNWs

### Song ID

360804

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 76962930 (Sakupen Circles)
Downloaded: Yes

This is what Diamond use for Sakupen Circles

**Comment by SpuckwasserDE** [comment]
accept
