### ISSUE TITLE
Add d by d

### ISSUE THREAD

**Issue by PluginHusky** [FlafyDev/auto-nong-indexes#3091]
### Song Name

d

### Artist Name

d

### Source

Youtube

### Youtube Link

https://youtu.be/7zp1TbLFPp8?si=10jpeT09Iy9KyQbp

### Song ID

2

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 13519
Downloaded: No

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Polargeist" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public

also artist and song name must be descriptive and correct
