### ISSUE TITLE
Add Godzilla (ft. Juice WRLD) by EminemMusic

### ISSUE THREAD

**Issue by EnormouslyCNS** [FlafyDev/auto-nong-indexes#3092]
### Song Name

Godzilla (ft. Juice WRLD)

### Artist Name

EminemMusic

### Source

Youtube

### Youtube Link

9XvXF1LrWgA

### Song ID

4

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 59847342
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Base after Base" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
