### ISSUE TITLE
Alan walker - the spectre

### ISSUE THREAD

**Issue by Lucashard1** [FlafyDev/auto-nong-indexes#3109]
### Song Name

Alan walker - the spectre

### Artist Name

alan walker

### Source

Youtube

### Youtube Link

alan walker

### Direct File Link

https:/www.youtube/alan walker - the spectre

### Song ID

9165093

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 91328416
Downloaded: si

**Comment by Lucashard1** [comment]
Solo no quiero que me eliminen :(

**Comment by Lucashard1** [comment]
Song alan walker

**Comment by Lucashard1** [comment]
![ImageTitle](https://github.com/user-attachments/assets/f27a7136-8111-4a16-82b2-db2a086e4248)

**Comment by Lucashard1** [comment]
Aceptar

**Comment by SpuckwasserDE** [comment]
reject

alan walker is not a link... also tf is going on here
