### ISSUE TITLE
Add shiawase VIP (Piano cover) by dion timmer

### ISSUE THREAD

**Issue by Milenium7** [FlafyDev/auto-nong-indexes#3114]
### Song Name

shiawase VIP (Piano cover)

### Artist Name

dion timmer

### Source

Youtube

### Youtube Link

qG-mxxkjBWo

### Song ID

1266014

### Start Offset [ms]

3000

### Extra

Created from Auto Nong.
Created for level: 86407629
Downloaded: Yes

**Comment by ANTIclockYT-source** [comment]
accept
