### ISSUE TITLE
Add FUJII KAZE SONG by FUJII KAZE

### ISSUE THREAD

**Issue by HARJUNADI140** [FlafyDev/auto-nong-indexes#3124]
### Song Name

FUJII KAZE SONG

### Artist Name

FUJII KAZE

### Source

Youtube

### Youtube Link

dawrQnvwMTY

### Song ID

621136

### Start Offset [ms]

50

### Extra

Created from Auto Nong.
Created for level: 11280109
Downloaded: YES

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Xenogenesis" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
