### ISSUE TITLE
Add mister beast by mister beast

### ISSUE THREAD

**Issue by TLauncherGD** [FlafyDev/auto-nong-indexes#3144]
### Song Name

mister beast

### Artist Name

mister beast

### Source

Youtube

### Youtube Link

9PGspaFVpec

### Song ID

0

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 109295478
Downloaded: No

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Stereo madness" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
