### ISSUE TITLE
Add TARZAN by Unicorn On Ketamine

### ISSUE THREAD

**Issue by chaufsi** [FlafyDev/auto-nong-indexes#3153]
### Song Name

TARZAN

### Artist Name

Unicorn On Ketamine

### Source

Youtube

### Youtube Link

OsHP2deFii8

### Song ID

123321

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 94909019

**Comment by SpuckwasserDE** [comment]
accept
