### ISSUE TITLE
Add Nong Song: Electroman Adventures (At the Speed of Light Remix)

### ISSUE THREAD

**Issue by SquareFloppa** [FlafyDev/auto-nong-indexes#3164]
### Song Name

Electroman Adventures (At the Speed of Light Remix)

### Artist Name

Josradu

### Source

Youtube

### Youtube Link

https://youtu.be/66t37JWJ4E4?si=KROJSg-sEUEPDgvm

### Song ID

12

### Start Offset [ms]

0

**Comment by WhoareyouXD** [comment]
accept
