### ISSUE TITLE
KETAMINE - Playboi Carti

### ISSUE THREAD

**Issue by Pablincho111** [FlafyDev/auto-nong-indexes#3167]
### Song Name

KETAMINE

### Artist Name

Playboi Carti

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=ma3qbyIo-Dw

### Direct File Link

https://www.youtube.com/watch?v=ma3qbyIo-Dw

### Song ID

111112

### Start Offset [ms]

0

### Extra

KETAMINE By Pablincho111

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
