### ISSUE TITLE
Add Love Dive by IVE

### ISSUE THREAD

**Issue by AmarinStar** [FlafyDev/auto-nong-indexes#3178]
### Song Name

Love Dive

### Artist Name

IVE

### Source

Youtube

### Youtube Link

5Lofm_k_VPZS6gE_

### Song ID

566770

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 79389474

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
