### ISSUE TITLE
Add LOVE DIVE by IVE

### ISSUE THREAD

**Issue by AmarinStar** [FlafyDev/auto-nong-indexes#3179]
### Song Name

LOVE DIVE

### Artist Name

IVE

### Source

Youtube

### Youtube Link

https://youtu.be/Gm0CM-6Pins?si=MdveagJuRxfvebt7

### Song ID

566770

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 79389474

**Comment by AmarinStar** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

popular songs (if used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
