### ISSUE TITLE
Add Going for the kill (Toji) by Rustage

### ISSUE THREAD

**Issue by kesito533** [FlafyDev/auto-nong-indexes#3265]
### Song Name

Going for the kill (Toji)

### Artist Name

Rustage

### Source

Youtube

### Youtube Link

oR4i3akwWY0

### Song ID

10003039

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 103551606
Downloaded: No

**Comment by SpuckwasserDE** [comment]
reject

popular songs (if used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
