### ISSUE TITLE
Add Going for the kill (Toji) by Rustage

### ISSUE THREAD

**Issue by kesito533** [FlafyDev/auto-nong-indexes#3266]
### Song Name

Going for the kill (Toji)

### Artist Name

Rustage

### Source

Youtube

### Youtube Link

oR4i3akwWY0

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 109256508
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "At the Speed of light" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
