### ISSUE TITLE
Add Nong Song: Acu X Eko X Goodbyes

### ISSUE THREAD

**Issue by OlivRulzGD** [FlafyDev/auto-nong-indexes#3299]
### Song Name

Acu X Eko X Goodbyes

### Artist Name

OlivRulz

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=jC2tI2kDWZc

### Song ID

723714

### Extra

idk if there is a start offset :(

**Comment by Daepicgdplayer** [comment]
Accept

**Comment by SpuckwasserDE** [comment]
reject

mashups/covers should have some popularity to show that people want it (especially if the song doesnt sound great).
Note that you can still use the nong yourself, but it wont be public
