### ISSUE TITLE
MHMM

### ISSUE THREAD

**Issue by GreyRayGD** [FlafyDev/auto-nong-indexes#33]
### Song Name

MHMM

### Artist Name

Glorb

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=tlooPT4pB1Y

### Song ID

467339

**Comment by FlafyDev** [comment]
but why replace "at the speed of light" with this

**Comment by SpuckwasserDE** [comment]
reject

as Flafy aready pointed out you cant just replace at the speed of light with this since it's too inconvenient
