### ISSUE TITLE
Napalm x Astronaut In The Ocean by GDtrilogy

### ISSUE THREAD

**Issue by Kudrex125** [FlafyDev/auto-nong-indexes#3304]
### Song Name

Napalm x Astronaut In The Ocean

### Artist Name

GDtrilogy

### Source

Youtube

### Youtube Link

QuP4SkX9tps

### Song ID

718171

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 65625974
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
reject

mashups/covers should have some popularity to show that people want it (especially if the song doesnt sound great).
Note that you can still use the nong yourself, but it wont be public
