### ISSUE TITLE
Congregation x pompeli

### ISSUE THREAD

**Issue by Nightmaregli** [FlafyDev/auto-nong-indexes#331]
### Song Name

Congregation x pompeli

### Artist Name

NegrettonGD

### Source

Direct file download

### Direct File Link

https://www.mediafire.com/file/wv77oozb04zkkm9/895761.mp3/file?dkey=loquiv9q40l&r=131

### Song ID

895761

### Extra

Congregation

**Comment by DrPater** [comment]
accept

**Comment by FlafyDev** [comment]
mediafile links are not supported. I suggest uploading to YouTube or using an existing video from YouTube.
