### ISSUE TITLE
Add this comes from the inside x its been so long (JJOZIAH JERSEY REMIX) by JJOZIAH

### ISSUE THREAD

**Issue by LLeaHf** [FlafyDev/auto-nong-indexes#3315]
### Song Name

this comes from the inside x its been so long (JJOZIAH JERSEY REMIX)

### Artist Name

JJOZIAH

### Source

Youtube

### Youtube Link

https://youtu.be/eA1NOr5sues?si=lKiyCYm20w3DEHcj

### Song ID

622262

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 42979536
Downloaded: No

**Comment by SpuckwasserDE** [comment]
accept
