### ISSUE TITLE
Add Wanchu Back by Aero Chord  its for my level

### ISSUE THREAD

**Issue by TGP9063** [FlafyDev/auto-nong-indexes#3316]
### Song Name

Wanchu Back

### Artist Name

Aero Chord

### Source

Youtube

### Youtube Link

WAnVGnfculw

### Direct File Link

https://www.youtube.com/watch?v=WAnVGnfculw

### Song ID

815245

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 105593215
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
reject

popular songs (if used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
