### ISSUE TITLE
Add GET OUT by DAGamees

### ISSUE THREAD

**Issue by CoderMonkey1956** [FlafyDev/auto-nong-indexes#3348]
### Song Name

GET OUT

### Artist Name

DAGamees

### Source

Youtube

### Youtube Link

ziaf3RrG80U

### Song ID

475234

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107577910
Downloaded: No

**Comment by showyxxx** [comment]
yo 28 aug💀

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "RUN!" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
