### ISSUE TITLE
GMFU

### ISSUE THREAD

**Issue by TheWhiteStarLine** [FlafyDev/auto-nong-indexes#335]
### Song Name

GMFU

### Artist Name

Odetari

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=it1CatEknr8

### Direct File Link

https://www.youtube.com/watch?v=it1CatEknr8

### Song ID

1

### Extra

Level.

**Comment by TheWhiteStarLine** [comment]
accept

**Comment by TheWhiteStarLine** [comment]
> Thanks for contributing! Someone will soon review your request.
> 
> Here is the JSON result for the reviewer:
> 
> ```json
> {
>   "name": "GMFU",
>   "artist": "Odetari",
>   "source": "youtube",
>   "yt-id": "it1CatEknr8",
>   "songs": [
>     1
>   ]
> }
> ```
> 
> To accept the request, a reviewer needs to write "accept".

accept

**Comment by TheWhiteStarLine** [comment]
Accept.

**Comment by IMGer4** [comment]
reject
