### ISSUE TITLE
Add Crab Rave by Noisestorm

### ISSUE THREAD

**Issue by ezpz256** [FlafyDev/auto-nong-indexes#3372]
### Song Name

Crab Rave

### Artist Name

Noisestorm

### Source

Youtube

### Youtube Link

youtube.com/watch?v=LDU_txk06tm

### Song ID

845240

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level:
Downloaded: No

**Comment by TGP9063** [comment]
yes lets gooooo crab rave
