### ISSUE TITLE
Add Zinnia Battle Theme

### ISSUE THREAD

**Issue by TheBearodactyl** [FlafyDev/auto-nong-indexes#3380]
### Song Name

Omega Ruby & Alpha Sapphire - Zinnia Battle Theme

### Artist Name

Nintendo

### Source

Youtube

### Youtube Link

GIn8_Q27WFY

### Song ID

509162

### Start Offset [ms]

0.1

### Extra

Created from Auto Nong.
Created for level: 105575748
Downloaded: Yes

**Comment by TheBearodactyl** [comment]
https://github.com/user-attachments/assets/a885e07f-5a86-4fad-9c56-c158efa31117

**Comment by TheBearodactyl** [comment]
https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by TheBearodactyl** [comment]
bruh

**Comment by SpuckwasserDE** [comment]
reject

popular songs like The wasureta song are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public

**Comment by TheBearodactyl** [comment]
> reject
> 
> popular songs like The wasureta song are too inconvenient to be replaced by smth unrelated and are therefore usually rejected. Note that you can still use the song yourself, but it won't be public

it's for galeforce when it comes out
