### ISSUE TITLE
Hai Yorokonde by This Kento

### ISSUE THREAD

**Issue by ASodiiGD** [FlafyDev/auto-nong-indexes#3383]
### Song Name

Hai Yorokonde

### Artist Name

This Kento

### Source

Youtube

### Youtube Link

jzi6RNVEOtA

### Song ID

123

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107252586
Downloaded: No

**Comment by ASodiiGD** [comment]
accept

**Comment by TheVariety1** [comment]
Accept
