### ISSUE TITLE
Add ? x MrBeast Rizz by Schtiffles

### ISSUE THREAD

**Issue by AskMarti** [FlafyDev/auto-nong-indexes#3401]
### Song Name

? x MrBeast Rizz

### Artist Name

Schtiffles

### Source

Youtube

### Youtube Link

PBfQZ8tgvPw

### Song ID

727020

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 101176038
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
