### ISSUE TITLE
Add Nong Song: Listen Not 

### ISSUE THREAD

**Issue by DatKairyu1** [FlafyDev/auto-nong-indexes#3405]
### Song Name

Listen Not 

### Artist Name

DatKairyu

### Source

Youtube

### Youtube Link

https://youtu.be/rDfqwwob9Zc?si=mL7BasTGgvB0YJ7L

### Song ID

GEOMETRICAL DOMINATOR

### Start Offset [ms]

0

### Extra

Used in the lv "Listen Not Layout"
![Screenshot_2024-08-29-14-42-18-32_73932565f5d18c5d7f2b58eb6d5de17f](https://github.com/user-attachments/assets/a44c517c-5225-438e-ac3e-2c3d3cbdfce9)

**Comment by DatKairyu** [comment]
The music is great I need it too!
