### ISSUE TITLE
Add gladiator by Ne1rohhhhh

### ISSUE THREAD

**Issue by Ne1rohhhhh** [FlafyDev/auto-nong-indexes#3416]
### Song Name

gladiator

### Artist Name

Ne1rohhhhh

### Source

Youtube

### Youtube Link

VUlkvVNuNeA

### Song ID

587069

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 5904109
Downloaded: No

**Comment by neprao** [comment]
reject

replacing a well known song (endgame)
