### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by Triple666-666** [FlafyDev/auto-nong-indexes#3417]
### Song Name

Kerosene

### Artist Name

Crystal Castles

### Source

Youtube

### Youtube Link

https://youtu.be/qR2QIJdtgiU?si=zX00I8e-Glrcy7pE

### Song ID

815742

### Start Offset [ms]

0

### Extra

Used in level - Kerosene

**Comment by neprao** [comment]
reject

already in the index
