### ISSUE TITLE
Kerosene

### ISSUE THREAD

**Issue by Triple666-666** [FlafyDev/auto-nong-indexes#3418]
### Song Name

Kerosene

### Artist Name

Crystal Castles

### Source

Youtube

### Youtube Link

https://youtu.be/qR2QIJdtgiU?si=zX00I8e-Glrcy7pE

### Song ID

785995

### Start Offset [ms]

0

### Extra

Used in the level - ''Kerosene" 79736429

**Comment by neprao** [comment]
reject

this has been added already
