### ISSUE TITLE
Add Shell of Light by Burial

### ISSUE THREAD

**Issue by chwdunder** [FlafyDev/auto-nong-indexes#3420]
### Song Name

Shell of Light

### Artist Name

Burial

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=0mkLNYaCJns

### Song ID

858998

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86651761
Downloaded: Yes

**Comment by neprao** [comment]
reject

replacing a well known and used song
