### ISSUE TITLE
Add Dry Out (Oskar remix) by Oskar Xkx gaming

### ISSUE THREAD

**Issue by tahiadz1962** [FlafyDev/auto-nong-indexes#346]
### Song Name

Dry Out (Oskar remix)

### Artist Name

Oskar Xkx gaming

### Source

Youtube

### Youtube Link

kiMB8YiKqHZlWn7o

### Song ID

3

### Extra

Created from Auto Nong.
Created for level: 1314024

**Comment by Khonlanggg** [comment]
..
