### ISSUE TITLE
Add Sakupen's Paradise by Gab1239Muzic

### ISSUE THREAD

**Issue by Gabriel-Cre** [FlafyDev/auto-nong-indexes#351]
### Song Name

Sakupen's Paradise

### Artist Name

Gab1239Muzic

### Source

Youtube

### Youtube Link

https://youtu.be/MYJkFQ4pNoM?si=FRo_zzL-xxuaFn2C

### Direct File Link

https://youtu.be/MYJkFQ4pNoM?si=FRo_zzL-xxuaFn2C

### Song ID

291008

### Extra

Created from Auto Nong.
Created for level: Sakupen Circles

**Comment by Gabriel-Cre** [comment]
Hi

**Comment by FlafyDev** [comment]
there isn't a level with the song 291008
