### ISSUE TITLE
Add Dancin' by Aaron Smith

### ISSUE THREAD

**Issue by porotit** [FlafyDev/auto-nong-indexes#3519]
### Song Name

Dancin' (KRONO Remix)

### Artist Name

Aaron Smith

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=Cjp6RVrOOW0

### Song ID

1000

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 7426972
Downloaded: No

**Comment by Elpolter** [comment]
Accept

**Comment by Elpolter** [comment]
> ¡Gracias por tu colaboración! Pronto alguien revisará tu solicitud.
> 
> Aquí está el resultado JSON para el revisor:
> 
> ```json
> {
>   "name": "Dancin' (KRONO Remix)",
>   "artist": "Aaron Smith",
>   "source": "youtube",
>   "startOffset": 0,
>   "yt-id": "Cjp6RVrOOW0",
>   "songs": [
>     1000
>   ]
> }
> ```
> 
> Para aceptar la solicitud, un revisor debe escribir "aceptar".

Accept
