### ISSUE TITLE
Add awareness by KENTENSHI

### ISSUE THREAD

**Issue by LLeaHf** [FlafyDev/auto-nong-indexes#3524]
### Song Name

awareness

### Artist Name

KENTENSHI

### Source

Youtube

### Youtube Link

https://youtu.be/LTM5bSPrOFw?si=Ie6W0LENfRQSfw1n

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 4456683
Downloaded: No

**Comment by SpuckwasserDE** [comment]
accept
