### ISSUE TITLE
Add At the Speed of Light (AceTAD Remix) by Dimrain47

### ISSUE THREAD

**Issue by Logboi731** [FlafyDev/auto-nong-indexes#364]
### Song Name

At the Speed of Light (AceTAD Remix)

### Artist Name

Dimrain47

### Source

Youtube

### Youtube Link

KGcw_U-8HXM

### Song ID

467339

### Extra

Created from Auto Nong.
Created for level: 10565740

**Comment by FlafyDev** [comment]
accept
