### ISSUE TITLE
Add F-777 - Sonic Blaster (Vaporwave Remix) by Valu Joy

### ISSUE THREAD

**Issue by AskMarti** [FlafyDev/auto-nong-indexes#3670]
### Song Name

F-777 - Sonic Blaster (Vaporwave Remix)

### Artist Name

Valu Joy

### Source

Youtube

### Youtube Link

o9yks4oN3GE

### Song ID

574484

### Start Offset [ms]

1800

### Extra

Created from Auto Nong.
Created for level: 101084745
Downloaded: Yes

**Comment by AskMarti** [comment]
Aaaaaaa a

**Comment by AskMarti** [comment]
Htthutyrdhgsdfqa

**Comment by SpuckwasserDE** [comment]
accept
