### ISSUE TITLE
Add BOFU2016ChronomiaLimeBGA by inukoro

### ISSUE THREAD

**Issue by Duong57** [FlafyDev/auto-nong-indexes#3673]
### Song Name

BOFU2016ChronomiaLimeBGA

### Artist Name

inukoro

### Source

Youtube

### Youtube Link

hUpV1872pWs

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Downloaded: Yes

**Comment by Duong57** [comment]
accept

**Comment by superlmao** [comment]
accept
