### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by Sinkgod82** [FlafyDev/auto-nong-indexes#3682]
### Song Name

Kami no Kotoba

### Artist Name

Skyward

### Source

Youtube

### Youtube Link

[4K | RTX: ON] "Wasureta" by Augi and More 100% | Full Detail Showcase I Geometry Dash

### Song ID

509162

### Start Offset [ms]

0

**Comment by IMGer4** [comment]
The youtube link is not a link, just a youtube video title

**Comment by IMGer4** [comment]
reject
