### ISSUE TITLE
Add NightmaresX by IDK

### ISSUE THREAD

**Issue by Amogus7676** [FlafyDev/auto-nong-indexes#3685]
### Song Name

NightmaresX

### Artist Name

IDK

### Source

Youtube

### Youtube Link

oLUTwdUNADc

### Song ID

1000

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 95655747
Downloaded: Yes
-13 doesn't work

**Comment by Amogus7676** [comment]
accept

**Comment by IMGer4** [comment]
reject
