### ISSUE TITLE
Add Nong Song: Tidal Wave (NCS) x Shiawase VIP mashup

### ISSUE THREAD

**Issue by AnAcaRaAlt** [FlafyDev/auto-nong-indexes#369]
### Song Name

Tidal Wave (NCS) x Shiawase VIP mashup

### Artist Name

KHEMIS, Coopex, ZANA

### Source

Direct file download

### Direct File Link

https://onedrive.live.com/download?resid=633E0CF7E735FDF2%2155693

### Song ID

10010067

### Extra

Used in the level "Tidal Wave" - 106708729

**Comment by FlafyDev** [comment]
onedrive links are not supported. I suggest uploading to YouTube or using an existing video from YouTube.

**Comment by AnAcaRaAlt** [comment]
Sorry, my bad. When I wanted to repost the song with a youtube link i actually saw that cloud provider links are not supported
