### ISSUE TITLE
Add God's Word by Luschka

### ISSUE THREAD

**Issue by Thiago09100** [FlafyDev/auto-nong-indexes#3691]
### Song Name

God's Word

### Artist Name

Luschka

### Source

Youtube

### Youtube Link

NaBF7qsPxWg

### Song ID

509162

### Start Offset [ms]

215.1

### Extra

Created from Auto Nong.
Created for level: 61842700
Downloaded: No

**Comment by IMGer4** [comment]
Sorry, there is alredy a lot of nongs with that nong, so reject

**Comment by IMGer4** [comment]
reject
