### ISSUE TITLE
$ilent Kocmo€ ∆∆∆

### ISSUE THREAD

**Issue by Yourself20** [FlafyDev/auto-nong-indexes#37]
### Song Name

Silent Kocmoc

### Artist Name

Megabricks - reuploads

### Source

Direct file download

### Direct File Link

https://songfilehub.com/home#google_vignette

### Song ID

444222

### Extra

Used in the level Silent Kocmoc

**Comment by Yourself20** [comment]
accept

**Comment by Looker5678** [comment]
accept

**Comment by Looker5678** [comment]
> Thanks for contributing! Someone will soon review your request.
> 
> Here is the JSON result for the reviewer:
> 
> ```json
> {
>   "name": "Silent Kocmoc",
>   "artist": "Megabricks - reuploads",
>   "source": "host",
>   "url": "https://songfilehub.com/home#google_vignette",
>   "songs": [
>     444222
>   ]
> }
> ```
> 
> To accept the request, a reviewer needs to write "accept".

accept

**Comment by Looker5678** [comment]
accept

**Comment by Looker5678** [comment]
> Thanks for contributing! Someone will soon review your request.
> 
> Here is the JSON result for the reviewer:
> 
> ```json
> {
>   "name": "Silent Kocmoc",
>   "artist": "Megabricks - reuploads",
>   "source": "host",
>   "url": "https://songfilehub.com/home#google_vignette",
>   "songs": [
>     444222
>   ]
> }
> ```
> 
> To accept the request, a reviewer needs to write "accept".

accept

**Comment by Looker5678** [comment]
accept

**Comment by FlafyDev** [comment]
no song link was provided.
you did link the sfh site tho. if it exists there then you already have it in auto nong anyway..
