### ISSUE TITLE
Add Isolation x B&W2 Gym Leader Theme

### ISSUE THREAD

**Issue by kekevids134** [FlafyDev/auto-nong-indexes#3707]
### Song Name

Isolation x B&W2 Gym Leader Theme

### Artist Name

RobvaTopper

### Source

Youtube

### Youtube Link

gOvbPUcC8Pc

### Song ID

76743

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 87076958
Downloaded: No

**Comment by Careamel** [comment]
accept
