### ISSUE TITLE
Add Solar Wind X Kotletki S Pureshkoy by Lemour (Ft. Jumper)

### ISSUE THREAD

**Issue by Leonard4446** [FlafyDev/auto-nong-indexes#3716]
### Song Name

Solar Wind X Kotletki S Pureshkoy

### Artist Name

Lemour (Ft. Jumper)

### Source

Youtube

### Youtube Link

VENS5A-5Ee0

### Song ID

493898

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 90390075
Downloaded: Yes

**Comment by Leonard4446** [comment]
Accept

**Comment by Leonard4446** [comment]
I'm waiting :)

**Comment by Leonard4446** [comment]
Accept

**Comment by SpuckwasserDE** [comment]
reject

mashups/covers should have some popularity to show that people want it (especially if the song doesnt sound great).
Note that you can still use the nong yourself, but it wont be public
