### ISSUE TITLE
Add Nong Song: Eternal Silence

### ISSUE THREAD

**Issue by Kawoshin1995** [FlafyDev/auto-nong-indexes#373]
### Song Name

Eternal Silence

### Artist Name

dj-nate

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=JWUg2ZILWbM&t=1s

### Song ID

-14

### Extra

Used in the level "Eternal Silence" - 83476262

**Comment by Kawoshin1995** [comment]
Okay

**Comment by SpuckwasserDE** [comment]
reject

-14 is not the correct song id. Clubsteps song id is 12
