### ISSUE TITLE
Add Nong Song: NightmaresX

### ISSUE THREAD

**Issue by Amogus7676** [FlafyDev/auto-nong-indexes#3737]
### Song Name

NightmaresX

### Artist Name

-CløseUp+

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=oLUTwdUNADc

### Song ID

1000

### Extra

Used in the level Last nightmare
ID -13 doesn't work
I'm making a level called ### My nightmare

**Comment by IDKwhyimhere0** [comment]
accept

**Comment by LoardPTT** [comment]
accept
