### ISSUE TITLE
Add At the speed of Electroman by Dimrain47

### ISSUE THREAD

**Issue by Foxiseminger** [FlafyDev/auto-nong-indexes#3763]
### Song Name

At the speed of Electroman

### Artist Name

Dimrain47

### Source

Youtube

### Youtube Link

66t37JWJ4E4

### Song ID

462046

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 109902107
Downloaded: Yes

its for electrobath pls acccept

**Comment by Foxiseminger** [comment]
for id 109902107

**Comment by FoxyWorld1** [comment]
do it again daddy
