### ISSUE TITLE
Add Nong Song: Space Abyss VIP

### ISSUE THREAD

**Issue by Marcotrix** [FlafyDev/auto-nong-indexes#3779]
### Song Name

Space abyss VIP

### Artist Name

Lchavasse

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=vw_6VfBWgrg

### Song ID

737166

### Extra

alternative to normal space abyss, is more energetic

**Comment by SpuckwasserDE** [comment]
accept
