### ISSUE TITLE
Thanks for contributing!

### ISSUE THREAD

**Issue by icker123** [FlafyDev/auto-nong-indexes#378]
Thanks for contributing!
Someone will soon review your request.

Here is the JSON result for the reviewer:
```json
{
  "name": "Ta1lsd004",
  "artist": "Ta1lsd0lll",
  "source": "youtube",
  "yt-id": "s0u10cFVrjc",
  "songs": [
    580675
  ]
}
```
To accept the request, a reviewer needs to write "accept".

_Originally posted by @auto-nong[bot] in https://github.com/FlafyDev/auto-nong-indexes/issues/377#issuecomment-2184078813_

**Comment by icker123** [comment]
accept

**Comment by FlafyDev** [comment]
you can't accept your own submission
