### ISSUE TITLE
Add Sonic Wave Rebirth (RTX: ON) - Without LDM in Perfect Quality (4K, 60fps) - Geometry Dash by Neiro

### ISSUE THREAD

**Issue by hater-mania** [FlafyDev/auto-nong-indexes#3789]
### Song Name

Sonic Wave Rebirth (RTX: ON) - Without LDM in Perfect Quality (4K, 60fps) - Geometry Dash

### Artist Name

Neiro

### Source

Youtube

### Youtube Link

onQ8jFenEnY

### Song ID

574484

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 108870731

**Comment by IMGer4** [comment]
The name of the nong that you want to add is Sonic Blaster (HJFod Remix), but this nong is alredy on the mod!

**Comment by IMGer4** [comment]
reject

**Comment by yeayeaboiGD** [comment]
why did u friggin add a fugin Showcase by neuro💀💀💀💀💀💀🙏🙏🙏
