### ISSUE TITLE
Add Creo - Sphere x Cholorine Twenty One Pilots

### ISSUE THREAD

**Issue by Salchipapasz** [FlafyDev/auto-nong-indexes#3790]
### Song Name

Sphere x Cholorine

### Artist Name

Creo

### Source

Direct file download

### Direct File Link

https://files.fm/u/cnt9kwgejs

### Song ID

739991

### Extra

Used in the level Zodiac (739991)

**Comment by IMGer4** [comment]
Please only submit YouTube video links, or permanent direct download links from CDNs that has given permission for Auto Nong to download from. Right now there isn't any CDNs that are allowed.

**Comment by IMGer4** [comment]
reject
