### ISSUE TITLE
Auto Nong GD

### ISSUE THREAD

**Issue by Firzo** [FlafyDev/auto-nong-indexes#38]
### Song Name

Lost (XVA Remix) x World Cup Mashup

### Artist Name

AidanTR

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=FsiXaDwrTWg

### Song ID

945695

### Extra

27960100 - Slaughterhouse

**Comment by FlafyDev** [comment]
slaugtherhouse's song starts with a delay of like 40 seconds iirc. so the youtube song has to have an into of 40 seconds of silence.. so that means it will not sync :(

**Comment by Firzo** [comment]
It does have delay, but the nong doesn't show it
