### ISSUE TITLE
add thermodynamix x malas decisiones

### ISSUE THREAD

**Issue by thomas85jjk** [FlafyDev/auto-nong-indexes#382]
### Song Name

thermodynamix x malas decisiones

### Artist Name

DJ-Nate

### Source

Direct file download

### Direct File Link

https://www.mediafire.com/file/24r0hesnm4p6q0v/770520.mp3/file

### Song ID

770520

**Comment by thomas85jjk** [comment]
accept

**Comment by FlafyDev** [comment]
mediafile links are not supported. I suggest uploading to YouTube or using an existing video from YouTube.
