### ISSUE TITLE
Gunslinga Corridor

### ISSUE THREAD

**Issue by ThePapastron** [FlafyDev/auto-nong-indexes#385]
### Song Name

Gunslinga

### Artist Name

Pegboard Nerds

### Source

Direct file download

### Direct File Link

https://cdn.discordapp.com/attachments/662699103259721731/1253803433362722876/500476.mp3?ex=66772ef1&is=6675dd71&hm=1e5934d5a1ce151c33024f01986654ac70ca4b14458189bfc120f7ca294dec99&

### Song ID

500476

### Extra

Used in the level Gunslinga Corridor

**Comment by FlafyDev** [comment]
discord links are not supported. I suggest uploading to YouTube or using an existing video from YouTube.
