### ISSUE TITLE
Infinite Repeating by Daft Punk

### ISSUE THREAD

**Issue by MarcGamingUwU** [FlafyDev/auto-nong-indexes#386]
### Song Name

Infinite Repeating

### Artist Name

Daft Punk

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=imBlPXbAv6E

### Song ID

1000000

### Extra

Created from Auto Nong.
Created for level: 106228687
UwU

**Comment by MarcGamingUwU** [comment]
accept

**Comment by MarcGamingUwU** [comment]
I

**Comment by SpuckwasserDE** [comment]
accept
