### ISSUE TITLE
Add dance till your death by phtheven hocking

### ISSUE THREAD

**Issue by jimmy5272** [FlafyDev/auto-nong-indexes#387]
### Song Name

dance till your death

### Artist Name

phtheven hocking

### Source

Youtube

### Youtube Link

wkPKR-BHVi9_xs8W

### Song ID

1

### Extra

Created from Auto Nong.
Created for level: 114082

**Comment by jimmy5272** [comment]
''accept''

**Comment by IMGer4** [comment]
reject
