### ISSUE TITLE
Add Kibo by Dion Timmer

### ISSUE THREAD

**Issue by Toe-Enjoyer42** [FlafyDev/auto-nong-indexes#3884]
### Song Name

Kibo

### Artist Name

Dion Timmer

### Source

Youtube

### Youtube Link

sVzpEAdBivs

### Song ID

456732

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 110017353
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
accept
