### ISSUE TITLE
8 bit Explorers 

### ISSUE THREAD

**Issue by Noahgd090** [FlafyDev/auto-nong-indexes#39]
### Song Name

Explorers 

### Artist Name

Hinkik 

### Source

Youtube

### Youtube Link

https://youtu.be/fc1tg9qkGyI?si=FDgjiUiddV8KgK_F

### Direct File Link

https://youtu.be/fc1tg9qkGyI?si=FDgjiUiddV8KgK_F

### Song ID

87539

**Comment by LousyBook-01** [comment]
reject

no
