### ISSUE TITLE
Add PRINCE OF DARKNESS by SHADXWBXRN

### ISSUE THREAD

**Issue by LevGasht** [FlafyDev/auto-nong-indexes#3920]
### Song Name

PRINCE OF DARKNESS

### Artist Name

SHADXWBXRN

### Source

Youtube

### Youtube Link

https://youtu.be/Wv2NLzBeX5Q?si=qMw1TjgDnj33hAFs

### Song ID

383154

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 110042400
Downloaded: No

**Comment by LevGasht** [comment]
Cgc

**Comment by LevGasht** [comment]
!

**Comment by SpuckwasserDE** [comment]
reject

popular songs (if used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
