### ISSUE TITLE
Add Lost x IshowSpeed

### ISSUE THREAD

**Issue by Neypro09** [FlafyDev/auto-nong-indexes#393]
### Song Name

Lost x IShowSpeed

### Artist Name

Crim3s

### Source

Direct file download

### Youtube Link

945695.mp3

### Direct File Link

https://download2290.mediafire.com/te2ht0j9sdcgM9URpauZwg5SevaQNo0ILa9ObRp4TXCOLWxazqQ-0hz-7vpuVrwiPUUqdVdCuQXPTOq-ltjKuf0B2ZMvoHItjy-u0eCujRZEehOu-1nI6j4dvCBhWQQ-NnjS6LVCoPjP1fBIq6UkzAH5HsCmLx96bmz2XeZV5yQtC0uf/7x3slatwtxjfgs2/945695.mp3

### Song ID

945695

### Extra

Created from Auto Nong.
Created for level: 27690100

**Comment by FlafyDev** [comment]
mediafile links are not supported. I suggest uploading to YouTube or using an existing video from YouTube.
