### ISSUE TITLE
Add I dont wna cry (haste) by Kurffew

### ISSUE THREAD

**Issue by AverageGDplayer** [FlafyDev/auto-nong-indexes#394]
### Song Name

I dont wna cry (haste)

### Artist Name

Kurffew

### Source

Youtube

### Youtube Link

NIJtEybSCCOzUKdg

### Direct File Link

https://www.I don't wna cry.com/song.mp3

### Song ID

1151602

### Extra

Created from Auto Nong.
Created for level: 102320078

**Comment by elnexreal** [comment]
song link doesnt work, please fix
