### ISSUE TITLE
Time Leaper (Piano Cover)

### ISSUE THREAD

**Issue by Firzo** [FlafyDev/auto-nong-indexes#40]
### Song Name

Time Leaper (Piano Cover)

### Artist Name

Hinkik

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=Pg2sJG0vhNA

### Song ID

683996

### Extra

24301797 - "Falling Up"

**Comment by FlafyDev** [comment]
the youtube video has a 2 seconds intro so i don't think it will sync :(
