### ISSUE TITLE
Add Night Dancer by Imase

### ISSUE THREAD

**Issue by Folip631** [FlafyDev/auto-nong-indexes#400]
### Song Name

Night Dancer

### Artist Name

Imase

### Source

Youtube

### Youtube Link

https://youtu.be/QbHBfxAOucI?si=quICGs_ex0YfAA37

### Song ID

1

### Extra

Created from Auto Nong.
Created for level: 92630070

**Comment by Folip631** [comment]
accept

**Comment by IMGer4** [comment]
reject
