### ISSUE TITLE
When You Find Me (Low Pitch) by Wist8nGD

### ISSUE THREAD

**Issue by wist8nGD** [FlafyDev/auto-nong-indexes#406]
### Song Name

When You Find Me (Low Pitch)

### Artist Name

Wist8nGD

### Source

Youtube

### Youtube Link

RQ3ZMYlSvqzgqM8i

### Song ID

30

### Extra

Created from Auto Nong.

**Comment by elnexreal** [comment]
video is not available, please update the url

**Comment by elnexreal** [comment]
accepted in another issue
