### ISSUE TITLE
Add Stuck Inside, cuz why not:3

### ISSUE THREAD

**Issue by whosmynametho** [FlafyDev/auto-nong-indexes#4066]
### Song Name

Stuck Inside

### Artist Name

Living Tombstone, Black Gryph0n, Baasik, Kevin Foster

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=9PD1PpZ2q78

### Song ID

945695

### Start Offset [ms]

0

**Comment by NikAlexIKS** [comment]
Who is a reviewer
