### ISSUE TITLE
Add When You Find Me (Low Pitch) by Wist8nGD

### ISSUE THREAD

**Issue by wist8nGD** [FlafyDev/auto-nong-indexes#408]
### Song Name

When You Find Me (Low Pitch)

### Artist Name

Wist8nGD

### Source

Youtube

### Youtube Link

https://youtu.be/nFePbe03800?si=RQ3ZMYlSvqzgqM8i

### Song ID

30

### Extra

Created from Auto Nong.

**Comment by elnexreal** [comment]
accept
