### ISSUE TITLE
Add Nong Song: Manny Heffley - Menace (Mustard - Ballin (Feat. Roddy Ricch) Mashup)

### ISSUE THREAD

**Issue by KillerMeganet** [FlafyDev/auto-nong-indexes#4097]
### Song Name

Ballace

### Artist Name

Manny Heffley

### Source

Youtube

### Youtube Link

https://youtu.be/rMFwCn14Mx0?si=iCv8-R5rN7UtywG7

### Song ID

1304920

### Extra

Can be used in the level: Menace by Manny Heffley 

107805281

**Comment by SpuckwasserDE** [comment]
accept
