### ISSUE TITLE
Add Nong Song: Tidal Wave (Cat Edition)

### ISSUE THREAD

**Issue by Termantita** [FlafyDev/auto-nong-indexes#410]
### Song Name

Shiawase (VIP - Cat Edition)

### Artist Name

SupaCLUCK

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=FlaPfkW7DjE

### Song ID

1266014

### Extra

Used in Tidal Wave

**Comment by elnexreal** [comment]
song offset is wrong. if you can, reupload the song please
