### ISSUE TITLE
Deadringer 

### ISSUE THREAD

**Issue by Oixelidiot** [FlafyDev/auto-nong-indexes#4187]
### Song Name

Deadringer (Kibo | panpan remix)

### Artist Name

Jamangar

### Source

Youtube

### Youtube Link

https://youtu.be/wYF1nmIXWbw?si=SEyOKqxIC3uhN0x4

### Song ID

501029

**Comment by wardahub-design** [comment]
maybe this will help
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)
