### ISSUE TITLE
Add The Hallucination(Right version) by Fashrod

### ISSUE THREAD

**Issue by Harameen** [FlafyDev/auto-nong-indexes#4249]
### Song Name

The Hallucination(Right version)

### Artist Name

Fashrod

### Source

Youtube

### Youtube Link

YsgelW8ocYc

### Song ID

568369

### Start Offset [ms]

44500

### Extra

Created from Auto Nong.
Created for level: 103127877
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
accept
