### ISSUE TITLE
Add Feel Good Inc. by Gorrilaz

### ISSUE THREAD

**Issue by LLeaHf** [FlafyDev/auto-nong-indexes#4300]
### Song Name

Feel Good Inc.

### Artist Name

Gorrilaz

### Source

Youtube

### Youtube Link

https://youtu.be/HyHNuVaZJ-k?si=dQhDcC35-DRFEtkV

### Song ID

760983

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 72665872
Downloaded: No

**Comment by SpuckwasserDE** [comment]
reject

popular songs (if used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
