### ISSUE TITLE
Remember the rain

### ISSUE THREAD

**Issue by Diosmio-hue** [FlafyDev/auto-nong-indexes#4331]
### Song Name

Lost x do You remember the rain

### Artist Name

Crim3s

### Source

Direct file download

### Song ID

945695

### Extra

Slaughterhouse

**Comment by Diosmio-hue** [comment]
Accept

**Comment by neprao** [comment]
reject

"Source
Direct file download" 🔥🔥 (theres literally no links in this entire issue)
