### ISSUE TITLE
Add Stereo Madness (full) REMIX by Goodvil Dasher

### ISSUE THREAD

**Issue by GoodvilDasher** [FlafyDev/auto-nong-indexes#436]
### Song Name

Stereo Madness (full) REMIX

### Artist Name

Goodvil Dasher

### Source

Youtube

### Youtube Link

zOhy0VMVy0M3SlWO

### Direct File Link

https://www.dropbox.com/scl/fi/6ikvcxytw6dmmu88r99ty/Stereo-Madness-Veysmix-FULL.mp3?rlkey=ouimemfkzadsxwxh9wvobxqie&st=5z5in14w&dl=0

### Song ID

500476

### Extra

Created from Auto Nong.
Created for level: 12260817

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
