### ISSUE TITLE
High Life

### ISSUE THREAD

**Issue by Elmau7w7** [FlafyDev/auto-nong-indexes#44]
### Song Name

Magic Touch  (31songmashup)

### Artist Name

Romos

### Source

Youtube

### Youtube Link

https://m.youtube.com/watch?v=cG8p6B4-Dmc&pp=ygURcm9tb3MgbWFnaWMgdG91Y2g%3D

### Song ID

595342

### Extra

Low Death

**Comment by FlafyDev** [comment]
accept
