### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by Kalimeno453** [FlafyDev/auto-nong-indexes#4422]
### Song Name

3008 Thursday theme

### Artist Name

uglyburger0

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=PGEhbK1okBU

### Song ID

3008

### Extra

This song could be used in sweden corridor, or other 3008 based levels (mine for example)

**Comment by SpuckwasserDE** [comment]
accept
