### ISSUE TITLE
Add Nong Song: Lost x Can U Be

### ISSUE THREAD

**Issue by DrizFr** [FlafyDev/auto-nong-indexes#4473]
### Song Name

Lost x Can U Be

### Artist Name

Kanye West, Travis Scott, Ty Dolla $ign, Y$

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=2_N7Rx-53YQ

### Song ID

945695

### Start Offset [ms]

35.0

### Extra

Used in the level "Slaughterhouse"

**Comment by SpuckwasserDE** [comment]
accept

**Comment by SpuckwasserDE** [comment]
accept
