### ISSUE TITLE
Add Magnolia Pimp Named Slicback by iluvUso

### ISSUE THREAD

**Issue by LLeaHf** [FlafyDev/auto-nong-indexes#4482]
### Song Name

Magnolia Pimp Named Slicback

### Artist Name

iluvUso

### Source

Youtube

### Youtube Link

https://youtu.be/ZGwAJiBSl0E?si=OWVElO7v1WsFOCyX

### Song ID

15

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 67392944
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
reject

duplicate request, no worries the song has been accepted
