### ISSUE TITLE
Add What's a future funk? x All stars by EpochGD

### ISSUE THREAD

**Issue by HoneyPiieeee** [FlafyDev/auto-nong-indexes#4513]
### Song Name

What's a future funk? x All stars

### Artist Name

EpochGD

### Source

Youtube

### Youtube Link

VLy5cI28vHQ

### Song ID

701013

### Start Offset [ms]

3800

### Extra

Created from Auto Nong.
Created for level: 44062068
Downloaded: No

**Comment by Cosmo304** [comment]
accept
