### ISSUE TITLE
Add Blast Processing Fusion Collab by Robvatopper and more

### ISSUE THREAD

**Issue by PlankNom** [FlafyDev/auto-nong-indexes#4527]
### Song Name

Blast Processing Fusion Collab

### Artist Name

OMFG, Toby Fox, Crazy Frog, Daft Punk and more

### Source

Youtube

### Youtube Link

5wQ2rFS-Zd4

### Song ID

507560

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 26935043
Downloaded: Yes

**Comment by Cosmo304** [comment]
accept
