### ISSUE TITLE
Add Aria Math by C418

### ISSUE THREAD

**Issue by Retrocathinks** [FlafyDev/auto-nong-indexes#4588]
### Song Name

Aria Math

### Artist Name

C418

### Source

Youtube

### Youtube Link

atgjKEgSqSU

### Direct File Link

https://www.mediafire.com/file/78sxlsg9xvr9zl4/C418_-_Aria_Math.mp3/file

### Song ID

889642

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 106038388
Downloaded: No

**Comment by Retrocathinks** [comment]
accept

**Comment by Retrocathinks** [comment]
> Thanks for contributing! Someone will soon review your request.
> 
> Here is the JSON result for the reviewer:
> 
> ```json
> {
>   "name": "Aria Math",
>   "artist": "C418",
>   "source": "youtube",
>   "startOffset": 0,
>   "yt-id": "atgjKEgSqSU",
>   "songs": [
>     889642
>   ]
> }
> ```
> 
> To accept the request, a reviewer needs to write "accept".

accept

**Comment by Cosmo304** [comment]
reject. NG song is slightly faster than the NONG, making it become out of sync
