### ISSUE TITLE
Add lost x ishowspeed by ishowspeed

### ISSUE THREAD

**Issue by Spacex899** [FlafyDev/auto-nong-indexes#459]
### Song Name

lost x ishowspeed

### Artist Name

ishowspeed

### Source

Youtube

### Youtube Link

Slaughterhouse mashup with World Cup

### Song ID

945695

### Extra

Created from Auto Nong.
Created for level: 70964912

**Comment by Spacex899** [comment]
Ok thanks

**Comment by IMGer4** [comment]
please enter a valid yt url

**Comment by IMGer4** [comment]
reject
