### ISSUE TITLE
Add Waiting For You by NyxTheShield

### ISSUE THREAD

**Issue by Acronix2** [FlafyDev/auto-nong-indexes#4599]
### Song Name

Waiting For You

### Artist Name

NyxTheShield

### Source

Youtube

### Youtube Link

bxbYUOWZZIs

### Song ID

8

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 110697615
Downloaded: No

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Cycles" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
