### ISSUE TITLE
Add Nong song

### ISSUE THREAD

**Issue by JoseTroll26** [FlafyDev/auto-nong-indexes#46]
### Song Name

EDÉN-XO COVER ESPAÑOL

### Artist Name

J O N A T Á N

### Source

Youtube

### Youtube Link

https://youtu.be/HLeVbWW0FTk?si=rDKc11-RUeNhK2tg

### Song ID

766165

**Comment by FlafyDev** [comment]
this sadly doesn't sync to the level in game. there is intro for like 2 seconds
