### ISSUE TITLE
Add Lost X World Cup by Bejski

### ISSUE THREAD

**Issue by Bejski** [FlafyDev/auto-nong-indexes#460]
### Song Name

Lost X World Cup

### Artist Name

Bejski

### Source

Youtube

### Youtube Link

WIvlC88ynDg

### Song ID

945695

### Extra

Created from Auto Nong.
Created for level: 27690100

**Comment by Bejski** [comment]
still waiting till u get that in the game

so 13. 7. 2024 o 14:47 github-actions[bot] ***@***.***>
napísal(a):

**Comment by SpuckwasserDE** [comment]
accept
