### ISSUE TITLE
Add at the speed of light (Piano Cover) by from1noobto1pro

### ISSUE THREAD

**Issue by From1NoobTo1Pro** [FlafyDev/auto-nong-indexes#4629]
### Song Name

at the speed of light (piano cover)

### Artist Name

from1noobto1pro

### Source

Youtube

### Youtube Link

rJb5E-P_wYw

### Direct File Link

https://www.youtube.com/watch?v=rJb5E-P_wYw

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 7485599
Downloaded: No

**Comment by From1NoobTo1Pro** [comment]
accept

**Comment by Creatorguest** [comment]
accept
