### ISSUE TITLE
Add Her Name Is ???Lady x Mi Pueblo No Se Toca by CindecK [A.C.E™🔥]

### ISSUE THREAD

**Issue by JumperCrazeGD** [FlafyDev/auto-nong-indexes#4632]
### Song Name

Her Name Is ???Lady x Mi Pueblo No Se Toca

### Artist Name

CindecK [A.C.E™🔥]

### Source

Youtube

### Youtube Link

fILG2JGBp-o

### Direct File Link

https://www.mediafire.com/file/ybo1e1mljc62o13/her#geometrydash

### Song ID

818027

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 66092652
Downloaded: Yes

**Comment by Aaronbey** [comment]
accept
