### ISSUE TITLE
Add Lost Umbrella by inabakumori

### ISSUE THREAD

**Issue by LLeaHf** [FlafyDev/auto-nong-indexes#4638]
### Song Name

Lost Umbrella

### Artist Name

inabakumori

### Source

Youtube

### Youtube Link

https://youtu.be/DeKLpgzh-qQ?si=RE33IEzUx9xdX8ke

### Song ID

1309753

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 104039496
Downloaded: No

**Comment by Cosmo304** [comment]
accept. Can't wait for this to be in Auto Nong!
