### ISSUE TITLE
XO Eden Cover

### ISSUE THREAD

**Issue by AireX72GD** [FlafyDev/auto-nong-indexes#47]
### Song Name

XO (eden cover and remake)

### Artist Name

Aaron Musslewhite

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=MbuP33ugiPU

### Song ID

766165

**Comment by FlafyDev** [comment]
isn't this already the default song in the game?

**Comment by SpuckwasserDE** [comment]
reject

as Flafy said, Im just cleaning up
