### ISSUE TITLE
Add Tek It (sped up) by Cafune

### ISSUE THREAD

**Issue by LLeaHf** [FlafyDev/auto-nong-indexes#4709]
### Song Name

Tek It (sped up)

### Artist Name

Cafune

### Source

Youtube

### Youtube Link

https://youtu.be/oIvFXVqtzxg?si=AoYts1UTNuQfSvZC

### Song ID

1241254

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 106658254
Downloaded: No

**Comment by Cosmo304** [comment]
reject. Doesn't sync properly
