### ISSUE TITLE
Add Tek It by Cafune

### ISSUE THREAD

**Issue by LLeaHf** [FlafyDev/auto-nong-indexes#4712]
### Song Name

Tek It

### Artist Name

Cafune

### Source

Youtube

### Youtube Link

https://youtu.be/oIvFXVqtzxg?si=AoYts1UTNuQfSvZC

### Song ID

100

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 86871436
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
accept
