### ISSUE TITLE
Add Linkin Park - Given Up by Linkin Park

### ISSUE THREAD

**Issue by Zamasu05** [FlafyDev/auto-nong-indexes#4827]
### Song Name

Linkin Park - Given Up

### Artist Name

Linkin Park

### Source

Youtube

### Youtube Link

0xyxtzD54rM

### Song ID

814267

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 110849063
Downloaded: No

**Comment by SpuckwasserDE** [comment]
accept
