### ISSUE TITLE
Add Linkin Park - No More Sorrow by Linkin Park 

### ISSUE THREAD

**Issue by Zamasu05** [FlafyDev/auto-nong-indexes#4908]
### Song Name

Linkin Park - No More Sorrow

### Artist Name

Linkin Park 

### Source

Youtube

### Youtube Link

https://youtu.be/rW4uBvP2Dqc?si=TlAiMPtOBUVaxHh7

### Song ID

814267

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 110849063
Downloaded: No

**Comment by SpuckwasserDE** [comment]
accept
