### ISSUE TITLE
 Turn The Lights Off by Tally Hall

### ISSUE THREAD

**Issue by zenvo-white** [FlafyDev/auto-nong-indexes#4927]
### Song Name

Turn The Lights Off

### Artist Name

Tally Hall

### Source

Youtube

### Youtube Link

dLrdSC9MVb4

### Song ID

720034

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 25999999
Downloaded: No

**Comment by Izzybizyy** [comment]
Sounds like kinda like a fnaf song, but it's not related to fnaf lol

**Comment by Izzybizyy** [comment]
Are you making a level with the songs you suggest. Especially the underverse song called tangled
