### ISSUE TITLE
Add Nong Song: 13. Cight & Vaiku - ｍｉｓｆｏｒｔｕｎｅ

### ISSUE THREAD

**Issue by Amogus7676** [FlafyDev/auto-nong-indexes#4937]
### Song Name

ｍｉｓｆｏｒｔｕｎｅ

### Artist Name

Cight

### Source

Youtube

### Youtube Link

https://m.youtube.com/watch?v=uD76KznabMQ&t=0s

### Song ID

555555

### Extra

Used in m I s f o r t u n e

**Comment by SpuckwasserDE** [comment]
reject

popular songs (used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
