### ISSUE TITLE
Add M i s f o r t u n e by Chight

### ISSUE THREAD

**Issue by Amogus7676** [FlafyDev/auto-nong-indexes#4948]
### Song Name

M i s f o r t u n e

### Artist Name

Chight

### Source

Youtube

### Youtube Link

uD76KznabMQ

### Song ID

555555

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 111042284
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
reject

popular songs (used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public

**Comment by Amogus7676** [comment]
But its not in any rated levels?

**Comment by SpuckwasserDE** [comment]
45175370
