### ISSUE TITLE
Add do ya like x resonance by Marcella

### ISSUE THREAD

**Issue by LLeaHf** [FlafyDev/auto-nong-indexes#4980]
### Song Name

do ya like x resonance

### Artist Name

Marcella

### Source

Youtube

### Youtube Link

https://youtu.be/QxWKRrsDank?si=cP2ztFIYUvQW-akH

### Song ID

171717

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 30949624
Downloaded: No

**Comment by SpuckwasserDE** [comment]
accept
