### ISSUE TITLE
Add Voilent Crimes x Jersy Club by ProdbyCpkShawn

### ISSUE THREAD

**Issue by LLeaHf** [FlafyDev/auto-nong-indexes#5017]
### Song Name

Voilent Crimes x Jersy Club

### Artist Name

ProdbyCpkShawn

### Source

Youtube

### Youtube Link

https://youtu.be/Z5xD6sNVabg?si=emvlFJ4iW8hcGq2D

### Song ID

181818

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 82378740
Downloaded: No

**Comment by SpuckwasserDE** [comment]
accept
