### ISSUE TITLE
Add XO (SiKkY cover) by Aaron Musslewhite 

### ISSUE THREAD

**Issue by DummyGMD** [FlafyDev/auto-nong-indexes#5065]
### Song Name

XO (SiKkY cover)

### Artist Name

Aaron Musslewhite & SiKky

### Source

Youtube

### Youtube Link

TCmswYU7ff4

### Song ID

766165

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 58825144
Downloaded: No

**Comment by SpuckwasserDE** [comment]
accept
