### ISSUE TITLE
Add Shiawase (VIP) x Syn Cole by Timka

### ISSUE THREAD

**Issue by Cosmo304** [FlafyDev/auto-nong-indexes#507]
### Song Name

Shiawase (VIP) x Syn Cole

### Artist Name

Timka

### Source

Youtube

### Youtube Link

X6ntzRC1tIo

### Song ID

1266014

### Extra

Created from Auto Nong.
Created for level: 104356905

**Comment by Cosmo304** [comment]
Accept

**Comment by SpuckwasserDE** [comment]
accept
