### ISSUE TITLE
Add GREEDY by kofukune (FIXED LINK)

### ISSUE THREAD

**Issue by LLeaHf** [FlafyDev/auto-nong-indexes#5088]
### Song Name

GREEDY

### Artist Name

kofukune

### Source

Youtube

### Youtube Link

https://youtu.be/xgF9TXmW75M?si=Youd2sOj0dmPqcGh

### Song ID

202020

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 72014998
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
reject

wrong artist name
