### ISSUE TITLE
Add Nong Song: RAAA

### ISSUE THREAD

**Issue by NocturneWC** [FlafyDev/auto-nong-indexes#5099]
### Song Name

Time Machine x Bake a Pretty Cake

### Artist Name

Waterflame

### Source

Youtube

### Youtube Link

https://youtu.be/Yn2OycGyiDg?si=8dnGlE_W-PBVtFmq

### Song ID

7

### Start Offset [ms]

0

### Extra

just time machine x bake a pretty cake
nothing else
![image_2024-10-16_005038855](https://github.com/user-attachments/assets/177ce5ef-ffdb-4f0f-a191-35352ec78245)

**Comment by SpuckwasserDE** [comment]
accept
