### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by Ffis23** [FlafyDev/auto-nong-indexes#5126]
### Song Name

Even after (by YoyleCakeMichael)

### Artist Name

Yoylecake Micheal

### Source

Youtube

### Youtube Link

https://youtu.be/nMDzc6W1Cjc?si=59Ekv__TH9rWSwlx

### Song ID

2345

**Comment by Ffis23** [comment]
accept

**Comment by Ffis123** [comment]
accept
