### ISSUE TITLE
Add Miami hotline vol.3 x Baldi: your mine 

### ISSUE THREAD

**Issue by Daepicgdplayer** [FlafyDev/auto-nong-indexes#513]
### Song Name

Miami hotline vol.3 x Baldi: your mine 

### Artist Name

Demoncity

### Source

Direct file download

### Direct File Link

https://drive.google.com/uc?export=download&id=19ETbpkT0nZYU6Wfoh1nBQaKG3fEUk_dj

### Song ID

673473

### Extra

used in hi - 25147297

**Comment by FlafyDev** [comment]
google drive links are not supported. I suggest uploading to YouTube or using an existing video from YouTube.
