### ISSUE TITLE
Add Take a slice by glass animals

### ISSUE THREAD

**Issue by ARking-eng** [FlafyDev/auto-nong-indexes#5156]
### Song Name

Take a slice

### Artist Name

glass animals

### Source

Youtube

### Youtube Link

ePXRN7O09uo

### Song ID

532686

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 110140178
Downloaded: Yes

**Comment by darwin-eng** [comment]
Bro ITS already added in auto nong
