### ISSUE TITLE
Add top 10 songs by spaul by Spaul

### ISSUE THREAD

**Issue by suslya333** [FlafyDev/auto-nong-indexes#516]
### Song Name

top 10 songs by spaul

### Artist Name

Spaul

### Source

Youtube

### Youtube Link

https://youtu.be/85MnKDnhU1o?si=RmC56b0MccFNNCY4

### Song ID

1

### Extra

Created from Auto Nong.
Created for level: 98437696

**Comment by suslya333** [comment]
accept

**Comment by IMGer4** [comment]
reject
