### ISSUE TITLE
Take a Slice by Glass Animals

### ISSUE THREAD

**Issue by darwin-eng** [FlafyDev/auto-nong-indexes#5209]
### Song Name

Take a Slice

### Artist Name

Glass Animals

### Source

Youtube

### Youtube Link

9DySfgEj1hY

### Song ID

293809

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Downloaded: Yes

**Comment by darwin-eng** [comment]
accept

**Comment by SpuckwasserDE** [comment]
accept
