### ISSUE TITLE
Add GREEDY by plasterbrain

### ISSUE THREAD

**Issue by LLeaHf** [FlafyDev/auto-nong-indexes#5212]
### Song Name

GREEDY

### Artist Name

plasterbrain

### Source

Youtube

### Youtube Link

xgF9TXmW75M

### Song ID

202020

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 72014998
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
accept
