### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by baixabiel** [FlafyDev/auto-nong-indexes#5217]
### Song Name

Hot Shit

### Artist Name

Tom Cardy

### Source

Youtube

### Youtube Link

https://youtu.be/kK0KPuH32mc?si=IoS_UU3S9Sk9tLJA

### Song ID

903405

### Start Offset [ms]

0

### Extra

I'm making a level with this song and I want other people to play it without any problems so they do not have to go to the game files and all that.

**Comment by baixabiel** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

popular songs (if used in rated levels) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
