### ISSUE TITLE
Add Nice Boys by TEMPOREX

### ISSUE THREAD

**Issue by LLeaHf** [FlafyDev/auto-nong-indexes#5246]
### Song Name

Nice Boys

### Artist Name

TEMPOREX

### Source

Youtube

### Youtube Link

https://youtu.be/1xL-GRBUNCw?si=_bfMlobCmKU3baZI

### Song ID

232323

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 61426552
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
accept
