### ISSUE TITLE
Add Slaughterhouse X Sneedle and Migul

### ISSUE THREAD

**Issue by SneedleGMD** [FlafyDev/auto-nong-indexes#529]
### Song Name

Slaughterhouse X Sneedle and Migul

### Artist Name

Sneedle and Migul

### Source

Youtube

### Youtube Link

fl1Az5ckxC0

### Song ID

945695

### Extra

Created from Auto Nong.
Created for level: 27690100

**Comment by SneedleGMD** [comment]
Ok

**Comment by SpuckwasserDE** [comment]
reject

the song is not synced, I suggest adding a delay
