### ISSUE TITLE
At The Speed of Light x Squid Game vs. MrBeast

### ISSUE THREAD

**Issue by Elznahoria** [FlafyDev/auto-nong-indexes#535]
### Song Name

At The Speed of Light x Squid Game vs. MrBeast

### Artist Name

Dimrain47 & Freshy Kanal

### Source

Direct file download

### Direct File Link

https://www.mediafire.com/file/pfnlugfvqd4zrvk/bloodbath_vs_mrbeast.mp3

### Song ID

467339

### Extra

Used in the level "Bloodbath" - 10565740

**Comment by FlafyDev** [comment]
mediafile links are not supported. I suggest uploading to YouTube or using an existing video from YouTube.
