### ISSUE TITLE
El Escuadron de la Esquina (RobertGoat & MarioRRom)

### ISSUE THREAD

**Issue by peluchecuery** [FlafyDev/auto-nong-indexes#537]
### Song Name

El Escuadron de la Esquina (RobertGoat 

### Artist Name

RobertGoat

### Source

Youtube

### Youtube Link

iSJJfr28gFOwqvQi

### Direct File Link

file:///C:/Users/Alumno/Downloads/EL%20ESCUADR%C3%93N%20DE%20LA%20ESQUINA%20(320).mp3

### Song ID

559333

### Extra

Created from Auto Nong.
Created for level: 106553503

**Comment by FlafyDev** [comment]
reject

youtube video id is invalid
