### ISSUE TITLE
Add Life Force by Rj Pasin

### ISSUE THREAD

**Issue by LLeaHf** [FlafyDev/auto-nong-indexes#5383]
### Song Name

Life Force

### Artist Name

Rj Pasin

### Source

Youtube

### Youtube Link

https://youtu.be/fJGmC4Q-qjU?si=W4d_cghHakKyUB5b

### Song ID

242424

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 76551714
Downloaded: Yes

**Comment by SpuckwasserDE** [comment]
accept
