### ISSUE TITLE
Add Time Leaper x Etzer by Hinkik

### ISSUE THREAD

**Issue by Q9769611** [FlafyDev/auto-nong-indexes#540]
### Song Name

Time Leaper x Etzer

### Artist Name

Hinkik

### Source

Youtube

### Youtube Link

https://youtu.be/giNn4BdCPw0?si=7r7ruI4rJkszZsl9

### Song ID

683996

### Extra

Created from Auto Nong.
Created for level: 24301797

**Comment by Q9769611** [comment]
Accept

**Comment by SpuckwasserDE** [comment]
accept

**Comment by Q9769611** [comment]
Awesome, thanks for the update!
