### ISSUE TITLE
Mary on a cross

### ISSUE THREAD

**Issue by adilweee** [FlafyDev/auto-nong-indexes#5415]
### Song Name

Ghost - Mary On A Cross

### Artist Name

LatinHype

### Source

Youtube

### Youtube Link

https://youtu.be/8JMMjCyyznI?si=k9KEtiL96OLgb770

### Song ID

633385

### Start Offset [ms]

0

**Comment by adilweee** [comment]
accept

**Comment by Fethi-dev** [comment]
accept
