### ISSUE TITLE
Add windows breakcore by proloxx

### ISSUE THREAD

**Issue by mossIsEdible** [FlafyDev/auto-nong-indexes#5421]
### Song Name

windows breakcore

### Artist Name

proloxx

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=AMc4kuUHmhw

### Song ID

1

### Start Offset [ms]

0

**Comment by Zee-bit-hash** [comment]
I LOVE THIS SONG PLEASE ADD IT
