### ISSUE TITLE
The Golden Drip

### ISSUE THREAD

**Issue by VicenteSayson** [FlafyDev/auto-nong-indexes#544]
### Song Name

The Golden Drip (VicenteSayson)

### Artist Name

Waterflame

### Source

Direct file download

### Direct File Link

https://drive.google.com/file/d/15jbTUT-0pL8_IG6OrANAkUIfNqcdHuA4/view?usp=drivesdk

### Song ID

638150

**Comment by FlafyDev** [comment]
google drive links are not supported. I suggest uploading to YouTube or using the video from YouTube.
