### ISSUE TITLE
XO by Aaron Musslewhite

### ISSUE THREAD

**Issue by raizuwi** [FlafyDev/auto-nong-indexes#545]
### Song Name

XO eden cover

### Artist Name

Aaron Musslewhite

### Source

Youtube

### Youtube Link

https://youtu.be/MbuP33ugiPU?si=X_W5fnz_ACdUe-Tt

### Song ID

766165

### Extra

Created from Auto Nong.
Created for level: 62195944

**Comment by IMGer4** [comment]
reject

**Comment by IMGer4** [comment]
song is in game
