### ISSUE TITLE
Add Creo-Flower X Eminem by Medved

### ISSUE THREAD

**Issue by PacificRay7** [FlafyDev/auto-nong-indexes#552]
### Song Name

Creo-Flower X Eminem

### Artist Name

Medved

### Source

Direct file download

### Direct File Link

/storage/emulated/0/Download/1132447gatekeeping (1).mp3

### Song ID

1132447

### Extra

Created from Auto Nong.
Created for level: 94358913

**Comment by FlafyDev** [comment]
can't download from your local storage...
