### ISSUE TITLE
Add Bad Apple!! (feat. nomico) by Masayoshi Minoshima

### ISSUE THREAD

**Issue by Orech2** [FlafyDev/auto-nong-indexes#5530]
### Song Name

Bad Apple!! (feat. nomico)

### Artist Name

Masayoshi Minoshima

### Source

Youtube

### Youtube Link

FtutLA63Cp8

### Song ID

521559

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 37678756
Downloaded: Yes

**Comment by SUKITCHMAN** [comment]
accept
