### ISSUE TITLE
Add Nong Song: Hot shit to the fog

### ISSUE THREAD

**Issue by baixabiel** [FlafyDev/auto-nong-indexes#5544]
### Song Name

Hot Shit

### Artist Name

Tom Cardy

### Source

Youtube

### Youtube Link

https://youtu.be/kK0KPuH32mc?si=IoS_UU3S9Sk9tLJA

### Song ID

10006547

### Extra

uhhhhhhhh pretty please?

**Comment by SergantSewerwater** [comment]
patience young one

**Comment by thegoatofgd** [comment]
patience
