### ISSUE TITLE
Add Slaughterhouse x Ton 618 by CRIM3S x Djjaner

### ISSUE THREAD

**Issue by Speedymule6858** [FlafyDev/auto-nong-indexes#5546]
### Song Name

Slaughterhouse x Ton 618

### Artist Name

CRIM3S x Djjaner

### Source

Youtube

### Youtube Link

TpTaUF1fWJo

### Song ID

945695

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 27690100
Downloaded: Yes

**Comment by SUKITCHMAN** [comment]
accept
