### ISSUE TITLE
Add Mr. Krabs' Smallest Violin (HARDCORE REMIX) by CASHEW

### ISSUE THREAD

**Issue by thecoolestboi** [FlafyDev/auto-nong-indexes#5561]
### Song Name

Mr. Krabs' Smallest Violin (HARDCORE REMIX)

### Artist Name

CASHEW

### Source

Youtube

### Youtube Link

https://youtu.be/8jJJM_WYEx0?si=Jb7NvLZg9zaOYv8h

### Song ID

1289030

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 103755492
Downloaded: Yes

**Comment by darwin-eng** [comment]
accept
