### ISSUE TITLE
Add At the Speed of Light X Thick of It by Dimrain47

### ISSUE THREAD

**Issue by JaydenOsa** [FlafyDev/auto-nong-indexes#5726]
### Song Name

At the Speed of Light X Thick of It

### Artist Name

Dimrain47

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=La2-uiI0Fl8

### Song ID

467339

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 10565740
Downloaded: No

**Comment by arthurprograma** [comment]
accept
