### ISSUE TITLE
Add lost umbrella by idk

### ISSUE THREAD

**Issue by blu010** [FlafyDev/auto-nong-indexes#579]
### Song Name

lost umbrella

### Artist Name

idk

### Source

Youtube

### Youtube Link

Y-CkTa4XJeYqF46R

### Song ID

100

### Extra

Created from Auto Nong.
Created for level: 79575024

**Comment by IMGer4** [comment]
reject

**Comment by IMGer4** [comment]
artist: "idk" please enter a valid artist
