### ISSUE TITLE
Sphere x Henk Wijngaard by Creo

### ISSUE THREAD

**Issue by JanPieter05** [FlafyDev/auto-nong-indexes#598]
### Song Name

Sphere x Henk Wijngaard

### Artist Name

Creo

### Source

Youtube

### Youtube Link

https://youtu.be/FTcyZQMTSyY?si=6uf9UFE1Yal3u8Fg

### Song ID

739991

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Creo - Sphere x Henk Wijngaard - Met de vlam in de pijp.
Created by Money01 in 2021 (improved in 2024)

**Comment by SpuckwasserDE** [comment]
accept
