### ISSUE TITLE
Celestial 

### ISSUE THREAD

**Issue by CloOoudy01** [FlafyDev/auto-nong-indexes#60]
### Song Name

Celestial 

### Artist Name

Ed sheeran

### Source

Youtube

### Youtube Link

https://m.youtube.com/watch?v=eUlA12xv8To&pp=ygUJQ2VsZXN0aWFs

### Song ID

1132447

**Comment by FlafyDev** [comment]
why replace 1132447

**Comment by SpuckwasserDE** [comment]
reject

popular songs like Creo Songs are too inconvenient to be replaced by smth unrelated and are therefore usually rejected
