### ISSUE TITLE
Artcore | NamiRyo - Aisthimata

### ISSUE THREAD

**Issue by darklordomeg** [FlafyDev/auto-nong-indexes#607]
### Song Name

Artcore | NamiRyo - Aisthimata

### Artist Name

namiryo

### Source

Youtube

### Youtube Link

https://youtu.be/nJkvPCQqeUE?si=0X9F70F13CGESa3i

### Song ID

646748

### Extra

Created from Auto Nong.
Created for level: 107052579

**Comment by darklordomeg** [comment]
i really want this to be a song i can use in gd without me having to add it

**Comment by SpuckwasserDE** [comment]
accept
