### ISSUE TITLE
Bang Bang 

### ISSUE THREAD

**Issue by Thesillyestperson** [FlafyDev/auto-nong-indexes#614]
### Song Name

Bang Bang 

### Artist Name

K'naan

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=rbRSYYPSjWc

### Song ID

640041

### Start Offset [ms]

0

### Extra

Bang Bang -13191454

**Comment by Thesillyestperson** [comment]
Accept

**Comment by FlafyDev** [comment]
accept
