### ISSUE TITLE
Add Lost (XVA remix) x world cup by crim3s

### ISSUE THREAD

**Issue by IMGer4** [FlafyDev/auto-nong-indexes#615]
### Song Name

Lost (XVA remix) x world cup

### Artist Name

crim3s

### Source

Youtube

### Youtube Link

[https://www.youtube.com/watch?v=FsiXaDwrTWg](https://www.youtube.com/watch?v=FsiXaDwrTWg)

### Direct File Link

https://www.mediafire.com/file/7x3slatwtxjfgs2/945695.mp3/file

### Song ID

945695

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 27690100
For slaughterhouse levels.

**Comment by FlafyDev** [comment]
reject

not syncing
