### ISSUE TITLE
Add Tidal Wave X Freddy Fazbear by HypnoTronic

### ISSUE THREAD

**Issue by HypnoTronicGD** [FlafyDev/auto-nong-indexes#627]
### Song Name

Tidal Wave X Freddy Fazbear

### Artist Name

HypnoTronic

### Source

Youtube

### Youtube Link

f_P-vEmBwJo

### Song ID

1266014

### Extra

Created from Auto Nong.
Created for level: 86407629

**Comment by IMGer4** [comment]
reject

**Comment by IMGer4** [comment]
stupid mashup
