### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by Imsoepiclol** [FlafyDev/auto-nong-indexes#63]
### Song Name

Estralar

### Artist Name

DJ ze pedro

### Source

Youtube

### Youtube Link

https://m.youtube.com/watch?v=gWiHro7_lZ4&pp=ygUUZXN0cmVsYXIgZGogemUgcGVkcm8%3D

### Song ID

500706

### Extra

Used in level 
Troll level

**Comment by FlafyDev** [comment]
reject

double submit
