### ISSUE TITLE
Add Troi Em Lai by Quang Hung MasterD

### ISSUE THREAD

**Issue by ItzSrIan01** [FlafyDev/auto-nong-indexes#6317]
### Song Name

Troi Em Lai

### Artist Name

Quang Hung MasterD

### Source

Youtube

### Youtube Link

jMjejVH0c8o

### Song ID

574484

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 65499570
Downloaded: No

**Comment by ItzSrIan01** [comment]
accept

**Comment by Aiosimakkkk** [comment]
accept
