### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by Imsoepiclol** [FlafyDev/auto-nong-indexes#64]
### Song Name

Estrelar

### Artist Name

DJ Ze Pedro

### Source

Youtube

### Youtube Link

https://m.youtube.com/watch?v=gWiHro7_lZ4&pp=ygUUZXN0cmVsYXIgZGogemUgcGVkcm8%3D

### Song ID

500706

### Extra

In level "Troll level"

**Comment by FlafyDev** [comment]
accept
