### ISSUE TITLE
At the speed of light

### ISSUE THREAD

**Issue by GMDJumper** [FlafyDev/auto-nong-indexes#642]
### Song Name

(New version) (remix) Dimrain47-at the speed of light

### Artist Name

DatRealWrona

### Source

Direct file download

### Direct File Link

https://www.newgrounds.com/audio/listen/847621

### Song ID

467339

### Start Offset [ms]

0

### Extra

Cataclysm-3979721, Bloodbath-10565740,Bloodlust-42584142,Aftermath-25610878

**Comment by FlafyDev** [comment]
replacing with songs on newgrounds is not supported yet
