### ISSUE TITLE
Add Nong Song: Stereo Extremeness

### ISSUE THREAD

**Issue by slideglide** [FlafyDev/auto-nong-indexes#645]
### Song Name

Stereo Madness (Geometry Dash) cover

### Artist Name

Rock CovЁr

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=QIVkourF01U

### Song ID

0 (Official Stereo Madness song)

### Extra

https://youtu.be/QIVkourF01U?t=55 video url with current time (skips non-music sections)

**Comment by comicsteel** [comment]
reject

already existed
