### ISSUE TITLE
Add Em Khong Hieu by Changg (Ft. Minh Huy)

### ISSUE THREAD

**Issue by HKJ79-GDVN** [FlafyDev/auto-nong-indexes#651]
### Song Name

Em Khong Hieu

### Artist Name

Changg (Ft. Minh Huy)

### Source

Youtube

### Youtube Link

RaKifsK2cOc

### Song ID

18

### Extra

Created from Auto Nong.
Created for level: 74054225

**Comment by HKJ79-GDVN** [comment]
accept

**Comment by HKJ79-1020** [comment]
accept

**Comment by MPixel1029** [comment]
accept

**Comment by MPixel1029** [comment]
a

**Comment by SpuckwasserDE** [comment]
reject

popular songs like Geometrical Dominator are too inconvenient to be replaced by smth unrelated and are therefore usually rejected
