### ISSUE TITLE
Add Nong Song: Vierre cloud - Moment

### ISSUE THREAD

**Issue by Jkane01** [FlafyDev/auto-nong-indexes#669]
### Song Name

Moment

### Artist Name

Vierre Cloud

### Source

Direct file download

### Direct File Link

https://mp3uk-download2-dl4.ast-info.ru/downloadsong/id12303

### Song ID

526067

**Comment by FlafyDev** [comment]
file hosting links are not supported. I suggest uploading it to YouTube or using the original song from YouTube
