### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by Iwiey** [FlafyDev/auto-nong-indexes#689]
### Song Name

Creo-Idolize x KanYe West

### Artist Name

Creo/Kanye west

### Source

Direct file download

### Direct File Link

https://www.mediafire.com/file/4b7paxn48uqtw5o/829777.mp3/file

### Song ID

829777

### Start Offset [ms]

Ex. 0

### Extra

The mashup starts at 155.9 offset

**Comment by FlafyDev** [comment]
mediafire links are not supported. I suggest uploading it to YouTube or using the original song from YouTube
