### ISSUE TITLE
Add funk hole by destroid

### ISSUE THREAD

**Issue by MiguelD1514A** [FlafyDev/auto-nong-indexes#705]
### Song Name

funk hole

### Artist Name

destroid

### Source

Youtube

### Youtube Link

https://youtu.be/IWrZ0t185z0?si=BH4vrq8Gq9JED46W

### Direct File Link

https://youtu.be/IWrZ0t185z0?si=BH4vrq8Gq9JED46W

### Song ID

1

### Extra

Created from Auto Nong.
Created for level: 98437696

**Comment by IMGer4** [comment]
reject
