### ISSUE TITLE
Add Lycanthropy by ICardi

### ISSUE THREAD

**Issue by ForsakenEnder** [FlafyDev/auto-nong-indexes#716]
### Song Name

Lycanthropy

### Artist Name

ICardi

### Source

Youtube

### Youtube Link

4joh_k8BMkc

### Song ID

366026

### Extra

Created from Auto Nong.
Created for level: 107137624

**Comment by ForsakenEnder** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

popular songs like this one (used in shiver for example) are too inconvenient to be replaced by smth unrelated and are therefore usually rejected
