### ISSUE TITLE
Add onimai ost by enako

### ISSUE THREAD

**Issue by Xkcal** [FlafyDev/auto-nong-indexes#717]
### Song Name

onimai ost

### Artist Name

enako

### Source

Youtube

### Youtube Link

6OfPUWfbUFHdxrg0

### Song ID

250123

### Extra

Created from Auto Nong.
Created for level: 88463014

**Comment by Xkcal** [comment]
accept

2024년 6월 29일 (토) 오전 9:33, auto-nong[bot] ***@***.***>님이 작성:

**Comment by Xkcal** [comment]
Yes, I am working on it.

2024년 7월 13일 (토) 오후 9:41, github-actions[bot] ***@***.***>님이
작성:

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
