### ISSUE TITLE
Add Shiawase (VIP) Low Quality  by Dion Timmer

### ISSUE THREAD

**Issue by Ravz-oss** [FlafyDev/auto-nong-indexes#726]
### Song Name

Shiawase (VIP) Low Quality 

### Artist Name

Dion Timmer

### Source

Youtube

### Youtube Link

0zmE65ptla4

### Direct File Link

https://www.youtube.com/watch?v=0zmE65ptla4&t=25s

### Song ID

1266014

### Extra

Created from Auto Nong.
Created for level: 104356905

**Comment by IMGer4** [comment]
bad remix

**Comment by IMGer4** [comment]
reject
