### ISSUE TITLE
Add Chungus Blaster by sSolsta

### ISSUE THREAD

**Issue by WhirlPloof** [FlafyDev/auto-nong-indexes#727]
### Song Name

Chungus Blaster

### Artist Name

sSolsta

### Source

Youtube

### Youtube Link

GMTj_CnOk116Ts2_

### Song ID

574484

### Extra

Created from Auto Nong.
Created for level: 26681070

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
