### ISSUE TITLE
Wasted for Murkish & Hukin

### ISSUE THREAD

**Issue by xneri** [FlafyDev/auto-nong-indexes#728]
### Song Name

WASTED (murkish & huken nightcore remix)

### Artist Name

Juice WRLD, Lil Uzi Vert

### Source

Youtube

### Youtube Link

https://youtu.be/-UHnOA3Caww?si=yBvb2Nh_8eooCRd1

### Song ID

1199528

### Extra

Used in the level "W A S T E D"
92979046

**Comment by xneri** [comment]
accept

**Comment by SpuckwasserDE** [comment]
accept
