### ISSUE TITLE
Seventeen by (Haruka To Miyuki) (Spyagent) 

### ISSUE THREAD

**Issue by rolly-james** [FlafyDev/auto-nong-indexes#730]
### Song Name

Seventeen

### Artist Name

Haruka To Miyuki

### Source

Youtube

### Youtube Link

kXyVa2XgUvqUenMv

### Song ID

711933

### Extra

Created from Auto Nong.
Created for level: 104414842

**Comment by rolly-james** [comment]
This is the one of my favorite song so I make a nong song to this because I want to make a level using this song ;)

**Comment by rolly-james** [comment]
How long is this gonna verified? Or is this already verified?

**Comment by SpuckwasserDE** [comment]
reject

the YouTube link doesn't work
