### ISSUE TITLE
Add oyasumi german by Lunywoo

### ISSUE THREAD

**Issue by aaxaxaxaxaxaxaxaxxaxaxaxaxaxa** [FlafyDev/auto-nong-indexes#731]
### Song Name

oyasumi german

### Artist Name

Lunywoo

### Source

Youtube

### Youtube Link

https://youtu.be/lLmsPpwGfnc?si=k1LwQmRFqVW9ueyS

### Song ID

292929

### Extra

Created from Auto Nong.
Created for level: 105007780

**Comment by SpuckwasserDE** [comment]
reject

already exists
