### ISSUE TITLE
Add Freedom Dive by XI

### ISSUE THREAD

**Issue by AJXPRO** [FlafyDev/auto-nong-indexes#734]
### Song Name

Freedom Dive

### Artist Name

XI

### Source

Youtube

### Youtube Link

s-j6_RjuYkXlOdax

### Song ID

735623

### Extra

Created from Auto Nong.
Created for level: 99415706

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link

**Comment by AJXPRO** [comment]
Ok, I didn't realize, sorry I put it now
