### ISSUE TITLE
NONG HYPE

### ISSUE THREAD

**Issue by Rafamarq13** [FlafyDev/auto-nong-indexes#747]
### Song Name

HYPE

### Artist Name

TOKYO MACHINE

### Source

Youtube

### Youtube Link

https://youtu.be/N17omU8oykU?si=NF9YTH79lYmqDvGj

### Song ID

621134

### Extra

Usado no nível "Unity"

**Comment by SpuckwasserDE** [comment]
reject

Unity is a very popular song and replacing it with smth unrelated is only possible if the nong at least syncs well enough, which is not the case with this one
