### ISSUE TITLE
Seventeen by (Haruka To Miyuki)

### ISSUE THREAD

**Issue by rolly-james** [FlafyDev/auto-nong-indexes#749]
### Song Name

Seventeen

### Artist Name

Haruka To Miyuki

### Source

Youtube

### Youtube Link

r_6aeTZTqjTuciHp

### Song ID

711933

### Extra

Created from Auto Nong.
Created for level: 104414842

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
