### ISSUE TITLE
Add Sakupen Circles X Ganstas Paradise by DrCuber

### ISSUE THREAD

**Issue by felixdash1** [FlafyDev/auto-nong-indexes#756]
### Song Name

Sakupen Circles X Ganstas Paradise

### Artist Name

DrCuber

### Source

Youtube

### Youtube Link

F2OOpfRjkkg

### Song ID

360804

### Extra

Created from Auto Nong.
Created for level: 45226035

**Comment by Wildethingz** [comment]
Accept

**Comment by comicsteel** [comment]
reject

already existed
