### ISSUE TITLE
Lost (XVA Remix) x World Cup Mashup (FIXED)

### ISSUE THREAD

**Issue by Firzo** [FlafyDev/auto-nong-indexes#76]
### Song Name

Lost (XVA Remix) x World Cup Mashup

### Artist Name

AidanTR

### Source

Direct file download

### Direct File Link

https://www.mediafire.com/file/7x3slatwtxjfgs2/945695.mp3/file

### Song ID

945695

### Extra

Used in the level "Slaughterhouse" - 27690100

**Comment by FlafyDev** [comment]
reject

mediafire is not supported. upload to youtube or use an existing youtube video.
