### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by IcyuGD** [FlafyDev/auto-nong-indexes#766]
### Song Name

Universe Blaster

### Artist Name

F-777

### Source

Youtube

### Youtube Link

https://m.youtube.com/watch?v=Tv27z_lygTE&pp=ygURIGluZmluaXR5IGJsYXN0ZXI%3D 

### Song ID

574484

### Extra

Used for Sonic Wave or variants (Infinity, Rebirth, etc)

**Comment by comicsteel** [comment]
reject

f777 didnt create this mashup, the artist should be the name of the video uploader
