### ISSUE TITLE
Add Nong Song: space battle remix

### ISSUE THREAD

**Issue by Shineevee** [FlafyDev/auto-nong-indexes#767]
### Song Name

Space battle (maze remix v2)

### Artist Name

Maze Master002

### Source

Youtube

### Youtube Link

https://youtu.be/7UWBme1R8Zc?si=-DLq4xA9Q2sXAB0F

### Song ID

661012

### Extra

Used in the level OuterSpace of the fire gauntlet

**Comment by AlwaysJolly** [comment]
reject // The video you have linked is incorrect, I believe you meant to link [this song](https://www.youtube.com/watch?v=a5UW0gGQSUk), however what you have linked is the first Attack on Titan opening with Spanish subtitles.
