### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by kasitosasaaaaa** [FlafyDev/auto-nong-indexes#771]
### Song Name

Dreams 4Ever (Cancion de Alicia)

### Artist Name

Bad Influence

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=7HRJGvVLyYs

### Song ID

95

**Comment by kasitosasaaaaa** [comment]
accept

**Comment by comicsteel** [comment]
reject

should contain an id of the level that syncs with the song
