### ISSUE TITLE
Add specialz by tvoya mama

### ISSUE THREAD

**Issue by IGIZIG1** [FlafyDev/auto-nong-indexes#774]
### Song Name

specialz

### Artist Name

King gnu

### Source

Youtube

### Youtube Link

https://youtu.be/5yb2N3pnztU?si=KeeWYwm3ZfEEIY3U

### Song ID

22

### Extra

Created from Auto Nong.
Created for level: 100860730

**Comment by comicsteel** [comment]
reject

already existed
