### ISSUE TITLE
Add Venta Black by Leon Riskin

### ISSUE THREAD

**Issue by Technostorm313** [FlafyDev/auto-nong-indexes#778]
### Song Name

Venta Black

### Artist Name

Leon Riskin

### Source

Youtube

### Youtube Link

https://youtu.be/yiHfvsUsj5c?si=LellrrdpFsWWxV7m

### Song ID

1

### Extra

Created from Auto Nong.
Created for level: 107216500

**Comment by IMGer4** [comment]
reject
