### ISSUE TITLE
Add Kami no Kotoba by Luschka

### ISSUE THREAD

**Issue by ivanspofy** [FlafyDev/auto-nong-indexes#783]
### Song Name

Kami no Kotoba

### Artist Name

Luschka

### Source

Direct file download

### Direct File Link

https://drive.google.com/file/d/1ds2fVvqPkpCM6iHod8lCw75ieudBjrSz/view?usp=drivesdk

### Song ID

509162

### Extra

Created from Auto Nong.
Created for level: 64658786

**Comment by FlafyDev** [comment]
google drive links are not supported. I suggest uploading it to YouTube or using the original song from YouTube
