### ISSUE TITLE
Add Centipede by Knife Party

### ISSUE THREAD

**Issue by ivanspofy** [FlafyDev/auto-nong-indexes#785]
### Song Name

Centipede

### Artist Name

Knife Party

### Source

Direct file download

### Direct File Link

https://drive.google.com/file/d/12OLrehTa3nQk9trIdza7n_HuXfjwPcIH/view

### Song ID

1306366

### Extra

Created from Auto Nong.
Created for level: 106646765

**Comment by FlafyDev** [comment]
google drive links are not supported. I suggest uploading it to YouTube or using the original song from YouTube
