### ISSUE TITLE
Secret Club

### ISSUE THREAD

**Issue by Space-34** [FlafyDev/auto-nong-indexes#8]
### Song Name

Clubstep (VIP)

### Artist Name

dj-Nate

### Source

Youtube

### Youtube Link

https://youtu.be/BkMBpGVVqzQ?si=IJIYrEYFtft13zxR

### Song ID

13

**Comment by FlafyDev** [comment]
isn't the name "Clubstep (VIP)" ? Where is "Secret Club" from?

**Comment by elnexreal** [comment]
accept

**Comment by elnexreal** [comment]
reverted it because the song was out of sync
