### ISSUE TITLE
Vacation

### ISSUE THREAD

**Issue by DragosDobrican** [FlafyDev/auto-nong-indexes#80]
### Song Name

Vacation

### Artist Name

Dirty heads

### Source

Youtube

### Youtube Link

https://youtu.be/S3kIwRsSF_8?si=6RENAVKdrhFCKqI7

### Song ID

2586

**Comment by FlafyDev** [comment]
why 2586?

**Comment by FlafyDev** [comment]
reject

No valid resson to use the song id I think
