### ISSUE TITLE
Add Epilogue (Low pitch) by Creo

### ISSUE THREAD

**Issue by Diinkinity** [FlafyDev/auto-nong-indexes#803]
### Song Name

Zodiac (Low Pitch)

### Artist Name

Creo

### Source

Youtube

### Youtube Link

uD3nIUwFkuo

### Direct File Link

https://www.sphere.com/song.mp3

### Song ID

739991

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 52374843

**Comment by Draogn12345678** [comment]
accept
