### ISSUE TITLE
Pikito

### ISSUE THREAD

**Issue by ZcoofGF** [FlafyDev/auto-nong-indexes#805]
### Song Name

Pikito

### Artist Name

Rusowsky

### Source

Youtube

### Youtube Link

https://youtu.be/DPqULcZXuGE?si=SQFlQftnPd8HYq6l

### Direct File Link

ve39.aadika.xyz

### Song ID

19280

### Start Offset [ms]

0

### Extra

106892929

**Comment by ZcoofGF** [comment]
accept

**Comment by SpuckwasserDE** [comment]
accept
