### ISSUE TITLE
Add Final Battle x Skibidi Toilet by Waterflame

### ISSUE THREAD

**Issue by PanicArsons** [FlafyDev/auto-nong-indexes#810]
### Song Name

Final Battle x Skibidi Toilet

### Artist Name

Waterflame

### Source

Youtube

### Youtube Link

6mZhDHvpvD8

### Song ID

598349

### Extra

Created from Auto Nong.
Created for level: 5155022

**Comment by Wildethingz** [comment]
Accept

**Comment by Wildethingz** [comment]
Reject: Youtube video does not work
