### ISSUE TITLE
Add Intro by Junior H

### ISSUE THREAD

**Issue by VotiveManxs** [FlafyDev/auto-nong-indexes#819]
### Song Name

Intro

### Artist Name

Junior H

### Source

Youtube

### Youtube Link

https://youtu.be/y3JcRIfX5Ao?si=1kGAPi-y7BkD7CfJ

### Song ID

613929

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 98867102

**Comment by VotiveManxs** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Dance of the Violins" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected
