### ISSUE TITLE
Iron God Sakupen Hell Yes Rmx X Gangstas Paradise

### ISSUE THREAD

**Issue by Emizut** [FlafyDev/auto-nong-indexes#822]
### Song Name

Iron God Sakupen Hell Yes Rmx X Gangstas Paradise

### Artist Name

mr-jazzman

### Source

Youtube

### Youtube Link

LzyGOm8qLvCon7z9

### Song ID

360804

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 23262780

**Comment by Wildethingz** [comment]
Reject 
Youtube video does not work
