### ISSUE TITLE
Add Iron god Sakupen hell Rmx X Gangstas Paradise by mr-jazzman

### ISSUE THREAD

**Issue by Emizut** [FlafyDev/auto-nong-indexes#823]
### Song Name

Iron god Sakupen hell Rmx X Gangstas Paradise

### Artist Name

mr-jazzman

### Source

Youtube

### Youtube Link

LzyGOm8qLvCon7z9

### Song ID

360804

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 23262780

**Comment by Daepicgdplayer** [comment]
The youtube video isn't up anymore, can you re-upload it and make a new issue?

**Comment by Daepicgdplayer** [comment]
reject The youtube video isn't up anymore, can you re-upload it and make a new issue?
