### ISSUE TITLE
Add Creator by Lena Raine

### ISSUE THREAD

**Issue by spacecat1505** [FlafyDev/auto-nong-indexes#825]
### Song Name

Creator

### Artist Name

Lena Raine

### Source

Youtube

### Youtube Link

LdPL0a165dcaS5Tl

### Song ID

10005436

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 100157619

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
