### ISSUE TITLE
End me by Suicidal Idol

### ISSUE THREAD

**Issue by MinusEpix** [FlafyDev/auto-nong-indexes#826]
### Song Name

End me

### Artist Name

Suicidal Idol

### Source

Youtube

### Youtube Link

IOANzaKqjH1DH7C3

### Song ID

587069

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 2997354
It literally syncs at the slow part

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
