### ISSUE TITLE
Add Rush D by Sheet Music Boss

### ISSUE THREAD

**Issue by DanybossGD** [FlafyDev/auto-nong-indexes#829]
### Song Name

Rush D

### Artist Name

Sheet Music Boss

### Source

Youtube

### Youtube Link

IVK_KPTC7xc

### Song ID

67864

### Start Offset [ms]

9000

### Extra

Created from Auto Nong.
Created for level: 84202584

**Comment by SpuckwasserDE** [comment]
accept
