### ISSUE TITLE
Add Rush B by Sheet Music Boss

### ISSUE THREAD

**Issue by DanybossGD** [FlafyDev/auto-nong-indexes#830]
### Song Name

Rush B

### Artist Name

Sheet Music Boss

### Source

Youtube

### Youtube Link

5zo7BYoaqAA

### Song ID

571236

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 101324845

**Comment by SpuckwasserDE** [comment]
accept
