### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by LorenzOFFICIAL1111** [FlafyDev/auto-nong-indexes#833]
### Song Name

Close eyes

### Artist Name

Dxrt

### Source

Youtube

### Youtube Link

https://youtu.be/ao4RCon11eY?si=Ntgwu5hWbV1iPzUk

### Song ID

88

**Comment by SpuckwasserDE** [comment]
reject

sorry, but the artist is called DVRST
if you think this was a mistake on my end please message @spuckwasser.de on Discord
