### ISSUE TITLE
Add STAGER by Ras again and delete old nongs

### ISSUE THREAD

**Issue by LuqFur** [FlafyDev/auto-nong-indexes#834]
### Song Name

STAGER

### Artist Name

Ras

### Source

Direct file download

### Direct File Link

https://drive.google.com/file/d/1Z4WcB_h8pmZ6KzZJsuptD0onNADh-RdL/view?usp=drive_link

### Song ID

1241510

### Start Offset [ms]

0

### Extra

created for level 104294785, STAGER ALWAYS CLEAR by LuqFur
also delete all other nongs of this song pls, I changed the replacement song so those don't work anymore
tysm!!

**Comment by LuqFur** [comment]
also, forgot to mention just in case: I had to cut the audio file to sync it to the replacement song, so it isn't 100% the original song but it works with my level.

**Comment by FlafyDev** [comment]
google drive links are not supported. I suggest uploading it to YouTube or using the original song from YouTube and changing the start offset to sync it

**Comment by LuqFur** [comment]
would a discord file link work? or what other way could I use the original file? i tried using the youtube link locally and it added delay to the song

**Comment by FlafyDev** [comment]
you can adjust the delay with the start offset property

**Comment by LuqFur** [comment]
i know, but i still prefered to use the original audio file to keep the exact same file (and offset) from the song in the gd song file hub.
anyways, this youtube link should work with offset 0, I already tried it out and changed the offset myself.
https://youtu.be/GWJtmovgfEw
if necesary lmk and I'll create a new thread for it

**Comment by FlafyDev** [comment]
yeah create a new submission. you can do it through the mod too
