### ISSUE TITLE
Regulate (j period remix) by Nate Dogg, J.Period

### ISSUE THREAD

**Issue by modestlettuce** [FlafyDev/auto-nong-indexes#839]
### Song Name

Regulate (j period remix)

### Artist Name

Nate Dogg, J.Period

### Source

Youtube

### Youtube Link

QRVTuVBBJUk

### Song ID

598349

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 5155022

**Comment by SpuckwasserDE** [comment]
reject

final battle by waterflame is too popular to be replaced with an unrelated song
