### ISSUE TITLE
Add Through The Fire and Flames by DragonForce

### ISSUE THREAD

**Issue by cdjohnson3** [FlafyDev/auto-nong-indexes#851]
### Song Name

Through The Fire and Flames

### Artist Name

DragonForce

### Source

Youtube

### Youtube Link

DZyYapMZSec

### Song ID

533927

### Extra

Created from Auto Nong.
Created for level: 73977718

**Comment by SpuckwasserDE** [comment]
reject

song has nothing to do with nine circles, which is too popular to serve as the replaced song
