### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by Fruitfulz** [FlafyDev/auto-nong-indexes#852]
### Song Name

Jumper x Hello

### Artist Name

Waterflame & OMFG

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=Z_WrSy2muHs

### Song ID

-6

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

adjust the song id to 6 instead of -6
