### ISSUE TITLE
Add BAZOOKA - Doi Saci de Gunoi (Video Oficial) by codrin bradea satana

### ISSUE THREAD

**Issue by angrywonc** [FlafyDev/auto-nong-indexes#854]
### Song Name

BAZOOKA - Doi Saci de Gunoi (Video Oficial)

### Artist Name

codrin bradea satana

### Source

Youtube

### Youtube Link

plvh_E2Q0jPHmFEx

### Song ID

134270

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 10229235

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
