### ISSUE TITLE
Add SUPERHATEMEWORLD x Feel Good by EDENLEFT

### ISSUE THREAD

**Issue by Bodysz** [FlafyDev/auto-nong-indexes#856]
### Song Name

SUPERHATEMEWORLD x Feel Good

### Artist Name

EDENLEFT

### Source

Youtube

### Youtube Link

4IWGnTGFzCM

### Song ID

1135860

### Start Offset [ms]

58

### Extra

Created from Auto Nong.
Created for level: 57571983

**Comment by Bodysz** [comment]
yoo

**Comment by SpuckwasserDE** [comment]
reject 

mashups should have some popularity to show that people want it.
Note that you can still use the nong yourself, but it wont be
