### ISSUE TITLE
Add no more parties in L.A. by Kanye West, Kendrick Lamar

### ISSUE THREAD

**Issue by v3rtual** [FlafyDev/auto-nong-indexes#858]
### Song Name

no more parties in L.A.

### Artist Name

Kanye West, Kendrick Lamar

### Source

Youtube

### Youtube Link

NnMuFqsmYSE

### Song ID

1090791

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 99371148

**Comment by SpuckwasserDE** [comment]
accept
