### ISSUE TITLE
Add Electroman Adventures (SARY NEVER CLEAR) by Robvatopper

### ISSUE THREAD

**Issue by ultragay-bacon** [FlafyDev/auto-nong-indexes#863]
### Song Name

Electroman Adventures (SARY NEVER CLEAR)

### Artist Name

Robvatopper

### Source

Youtube

### Youtube Link

mijQG001w7bIWp9d

### Song ID

123263

### Start Offset [ms]

0

### Extra

Created from Auto Nong.

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
