### ISSUE TITLE
Add specialz by king gnu

### ISSUE THREAD

**Issue by IGIZIG1** [FlafyDev/auto-nong-indexes#864]
### Song Name

specialz

### Artist Name

King gnu

### Source

Youtube

### Youtube Link

https://youtu.be/5yb2N3pnztU?si=ww8oUbBZMjH_wMvS

### Song ID

22

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 96398623

**Comment by SpuckwasserDE** [comment]
accept
