### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by albal-arch** [FlafyDev/auto-nong-indexes#867]
### Song Name

Grazhdanskaya Oborona - Lunar Abyss

### Artist Name

levanfors (Egor Letov x LCHAVASSE)

### Source

Youtube

### Youtube Link

https://youtu.be/qjb3G2_K-bE?si=B9PL2hmI3xvrsM5Z

### Song ID

645631

### Start Offset [ms]

0

### Extra

Duelo Maestro

**Comment by SpuckwasserDE** [comment]
reject

this sounds horrible and the songs don't fit together at all
