### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by Fruitfulz** [FlafyDev/auto-nong-indexes#869]
### Song Name

Jumper x Hello

### Artist Name

Waterflame & OMFG

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=Z_WrSy2muHs

### Song ID

6

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
why do I like it so much tho...

**Comment by SpuckwasserDE** [comment]
accept
