### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by Leatsyke** [FlafyDev/auto-nong-indexes#87]
### Song Name

Clubstep X Crank That (Soulja Boy)

### Artist Name

dj-Nate

### Source

Direct file download

### Direct File Link

https://drive.google.com/uc?export=download&id=1xOxWlPJ1UvEIQgvfYhtLiInhILzfWGHj

### Song ID

Clubstep

**Comment by FlafyDev** [comment]
reject

google drive is not supported. use an existing youtube video or upload the audio as a yt video
