### ISSUE TITLE
Add moonlight by ..

### ISSUE THREAD

**Issue by MaxThumbwood** [FlafyDev/auto-nong-indexes#870]
### Song Name

moonlight

### Artist Name

Krlx

### Source

Youtube

### Youtube Link

wxXhzomDakfBCV5n

### Song ID

593046

### Extra

Created from Auto Nong.
Created for level: 104633179

**Comment by MaxThumbwood** [comment]
Accept

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
