### ISSUE TITLE
Add Travis Scott - SICKO MODE ft. Drake by Travis Scott

### ISSUE THREAD

**Issue by angrywonc** [FlafyDev/auto-nong-indexes#873]
### Song Name

Travis Scott - SICKO MODE ft. Drake

### Artist Name

TravisScott

### Source

Youtube

### Youtube Link

b3dE3lCRS2zzK7a7

### Song ID

533927

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 4284013

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
