### ISSUE TITLE
Add Nong Song: Step - Polargeist REMIX

### ISSUE THREAD

**Issue by YassirTahriYT** [FlafyDev/auto-nong-indexes#874]
### Song Name

Step - Polargeist REMIX - for Geometry Dash

### Artist Name

Fendroca

### Source

Youtube

### Youtube Link

www.youtube.com/watch?v=_LlJScME4w4&

### Song ID

2

### Start Offset [ms]

0

### Extra

This is used in the level "Extremegeist" by Vortrox, "The Nightmare" by Jax, and could be also used in YouTube videos to help content creators find remixes easily instead of looking for them online.

**Comment by SpuckwasserDE** [comment]
reject

song is off sync (which means you need to adjust the offset)
