### ISSUE TITLE
Add Lucy VIP (Elfen Lied) by Vespar

### ISSUE THREAD

**Issue by StayVis** [FlafyDev/auto-nong-indexes#879]
### Song Name

Lucy VIP (Elfen Lied)

### Artist Name

Vespar

### Source

Youtube

### Youtube Link

nZ_wr06K058

### Song ID

636526

### Start Offset [ms]

0

### Extra

stanears
Created from Auto Nong.
Created for level: 48506815

**Comment by SpuckwasserDE** [comment]
accept
