### ISSUE TITLE
Add It Burns! Burns! Burns! by Loco Loco

### ISSUE THREAD

**Issue by StayVis** [FlafyDev/auto-nong-indexes#880]
### Song Name

It Burns! Burns! Burns!

### Artist Name

Loco Loco

### Source

Youtube

### Youtube Link

rBhbxVmolTE

### Song ID

666666

### Start Offset [ms]

0

### Extra

stanears
Created from Auto Nong.
Created for level: 100713793

**Comment by SpuckwasserDE** [comment]
accept
