### ISSUE TITLE
Add Gg by bad pigges

### ISSUE THREAD

**Issue by dortinnrebalans** [FlafyDev/auto-nong-indexes#882]
### Song Name

Gg

### Artist Name

bad pigges

### Source

Youtube

### Youtube Link

7W64lZIs0aV3Wq1S

### Song ID

1021189

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 95832772

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
