### ISSUE TITLE
Add veseley by song for Dima Kuplinov

### ISSUE THREAD

**Issue by dortinnrebalans** [FlafyDev/auto-nong-indexes#885]
### Song Name

veseley

### Artist Name

song for Dima Kuplinov

### Source

Youtube

### Youtube Link

fjmEguGDXtHeXvuk

### Song ID

0

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 93863703

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
