### ISSUE TITLE
Add Shiawase by Dion Timmer

### ISSUE THREAD

**Issue by CharlGD1** [FlafyDev/auto-nong-indexes#889]
### Song Name

Shiawase

### Artist Name

Dion Timmer

### Source

Youtube

### Youtube Link

ACX8jwUFZlo

### Song ID

1266014

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 100152198

**Comment by SpuckwasserDE** [comment]
reject

duplicate request, already accepted
