### ISSUE TITLE
Add best mashap by rar file

### ISSUE THREAD

**Issue by dortinnrebalans** [FlafyDev/auto-nong-indexes#892]
### Song Name

best mashap

### Artist Name

rar file

### Source

Youtube

### Youtube Link

TC3n-AZmqA_mOrxz

### Direct File Link

https://youtu.be/RGBObaubw1A?si=TC3n-AZmqA_mOrxz

### Song ID

770520

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 73667628

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
