### ISSUE TITLE
Add song for Dima Kuplinov by veseley

### ISSUE THREAD

**Issue by dortinnrebalans** [FlafyDev/auto-nong-indexes#895]
### Song Name

song for Dima Kuplinov

### Artist Name

veseley

### Source

Youtube

### Youtube Link

fjmEguGDXtHeXvuk

### Direct File Link

https://youtu.be/UrfYbQ9Vtvo?si=fjmEguGDXtHeXvuk

### Song ID

0

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 93863703

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
