### ISSUE TITLE
Add Nightmare by plenka

### ISSUE THREAD

**Issue by dortinnrebalans** [FlafyDev/auto-nong-indexes#897]
### Song Name

Nightmare

### Artist Name

plenka

### Source

Youtube

### Youtube Link

omzDgQ-lnfKdHccu

### Direct File Link

https://youtu.be/-6LAjAp-XfU?si=omzDgQ-lnfKdHccu

### Song ID

-13

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 96024475

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
