### ISSUE TITLE
 Bailan Rochas y Chetas by Nene Malo

### ISSUE THREAD

**Issue by ZithroX** [FlafyDev/auto-nong-indexes#899]
### Song Name

Bailan Rochas y Chetas

### Artist Name

Nene Malo

### Source

Youtube

### Youtube Link

https://youtu.be/ebmes8Ci7_0?si=wZrnyKhetHFFM9qO

### Song ID

56

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 95068752

**Comment by ZithroX** [comment]
I would like to see this song being added

**Comment by SpuckwasserDE** [comment]
accept
