### ISSUE TITLE
Add skibidi x acropolis by cursed

### ISSUE THREAD

**Issue by johnnyfoot12** [FlafyDev/auto-nong-indexes#900]
### Song Name

skibidi x acropolis

### Artist Name

cursed

### Source

Youtube

### Youtube Link

7NXZlmimGUGS9Ssj

### Song ID

598349

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 5155022

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
