### ISSUE TITLE
Add Rhythm hell by ***

### ISSUE THREAD

**Issue by Ramos989** [FlafyDev/auto-nong-indexes#904]
### Song Name

Rhythm hell

### Artist Name

Deluxe12

### Source

Youtube

### Youtube Link

https://youtu.be/3-0tmbWfL-I?si=D1xjYX078OEnfZw2

### Song ID

1213840

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 90609201

**Comment by SpuckwasserDE** [comment]
reject

the delay is wrong making the level unsynced
