### ISSUE TITLE
Add Curious light by LSPLASH

### ISSUE THREAD

**Issue by Rodialont** [FlafyDev/auto-nong-indexes#912]
### Song Name

Curious light

### Artist Name

LSPLASH

### Source

Youtube

### Youtube Link

hGhFETQxHiI

### Song ID

771277

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 89201076

**Comment by SpuckwasserDE** [comment]
reject

creo songs are too pupular to be replaced by smth unrelated
