### ISSUE TITLE
Add Whats A Future Funk? X Smash Mouth by LemKuuja

### ISSUE THREAD

**Issue by KitGD** [FlafyDev/auto-nong-indexes#913]
### Song Name

Whats A Future Funk? X Smash Mouth

### Artist Name

LemKuuja

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=VLy5cI28vHQ

### Song ID

701013

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 44062068

**Comment by SpuckwasserDE** [comment]
reject

delay is wrong making the level unsynced
