### ISSUE TITLE
 * 3 *7lucjlo0t6 by EUPHXRIA

### ISSUE THREAD

**Issue by 1Reix1** [FlafyDev/auto-nong-indexes#918]
### Song Name

* 3 *7lucjlo0t6

### Artist Name

EUPHXRIA

### Source

Youtube

### Youtube Link

IR2kd_kDD7sdtjnF

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 102688428

**Comment by 1Reix1** [comment]
I hope this sound is accepted :)

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
