### ISSUE TITLE
Add Nong Song: DEVIL IS A LIE

### ISSUE THREAD

**Issue by brbggd** [FlafyDev/auto-nong-indexes#919]
### Song Name

DEVIL IS A LIE

### Artist Name

Tommy Richman

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=SMvmAWECT8U

### Song ID

500476

### Start Offset [ms]

0

### Extra

Used to replace stereo madness because that shit aint madness its mad ass😭🙏

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "Stereo Madness" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected.
Note that you can still use the song yourself, but it won't be public
