### ISSUE TITLE
Add ColBreaks - 2011 /// (Spider Gang - F.A.N.U. Mashup) by ColBreaks / Spider Gang

### ISSUE THREAD

**Issue by BrumBerBli** [FlafyDev/auto-nong-indexes#920]
### Song Name

ColBreaks - 2011 /// (Spider Gang - F.A.N.U. Mashup)

### Artist Name

ColBreaks / Spider Gang

### Source

Direct file download

### Song ID

700211

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 28225110

**Comment by SpuckwasserDE** [comment]
reject

no link provided
