### ISSUE TITLE
Add Kocmoc unleashed(cover) by Killoway

### ISSUE THREAD

**Issue by Nikitabz2014** [FlafyDev/auto-nong-indexes#923]
### Song Name

Kocmoc unleashed(cover)

### Artist Name

Killoway

### Source

Youtube

### Youtube Link

ioXKzmMcyao

### Direct File Link

https://drive.google.com/file/d/1vdEmO1kEXQRmsnob_rtG1i0FagyDQJHm/view?pli=1

### Song ID

6666

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 75179605

**Comment by Nikitabz2014** [comment]
accept

ср, 3 июл. 2024 г., 10:04 auto-nong[bot] ***@***.***>:

**Comment by LousyBook-01** [comment]
accept

very cool @Nikitabz2014
