### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by Nestor360gd** [FlafyDev/auto-nong-indexes#926]
### Song Name

Dash & Strike

### Artist Name

Hironobu Kageyama 

### Source

Youtube

### Youtube Link

https://youtu.be/LXqVftthXN0?si=Dm3rforEkuAqjI_C

### Direct File Link

https://www.mediafire.com/file/motpfsdiaj293tv/Dash_Strike%2528MP3_320K%2529.mp3/file

### Song ID

125

### Extra

Used in the level: Dash And Strike

**Comment by LousyBook-01** [comment]
accept
