### ISSUE TITLE
Add Sonic Blaster x Gas Gas Gas by FullSound

### ISSUE THREAD

**Issue by einXYZ** [FlafyDev/auto-nong-indexes#928]
### Song Name

Sonic Blaster x Gas Gas Gas

### Artist Name

FullSound

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=_eAJV75L_U0&ab_channel=FullSound

### Song ID

574484

### Start Offset [ms]

0

### Extra

The mashup covers the whole song, so every Sonic Blaster level can use it.

**Comment by SpuckwasserDE** [comment]
accept
