### ISSUE TITLE
Add Climax x Mecha by SmK

### ISSUE THREAD

**Issue by Tuga64** [FlafyDev/auto-nong-indexes#929]
### Song Name

Climax x Mecha

### Artist Name

SmK

### Source

Direct file download

### Youtube Link

NMGeVV26mBA

### Direct File Link

https://www.mediafire.com/file/vc25lbkmvyh3iys/495840.MP3/file

### Song ID

495840

### Start Offset [ms]

81000

### Extra

Created from Auto Nong.
Created for level: 59209010

**Comment by LousyBook-01** [comment]
reject

no
