### ISSUE TITLE
 totalitarianism ii by staysold

### ISSUE THREAD

**Issue by Orgot908776** [FlafyDev/auto-nong-indexes#951]
### Song Name

totalitarianism ii

### Artist Name

staysold

### Source

Youtube

### Youtube Link

https://youtu.be/7XTRbvMc9Vg?si=umnqJdKUoCmRSQ_s

### Song ID

467339

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 10565740

**Comment by SpuckwasserDE** [comment]
reject

popular songs like "At the Speed of light" are too inconvenient to be replaced by smth unrelated and are therefore usually rejected
