### ISSUE TITLE
Add overdose party by funyan 

### ISSUE THREAD

**Issue by MiguelD1514A** [FlafyDev/auto-nong-indexes#952]
### Song Name

overdose party

### Artist Name

funyan 

### Source

Youtube

### Youtube Link

https://youtu.be/XDxFcZyMiNM?si=uZwft4DH8M87B42V

### Direct File Link

https://music.apple.com/es/album/overdose-party-single/1556816006

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.

**Comment by SpuckwasserDE** [comment]
accept
