### ISSUE TITLE
Add overdose party by funyan 

### ISSUE THREAD

**Issue by MiguelD1514A** [FlafyDev/auto-nong-indexes#953]
### Song Name

overdose party

### Artist Name

funyan 

### Source

Youtube

### Youtube Link

uZwft4DH8M87B42V

### Song ID

1

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 11359854

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
