### ISSUE TITLE
Add Ride(cover GuitarHeroStyles) by Guitar

### ISSUE THREAD

**Issue by MRerick957** [FlafyDev/auto-nong-indexes#955]
### Song Name

Ride(cover GuitarHeroStyles)

### Artist Name

Twenty one pilots

### Source

Youtube

### Youtube Link

xaTgZ0l3iK7zbsM6

### Song ID

682387

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 34585270

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
