### ISSUE TITLE
Add JVKE by golden hour original song

### ISSUE THREAD

**Issue by Vmgd2** [FlafyDev/auto-nong-indexes#956]
### Song Name

JVKE

### Artist Name

golden hour original song

### Source

Youtube

### Youtube Link

iYrWwdMxwUzZrlAQ

### Song ID

1278923

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 103709056

**Comment by SpuckwasserDE** [comment]
reject

the link is invalid and you swapped artist and song name

**Comment by Vmgd2** [comment]
Accept

Em dom., 7 de jul. de 2024, 06:11, auto-nong[bot] ***@***.***>
escreveu:
