### ISSUE TITLE
Add M i s f o r t u n e by Cight 

### ISSUE THREAD

**Issue by PapafritaGD** [FlafyDev/auto-nong-indexes#957]
### Song Name

M i s f o r t u n e

### Artist Name

Cight & Vaiku

### Source

Youtube

### Youtube Link

GaUzrVYLmunBCaPM

### Song ID

555555

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 105021385

**Comment by SpuckwasserDE** [comment]
reject

The YouTube Link doesn't work. I suggest using uD76KznabMQ and making a new request. You can message @spuckwasser.de on Discord telling me the new issue number and I'll have a look on the new request
