### ISSUE TITLE
Add Intro by Junior H

### ISSUE THREAD

**Issue by VotiveManxs** [FlafyDev/auto-nong-indexes#958]
### Song Name

Intro

### Artist Name

Junior H

### Source

Youtube

### Youtube Link

1kGAPi-y7BkD7CfJ

### Song ID

613929

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 97417472

**Comment by VotiveManxs** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
