### ISSUE TITLE
Add clubstep x Out da front (aboriginal Remix) by ReddGMD

### ISSUE THREAD

**Issue by LFGMD** [FlafyDev/auto-nong-indexes#962]
### Song Name

clubstep x Out da front (aboriginal Remix)

### Artist Name

Noongah

### Source

Youtube

### Youtube Link

https://youtu.be/uhRzUIka7Zo

### Song ID

13

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 59075347

**Comment by LFGMD** [comment]
Yeah it’s still active

**Comment by SpuckwasserDE** [comment]
reject

mashups should have some popularity to show that people want it.
Note that you can still use the nong yourself, it just won't be public
