### ISSUE TITLE
Add CUTE DEPRESSED by Dyan Dxddy

### ISSUE THREAD

**Issue by Pithobu** [FlafyDev/auto-nong-indexes#963]
### Song Name

CUTE DEPRESSED

### Artist Name

Dyan Dxddy

### Source

Youtube

### Youtube Link

abwf-BdPFsQ

### Song ID

315202

### Start Offset [ms]

0

### Extra

For if you want to use CUTE DEPRESSED

**Comment by Pithobu** [comment]
accept

**Comment by SpuckwasserDE** [comment]
accept
