### ISSUE TITLE
Add overdose party by furyan 

### ISSUE THREAD

**Issue by MiguelD1514A** [FlafyDev/auto-nong-indexes#964]
### Song Name

overdose party

### Artist Name

furyan 

### Source

Youtube

### Youtube Link

gxJAiZH-5XOsVW08

### Song ID

0

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 107394885

**Comment by SpuckwasserDE** [comment]
reject

wrong song id
