### ISSUE TITLE
Add mus_f_part3 by Toby Fox

### ISSUE THREAD

**Issue by GdPlayer5151** [FlafyDev/auto-nong-indexes#965]
### Song Name

mus_f_part3

### Artist Name

Toby Fox

### Source

Youtube

### Youtube Link

RAC5sRU9ZmMc1B4N

### Song ID

1

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 107394763

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
