### ISSUE TITLE
Add Ludi Letnji Ples by Flamingosi

### ISSUE THREAD

**Issue by Sax93** [FlafyDev/auto-nong-indexes#966]
### Song Name

Ludi Letnji Ples

### Artist Name

Flamingosi

### Source

Youtube

### Youtube Link

https://youtu.be/ahu6__i80MI?si=-L1CtnJLOIWAO4SU

### Song ID

342343

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 71453556

**Comment by SpuckwasserDE** [comment]
reject

already in the mod. Pretty sure I was the one who accepted it
