### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by Sax93** [FlafyDev/auto-nong-indexes#967]
### Song Name

Ludi Letnji Ples

### Artist Name

Flamingosi

### Source

Youtube

### Youtube Link

https://youtu.be/ahu6__i80MI?si=-L1CtnJLOIWAO4SU

### Direct File Link

file:///C:/Users/HP/Downloads/Ludi%20Letnji%20Ples_ahu6__i80MI.mp3

### Song ID

342343

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
accept
