### ISSUE TITLE
Add Nong Song: the path of pain from hollow knight

### ISSUE THREAD

**Issue by Shineevee** [FlafyDev/auto-nong-indexes#969]
### Song Name

Path of pain song - Hollow knight

### Artist Name

Christopher Larkin

### Source

Youtube

### Youtube Link

https://youtu.be/AQ71AUNdjL0?si=a_vcMyRu7GcrU2Yk

### Song ID

10006026

**Comment by SpuckwasserDE** [comment]
accept
