### ISSUE TITLE
Add Nong Song

### ISSUE THREAD

**Issue by GALAGTICGD** [FlafyDev/auto-nong-indexes#97]
### Song Name

Kawaikute breacker

### Artist Name

Sati Akura

### Source

Youtube

### Youtube Link

https://youtube.com/@frozixgd?si=ZQaWzbi7quMjkHeE

### Song ID

574484

### Extra

> Для SONIC WAVE

**Comment by GALAGTICGD** [comment]
Я это создал для себя

**Comment by FlafyDev** [comment]
The provided youtube link isn't a video. Edit the issue with the correct link
