### ISSUE TITLE
pls work pls

### ISSUE THREAD

**Issue by icon908** [FlafyDev/auto-nong-indexes#970]
### Song Name

hard heart

### Artist Name

elliot holmes-subiect

### Source

Youtube

### Youtube Link

qNvz0zJYCuimRdYE

### Song ID

844658

### Start Offset [ms]

1

### Extra

Created from Auto Nong.
Created for level: 52469322

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link. Also note that replacing popular songs such as creo songs with unrelated nongs is inconvenient and is therefore likely to be rejected
