### ISSUE TITLE
Add Heroico De Papel by YKN

### ISSUE THREAD

**Issue by gdplayer993** [FlafyDev/auto-nong-indexes#973]
### Song Name

Heroico De Papel

### Artist Name

YKN

### Source

Youtube

### Youtube Link

BzpGkblqtg98MfCM

### Direct File Link

https://youtu.be/MDgZYLxJZPw?si=BzpGkblqtg98MfCM

### Song ID

69696969

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 1244147

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
