### ISSUE TITLE
Chipitune processing

### ISSUE THREAD

**Issue by ZrroOficial** [FlafyDev/auto-nong-indexes#974]
### Song Name

Blast processing chipitune remix

### Artist Name

Vorlex

### Source

Youtube

### Youtube Link

https://youtu.be/WW-w8vFp85o?si=Hay68RcX2EUNcnlM

### Song ID

16

### Extra

A blast processing chipitune remix by vorlex

**Comment by ZrroOficial** [comment]
accept

**Comment by SpuckwasserDE** [comment]
reject

song isn't synced due to wrong start offset
