### ISSUE TITLE
FOCUS by perplexing

### ISSUE THREAD

**Issue by Teupai946** [FlafyDev/auto-nong-indexes#980]
### Song Name

FOCUS

### Artist Name

perplexing

### Source

Youtube

### Youtube Link

VsAksWHpTBAML7By

### Direct File Link

https://youtu.be/KuCngi6YXn8?si=VsAksWHpTBAML7By

### Song ID

122223

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 104257973

**Comment by Teupai946** [comment]
Accept

**Comment by Teupai946** [comment]
accept

**Comment by Teupai946** [comment]
Accept

Em sex., 5 de jul. de 2024 00:38, auto-nong[bot] ***@***.***>
escreveu:

**Comment by SpuckwasserDE** [comment]
reject

invalid YouTube link
