### ISSUE TITLE
Sphere by Creo

### ISSUE THREAD

**Issue by Fazco7** [FlafyDev/auto-nong-indexes#982]
### Song Name

Creo x Marshmello - Sphere x Happier

### Artist Name

AidanTR (Uploaded by Zafkhiel17)

### Source

Youtube

### Youtube Link

3WobR1H6B0Y

### Song ID

739991

### Extra

Created from Auto Nong.
Created for level: 53858796

**Comment by SpuckwasserDE** [comment]
accept
