### ISSUE TITLE
Add 腐蝕ルサンチマン、不死欲の猿楽座 by Imperial Circus Dead Decadence

### ISSUE THREAD

**Issue by hellopeope** [FlafyDev/auto-nong-indexes#984]
### Song Name

腐蝕ルサンチマン、不死欲の猿楽座 (fushoku ressentiment)

### Artist Name

Imperial Circus Dead Decadence

### Source

Youtube

### Youtube Link

https://youtu.be/Y1BIFydkcIQ?si=VJNuZyt1app_u3pE

### Song ID

1262293

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
not created for any level

**Comment by SpuckwasserDE** [comment]
accept
