### ISSUE TITLE
Add IFHY by Tyler, the Creator

### ISSUE THREAD

**Issue by KyuiCui** [FlafyDev/auto-nong-indexes#993]
### Song Name

IFHY

### Artist Name

Tyler, the Creator

### Source

Youtube

### Youtube Link

OZ9IELefyeQ

### Song ID

2

### Start Offset [ms]

0

### Extra

Created from Auto Nong.
Created for level: 138

**Comment by SpuckwasserDE** [comment]
reject

the main level songs are too popular to be replaced by an unrelated nong
