### ISSUE TITLE
Add Nong Song: 

### ISSUE THREAD

**Issue by KyuiCui** [FlafyDev/auto-nong-indexes#994]
### Song Name

Super Rich Kids

### Artist Name

Frank Ocean

### Source

Youtube

### Youtube Link

https://www.youtube.com/watch?v=0XCQNpjWmRE

### Song ID

2

### Start Offset [ms]

0

**Comment by SpuckwasserDE** [comment]
reject

the main level songs are too popular too be replaced by smth unrelated
