### ISSUE TITLE
Add Nong Song: SS

### ISSUE THREAD

**Issue by StarMelandiz** [FlafyDev/auto-nong-indexes#998]
### Song Name

SS

### Artist Name

Ken Carson

### Source

Youtube

### Youtube Link

https://youtu.be/TMzs6GvsZXU?feature=shared

### Song ID

13

### Extra

To be used for an official Layout List collab

**Comment by SpuckwasserDE** [comment]
reject

electroman adventures is too popular of a song to be replaced with smth unrelated
